### ISSUE TITLE
AdamCPU creates error

### ISSUE THREAD

**Issue by Moldoteck** [microsoft/DeepSpeed#1077]
self.optimizer = deepspeed.ops.adam.DeepSpeedCPUAdam(self.model.parameters(), lr=0.01, bias_correction=True, betas=(0.9, 0.999), eps=1e-08, weight_decay=0.0001, amsgrad=False, adamw_mode=True)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/adam/cpu_adam.py", line 78, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/op_builder/builder.py", line 215, in load
    return self.jit_load(verbose)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/op_builder/builder.py", line 230, in jit_load
    assert_no_cuda_mismatch()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/op_builder/builder.py", line 60, in assert_no_cuda_mismatch
    f"Installed CUDA version {sys_cuda_version} does not match the "
Exception: Installed CUDA version 11.0 does not match the version torch was compiled with 10.1, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f30c6ca0830>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/ops/adam/cpu_adam.py", line 91, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by tjruwase** [comment]
> Exception: Installed CUDA version 11.0 does not match the version torch was compiled with 10.1, unable to compile cuda/cpp extensions without a matching cuda version.

It seems the above exception is the original issues. Can you please check if you have CUDA version mismatch by running and sharing the output of  `ds_report`?

**Comment by Moldoteck** [comment]
Yes, after installing cuda 11 the problem was solved, thank you. However i got some strange behavior: when creating adam from config, i get strange error, but when creating cudaadam manually, it works as expected. I will attach the error a bit later this day

**Comment by Moldoteck** [comment]
Nevermind. The problem was triggered by the fact that i haven't provided model.params when initializing
