### ISSUE TITLE
cifar10_deepspeed: NameError: name 'is_map_style_dataset' is not defined

### ISSUE THREAD

**Issue by python152** [microsoft/DeepSpeed#1087]
Hi 

I am running a vanilla cifar10_deepspeed.py  example, and run into the following error, on `is_map_style_dataset`, deepspeed version is 0.3.16 straight from pip install. Can you please help?

```
[2021-05-21 16:23:58,206] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0]}
[2021-05-21 16:23:58,206] [INFO] [launch.py:86:main] nnodes=1, num_local_procs=1, node_rank=0
[2021-05-21 16:23:58,206] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2021-05-21 16:23:58,206] [INFO] [launch.py:102:main] dist_world_size=1
[2021-05-21 16:23:58,207] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0
...

[2021-05-21 16:24:03,240] [INFO] [logging.py:60:log_dist] [Rank -1] DeepSpeed info: version=0.3.16, git-hash=unknown, git-branch=unknown
[2021-05-21 16:24:03,240] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
[2021-05-21 16:24:05,033] [INFO] [utils.py:11:_initialize_parameter_parallel_groups] data_parallel_size: 1, parameter_parallel_size: 1
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 143, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/opt/DeepSpeed/lib/python3.8/site-packages/deepspeed/__init__.py", line 120, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/op/DeepSpeed/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 164, in __init__
    self.training_dataloader = self.deepspeed_io(training_data)
  File "/opt/DeepSpeed/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 845, in deepspeed_io
    if not (is_map_style_dataset(dataset) or is_iterable_style_dataset(dataset)):
NameError: name 'is_map_style_dataset' is not defined
Killing subprocess 93984
```

**Comment by python152** [comment]
deepspeed from git master has no much errors.
