### ISSUE TITLE
Problems Installing with Windows

### ISSUE THREAD

**Issue by alexorona** [microsoft/DeepSpeed#1121]
Windows 10
Cuda Toolkit = 10.2
PyTorch = 8.1
VisualStudio = 2019

I'm trying to use this with the transformers library and carefully followed the instructions laid out by the transformers authors. I am using the `gloo` backend.

```
When using pip install deepspeed and trying to train, I get the following error:
    590         if not self.amp_enabled():
--> 591             self._broadcast_model()

c:\users\alexo\.conda\envs\gentext_005\lib\site-packages\deepspeed\runtime\engine.py in _broadcast_model(self)
    559                 dist.broadcast(p,
    560                                self.broadcast_src_rank,
--> 561                                group=self.data_parallel_group)

c:\users\alexo\.conda\envs\gentext_005\lib\site-packages\torch\distributed\distributed_c10d.py in broadcast(tensor, src, group, async_op)
   1045         return work
   1046     else:
-> 1047         work.wait()

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```
I am using these settings:
```
import os
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '9994' # modify if RuntimeError: Address already in use
os.environ['RANK'] = "0"
os.environ['LOCAL_RANK'] = "0"
os.environ['WORLD_SIZE'] = "1"
```
When I run the report, it looks like none of the ops installed. As a reference, `cmake` is installed as is `llvm`. I don't understand why `deepspeed wheel compiled w. ...... torch 1.7, cuda 10.1` when there is only one version of CUDA installed in both the environment and the system (10.2).
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
The system cannot find the file specified.
The system cannot find the file specified.
 [WARNING]  sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
The system cannot find the file specified.
 [WARNING]  sparse_attn requires the 'cmake' command, but it does not exist!
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
 [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing.
async_io ............... [NO] ....... [NO]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['C:\\Users\\alexo\\.conda\\envs\\gentext_005\\lib\\site-packages\\torch']
torch version .................... 1.8.1+cu102
torch cuda version ............... 10.2
nvcc version ..................... 10.2
deepspeed install path ........... ['C:\\Users\\alexo\\.conda\\envs\\gentext_005\\lib\\site-packages\\deepspeed']
deepspeed info ................... 0.3.16, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.7, cuda 10.1
```
I've tried uninstalling and reinstalling multiple times with different versions of CUDA and PyTorch. 

When building from source, I get the following error:
```
Complete output (21 lines):
    The system cannot find the file specified.
    The system cannot find the file specified.
    The system cannot find the file specified.
    The system cannot find the file specified.
    The system cannot find the file specified.
    The system cannot find the file specified.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alexo\AppData\Local\Temp\pip-req-build-93k76uvm\setup.py", line 147, in <module>
        create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
      File "C:\Users\alexo\AppData\Local\Temp\pip-req-build-93k76uvm\setup.py", line 141, in create_dir_symlink
        os.symlink(src, dest)
    OSError: symbolic link privilege not held
    DS_BUILD_OPS=1
```

**Comment by arqlz** [comment]
Same problem

**Comment by lifeiteng** [comment]
@alexorona Did you figure it out?

**Comment by lifeiteng** [comment]
`deepspeed.init_distributed(dist_backend="nccl")` Fixed this error

**Comment by mrwyattii** [comment]
The original error with symlinks is likely due to not running with admin privilege. We are working on removing this requirement (by removing all symlinks): #4323

**Comment by jomayeri** [comment]
Please check out the latest version of DeepSpeed for Windows compatibility.
