### ISSUE TITLE
Bug occurs when using the huggingface seq2seq model using the inference engine.

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/DeepSpeed#1162]
I'm trying to deploy some language models using DeepSpeed's inference engine. Currently, I am trying to deploy a seq2seq langauge model, I have succeeded in parallelizing the model. However, when I try to generate, Then the following error occurred.

```python
import time
import torch

from torch.distributed import get_rank
from deepspeed import InferenceEngine
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer


model_name = 'facebook/bart-large'
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).half()
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = InferenceEngine(
    model=model,
    mp_size=2,
    dtype=torch.half,
)

torch.cuda.empty_cache()

tokens = tokenizer.encode(
    "Hello",
    return_tensors="pt",
    truncation=True,
    padding=True,
).cuda()

output = model.generate(
    tokens,
    min_length=30,
    max_length=31,
)  # <--- problem

if get_rank() == 0:
    print(f"Output: {tokenizer.decode(output.tolist()[0])}")

```

```
deepspeed --num_gpus=2 inference.py
```
```
RuntimeError: Tensors must be non-overlapping and dense
```

**Comment by hyunwoongko** [comment]
here is output.

```
[2021-06-16 17:16:06,454] [INFO] [distributed.py:47:init_distributed] Initializing torch distributed with backend: nccl
[2021-06-16 17:16:06,463] [INFO] [distributed.py:47:init_distributed] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
Traceback (most recent call last):
  File "deepspeed_hf_blender_inference.py", line 50, in <module>
  File "deepspeed_hf_blender_inference.py", line 50, in <module>
        max_length=31,max_length=31,

  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
        return func(*args, **kwargs)return func(*args, **kwargs)

  File "/home/kevin/kevin/lib/python3.7/site-packages/transformers/generation_utils.py", line 1044, in generate
  File "/home/kevin/kevin/lib/python3.7/site-packages/transformers/generation_utils.py", line 1044, in generate
    **model_kwargs,
  File "/home/kevin/kevin/lib/python3.7/site-packages/transformers/generation_utils.py", line 1775, in beam_search
    **model_kwargs,
  File "/home/kevin/kevin/lib/python3.7/site-packages/transformers/generation_utils.py", line 1775, in beam_search
    output_hidden_states=output_hidden_states,
  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    output_hidden_states=output_hidden_states,
  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kevin/kevin/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 219, in forward
    result = self.forward(*input, **kwargs)
  File "/home/kevin/kevin/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 219, in forward
    dist.broadcast(kwargs[k], 0)
  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 860, in broadcast
    dist.broadcast(kwargs[k], 0)
  File "/home/kevin/kevin/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 860, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Tensors must be non-overlapping and dense
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Tensors must be non-overlapping and dense
Killing subprocess 32550
Killing subprocess 32551
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kevin/kevin/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 171, in <module>
    main()
  File "/home/kevin/kevin/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 161, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/kevin/kevin/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 139, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kevin/kevin/bin/python', '-u', 'deepspeed_hf_blender_inference.py', '--local_rank=1']' returned non-zero exit status 1.
```

**Comment by hyunwoongko** [comment]
<img width="1941" alt="스크린샷 2021-06-17 오후 5 33 58" src="https://user-images.githubusercontent.com/38183241/122361451-35387780-cf92-11eb-80e6-bed3491e80a3.png">

@RezaYazdaniAminabadi I solved the problem. Before broadcasting a model's parameters, you must make sure it is contiguous. For non-contiguous tensors, the broadcast operation throws an error. So with some code modifications, you can infer cleanly even in models like Bart. I will upload this as a PR.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @hyunwoongko 

Thanks for investigating the issue for these new models 👍 
I will test the branch and merge this soon :)

Reza

**Comment by aphedges** [comment]
I am getting the same error when using the `num_return_sequences` parameter with GPT-Neo. I ran `deepspeed --num_gpus 4 test.py` with the following code in `test.py`:

```python
import os

import deepspeed
import torch
from transformers import pipeline

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))
pipe = pipeline(
    "text-generation",
    model="EleutherAI/gpt-neo-2.7B",
    framework="pt",
    device=local_rank,
)
pipe.model = deepspeed.init_inference(pipe.model, mp_size=world_size, dtype=torch.float32)
output = pipe("I am very", do_sample=True, num_return_sequences=10)
if torch.distributed.get_rank() == 0:
    print(output)
```

I get `RuntimeError: Tensors must be non-overlapping and dense` errors when running `deepspeed==0.4.0`, but I can confirm that #1168 fixes the issue for me.

This code was run with Python 3.7.9, `torch==1.8.1`, and `transformers==Version: 4.6.1`.
