### ISSUE TITLE
Inference with `replace_method='auto'` fails for `gpt2-xl` generation

### ISSUE THREAD

**Issue by aphedges** [microsoft/DeepSpeed#1192]
I modified the code at "[End-to-End GPT NEO 2.7B Inference](https://github.com/microsoft/DeepSpeed/blob/aa16828c267dc7a790a5cc2f43f93a67617a2364/docs/_tutorials/inference-tutorial.md#end-to-end-gpt-neo-27b-inference)" by replacing `EleutherAI/gpt-neo-2.7B` with `gpt2-xl`, and I get the following stack trace when running on 2 GPUs:

```console
[2021-06-28 13:56:01,937] [ERROR] Uncaught Exception
Traceback (most recent call last):
  File "gpt2-generation.py", line 20, in <module>
    string = generator("DeepSpeed is", do_sample=True, min_length=50)
  File "venv/lib/python3.7/site-packages/transformers/pipelines/text_generation.py", line 148, in __call__
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1026, in generate
    **model_kwargs,
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1535, in sample
    output_hidden_states=output_hidden_states,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 229, in forward
    return self.model_orig_fwd(*inputs, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 956, in forward
    return_dict=return_dict,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 799, in forward
    output_attentions=output_attentions,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 611, in forward
    self.norm_b)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 393, in forward
    self.qkv_merging)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 308, in forward
    output, key_layer, value_layer, context_layer = selfAttention_fp()
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 273, in selfAttention_fp
    context_layer, key_layer, value_layer = compute_attention(qkv_out)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 207, in compute_attention
    mixed_query = _transpose_for_scores(mixed_query, False, True)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 148, in _transpose_for_scores
    x_1 = x.view(*new_x_shape)
RuntimeError: shape '[1, 3, 12, 66]' is invalid for input of size 2400
```

The code works without issues when using the default `EleutherAI/gpt-neo-2.7B`, and it also runs successfully with `gpt2`, `gpt2-medium`, and `gpt2-large`. Out of the GPT-2 models, only `gpt2-xl` fails. Setting `replace_method` to a value that is not `'auto'` (such as `'foo'`) allows it to work, but the DeepSpeed optimizations are not loaded.

This code was run with Python 3.7.9, `torch==1.8.1+cu102`, `transformers==4.8.1`, and `deepspeed==0.4.2+bc019a5` (compiled using `DS_BUILD_OPS=1` and CUDA 10.2.89).

I edited the stack trace to remove the parts of the path outside the virtual environment.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @aphedges 

Thanks for trying all these.
I will take a look at this. By the way, we have another [test script](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/test-gpt.sh) for this model architecture. I wonder if you see the same issue for that too.

Thanks,
Reza

**Comment by aphedges** [comment]
@RezaYazdaniAminabadi, thanks for looking into this!

The test script you linked worked without issues for 1 and 2 GPUs. However, it seems that removing the `--fp16` line from the script causes the following error when using 1 GPU:

```console
Traceback (most recent call last):
  File "run_generation.py", line 349, in <module>
    main()
  File "run_generation.py", line 316, in main
    num_return_sequences=args.num_return_sequences,
  File "venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1026, in generate
    **model_kwargs,
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1535, in sample
    output_hidden_states=output_hidden_states,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 965, in forward
    lm_logits = self.lm_head(hidden_states)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

I also got the above error when I ran the code for my initial comment on only 1 GPU, but I didn't mention it yesterday.

I get a different (third) error when running on 2 GPUs:

```console
!!!! kernel execution error. (m: 1600, n: 6, k: 6400, error: 13)
!!!! kernel execution error. (m: 4800, n: 6, k: 1600, error: 13)
Traceback (most recent call last):
  File "run_generation.py", line 349, in <module>
    main()
  File "run_generation.py", line 316, in main
    num_return_sequences=args.num_return_sequences,
  File "venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1026, in generate
    **model_kwargs,
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1535, in sample
    output_hidden_states=output_hidden_states,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 956, in forward
    return_dict=return_dict,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 799, in forward
    output_attentions=output_attentions,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 611, in forward
    self.norm_b)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 393, in forward
    self.qkv_merging)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 308, in forward
    output, key_layer, value_layer, context_layer = selfAttention_fp()
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 273, in selfAttention_fp
    context_layer, key_layer, value_layer = compute_attention(qkv_out)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 207, in compute_attention
    mixed_query = _transpose_for_scores(mixed_query, False, True)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 154, in _transpose_for_scores
    return x_1.reshape(x.shape)
RuntimeError: CUDA error: an illegal memory access was encountered
```

I am able to prevent the both errors with the following modifications:

```diff
--- /dev/fd/63	2021-06-29 12:44:58.984909630 -0700
+++ run_generation.py	2021-06-29 12:42:08.976235560 -0700
@@ -261,7 +261,7 @@
         model = deepspeed.init_inference(model,
                                          mp_size=1,
                                          dtype=(torch.half if args.fp16 else torch.float),
-                                         injection_policy=injection_policy)
+                                         injection_policy={},replace_method='')
         model = model.module

     args.length = adjust_length_to_model(args.length, max_sequence_length=model.config.max_position_embeddings)
```

This is consistent with the behavior I noted in my initial comment.

If it matters, I've been running these experiments on 1 and 2 Nvidia Quadro RTX 8000 cards with driver version 440.44.

**Comment by aphedges** [comment]
I forgot to check, but I can confirm that these errors also go away when I switch to `gpt2-large`.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @aphedges 

I think this PR fixes the issue.
Thanks,
Reza

**Comment by aphedges** [comment]
@RezaYazdaniAminabadi, I installed 65f1fe8, and it unfortunately does not fix my issue.

**Comment by RezaYazdaniAminabadi** [comment]
Can you please share your script with me to try on my side?
Thanks.

**Comment by aphedges** [comment]
I tried 7cb65cc, and that also didn't fix it.

Here is my script:

```python
# Filename: gpt2-generation.py
import os
import deepspeed
import torch
import transformers
from transformers import pipeline

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))
generator = pipeline('text-generation', model='gpt2-xl', device=local_rank, model_kwargs={'cache_dir': 'gpt2_component/.model_cache'})



generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto')

string = generator("DeepSpeed is", do_sample=True, min_length=50)
if torch.distributed.get_rank() == 0:
    print(string)
```

The only changes from the version in the tutorial is that it uses `gpt2-xl` and that I am using a local model cache directory.

I ran it with `deepspeed --num_gpus 2 gpt2-generation.py`. Here is the stack trace (given that line numbers are different after your changes; also seems to be some interleaving from the two processes):

```console
Traceback (most recent call last):
  File "gpt2-generation.py", line 19, in <module>
    string = generator("DeepSpeed is", do_sample=True, min_length=50)
  File "venv/lib/python3.7/site-packages/transformers/pipelines/text_generation.py", line 148, in __call__
Traceback (most recent call last):
  File "gpt2-generation.py", line 19, in <module>
    string = generator("DeepSpeed is", do_sample=True, min_length=50)
  File "venv/lib/python3.7/site-packages/transformers/pipelines/text_generation.py", line 148, in __call__
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1026, in generate
    return func(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1026, in generate
    **model_kwargs,
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1535, in sample
    **model_kwargs,
  File "venv/lib/python3.7/site-packages/transformers/generation_utils.py", line 1535, in sample
    output_hidden_states=output_hidden_states,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    output_hidden_states=output_hidden_states,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 229, in forward
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 229, in forward
    return self.model_orig_fwd(*inputs, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 956, in forward
    return self.model_orig_fwd(*inputs, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 956, in forward
    return_dict=return_dict,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    return_dict=return_dict,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 799, in forward
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 799, in forward
    output_attentions=output_attentions,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    output_attentions=output_attentions,
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 615, in forward
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 615, in forward
    self.norm_b)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    self.norm_b)
  File "venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 397, in forward
    result = self.forward(*input, **kwargs)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 397, in forward
    self.qkv_merging)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 312, in forward
    self.qkv_merging)
output, key_layer, value_layer, context_layer = selfAttention_fp()
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 312, in forward

  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 277, in selfAttention_fp
        output, key_layer, value_layer, context_layer = selfAttention_fp()
context_layer, key_layer, value_layer = compute_attention(qkv_out, input_mask)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 277, in selfAttention_fp

  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 203, in compute_attention
        context_layer, key_layer, value_layer = compute_attention(qkv_out, input_mask)mixed_query = _transpose_for_scores(mixed_query, False, True)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 144, in _transpose_for_scores

  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 203, in compute_attention
    x_1 = x.view(*new_x_shape)
RuntimeError: shape '[1, 3, 12, 66]' is invalid for input of size 2400
    mixed_query = _transpose_for_scores(mixed_query, False, True)
  File "venv/lib/python3.7/site-packages/deepspeed/ops/transformer/inference/transformer_inference.py", line 144, in _transpose_for_scores
    x_1 = x.view(*new_x_shape)
RuntimeError: shape '[1, 3, 12, 66]' is invalid for input of size 2400
```

**Comment by RezaYazdaniAminabadi** [comment]
Can you please send me the full log of your experiment?
thanks

**Comment by aphedges** [comment]
Here is the complete log: [log_2021_07_07_17_39_28.txt](https://github.com/microsoft/DeepSpeed/files/6779182/log_2021_07_07_17_39_28.txt). I used the same command as in my previous comment. I hope it helps.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @aphedges 

Sorry for the late reply on this thread.
I now see the issue with this model. The problem is that the number of heads is 25 and is not dividable by 2. So, we cannot parallelize it across 2 GPUs. In this case, the smallest model-parallel degree has to be 5, otherwise the kind of parallelism we support cannot work.
I can put an assert to clarify this issue more properly for the inference API.
Thanks,
Reza

**Comment by aphedges** [comment]
Should this issue be closed? An assert (or similar check) would be very useful here by providing a more clear error message, but the linked PR doesn't seem to add one.

**Comment by RezaYazdaniAminabadi** [comment]
Yes, I will do that in a separate PR.
Thanks @aphedges

**Comment by aphedges** [comment]
@RezaYazdaniAminabadi, thanks for figuring this out!

I did not know that model-parallelism had such restrictions. I guess I just can't use `gpt2-xl` with DeepSpeed on a single 4-GPU machine, then.
