### ISSUE TITLE
Encountered a problem when testing the SparseSelfAttention function

### ISSUE THREAD

**Issue by Liu-xiandong** [microsoft/DeepSpeed#1238]
Hi,  I want to test the performance of SparseSelfAttention ( https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/sparse_attention/sparse_self_attention.py ), so I added the following code at the end:
```
if __name__ == '__main__':
    sparsity_config = FixedSparsityConfig(num_heads=8)
    query = torch.randn(8,16,128,64)
    key = torch.randn(8,16,128,64)
    value = torch.randn(8,16,128,64)
    SparseSelfAttention(sparsity_config).forward(query, key, value)
```

Then the code reported an error：
```
Traceback (most recent call last):
  File "sparse_self_attention.py", line 177, in <module>
    SparseSelfAttention(sparsity_config).forward(query, key, value)
  File "sparse_self_attention.py", line 152, in forward
    attn_output_weights = sparse_dot_sdd_nt(query, key)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py", line 745, in __call__
    time_db)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py", line 549, in forward
    c_time)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/deepspeed/ops/sparse_attention/matmul.py", line 224, in _sdd_matmul
    grid=lambda opt: [opt.TZ,
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/triton/kernel.py", line 116, in __call__
    kernel = self.fn.autotune(params, grid, self.stream)
RuntimeError: CUDA: Error- context is destroyed
```

How should this problem be solved?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @Liu-xiandong 

Thanks for reporting this. I will check this to see if I can repro on my side. I'll let you once it is resolved.

Best,
Reza

**Comment by hyunwoongko** [comment]
I have same problem.

**Comment by hyunwoongko** [comment]
@Liu-xiandong 
This problem is caused by location of tensor and parameter.
You can solve by moving layer and tensor to cuda.
Could you try the following script?

```python
if __name__ == '__main__':
    sparsity_config = FixedSparsityConfig(num_heads=8)
    query = torch.randn(8,16,128,64).cuda()
    key = torch.randn(8,16,128,64).cuda()
    value = torch.randn(8,16,128,64).cuda()
    SparseSelfAttention(sparsity_config).cuda().forward(query, key, value)
```
