### ISSUE TITLE
Suggestion: Support CPU-only environments/remove CUDA requirement

### ISSUE THREAD

**Issue by peterukk** [microsoft/DeepSpeed#1279]
Hi,

I'm training neural networks on a small CPU-only workstation, and I wanted to use the DeepSpeedCPUAdam optimizer to accelerate the training, but noticed that CUDA is required:

```
 File "...python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 37, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
```

Making CUDA optional would be a great feature. In my own field (climate modeling and weather forecasting), machine learning is an increasingly popular topic but GPU's and deep learning are often overkill. (Right now, I'm training neural nets with 1-2 hidden layers and 10-20 neurons, which is quite efficient on CPU's). Furthermore, support for non-NVIDIA GPU's should be relevant in the longer term. 

I realize this is presented as a deep learning library, but dropping the CUDA requirement for features which do not really require it might still be useful. Thanks!

**Comment by tjruwase** [comment]
@peterukk, are you able to help test this PR #1280?

**Comment by peterukk** [comment]
Wow that's fast action! I'm still getting the same error. 

`(py39) [puk@3ymlvp2:~]$ pip3 install git+https://github.com/microsoft/DeepSpeed.git@cpu-adam/optional_CUDA-copy`
...
```
import torch
from torch import nn
import pytorch_lightning as pl
from pytorch_lightning.plugins import DeepSpeedPlugin
from deepspeed.ops.adam import DeepSpeedCPUAdam
from torch.utils.data import DataLoader, TensorDataset

class MLP_cpu(pl.LightningModule):    
      
    def __init__(self, nx, ny, nneur=8, learning_rate=None, SequentialModel=None):
      super().__init__()
      if SequentialModel==None:
          self.layers = nn.Sequential(
            nn.Linear(nx, nneur),
            nn.ReLU(),
            nn.Linear(nneur, nneur),
            nn.ReLU(),
            nn.Linear(nneur, ny)
          )
      else:
          self.layers = SequentialModel
      self.mse = nn.MSELoss()
      # Hyperparameters
      self.learning_rate = learning_rate
      self.save_hyperparameters()
      
    def forward(self, x):
      return self.layers(x)
    
    def training_step(self, batch, batch_idx):
      ...
      return loss
  
    def validation_step(self, batch, batch_idx):
        ...
        return loss
      
    def configure_optimizers(self):
      optimizer = DeepSpeedCPUAdam(self.parameters(), lr=self.learning_rate)
      return optimizer
```
...
```
lr          = 0.001
batch_size  = 1024
nneur       = 12

mlp     = MLP_cpu(nx=nx,ny=ny,learning_rate=lr)
trainer = pl.Trainer(accelerator="ddp_cpu", deterministic=True, num_processes=8) 

trainer.fit(mlp, train_dataloader=DataLoader(data_tr,batch_size=batch_size), 
        val_dataloaders=DataLoader(data_val,batch_size=batch_size))
```

Error:

```
Traceback (most recent call last):

  File "/tmp/ipykernel_9402/3263373796.py", line 9, in <module>
    trainer.fit(mlp, train_dataloader=DataLoader(data_tr,batch_size=batch_size),

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/accelerators/cpu.py", line 39, in setup
    return super().setup(trainer, model)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 88, in setup
    self.setup_optimizers(trainer)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 330, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 223, in init_optimizers
    return trainer.init_optimizers(model)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()

  File "/tmp/ipykernel_9402/4179932999.py", line 48, in configure_optimizers
    optimizer = DeepSpeedCPUAdam(self.parameters(), lr=self.learning_rate)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 79, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 353, in load
    return self.jit_load(verbose)

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 368, in jit_load
    assert_no_cuda_mismatch()

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 78, in assert_no_cuda_mismatch
    cuda_major, cuda_minor = installed_cuda_version()

  File "/home/puk/miniconda3/envs/py39/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 37, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"

AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

**Comment by tjruwase** [comment]
@peterukk, thanks for trying this out and sharing your feedback so quickly. It seems there is more work involved than we anticipated. Please stay tuned as we work through this.

**Comment by Atharva-Phatak** [comment]
Is there any update on this ? I am getting the same error when using FusedAdam !

**Comment by pme0** [comment]
> Is there any update on this ? I am getting the same error when using FusedAdam !

I'm also having this issue on deepspeed==0.5.10. 
My model trains fine with an optimizer from `torch.optim` but when using
`deepspeed.ops.adam.FusedAdam` I get:
```
File "[...]/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 38, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

**Comment by Yeqishen** [comment]
hello, I have the same problem now. Is there a solution?

**Comment by tjruwase** [comment]
@macabdul9, @Yeqishen, @peterukk, @pme0, apologies for the delay. CPUAdam and CPUAdagrad are usable in cpu-only environments since https://github.com/microsoft/DeepSpeed/pull/2507. Please share your feedback.

**Comment by molly-smith** [comment]
Closing since https://github.com/microsoft/DeepSpeed/pull/2507 should address this.
