### ISSUE TITLE
'torch._C' is not a package

### ISSUE THREAD

**Issue by mrseeker** [microsoft/DeepSpeed#1308]
For some unknown reason I cannot get deepspeed to run on my computer, I seem to get the following error:

```
(venv) julius@big-bertha:~/Documents/projects/DeepSpeed/dist$ python -m deepspeed.env_report
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/julius/Documents/projects/food/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 12, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "/home/julius/Documents/projects/food/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 16, in <module>
    from torch.distributed.distributed_c10d import _get_global_rank
  File "/home/julius/Documents/projects/food/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 15, in <module>
    from .constants import default_pg_timeout
  File "/home/julius/Documents/projects/food/venv/lib/python3.8/site-packages/torch/distributed/constants.py", line 1, in <module>
    from torch._C._distributed_c10d import _DEFAULT_PG_TIMEOUT
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```
I am unsure what is causing this "torch._C" is not a package, but I think it has something to do with https://bugs.python.org/issue43367.

Do you guys have any recommendations on how to solve this problem?

**Comment by tjruwase** [comment]
@mrseeker, could it be related to [this](https://github.com/pytorch/pytorch/issues/574)?

**Comment by khaotik** [comment]
I managed to fixed this problem by compiling torch with distributed support. Setting cmake flags `USE_DISTRIBUTED=ON` fixes. `torch.distributed.is_available()` can be check availability. Would be great if DeepSeed makes `torch.distributed` dependency optional.
