### ISSUE TITLE
 Unable to pre-compile cpu_adam

### ISSUE THREAD

**Issue by yinxx** [microsoft/DeepSpeed#1315]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-p66b9m1r\deepspeed\setup.py", line 135, in <module>
        abort(f"Unable to pre-compile {op_name}")
      File "C:\Users\admin\AppData\Local\Temp\pip-install-p66b9m1r\deepspeed\setup.py", line 43, in abort
        assert False, msg
    AssertionError: Unable to pre-compile cpu_adam
    [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
    DS_BUILD_OPS=1
     [WARNING]  One can disable cpu_adam with DS_BUILD_CPU_ADAM=0
     [ERROR]  Unable to pre-compile cpu_adam

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-p66b9m1r\deepspeed\

**Comment by RezaYazdaniAminabadi** [comment]
Hi @yinxx 

Can you please paste the whole log to see what caused the issue? Also, how do you install deepspeed?
Can you try running `sudo DS_BUILD_CPU_ADAM=1 python setup.py -v install` ?
Thanks,
Reza

**Comment by PuyangChen** [comment]
hi, @RezaYazdaniAminabadi 
I have meet this issue too.
here is the whole log:
pip install deepspeed
Downloading https://intelpypi.pdx.intel.com/root/pypi/%2Bf/067/d95579eeb13a0/deepspeed-0.5.1.tar.gz (476kB)
     |████████████████████████████████| 481kB 226kB/s
    ERROR: Command errored out with exit status 1:
     command: 'e:\software\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zhuang8\\AppData\\Local\\Temp\\2\\pip-install-w_4dcvu6\\deepspeed\\setup.py'"'"'; __file__='"'"'C:\\Users\\zhuang8\\AppData\\Local\\Temp\\2\\pip-install-w_4dcvu6\\deepspeed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\zhuang8\AppData\Local\Temp\2\pip-install-w_4dcvu6\deepspeed\
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zhuang8\AppData\Local\Temp\2\pip-install-w_4dcvu6\deepspeed\setup.py", line 135, in <module>
        abort(f"Unable to pre-compile {op_name}")
      File "C:\Users\zhuang8\AppData\Local\Temp\2\pip-install-w_4dcvu6\deepspeed\setup.py", line 43, in abort
        assert False, msg
    AssertionError: Unable to pre-compile cpu_adam
    DS_BUILD_OPS=1
     [WARNING]  One can disable cpu_adam with DS_BUILD_CPU_ADAM=0
     [ERROR]  Unable to pre-compile cpu_adam
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

btw, I want to install deepspeed in a Windows server instead of Linux. does the system lead to problem?

thanks,
Puyang

**Comment by PuyangChen** [comment]
Hi, @yinxx 
do you fix tis error?

**Comment by PuyangChen** [comment]
Hi, @yinxx
do you fix this error?

**Comment by lostmsu** [comment]
Can somebody share any insight about why cpu_adam and some other ops are not supported on Windows?

**Comment by Johnz86** [comment]
I have the same issue, default pip install and installation from source does not work for me. 
I will end up with:
```
```

**Comment by lostmsu** [comment]
This should have been fixed by https://github.com/microsoft/DeepSpeed/pull/1634

**Comment by tjruwase** [comment]
@lostmsu, thanks for fixing this. 

@yinxx, can you please confirm the fix so this can be closed?

**Comment by gaetanlop** [comment]
Still not working on my side on windows.
