### ISSUE TITLE
[BUG] PyTorch Lightning Finetuning callback crashes with Deepspeed

### ISSUE THREAD

**Issue by aakaashjois** [microsoft/DeepSpeed#1426]
**Describe the bug**
The Finetuning callback from Pytorch Lightning crashes when using Deepspeed plugin
```
/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:106: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 24 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:323: UserWarning: The number of training samples (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  f"The number of training samples ({self.num_training_batches}) is smaller than the logging interval"
/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:106: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 24 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Training: -1it [00:00, ?it/s]Traceback (most recent call last):
  File "/fast/cqa-fine-tune/cqa_video_models/trainers/deepspeed_issue.py", line 80, in <module>
    run()
  File "/fast/cqa-fine-tune/cqa_video_models/trainers/deepspeed_issue.py", line 75, in run
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 106, in run
    self.on_run_start(*args, **kwargs)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 106, in on_run_start
    self.trainer.call_hook("on_train_epoch_start")
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1219, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 92, in on_train_epoch_start
    callback.on_train_epoch_start(self, self.lightning_module)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/callbacks/finetuning.py", line 298, in on_train_epoch_start
    self._store(pl_module, opt_idx, num_param_groups, current_param_groups)
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/callbacks/finetuning.py", line 284, in _store
    current_param_groups, mapping
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/callbacks/finetuning.py", line 270, in __apply_mapping_to_param_groups
    group_state["params"] = [mapping[p] for p in g["params"]]
  File "/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/pytorch_lightning/callbacks/finetuning.py", line 270, in <listcomp>
    group_state["params"] = [mapping[p] for p in g["params"]]
KeyError: tensor([-0.0968,  0.0604,  0.0093, -0.1469, -0.0596,  0.0447,  0.0487,  0.1293,
         0.0826, -0.1409,  0.0026, -0.0222, -0.0800,  0.0198,  0.1702,  0.1146,
         0.1509,  0.0081,  0.0871,  0.0455, -0.0188, -0.1162, -0.0932, -0.0639,
         0.1352,  0.1364, -0.0046, -0.1604,  0.0396,  0.0236, -0.0839,  0.0949,
         0.1234, -0.1236,  0.1379, -0.0454,  0.0521, -0.1179,  0.0086,  0.1214,
        -0.1410, -0.1710, -0.0159,  0.0255, -0.0675, -0.0868, -0.0322, -0.0231,
        -0.0763,  0.1349,  0.1466,  0.0707,  0.0619, -0.0174, -0.0177, -0.0411,
        -0.0555,  0.0764, -0.0407, -0.1410,  0.1142, -0.0860,  0.0465,  0.0615,
        -0.0050, -0.0130], device='cuda:0', requires_grad=True)
Training: -1it [00:00, ?it/s]
```
The finetuning callback is trying to store the params in optimizer for each param group. Deepspeed changes the optimizer to store all params as a single array, which breaks the callback.

**To Reproduce**
```
import os

import torch
from torch.optim.optimizer import Optimizer
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import BaseFinetuning
from pytorch_lightning.plugins import DeepSpeedPlugin


class FreezeBase(BaseFinetuning):
    def freeze_before_training(self, pl_module: LightningModule) -> None:
        self.freeze(pl_module.layer1)

    def finetune_function(
            self,
            pl_module: LightningModule,
            epoch: int,
            optimizer: Optimizer,
            opt_idx: int,
    ) -> None:
        pass


class TestDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class FinetuningModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(32, 32)
        self.layer2 = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer2(self.layer1(x))

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()

    def configure_optimizers(self):
        return torch.optim.Adam(params = (filter(lambda p: p.requires_grad, self.parameters())), lr=0.1)


def run():
    train_data = DataLoader(TestDataset(32, 64), batch_size=2)
    val_data = DataLoader(TestDataset(32, 64), batch_size=2)
    test_data = DataLoader(TestDataset(32, 64), batch_size=2)

    model = FinetuningModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        fast_dev_run=True,
        plugins=DeepSpeedPlugin(stage=2),
        max_epochs=1,
        gpus=1,
        callbacks=[FreezeBase()]
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```
Call this code with at least 1 GPU to see the error. 

**Expected behavior**
Expect the experiment to run the same as it does without deepspeed plugged in.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/torch']
torch version .................... 1.9.0+cu102
torch cuda version ............... 10.2
nvcc version ..................... 10.2
deepspeed install path ........... ['/home/aj337a/.pyenv/versions/miniconda3-3.7-4.9.2/envs/py371/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.5.1, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.9, cuda 10.2
```

**System info (please complete the following information):**
 - OS: Ubuntu 16.04
 - GPU count and types 1 node with 8 x NVIDIA Tesla V100
 - Python version 3.7
 - Pytorch Lightning version 1.3.2

**Launcher context**
The experiment is launched with Pytorch lighting

**Comment by fcampagnexandr** [comment]
We have a similar issue when we freeze the model at the start, train for one epoch and then try to unfreeze and add params to the optimizer (see https://github.com/PyTorchLightning/pytorch-lightning/discussions/9774). As a consequence, we cannot use the deepspeed plugin to fine-tune a model trained with deepspeed, and end up with a very small batch size with the DDP plugin.

**Comment by SeanNaren** [comment]
Thanks for this issue! I think this is more related to Lightning than DeepSpeed so I made an issue to track on the Lightning side: https://github.com/PyTorchLightning/pytorch-lightning/issues/9833

**Comment by tjruwase** [comment]
Closing for lack of activity
