### ISSUE TITLE
[BUG] Multi-GPUs 'std::system_errorstd::system_error'

### ISSUE THREAD

**Issue by PythaGorilla** [microsoft/DeepSpeed#1515]
**Describe the bug**
Hi, I tried to train t5-3b with deepspeed and succeeded by using only one gpu (`--num_gpus==1`). But it always return a connection refused error whenever the setting `--num_gpus` is set to more than 2.  I couldn't find the root cause of this. Could you help to resolve the issue?

The error log:

> [2021-11-03 06:48:09,587] [WARNING] [runner.py:121:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
> [2021-11-03 06:48:09,732] [INFO] [runner.py:355:main] cmd = /lustre06/project/6000414/mojians/tqEnv/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 run_qg.py --model_name_or_path t5-3b --resume_from_checkpoint t5-3b-aeqg-hl --model_type t5 --tokenizer_name_or_path t5_qg_tokenizer --output_dir t5-3b-aeqg-hl --train_file_path data/train_data_aeqg_prepend_qg_format_t5.pt --valid_file_path data/valid_data_aeqg_prepend_qg_format_t5.pt --per_device_train_batch_size 4 --per_device_eval_batch_size 1 --gradient_accumulation_steps 1 --learning_rate 1e-4 --num_train_epochs 3 --seed 42 --do_train --do_eval --logging_steps 1000 --fp16 --deepspeed ds_config.json
> [2021-11-03 06:48:10,893] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0, 1]}
> [2021-11-03 06:48:10,894] [INFO] [launch.py:86:main] nnodes=1, num_local_procs=2, node_rank=0
> [2021-11-03 06:48:10,894] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
> [2021-11-03 06:48:10,894] [INFO] [launch.py:102:main] dist_world_size=2
> [2021-11-03 06:48:10,894] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0,1
> [2021-11-03 06:48:12,482] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
> [2021-11-03 06:48:12,482] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
> terminate called after throwing an instance of 'std::system_error'
> '
> '
>   what():    what():  Connection refused  what():  Connection refused
> Connection refused
> 
> Killing subprocess 755847
> Killing subprocess 755848
> Killing subprocess 755849
> Killing subprocess 755850
> 
> Traceback (most recent call last):
>  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/lustre06/project/6000414/mojians/tqEnv/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 171, in <module>
>     main()
>   File "/lustre06/project/6000414/mojians/tqEnv/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 161, in main
>     sigkill_handler(signal.SIGTERM, None)  # not coming back
>   File "/lustre06/project/6000414/mojians/tqEnv/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 139, in sigkill_handler
>     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)

**ds_report output**

```
> DeepSpeed C++/CUDA extension op report
> --------------------------------------------------
> NOTE: Ops not installed will be just-in-time (JIT) compiled at
>       runtime if needed. Op compatibility means that your system
>       meet the required dependencies to JIT install the op.
> --------------------------------------------------
> JIT compiled ops requires ninja
> ninja .................. [OKAY]
> --------------------------------------------------
> op name ................ installed .. compatible
> --------------------------------------------------
> cpu_adam ............... [NO] ....... [OKAY]
> cpu_adagrad ............ [NO] ....... [OKAY]
> fused_adam ............. [NO] ....... [OKAY]
> fused_lamb ............. [NO] ....... [OKAY]
> sparse_attn ............ [NO] ....... [OKAY]
> transformer ............ [NO] ....... [OKAY]
> stochastic_transformer . [NO] ....... [OKAY]
> async_io ............... [NO] ....... [OKAY]
> transformer_inference .. [NO] ....... [OKAY]
> utils .................. [NO] ....... [OKAY]
> quantizer .............. [NO] ....... [OKAY]
> --------------------------------------------------
> No CUDA runtime is found, using CUDA_HOME='/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2'
> DeepSpeed general environment info:
> torch install path ............... ['/lustre06/project/6000414/mojians/tqEnv/lib/python3.8/site-packages/torch']
> torch version .................... 1.10.0
> torch cuda version ............... 11.4
> nvcc version ..................... 11.0
> deepspeed install path ........... ['/lustre06/project/6000414/mojians/tqEnv/lib/python3.8/site-packages/deepspeed']
> deepspeed info ................... 0.5.5, unknown, unknown
> deepspeed wheel compiled w. ...... torch 1.10, cuda 11.4
```

**System info (please complete the following information):**
 - OS: Rocky Linux 8.4 (compute-canada)
 - GPU count and types: one machine with 4x A100
 - Python version: 3.8.1
 - CPU: 2 x AMD Milan 7413 @ 2.65 GHz 128M cache L3

**Launcher context**
deepspeed launcher

**Comment by PythaGorilla** [comment]
fixed after installing the typing-extension package.

**Comment by PythaGorilla** [comment]
It turns out to be the problem of the cluster. It has something to do with a conflict between pytorch and AMD cpu.
