### ISSUE TITLE
[BUG] Can not install DeepSpeed with DS_BUILD_OPS=1 or JIT-compile ops at runtime

### ISSUE THREAD

**Issue by dredwardhyde** [microsoft/DeepSpeed#1534]
**Describe the bug**
Can not install DeepSpeed with DS_BUILD_OPS=1 or JIT-compile ops at runtime.

**PyTorch version**:
Environment:
torch==1.10.0+cu113
torchvision==0.11.1+cu113

**CUDA SDK version**:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**GCC version**:
gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.

**To Reproduce**

1) git clone https://github.com/microsoft/DeepSpeed
    cd DeepSpeed
    run **sudo DS_BUILD_OPS=1 ../pip install -e . --global-option="build_ext" --global-option="-g" --global-option="-j8" --no-cache -v --disable-pip-version-check**

OR

2) run DS_BUILD_OPS=1 ./install.sh -s -n 

OR

3) Install from pypi
 run **DS_BUILD_OPS=1 pip install deepspeed --global-option="build_ext" --global-option="-g" --global-option="-j8" --no-cache -v --disable-pip-version-check**

**All these actions result in roughly the same error:**

[2021-11-08 18:19:01,584] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
[2021-11-08 18:19:01,589] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.5.5, git-hash=unknown, git-branch=unknown
Using amp fp16 backend
[2021-11-08 18:19:01,598] [INFO] [logging.py:68:log_dist] [Rank 0] initializing deepspeed groups
[2021-11-08 18:19:01,598] [INFO] [logging.py:68:log_dist] [Rank 0] initializing deepspeed model parallel group with size 1
[2021-11-08 18:19:01,598] [INFO] [logging.py:68:log_dist] [Rank 0] initializing deepspeed expert parallel group with size 1
[2021-11-08 18:19:01,598] [INFO] [logging.py:68:log_dist] [Rank 0] creating expert data parallel process group with ranks: [0]
[2021-11-08 18:19:01,598] [INFO] [logging.py:68:log_dist] [Rank 0] creating expert parallel process group with ranks: [0]
[2021-11-08 18:19:01,671] [INFO] [engine.py:207:__init__] DeepSpeed Flops Profiler Enabled: False
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Using /home/deepschneider/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected CUDA files, patching ldflags
Emitting ninja build file /home/deepschneider/.cache/torch_extensions/py38_cu113/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
[1/2] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/TH -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -std=c++14 -L/usr/local/cuda/lib64 -lcudart -lcublas -g -Wno-reorder -march=native -fopenmp -D__SCALAR__ -c /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
FAILED: cpu_adam.o 
c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/TH -isystem /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -std=c++14 -L/usr/local/cuda/lib64 -lcudart -lcublas -g -Wno-reorder -march=native -fopenmp -D__SCALAR__ -c /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
In file included from /home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp:1:
/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes/cpu_adam.h: In constructor ‘Adam_Optimizer::Adam_Optimizer(float, float, float, float, float, bool)’:
/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes/cpu_adam.h:39:49: error: ‘TILE’ was not declared in this scope; did you mean ‘FILE’?
   39 |         cudaMallocHost((void**)_doubled_buffer, TILE * sizeof(float));
      |                                                 ^~~~
      |                                                 FILE
/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp: In member function ‘void Adam_Optimizer::Step_1(float*, float*, float*, float*, size_t, __half*, bool)’:
/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp:51:61: error: ‘TILE’ was not declared in this scope; did you mean ‘FILE’?
   51 |         for (size_t t = rounded_size; t < _param_size; t += TILE) {
      |                                                             ^~~~
      |                                                             FILE
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/gpt_neo_xl_deepspeed.py", line 46, in <module>
    Trainer(model=model, args=training_args, train_dataset=train_dataset,
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1157, in train
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/transformers/deepspeed.py", line 362, in deepspeed_init
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 131, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 223, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 882, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 962, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 83, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 362, in load
    return self.jit_load(verbose)
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 394, in jit_load
    op_module = load(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'cpu_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f2351a98280>
Traceback (most recent call last):
  File "/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 97, in __del__
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Expected behavior**
Successfully compiled ops.

**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/torch']
torch version .................... 1.10.0+cu113
torch cuda version ............... 11.3
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/deepschneider/PycharmProjects/gpt-neo-fine-tuning-example/venv/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.10, cuda 11.3

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: 1xRTX A6000
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]: no
 - Python version: 3.8.10
 - Any other relevant info about your setup: no

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
Huggingface Trainer

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by dredwardhyde** [comment]
Essentially, all my attempts to build ops ended up with this error:
![FDrtH6hXEAQPJWb](https://user-images.githubusercontent.com/8986329/140778805-bc0f2c88-5ae4-4e9c-b912-43e84adb2747.png)

**Comment by dredwardhyde** [comment]
DeepSpeed 0.5.3 works fine with pytorch 1.8.1+cu111

**Comment by RezaYazdaniAminabadi** [comment]
Hi @dredwardhyde 

Thanks for reporting this. Please try this PR to see if it is resolved.
Thanks,
Reza

**Comment by dredwardhyde** [comment]
Hi, @RezaYazdaniAminabadi 
Well, at least the error is different now
![image](https://user-images.githubusercontent.com/8986329/140874095-4265bccb-a6f5-4646-ad81-5d433b130600.png)

**Comment by dredwardhyde** [comment]
**DS_BUILD_OPS=1 DS_BUILD_AIO=1 ./install.sh -s -n** works just fine, I'm trying to spot the difference

**Comment by RezaYazdaniAminabadi** [comment]
I used this: "sudo DS_BUILD_OPS=1 pip install . " at DeepSpeed directory.

**Comment by dredwardhyde** [comment]
This worked perfectly, thank you so much for this fix!
![image](https://user-images.githubusercontent.com/8986329/140885917-f70d11d7-8877-4914-b925-4e2114b36384.png)

**Comment by LarsVaehrens** [comment]
I have been facing the same compile error(regarding `x86_64-linux-gnu-g++`) as @dredwardhyde when I tried to install with pip and `DS_BUILD_OPS=1`. I just tried your PR and everything compiles nicely now with ds_report showing:

```sh
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
async_io ............... [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.6/dist-packages/torch']
torch version .................... 1.9.1+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['/usr/local/lib/python3.6/dist-packages/deepspeed']
deepspeed info ................... 0.5.6+43e6432, 43e6432, cpu-adam/fix-scalar-compile
deepspeed wheel compiled w. ...... torch 1.9, cuda 11.1
```

Unrelated to this issue, but I now run into a problem with NCCL when I get to the deepspeed initialization in my code `deepspeed.initialize(args, model, training_data, model_parameters, config)`:

```sh
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "main.py", line 47, in main
    config="conf/config.json",
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/__init__.py", line 141, in initialize
    config_params=config_params)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 193, in __init__
    self._configure_distributed_model(model)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 845, in _configure_distributed_model
    self._broadcast_model()
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 750, in _broadcast_model
    group=self.data_parallel_group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1094, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
```

I suppose this might be because I am running a single GPU system and something goes wrong with torch distributed. Would be greatful if anyone knows of a solution.

Additional information:

<details>

Virtualenv:
<details>

```
python3.6
torch==1.9.1+cu111
torchaudio==0.9.1
torchtext==0.10.1
torchvision==0.10.1+cu111
transformers==4.11.2
deepspeed==0.5.5
ninja==1.10.2.2
tensorboardX==1.8
triton==1.1.1
```
</details>

Hardware:
<details>

```
AMD Ryzen 9 5950X
32 GB RAM
RTX 3070 Ti 8 GB VRAM
NVMe M.2 SSD
```
</details>

Docker:
<details>

```
docker --version: Docker version 20.10.9, build c2ea9bc
nvidia-container-runtime --version: runc version 1.0.2
Docker image: nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
```
</details>

GCC:
<details>

```sh
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
```
</details>

nvcc --version:
<details>

```sh
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
</details>

</details>

**Comment by dredwardhyde** [comment]
I use this for a single GPU configuration

```python
import os
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '9994'
os.environ['RANK'] = "0"
os.environ['LOCAL_RANK'] = "0"
os.environ['WORLD_SIZE'] = "1"
```

**Comment by dredwardhyde** [comment]
Okay, I have another problem
With the installation from the screenshot above, I can't use nvme offloading
**DeepSpeed config**
```json
{
  "train_batch_size": 15,
  "fp16": {
    "enabled": true,
    "min_loss_scale": 1,
    "opt_level": "O3"
  },
  "zero_optimization": {
    "stage": 3,
    "offload_param": {
      "device": "nvme",
      "nvme_path": "/home/deepschneider/deepspeed",
      "buffer_count": 5,
      "buffer_size": 1e8,
      "max_in_cpu": 1e9
    },
    "offload_optimizer": {
      "device": "nvme",
      "nvme_path": "/home/deepschneider/deepspeed",
      "buffer_count": 4,
      "pipeline_read": false,
      "pipeline_write": false,
      "pin_memory": true
    },
    "contiguous_gradients": true,
    "overlap_comm": true
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 5e-05,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-08
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": 0,
      "warmup_max_lr": 5e-05,
      "warmup_num_steps": 100
    }
  },
  "aio": {
    "block_size": 1048576,
    "queue_depth": 8,
    "thread_count": 1,
    "single_submit": false,
    "overlap_events": true
  }
}
```
**Exception**:
![image](https://user-images.githubusercontent.com/8986329/140891094-52695d9b-8070-433b-8698-9fd6f47e70ba.png)

**Comment by LarsVaehrens** [comment]
Thank you @dredwardhyde. These settings helped with some other problem, but the NCCL error was resolved by using `DCCL_DEBUG=info` and getting the following two error messages:
```sh
d96bc6997760:75:75 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
d96bc6997760:75:240 [0] misc/nvmlwrap.cc:50 NCCL WARN Failed to open libnvidia-ml.so.1
```
After a little digging I found that I had to add `- utility` in `docker-compose.yml`:
```yml
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
              - gpu
              - utility
              - compute
```

**Comment by LarsVaehrens** [comment]
@dredwardhyde I am able to get nvme offloading to work with the following Deepspeed params in my config file:

```json
{
    "train_batch_size": 16,
    "gradient_accumulation_steps": 1,
    "gradient_clipping": 1.0,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.00015
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 3e-5,
            "warmup_num_steps": 100
        }
    },
    "fp16": {
        "enabled": true,
        "loss_scale": 0.0,
        "initial_scale_power": 32,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_optimization": {
        "stage": 3,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients": true,
        "offload_param": {
            "device": "nvme",
            "nvme_path": "/media/nvme",
            "pin_memory": false,
            "buffer_count": 5,
            "buffer_size": 1e8,
            "max_in_cpu": 1e9
        },
        "offload_optimizer": {
            "device": "nvme",
            "nvme_path": "/media/nvme",
            "pin_memory": false,
            "buffer_count": 4,
            "fast_init": true
        },
        "aio": {
            "block_size": 1048576,
            "queue_depth": 8,
            "thread_count": 1,
            "single_submit": false,
            "overlap_events": true
        },
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_prefetch_bucket_size": 5e8,
        "sub_group_size": 1e12,
        "stage3_param_persistence_threshold": 1e6,
        "stage3_gather_fp16_weights_on_model_save": false
    }
}
```

Partial terminal output:

```sh
[2021-11-09 09:27:39,983] [INFO] [engine.py:208:__init__] DeepSpeed Flops Profiler Enabled: False
Adam Optimizer #0 is created with scalar arithmetic capability.
Config: alpha=0.000150, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2021-11-09 09:27:40,198] [INFO] [engine.py:886:_configure_optimizer] Using DeepSpeed Optimizer param name adam as basic optimizer
[2021-11-09 09:27:40,207] [INFO] [engine.py:893:_configure_optimizer] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2021-11-09 09:27:40,207] [INFO] [utils.py:44:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2021-11-09 09:27:40,207] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 3 optimizer
Initializing ZeRO Stage 3
[2021-11-09 09:27:40,209] [INFO] [stage3.py:638:__init__] Reduce bucket size 500000000.0
[2021-11-09 09:27:40,209] [INFO] [stage3.py:639:__init__] Allgather bucket size 500000000.0
[2021-11-09 09:27:40,434] [INFO] [stage3.py:947:_configure_tensor_swapping] Tensor Swapping: Adding optimizer tensors
[2021-11-09 09:27:42,293] [INFO] [utils.py:30:print_object] SwapBufferManager:
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   count ........................ 4
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   dtype ........................ torch.float32
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   free_buffer_index ............ [0, 1, 2, 3]
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   gigabytes .................... 4.146228790283203
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   num_elems .................... 278248704
[2021-11-09 09:27:42,293] [INFO] [utils.py:34:print_object]   used_buffer_index ............ {}
[2021-11-09 09:27:42,294] [INFO] [utils.py:30:print_object] PartitionedOptimizerSwapper:
[2021-11-09 09:27:42,294] [INFO] [utils.py:34:print_object]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2021-11-09 09:27:42,294] [INFO] [utils.py:34:print_object]   aligned_bytes ................ 1024
[2021-11-09 09:27:42,294] [INFO] [utils.py:34:print_object]   dtype ........................ torch.float32
[2021-11-09 09:27:42,294] [INFO] [utils.py:34:print_object]   largest_numel ................ 278248704
[2021-11-09 09:27:42,294] [INFO] [utils.py:34:print_object]   min_aio_bytes ................ 1048576
[2021-11-09 09:27:42,295] [INFO] [utils.py:34:print_object]   numel_alignment .............. 256
[2021-11-09 09:27:42,295] [INFO] [utils.py:34:print_object]   swap_config .................. {'device': 'nvme', 'nvme_path': '/media/nvme', 'buffer_count': 4, 'pin_memory': False, 'pipeline_read': False, 'pipeline_write': False, 'fast_init': True, 'pipeline': False}
[2021-11-09 09:27:42,295] [INFO] [utils.py:34:print_object]   swap_element_size ............ 4
[2021-11-09 09:27:42,295] [INFO] [utils.py:34:print_object]   swap_folder .................. /media/nvme/zero_stage_3/optimizer/rank0
```

**Comment by dredwardhyde** [comment]
**/media/nvme** is just a folder or not?

**Comment by LarsVaehrens** [comment]
> @LarsVaehrens **/media/nvme** is just a folder or not?

I have my nvme drive mounted in `/media/` along with other RADI devices for easy access. You should checkout the [docs](https://www.deepspeed.ai/docs/config-json/#parameter-offloading) which describe what the `nvme_path` should be.

**Comment by dredwardhyde** [comment]
> > @LarsVaehrens **/media/nvme** is just a folder or not?
> 
> I have my nvme drive mounted in `/media/` along with other RADI devices for easy access. You should checkout the [docs](https://www.deepspeed.ai/docs/config-json/#parameter-offloading) which describe what the `nvme_path` should be.

Yeah, that's the problem, the docs are rather vague. I have only one nvme under **/dev/nvme0n1** with my OS installed (because it's an SFFPC), and I want to use part of it for params offloading.

**Comment by dredwardhyde** [comment]
So, for some reasons **nvme_swapper** is None at this point no matter what **nvme_path** I use
![image](https://user-images.githubusercontent.com/8986329/140933133-d7f1f26d-2006-44dd-a4ba-e7045224d1e9.png)

Exception is, accordingly, **AttributeError: 'NoneType' object has no attribute 'reserve_partitioned_swap_space'**

**Comment by dredwardhyde** [comment]
That's the whole output, no warnings, nothing
![image](https://user-images.githubusercontent.com/8986329/140936279-7ff823cc-4bc9-4171-8b13-7e53bf584c75.png)

**Comment by tjruwase** [comment]
@dredwardhyde, sorry about that. It seems you have hit a bug in our parameter offloading. I would like to repro this, but I have a few questions first. 
1. Are you able to run with optimizer offloading alone? This shares underlying logic with parameter offloading, so this can help to pinpoint where the issue might be. 
2. Can you please check your log for something like
![image](https://user-images.githubusercontent.com/4271600/140947113-748b4a94-a7ea-4a87-a0a8-8d1cba9d4e1d.png)

Thanks!

**Comment by dredwardhyde** [comment]
@tjruwase 
1. Yes, this works fine:
    ```json
      {
        "train_batch_size": 15,
        "fp16": {
          "enabled": true,
          "min_loss_scale": 1,
          "opt_level": "O3"
        },
        "zero_optimization": {
          "stage": 3,
          "offload_optimizer": {
            "device": "nvme",
            "nvme_path": "/home/deepschneider/deepspeed",
            "buffer_count": 4,
            "pipeline_read": false,
            "pipeline_write": false,
            "pin_memory": true
          },
          "allgather_partitions": true,
          "allgather_bucket_size": 5e8,
          "contiguous_gradients": true,
          "overlap_comm": true,
          "aio": {
            "block_size": 1048576,
            "queue_depth": 8,
            "thread_count": 1,
            "single_submit": false,
            "overlap_events": true
          }
        },
        "optimizer": {
          "type": "AdamW",
          "params": {
            "lr": 5e-05,
            "betas": [
              0.9,
              0.999
            ],
            "eps": 1e-08
          }
        },
        "scheduler": {
          "type": "WarmupLR",
          "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 5e-05,
            "warmup_num_steps": 100
          }
        }
      }
      ```
    
![image](https://user-images.githubusercontent.com/8986329/140948788-220e8472-215b-4d6b-9e69-fff29063eac8.png)

2. I can't find AsyncPartitionedParameterSwapper in the log (you can see the full output related to swapper above)

**Comment by tjruwase** [comment]
@dredwardhyde, thanks for the response. I think the problem is that swapper for parameter offloading was not initialized, and I would like to investigate further. Since your original issue regarding compiling cpu_adam is now fixed, do you want to open a different issue for this parameter offloading problem?

**Comment by dredwardhyde** [comment]
Yeah, I'll open a new issue now

**Comment by dredwardhyde** [comment]
Opened [#1543 ](https://github.com/microsoft/DeepSpeed/issues/1543)
