### ISSUE TITLE
subprocess.CalledProcessError: Command '['/data/xingdp/install/anaconda3/envs/py36th17/bin/python',

### ISSUE THREAD

**Issue by ReinholdM** [microsoft/DeepSpeed#1581]
Hi! I'm trying to train a big model with deepspeed but met the following error after the program running for a while. Thank you for your reply
```shell
[2021-11-21 08:32:07,148] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250621
[2021-11-21 08:32:07,149] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250622
[2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250623
[2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250624
[2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250625
[2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250626
[2021-11-21 08:32:07,151] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250629
[2021-11-21 08:32:07,153] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250632
Traceback (most recent call last):
  File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 167, in <module>
    main()
  File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 156, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 137, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/xingdp/install/anaconda3/envs/py36th17/bin/python', '-u', 'run_deepspeedpy', '--local_rank=7', '--deepspeed', '--deepspeed_config', 'deepspeed_bsz4096_adam_condig.json', '--cf', 'lamb.json', '--max_seq_length', '128', '--job_name', 'deepspeed_test', '--max_steps', '32', '--print_steps', '1', '--deepspeed_transformer_kernel', '--output_dir', './deepspeed_logs/']' died with <Signals.SIGKILL: 9>.```

**Comment by SamTube405** [comment]
I was having the same issue, any update?

**Comment by 9pearl** [comment]
Hello，how did you solve this problem

> Hi! I'm trying to train a big model with deepspeed but met the following error after the program running for a while. Thank you for your reply
> 
> ```shell
> [2021-11-21 08:32:07,148] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250621
> [2021-11-21 08:32:07,149] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250622
> [2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250623
> [2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250624
> [2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250625
> [2021-11-21 08:32:07,150] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250626
> [2021-11-21 08:32:07,151] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250629
> [2021-11-21 08:32:07,153] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 250632
> Traceback (most recent call last):
>   File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 167, in <module>
>     main()
>   File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 156, in main
>     sigkill_handler(signal.SIGTERM, None)  # not coming back
>   File "/data/xingdp/install/anaconda3/envs/py36th17/lib/python3.6/site-packages/deepspeed/launcher/launch.py", line 137, in sigkill_handler
>     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> subprocess.CalledProcessError: Command '['/data/xingdp/install/anaconda3/envs/py36th17/bin/python', '-u', 'run_deepspeedpy', '--local_rank=7', '--deepspeed', '--deepspeed_config', 'deepspeed_bsz4096_adam_condig.json', '--cf', 'lamb.json', '--max_seq_length', '128', '--job_name', 'deepspeed_test', '--max_steps', '32', '--print_steps', '1', '--deepspeed_transformer_kernel', '--output_dir', './deepspeed_logs/']' died with <Signals.SIGKILL: 9>.```
> ```

**Comment by Dionysusssss** [comment]
MARK
