### ISSUE TITLE
[BUG] ZeRO 3: save_checkpoint immediately followed by load_checkpoint breaks

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#1749]
**Describe the bug**

This is the reverse of https://github.com/microsoft/DeepSpeed/issues/1748 and is also ZeRO 3-specific.

Here the opposite fails: 

```
deepspeed.load_checkpoint()
# no train in between:
deepspeed.save_checkpoint()
```

**To Reproduce**

```
# add to tests/unit/test_checkpointing.py

def test_immediate_save_load(tmpdir):

    config_dict = {
        "train_batch_size": 4,
        "optimizer": {
            "type": 'Adam'
        },
        "fp16": {
            "enabled": True,
            "initial_scale_power": 8
        },
        "zero_optimization": {
            "stage": 3,
        }
    }
    hidden_dim = 10
    model = SimpleModel(hidden_dim)
    args = args_from_dict(tmpdir, config_dict)

    @distributed_test(world_size=[1])
    def _test_immediate_save_load(args, model, tmpdir):

        ds_model = create_deepspeed_model(args=args, model=model, base_optimizer=None)
        ds_model.save_checkpoint(tmpdir)
        ds_model.load_checkpoint(tmpdir, load_optimizer_states=False, load_lr_scheduler_states=False, load_module_only=False)

    _test_immediate_save_load(args, model, tmpdir)
```

```
$ pytest tests/unit/test_checkpointing.py -k test_immediate_save_load
[...]
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/nvme1/code/github/00optimize/DeepSpeed-save_16bit_model-save_checkpoint_prologue/tests/unit/common.py", line 93, in dist_init
    run_func(*func_args, **func_kwargs)
  File "/mnt/nvme1/code/github/00optimize/DeepSpeed-save_16bit_model-save_checkpoint_prologue/tests/unit/test_checkpointing.py", line 1298, in _test_immediate_save_load
    ds_model.load_checkpoint(tmpdir, load_optimizer_states=False, load_lr_scheduler_states=False, load_module_only=False)
  File "/mnt/nvme1/code/github/00optimize/DeepSpeed-save_16bit_model-save_checkpoint_prologue/deepspeed/runtime/engine.py", line 2452, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/mnt/nvme1/code/github/00optimize/DeepSpeed-save_16bit_model-save_checkpoint_prologue/deepspeed/runtime/engine.py", line 2506, in _load_checkpoint
    self.load_module_state_dict(state_dict=checkpoint['module'],
  File "/mnt/nvme1/code/github/00optimize/DeepSpeed-save_16bit_model-save_checkpoint_prologue/deepspeed/runtime/engine.py", line 2336, in load_module_state_dict
    self.module.load_state_dict(state_dict, strict=strict)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SimpleModel:
        size mismatch for linears.0.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([10, 10]).
        size mismatch for linears.0.bias: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([10]).
```

@tjruwase, @jeffra

**Comment by stas00** [comment]
actually after filing this one I recalled that we have diagnosed this condition before. That was the whole point of doing reinit of deepspeed engine between save and load that I had to add to HF Transformers:

https://github.com/huggingface/transformers/blob/0fe17f375a4f0fdd9aea260d0645ccfd4896e958/src/transformers/trainer.py#L1521-L1530

So 2 things about this Issue that are new:

1. I added a failing test that you can add to the test suite - saves you time
2. until this is resolved could this situation be somehow detected at least and asserted instead of fail in the very not-obvious way?
e.g.  `load_checkpoint` could check if some state that `save_checkpoint` creates is there?

and then assert with something like:

> currently it's not possible to `load_checkpoint` after `save_checkpoint` was called and requires a new deepspeed engine to use `load_checkpoint` in this situation.
