### ISSUE TITLE
[BUG] master breaks one of the HF/DS integration tests on 1 gpu

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#1763]
**Describe the bug**

I guess we always run the integration tests on multiple GPUs so we haven't spotted the problem despite running integration tests - @jeffra, do you think it'd be worthwhile to run another set on a single GPU? So far this is the only problem we have missed so perhaps it's OK to keep it as it is now. The HF daily CI discovered it as it runs both so we have it covered there. I just didn't have time to investigate it until now.

**To Reproduce**

1. Everything works up-to and including 0.5.10 - it breaks at some point after Jan 18 commits - so fails on master
2. Everything works with multi-gpu - the breakage is on 1 gpu only
3. The problem starts happening with pytorch-1.10 and continues with pt-nightly

```
git clone https://github.com/huggingface/transformers
cd transformers # assuming you got all the dependencies installed
CUDA_VISIBLE_DEVICES=0 RUN_SLOW=1 pytest tests/deepspeed/test_model_zoo.py::TestDeepSpeedModelZoo::test_zero_to_fp32_zero3_trans_fsmt -sv
```

```
Traceback (most recent call last):
  File "/mnt/nvme1/code/huggingface/transformers-master/examples/pytorch/translation/run_translation.py", line 624, in <module>
    main()
  File "/mnt/nvme1/code/huggingface/transformers-master/examples/pytorch/translation/run_translation.py", line 541, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/trainer.py", line 1398, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/trainer.py", line 1982, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/trainer.py", line 2014, in compute_loss
    outputs = model(**inputs)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/engine.py", line 1597, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/models/fsmt/modeling_fsmt.py", line 1163, in forward
    outputs = self.model(
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1109, in _call_impl
    result = hook(self, input)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/zero/stage3.py", line 1412, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/zero/stage3.py", line 1529, in pre_sub_module_forward_function
    self.param_coordinator.fetch_sub_module(sub_module)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed/deepspeed/runtime/zero/stage3.py", line 358, in fetch_sub_module
    raise RuntimeError(
RuntimeError: tracing error at step 1: expected the next 1 parameters in the parameter fetch queue to be ({'id': 1, 'status': 'AVAILABLE', 'numel': 168096, 'ds_numel': 168096, 'shape': (42024, 4), 'ds_shape': (42024, 4), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {1}},) but got ({'id': 2, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 4104, 'shape': (0,), 'ds_shape': (1026, 4), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set()},).
```

So unless it's obvious to you which commit created this issue, we will need to bisect. But good news I can tell that our CI run this test successfully on Jan 18. So it broke some time after

This works just fine: (same as the report, but 2 gpus this time)
```
CUDA_VISIBLE_DEVICES=0,1 RUN_SLOW=1 pytest tests/deepspeed/test_model_zoo.py::TestDeepSpeedModelZoo::test_zero_to_fp32_zero3_trans_fsmt -sv
```

@jeffra, @tjruwase

**Comment by stas00** [comment]
OK, `git bisected` it - it's the huge bf16 commit that broke it: https://github.com/microsoft/DeepSpeed/commit/4912e0ad7efcaf97389ae944259aa0e9f331038a

**Comment by stas00** [comment]
@jeffra, just a gentle reminder that this regression needs to be resolved. thank you!

**Comment by stas00** [comment]
I suspect that @tjruwase's tracing improvement PR https://github.com/microsoft/DeepSpeed/pull/1916 resolved this bug as well. (not 100% sure but it no longer fails with master).

So closing this.
