### ISSUE TITLE
[BUG] T5-11B Inference Error 

### ISSUE THREAD

**Issue by philschmid** [microsoft/DeepSpeed#1772]
**Describe the bug**

I am trying to run `T5-11B` using `deepspeed.init_inference`. I am running on a `g4dn.metal` which as the following stats 

![Bildschirmfoto 2022-02-15 um 10 20 45](https://user-images.githubusercontent.com/32632186/154031578-21d6c514-5ef7-42f2-828d-3731e474e997.png)

The script i use: 

```python
# Coming from https://github.com/microsoft/DeepSpeed/issues/1332#issuecomment-1020617723
   
import os
import torch
import deepspeed
import transformers
import time
from deepspeed import module_inject
from transformers import pipeline
from transformers.models.t5.modeling_t5 import T5Block


# Get local gpu rank from torch.distributed/deepspeed launcher
local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

print(
    "***************** Creating model in RANK ({0}) with WORLD_SIZE = {1} *****************"
    .format(local_rank,
            world_size))

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig

pipe = pipeline("text2text-generation", model="t5-11b")
print("model loaded on cpu")

assert pipe.model.config.num_heads % world_size == 0, f"{pipe.model.config.num_heads} % {world_size} = {pipe.model.config.num_heads % world_size} \nTo run the model parallel across the GPUs, the attention_heads require to be divisible by the world_size!This is because the attention computation is partitioned evenly among the parallel GPUs."

pipe.model = deepspeed.init_inference(
    pipe.model,
    mp_size=world_size,
    dtype=torch.float,
    injection_policy={T5Block: ('SelfAttention.o', 'EncDecAttention.o', 'DenseReluDense.wo')}
)

pipe.device = torch.device(f'cuda:{local_rank}')

print(
    f'({local_rank}) after deepspeed: allocated:{round(torch.cuda.memory_allocated()/1000/1000,2)}MB, cached:{round(torch.cuda.memory_allocated()/1000/1000,4)}MB'
)
print("check GPU memory usage")
time.sleep(10)


output = pipe("Is this review positive or negative? Review: this is the best cast iron skillet you will ever buy")

if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(output)
```

How i execute the script `python -m deepspeed.launcher.runner --num_gpus 8 t5_mp.py`

The CLI output

```bash
[2022-02-15 09:13:38,583] [WARNING] [runner.py:155:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-02-15 09:13:38,830] [INFO] [runner.py:438:main] cmd = /usr/bin/python3.7 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 t5_mp.py
[2022-02-15 09:13:39,586] [INFO] [launch.py:103:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2022-02-15 09:13:39,586] [INFO] [launch.py:110:main] nnodes=1, num_local_procs=8, node_rank=0
[2022-02-15 09:13:39,586] [INFO] [launch.py:122:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2022-02-15 09:13:39,586] [INFO] [launch.py:123:main] dist_world_size=8
[2022-02-15 09:13:39,586] [INFO] [launch.py:125:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
***************** Creating model in RANK (5) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (6) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (1) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (2) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (7) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (0) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (3) with WORLD_SIZE = 8 *****************
***************** Creating model in RANK (4) with WORLD_SIZE = 8 *****************
[2022-02-15 09:17:37,619] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50394
[2022-02-15 09:17:37,623] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50395
[2022-02-15 09:17:37,626] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50396
[2022-02-15 09:17:37,626] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50397
[2022-02-15 09:17:37,626] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50398
[2022-02-15 09:17:37,627] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50399
[2022-02-15 09:17:37,628] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50400
[2022-02-15 09:17:37,628] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 50401
[2022-02-15 09:17:37,628] [ERROR] [launch.py:184:sigkill_handler] ['/usr/bin/python3.7', '-u', 't5_mp.py', '--local_rank=7'] exits with return code = -9
```

**Expected behavior**
It looks like the script exits before the `init_inference` is even called, but i don't know why. Is there a way to improve the error? technically it should be possible to load the model on CPU since the machine has `384GB` Memory. Any idea why it is not working? is there something i am doing wrong?  

**ds_report output**
Please run `ds_report` to give us details about your setup.

```bash
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [YES] ...... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/.local/lib/python3.7/site-packages/torch']
torch version .................... 1.10.2+cu113
torch cuda version ............... 11.3
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/ubuntu/DeepSpeed/deepspeed']
deepspeed info ................... 0.6.0+5fe5b38, 5fe5b38, master
deepspeed wheel compiled w. ...... torch 1.10, cuda 11.3
```

cc @stas00 @RezaYazdaniAminabadi

**Comment by stas00** [comment]
Had to translate the table headers from German, so you have 384GB CPU memory and 128GB of GPU memory, 8x 16GB 

So you're trying to load 40 x 8 = 320GB of CPU, and the way `from_pretrained` works it uses up 2x model size by default. so 40*8*16 = 640 - can't fit and cgroups kills it - not sure why the system doesn't indicate that.

In order to use 1x cpu memory a `low_cpu_mem_usage=True` needs to be passed to `from_pretrained`. Perhaps for the sake of the experiment, hack the pipeline to use that. Actually I see in its API it has `model_kwargs` arg, so perhaps the fix here is:

```
pipe = pipeline("text2text-generation", model="t5-11b", low_cpu_mem_usage=True)
```
or did they mean to actually pass `model_kwargs` with a dict? have to scroll down a bit here to the API:
https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline

But really, in this situation clearly deepspeed-inference needs to provide a container like `zero.Init` which will split and instantiate the model directly on the gpus. Ideally it should re-use the `zero.Init` we are already using in `from_pretrained` here:

https://github.com/huggingface/transformers/blob/f45ac11fb32ba17e3e1fa831c30438ff9972a1ee/src/transformers/modeling_utils.py#L524-L531

BTW, does it work if you do t5-3b?

**Comment by molly-smith** [comment]
Please reopen if the issue still exists.

**Comment by ZeyiLiao** [comment]
Hi @stas00 , I want to do t5-11b inference via deepspeed-inference and here is my scripts:
```

import torch
import os
from transformers import AutoTokenizer, AutoModelForCausalLM,AutoModelForSeq2SeqLM
import deepspeed
import torch.distributed as dist
from argparse import ArgumentParser


DEFAULT_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


parser = ArgumentParser()
parser.add_argument("--local_rank", required=False, type=int, help="used by dist launchers")
parser.add_argument("--model_id", default= "t5-11b")

args = parser.parse_args()


local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))
print(f'We have args now and local rank is {local_rank}, and world_size is {world_size}')

# Model Repository on huggingface.co
model_id = args.model_id

# load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
# tokenizer.pad_token = tokenizer.eos_token
# tokenizer.padding_side = 'left'


def print_model_rank0(model):
    if local_rank != 0:
        return
    for name,param in model.named_parameters():
        print(name, param.device)

model = AutoModelForSeq2SeqLM.from_pretrained(model_id, torch_dtype=torch.float16)
print_model_rank0(model)



# init deepspeed inference engine
ds_model = deepspeed.init_inference(
    model=model,      # Transformers models
    mp_size=world_size,        # Number of GPU
    dtype=torch.float16, # dtype of the weights (fp16)
    replace_method="auto", # Lets DS autmatically identify the layer to replace
    replace_with_kernel_inject=True, # replace the model with the kernel injector
)
# print(f"model is loaded on device {ds_model.module.device}")

print(f'We have at {local_rank}')
print(f'rank = dist.get_rank() {dist.get_rank()}')
print(f'Look at where model.device {model.device}')

print_model_rank0(ds_model)




# Test model
example = "My name is Philipp and I"
input_ids = tokenizer(example,return_tensors="pt").input_ids.to(DEFAULT_DEVICE)
logits = ds_model.generate(input_ids, do_sample=True, max_length=30)
print(f'local rank is {local_rank} and the generation is: {tokenizer.decode(logits[0].tolist())}')
#     'My name is Philipp and I live in Freiburg in Germany and I have a project called Cenapen. After three months in development already it is finally finished – and it is a Linux based device / operating system on an ARM Cortex A9 processor on a Raspberry Pi.\n\nAt the moment it offers the possibility to store data locally, it can retrieve data from a local, networked or web based Sqlite database (I’m writing this tutorial while I’'

```

And I have two questions here:
1. When I print the model device, I notice that all parameters belong to cuda:0, this is because TP? Like part of the weights are located at cuda 0
2. From [here](https://www.deepspeed.ai/tutorials/inference-tutorial/), I notice that at the second paragraph, it said :' It will automatically partition the model as necessary', so does that means that when we do smaller model like 't5-base', it actually wont do TP but just copy the whole model to another GPU since one model can fit into one GPU.

**Comment by stas00** [comment]
@ZeyiLiao, you probably want to tag @RezaYazdaniAminabadi on ds-inference questions as he is the author of this project and will be much better at answering questions than myself.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @ZeyiLiao

**Comment by RezaYazdaniAminabadi** [comment]
> Had to translate the table headers from German, so you have 384GB CPU memory and 128GB of GPU memory, 8x 16GB
> 
> So you're trying to load 40 x 8 = 320GB of CPU, and the way `from_pretrained` works it uses up 2x model size by default. so `40*8*16 = 640` - can't fit and cgroups kills it - not sure why the system doesn't indicate what did the killing.
> 
> In order to use 1x cpu memory a `low_cpu_mem_usage=True` needs to be passed to `from_pretrained`. Perhaps for the sake of the experiment, hack the pipeline to use that. Actually I see in its API it has `model_kwargs` arg, so perhaps the fix here is:
> 
> ```
> pipe = pipeline("text2text-generation", model="t5-11b", model_kwargs=dict(low_cpu_mem_usage=True))
> ```
> 
> But really, in this situation clearly deepspeed-inference needs to provide a container like `zero.Init` which will split and instantiate the model directly on the gpus. Ideally it should re-use the `zero.Init` we are already using in `from_pretrained` here:
> 
> https://github.com/huggingface/transformers/blob/f45ac11fb32ba17e3e1fa831c30438ff9972a1ee/src/transformers/modeling_utils.py#L524-L531
> 
> BTW, does it work if you do t5-3b?

For this issue, I am wondering if we can solve it by initializing this with meta tensors and then load the model onto GPU directly. @philschmid, did you try this with `low_cpu_mem_usage` and see if it resolves the issue as suggested by @stas00 ?
Thanks,
Reza

**Comment by ZeyiLiao** [comment]
@RezaYazdaniAminabadi 



Hi Reze, thanks for your reply and it solves my problem. I modify the code according your advice and add a new line `ds_model._validate_model_kwargs({})`. 

```

import torch
import os

from transformers import AutoTokenizer, AutoModelForCausalLM,AutoModelForSeq2SeqLM
import deepspeed
import torch.distributed as dist
from argparse import ArgumentParser
from transformers.models.t5.modeling_t5 import T5Block


DEFAULT_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


parser = ArgumentParser()
parser.add_argument("--local_rank", required=False, type=int, help="used by dist launchers")
parser.add_argument("--model_id", default= "t5-3b")

args = parser.parse_args()


local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))
print(f'We have args now and local rank is {local_rank}, and world_size is {world_size}')

# Model Repository on huggingface.co
model_id = args.model_id

# load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
# tokenizer.pad_token = tokenizer.eos_token
# tokenizer.padding_side = 'left'


def print_model_rank0(model):
    if local_rank != 0:
        return
    for name,param in model.named_parameters():
        print(name, param.device)

def print_model_rank1(model):
    if local_rank != 1:
        return
    for name,param in model.named_parameters():
        print(name, param.device)


model = AutoModelForSeq2SeqLM.from_pretrained(model_id, torch_dtype=torch.float16)
print_model_rank0(model)


# t5 doesn't have supported kernel
# init deepspeed inference engine
ds_model = deepspeed.init_inference(
    model=model,      # Transformers models
    mp_size=world_size,        # Number of GPU
    dtype=torch.float16, # dtype of the weights (fp16)
    injection_policy={T5Block: ('SelfAttention.o', 'EncDecAttention.o', 'DenseReluDense.wo')}
)
# print(f"model is loaded on device {ds_model.module.device}")


print(f'We have at {local_rank}')
print(f'rank = dist.get_rank() {dist.get_rank()}')
print(f'Look at where model.device {model.device}')

print_model_rank0(ds_model)
print_model_rank1(ds_model)


# Test model
example = "My name is Philipp and I"
input_ids = tokenizer(example,return_tensors="pt").input_ids.to(DEFAULT_DEVICE)

ds_model._validate_model_kwargs({})

logits = ds_model.generate(input_ids, do_sample=True, max_length=30)
print(f'local rank is {local_rank} and the generation is: {tokenizer.decode(logits[0].tolist())}')
#     'My name is Philipp and I live in Freiburg in Germany and I have a project called Cenapen. After three months in development already it is finally finished – and it is a Linux based device / operating system on an ARM Cortex A9 processor on a Raspberry Pi.\n\nAt the moment it offers the possibility to store data locally, it can retrieve data from a local, networked or web based Sqlite database (I’m writing this tutorial while I’'

```


This is because I am modifying the inner code of generation and just have a function named `generate(ds_model)` and pass the model into this function. I followed what huggingface did, i.e. `ds_model._validate_model_kwargs({})`, but it said that
```
Traceback (most recen
t call last):
  File "test.py", line 73, in <module>
    ds_model._validate_model_kwargs({})
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))

AttributeError: 'InferenceEngine' object has no attribute '_validate_model_kwargs'
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    ds_model._validate_model_kwargs({})
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'InferenceEngine' object has no attribute '_validate_model_kwargs'
[2022-11-12 01:18:46,970] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 87369
[2022-11-12 01:18:46,970] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 87370
[2022-11-12 01:18:47,015] [ERROR] [launch.py:292:sigkill_handler] ['/home/zeyi/miniconda3/envs/longtail/bin/python', '-u', 'test.py', '--local_rank=1'] exits with return code = 1
```

How can I deal with it?



Also Can you help me about where can I find more details about `injection_policy={T5Block: ('SelfAttention.o', 'EncDecAttention.o', 'DenseReluDense.wo')}` since I am kind confused about what does this line mean. Just incase I may need to customize it if I encounter the same problem later.

**Comment by molly-smith** [comment]
Hi @ZeyiLiao, please open a new issue if you still need assistance. We are closing this since the original issue has been addressed.
