### ISSUE TITLE
[BUG] save_checkpoint() missing some params

### ISSUE THREAD

**Issue by skpig** [microsoft/DeepSpeed#1789]
**Describe the bug**
I'm using deepspeed to train GNN model from pgn (https://github.com/pyg-team/pytorch_geometric). But after I save the model with `engine.save_checkpoint()`, I couldn't load the checkpoint because of missing parameters.

**To Reproduce**
I provide a code snippet.
I launch `save()` function with `deepspeed --include="localhost:2,3" train.py  --deepspeed  --deepspeed_config config/ds_config.json` (I've tried no-ZeRO, ZeRO1 and ZeRO2 settings, all failed). 
```
def save():
    from torch_geometric.nn import GATConv
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", default=0, type=int,
                        help="local_rank for distributed training on gpus")
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()
    os.environ['MASTER_ADDR'] = 'localhost'  #
    os.environ['MASTER_PORT'] = '12345'  #
    args.local_rank = int(os.environ['LOCAL_RANK'])

    model = GATConv(4, 2, heads=2, edge_dim=3)
    engine, _, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=model.parameters())
    engine.save_checkpoint('Model/tmp_model', tag='checkpoint-0')
```
And load checkpoint with python launcher.
```
def load():
    from torch_geometric.nn import GATConv
    model = GATConv(4, 2, heads=2, edge_dim=3)
    model = load_state_dict_from_zero_checkpoint(model, "Model/tmp_model", 'checkpoint-0')
```

**output**
```
[2022-02-24 02:43:46,824] [INFO] [zero_to_fp32.py:425:load_state_dict_from_zero_checkpoint] Extracting fp32 weights
Processing zero checkpoint 'Model/tmp_model/checkpoint-0'
Detected checkpoint of type zero stage 2, world_size: 2
Reconstructed fp32 state dict with 6 params 44 elements
[2022-02-24 02:43:46,826] [INFO] [zero_to_fp32.py:428:load_state_dict_from_zero_checkpoint] Overwriting model with fp32 weights
Traceback (most recent call last):
  File "/home/huangbz/_project2/train.py", line 344, in <module>
    model = load_state_dict_from_zero_checkpoint(model, "Model/tmp_model", 'checkpoint-0')
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/deepspeed/utils/zero_to_fp32.py", line 430, in load_state_dict_from_zero_checkpoint
    model.load_state_dict(state_dict, strict=False)
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1468, in load_state_dict
    load(self)
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1463, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1372, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/huangbz/.conda/envs/Graph/lib/python3.6/site-packages/torch_geometric/nn/dense/linear.py", line 131, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'lin_dst.weight'
```

**System info (please complete the following information):**
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Python version: 3.6
 - PGN version: 2.0.3

**Comment by tjruwase** [comment]
@skpig, apologies for the late reply. Can you please check if this problem remains the latest tree?

**Comment by skpig** [comment]
Yes, it remains in the current master branch. @tjruwase 
I've already dug into the code and found the missing params. Here I also provide a simpler net that also reproduces the bug.
```
class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(1,2)
        self.linear2 = self.linear1

    def forward(self, x):
        return self.linear1(self.linear2(x))
```

**Comment by skpig** [comment]
@tjruwase  any advice?

**Comment by tjruwase** [comment]
@skpig, yes it is possible that DeepSpeed model checkpointing might miss some model states. To help with this situation, [save_checkpoint()](https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html#saving-training-checkpoints) accepts a `client_state` argument which is a dict that the client use to store any arbitrary state information. At checkpoint load time, [load_checkpoint()](https://deepspeed.readthedocs.io/en/latest/model-checkpointing.html#saving-training-checkpoints) will return this `client_state` dict for the client to restore as appropriate. See a suggested usage below. Can you try this?

```python
client_state = {...}
engine.save_checkpoint(..., client_state=client_state)
....
load_path, client_state = engine.load_checkpoint(...)
... = client_state
```

**Comment by tjruwase** [comment]
@skpig, apologies for the confusion. It is possible that I may have misunderstood your original question. I thought you wanted to save some additional parameters that are either not part of the module or won't be properly saved by `torch.save()`. DeepSpeed uses `torch.save()` internally. So, I suggest trying two things:

1. Confirm that you can `torch.save()` and `torch.load()` work for you as expected. In other words, don't use deepspeed. 
2. Regarding checkpoint loading. Yes, this happens after the model and engine has been initialized. Please see the sequence below:

   ```python
     model = GATConv(4, 2, heads=2, edge_dim=3)
     engine, _, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=model.parameters())
     load_path, client_state = engine.load_checkpoint(load_dir='Model/tmp_model', 'checkpoint-0')
  ```

In the meantime, I will try to run your code snippet on my side.

**Comment by tjruwase** [comment]
@skpig, how is it going? Just wanted to share that the following script worked for me. Can you try it on your side with the following commands:

1. To save:  `python test.py`
2. To load:  `python test.py --load`

```python
import argparse
import os 
import deepspeed 
import torch_geometric 
from torch_geometric.nn import GATConv

ds_config = {
    "train_batch_size": 1,
    "train_micro_batch_size_per_gpu": 1,
    "optimizer": {
        "type": "Adam"
    }    
}

def init_engine():
    model = GATConv(4, 2, heads=2, edge_dim=3)
    engine, _, _, _ = deepspeed.initialize(model=model, model_parameters=model.parameters(), config=ds_config)
    return engine 

def load():
    engine = init_engine()
    load_path, client_state = engine.load_checkpoint(load_dir='/tmp/Model/tmp_model', tag='checkpoint-0')
    print(f'successfully loaded checkpoint from {load_path}')


def save():   
    engine = init_engine()
    engine.save_checkpoint('/tmp/Model/tmp_model', tag='checkpoint-0')


parser = argparse.ArgumentParser()
parser.add_argument('--load', action='store_true', help='Load checkpoint')
args = parser.parse_args()

if args.load:
    load()
else:
    save()
