### ISSUE TITLE
[BUG] Job fails with NCCLTimeout error

### ISSUE THREAD

**Issue by amsword** [microsoft/DeepSpeed#1834]
**Describe the bug**
The job fails with the following error. After restarting, the job can continue, which means the node is healthy. Any idea on what is going on? Thanks

```
[1,19]<stderr>:RuntimeError[1,19]<stderr>:: NCCL communicator was aborted on rank 19.
[1,60]<stderr>:Traceback (most recent call last):
[1,60]<stderr>:  File "src/qd/qd_common.py", line 3868, in <module>
[1,60]<stderr>:    locals()[function_name](**kwargs)
[1,60]<stderr>:  File "src/qd/qd_common.py", line 3375, in execute_func
[1,60]<stderr>:    return getattr(modules, info['import'])(**info['param'])
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipeline.py", line 679, in pipeline_train_eval_multi
[1,60]<stderr>:    pip.ensure_train()
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1062, in ensure_train
[1,60]<stderr>:    train_result = self.train()
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1405, in train
[1,60]<stderr>:    self.do_train(train_loader, model, optimizer, scheduler, checkpointer,
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1524, in do_train
[1,60]<stderr>:    DeepspeedTrainer(
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1540, in do
[1,60]<stderr>:    self.inner_loop()
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1453, in inner_loop
[1,60]<stderr>:    self.inner_loop_step()
[1,60]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1584, in inner_loop_step
[1,60]<stderr>:    self.model_engine.backward(loss)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1740, in backward
[1,60]<stderr>:    self.allreduce_gradients()
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1668, in allreduce_gradients
[1,60]<stderr>:    self.optimizer.reduce_gradients(
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 589, in reduce_gradients
[1,60]<stderr>:    self.reduce_ready_partitions_and_remove_grads(param, i)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1237, in reduce_ready_partitions_and_remove_grads
[1,60]<stderr>:    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 798, in reduce_independent_p_g_buckets_and_remove_grads
[1,60]<stderr>:    self.reduce_ipg_grads()
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1191, in reduce_ipg_grads
[1,60]<stderr>:    self.buffered_reduce_fallback(
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1386, in buffered_reduce_fallback
[1,60]<stderr>:    self.allreduce_no_retain(bucket,
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1374, in allreduce_no_retain
[1,60]<stderr>:    self.allreduce_and_copy(small_bucket, rank=rank, log=log)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1354, in allreduce_and_copy
[1,60]<stderr>:    allreduced = self.allreduce_bucket(small_bucket, rank=rank, log=log)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1326, in allreduce_bucket
[1,60]<stderr>:    dist.all_reduce(tensor_to_allreduce, group=self.dp_process_group)
[1,60]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1209, in all_reduce
[1,60]<stderr>:    work = group.allreduce([tensor], opts)
[1,60]<stderr>:RuntimeError: NCCL communicator was aborted on rank 60.
[1,231]<stderr>:[E ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[1,231]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
[1,231]<stderr>:  what():  [1,231]<stderr>:[Rank 231] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805392 milliseconds before timing out.
[1,128]<stderr>:[E ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[1,128]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
[1,128]<stderr>:  what():  [Rank 128] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1804322 milliseconds before timing out.
[1,104]<stderr>:Traceback (most recent call last):
[1,104]<stderr>:  File "src/qd/qd_common.py", line 3868, in <module>
[1,104]<stderr>:    locals()[function_name](**kwargs)
[1,104]<stderr>:  File "src/qd/qd_common.py", line 3375, in execute_func
[1,104]<stderr>:    return getattr(modules, info['import'])(**info['param'])
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipeline.py", line 679, in pipeline_train_eval_multi
[1,104]<stderr>:    pip.ensure_train()
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1062, in ensure_train
[1,104]<stderr>:    train_result = self.train()
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1405, in train
[1,104]<stderr>:    self.do_train(train_loader, model, optimizer, scheduler, checkpointer,
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/pipelines/uni_pipeline.py", line 1524, in do_train
[1,104]<stderr>:    DeepspeedTrainer(
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1540, in do
[1,104]<stderr>:    self.inner_loop()
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1453, in inner_loop
[1,104]<stderr>:    self.inner_loop_step()
[1,104]<stderr>:  File "/tmp/code/quickdetection/src/qd/opt/trainer.py", line 1584, in inner_loop_step
[1,104]<stderr>:    self.model_engine.backward(loss)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1740, in backward
[1,104]<stderr>:    self.allreduce_gradients()
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1668, in allreduce_gradients
[1,104]<stderr>:    self.optimizer.reduce_gradients(
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 589, in reduce_gradients
[1,104]<stderr>:    self.reduce_ready_partitions_and_remove_grads(param, i)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1237, in reduce_ready_partitions_and_remove_grads
[1,104]<stderr>:    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 798, in reduce_independent_p_g_buckets_and_remove_grads
[1,104]<stderr>:    self.reduce_ipg_grads()
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1191, in reduce_ipg_grads
[1,104]<stderr>:    self.buffered_reduce_fallback(
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1386, in buffered_reduce_fallback
[1,104]<stderr>:    self.allreduce_no_retain(bucket,
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1374, in allreduce_no_retain
[1,104]<stderr>:    self.allreduce_and_copy(small_bucket, rank=rank, log=log)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1354, in allreduce_and_copy
[1,104]<stderr>:    allreduced = self.allreduce_bucket(small_bucket, rank=rank, log=log)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage2.py", line 1326, in allreduce_bucket
[1,104]<stderr>:    dist.all_reduce(tensor_to_allreduce, group=self.dp_process_group)
[1,104]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1209, in all_reduce
[1,104]<stderr>:    work = group.allreduce([tensor], opts)


```

**ds_report output**
--------------------------------------------------                                                                                     [5/1810]
DeepSpeed C++/CUDA extension op report                                                                                                         
--------------------------------------------------                                                                                             
NOTE: Ops not installed will be just-in-time (JIT) compiled at                                                                                 
      runtime if needed. Op compatibility means that your system                                                                               
      meet the required dependencies to JIT install the op.                                                                                    
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be f
ound.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info: 
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.9.0a0+c3d40fd
torch cuda version ............... 11.3
nvcc version ..................... 11.3
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.8, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.9, cuda 11.3

**System info (please complete the following information):**
 - OS: docker image/Ubuntu 18.04
 - GPU count and types 32*8A100 80GB
 - Interconnects (if applicable) connected with IB
 - Python version, 3.8

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else? MPI

**Comment by loadams** [comment]
Closing as the issue is >1 year old and stale.  If you are still hitting this issue, please open a new issue and link this one.
