### ISSUE TITLE
[Question] How to parallelize XGLM for inference?

### ISSUE THREAD

**Issue by z-bookworm** [microsoft/DeepSpeed#1864]
## The Problem

The [doc](https://www.deepspeed.ai/tutorials/inference-tutorial/#initializing-for-inference) mentions a way to parallelize models whose kernels are not supported yet.

I try to paralleize the [facebook/xglm-7.5B](https://huggingface.co/facebook/xglm-7.5B) for inference, which has 32 `XGLMDecoderLayer` and no encoders. The decoder layer looks like:

```txt
(0): XGLMDecoderLayer(
    (self_attn): XGLMAttention(
        (k_proj): Linear(in_features=4096, out_features=4096, bias=True)
        (v_proj): Linear(in_features=4096, out_features=4096, bias=True)
        (q_proj): Linear(in_features=4096, out_features=4096, bias=True)
        (out_proj): Linear(in_features=4096, out_features=4096, bias=True)
    )
    (activation_fn): GELUActivation()
    (self_attn_layer_norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
    (fc1): Linear(in_features=4096, out_features=16384, bias=True)
    (fc2): Linear(in_features=16384, out_features=4096, bias=True)
    (final_layer_norm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
)
```

But at `fc2`, a shape mismatch error occurred and the source code could be found [here](https://github.com/huggingface/transformers/blob/13af4a278de8bf6571967c4774369118ac3b3d90/src/transformers/models/xglm/modeling_xglm.py#L491)

```txt
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)
```

Since the model is too large for a single GPU, I wonder what's the correct way to parallelize the model?

Any help will be appreciated!

## To Reproduce

```python
import os

import deepspeed
import torch
from transformers import XGLMForCausalLM, XGLMTokenizer
from transformers.models.xglm.modeling_xglm import XGLMDecoderLayer

# Get local gpu rank from torch.distributed/deepspeed launcher
local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model_tag = "facebook/xglm-7.5B"
model = XGLMForCausalLM.from_pretrained(model_tag)
tokenizer = XGLMTokenizer.from_pretrained(model_tag)

injection_policy = {XGLMDecoderLayer: ('self_attn.out_proj', 'fc1', 'fc2')}
model = deepspeed.init_inference(
    model,
    mp_size=world_size,
    dtype=torch.float,
    injection_policy=injection_policy
)

prompt = "I am going to"
inputs = tokenizer(prompt, return_tensors="pt").to(device=local_rank)
outputs = model.generate(
    **inputs, 
    synced_gpus=True, 
    max_new_tokens=64,
    return_dict_in_generate=True
)
print(tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @z-bookworm 

Can you please try this again without passing the fc1 layer in the injection policy?
Thanks,
Reza

**Comment by z-bookworm** [comment]
@RezaYazdaniAminabadi 

Sure. After changing injection policy to

```python
injection_policy = {XGLMDecoderLayer: ('self_attn.out_proj', 'fc2')}
```

Running:

```bash
deepspeed --num_gpus 4 ds_infer.py
```

will still raise RuntimeError:
```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)
```

**Comment by RezaYazdaniAminabadi** [comment]
Can you please share the full stack trace? 
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Your input seems to have this shape: 5x1024. So, I am assuming it is giving you the error at fc1. But, this layer should not have some shape like this 4096x256, since based on the policy you're providing DeepSpeed only partitions out_proj and fc2. Can you please verify this?

**Comment by z-bookworm** [comment]
Thanks for your patience! @RezaYazdaniAminabadi 

> Your input seems to have this shape: 5x1024

Yes. Because `inputs` is:

```python
{
  'input_ids': tensor([[   2,   44,  418, 3168,   33]], device='cuda:2'), 
  'attention_mask': tensor([[1, 1, 1, 1, 1]], device='cuda:2')
}
```

And the model architecture is 

```
root
├── model (XGLMModel)
│   ├── embed_tokens (Embedding) weight:[256008, 1024]
│   ├── embed_positions (XGLMSinusoidalPositionalEmbedding) weights:[2050, 1024]
│   ├── layers (ModuleList)
│   │   └── 0-23(XGLMDecoderLayer)
│   │       ├── self_attn (XGLMAttention)
│   │       │   └── k_proj,v_proj,q_proj,out_proj(Linear) weight:[1024, 1024] bias:[1024]
│   │       ├── self_attn_layer_norm,final_layer_norm(LayerNorm) weight:[1024] bias:[1024]
│   │       ├── fc1 (Linear) weight:[4096, 1024] bias:[4096]
│   │       └── fc2 (Linear) weight:[1024, 4096] bias:[1024]
│   └── layer_norm (LayerNorm) weight:[1024] bias:[1024]
└── lm_head (Linear) weight:[256008, 1024]
```

## Full logs

```bash
$ deepspeed --num_gpus 4 ds_infer.py
```

```
[2022-04-07 11:03:49,415] [WARNING] [runner.py:155:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-04-07 11:03:49,870] [INFO] [runner.py:438:main] cmd = /data/envs/conda/envs/py38/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 ds_infer.py
[2022-04-07 11:03:50,472] [INFO] [launch.py:103:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2022-04-07 11:03:50,472] [INFO] [launch.py:109:main] nnodes=1, num_local_procs=4, node_rank=0
[2022-04-07 11:03:50,472] [INFO] [launch.py:122:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2022-04-07 11:03:50,472] [INFO] [launch.py:123:main] dist_world_size=4
[2022-04-07 11:03:50,472] [INFO] [launch.py:125:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2022-04-07 11:04:04,709] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.0, git-hash=unknown, git-branch=unknown
[2022-04-07 11:04:04,710] [INFO] [engine.py:189:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-04-07 11:04:04,772] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.0, git-hash=unknown, git-branch=unknown
[2022-04-07 11:04:04,772] [INFO] [engine.py:189:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-04-07 11:04:04,775] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl
[2022-04-07 11:04:04,786] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.0, git-hash=unknown, git-branch=unknown
[2022-04-07 11:04:04,786] [INFO] [engine.py:189:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-04-07 11:04:05,636] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.0, git-hash=unknown, git-branch=unknown
[2022-04-07 11:04:05,636] [INFO] [engine.py:189:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-04-07 11:04:11,008] [INFO] [engine.py:122:__init__] Place model to device: 1
[2022-04-07 11:04:11,026] [INFO] [engine.py:122:__init__] Place model to device: 3
[2022-04-07 11:04:11,064] [INFO] [engine.py:122:__init__] Place model to device: 0
[2022-04-07 11:04:11,210] [INFO] [engine.py:122:__init__] Place model to device: 2
{'input_ids': tensor([[   2,   44,  418, 3168,   33]], device='cuda:1'), 'attention_mask': tensor([[1, 1, 1, 1, 1]], device='cuda:1')}
{'input_ids': tensor([[   2,   44,  418, 3168,   33]], device='cuda:3'), 'attention_mask': tensor([[1, 1, 1, 1, 1]], device='cuda:3')}
{'input_ids': tensor([[   2,   44,  418, 3168,   33]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1]], device='cuda:0')}
{'input_ids': tensor([[   2,   44,  418, 3168,   33]], device='cuda:2'), 'attention_mask': tensor([[1, 1, 1, 1, 1]], device='cuda:2')}
Traceback (most recent call last):
  File "ds_infer.py", line 28, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "ds_infer.py", line 28, in <module>
  File "ds_infer.py", line 28, in <module>
    outputs = model.generate(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
Traceback (most recent call last):
  File "ds_infer.py", line 28, in <module>
    return func(*args, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1190, in generate
        outputs = model.generate(outputs = model.generate(

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    outputs = model.generate(
        return func(*args, **kwargs)  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1190, in generate
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1190, in generate
    return func(*args, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1190, in generate
    return self.greedy_search(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1530, in greedy_search
    return self.greedy_search(
      File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1530, in greedy_search
return self.greedy_search(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1530, in greedy_search
    return self.greedy_search(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/generation_utils.py", line 1530, in greedy_search
    outputs = self(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    outputs = self(
      File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
outputs = self(
          File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
outputs = self(return forward_call(*input, **kwargs)

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/inference/engine.py", line 367, in forward
    outputs = self.model_orig_fwd(*inputs, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 884, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/inference/engine.py", line 367, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/inference/engine.py", line 367, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/inference/engine.py", line 367, in forward
    outputs = self.model_orig_fwd(*inputs, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 884, in forward
        outputs = self.model_orig_fwd(*inputs, **kwargs)outputs = self.model(
    
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 884, in forward
outputs = self.model_orig_fwd(*inputs, **kwargs)  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 884, in forward
    outputs = self.model(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    outputs = self.model(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
        return forward_call(*input, **kwargs)outputs = self.model(

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 764, in forward
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 764, in forward
    return forward_call(*input, **kwargs)
      File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 764, in forward
layer_outputs = decoder_layer(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 764, in forward
    layer_outputs = decoder_layer(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    layer_outputs = decoder_layer(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    layer_outputs = decoder_layer(
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 491, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 491, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 491, in forward
    hidden_states = self.fc2(hidden_states)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
        hidden_states = self.fc2(hidden_states)return forward_call(*input, **kwargs)

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/transformers/models/xglm/modeling_xglm.py", line 491, in forward
    hidden_states = self.fc2(hidden_states)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    hidden_states = self.fc2(hidden_states)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 35, in forward
    return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 35, in forward
    output = torch.matmul(input, self.weight)
RuntimeError    output = torch.matmul(input, self.weight): 
mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)    
return forward_call(*input, **kwargs)
  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 35, in forward
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)
        output = torch.matmul(input, self.weight)return forward_call(*input, **kwargs)

  File "/data/envs/conda/envs/py38/lib/python3.8/site-packages/deepspeed/module_inject/replace_module.py", line 35, in forward
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)
    output = torch.matmul(input, self.weight)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1024 and 4096x256)
[2022-04-07 11:04:13,520] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 49616
[2022-04-07 11:04:13,520] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 49617
[2022-04-07 11:04:13,521] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 49618
[2022-04-07 11:04:13,521] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 49619
[2022-04-07 11:04:13,521] [ERROR] [launch.py:184:sigkill_handler] ['/data/envs/conda/envs/py38/bin/python', '-u', 'ds_infer.py', '--local_rank=3'] exits with return code = 1
```

## To reproduce

BTW, this code works after removing deepspeed related lines.

```python
import os

import deepspeed
import torch
from transformers import XGLMForCausalLM, XGLMTokenizer
from transformers.models.xglm.modeling_xglm import XGLMDecoderLayer

# Get local gpu rank from torch.distributed/deepspeed launcher
local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model_tag = "facebook/xglm-564M"
model = XGLMForCausalLM.from_pretrained(model_tag)
# model.to(device=local_rank)
tokenizer = XGLMTokenizer.from_pretrained(model_tag)

# injection_policy = {XGLMDecoderLayer: ('self_attn.out_proj', 'fc1', 'fc2')}
injection_policy = {XGLMDecoderLayer: ('self_attn.out_proj', 'fc2')}
model = deepspeed.init_inference(
    model,
    mp_size=world_size,
    dtype=torch.float,
    injection_policy=injection_policy
)

prompt = "I am going to"
inputs = tokenizer(prompt, return_tensors="pt").to(device=local_rank)
print(inputs)
outputs = model.generate(
    **inputs, 
    # synced_gpus=True, 
    max_new_tokens=64,
    return_dict_in_generate=True
)
print(tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))
```

**Comment by hyunwoongko** [comment]
@RezaYazdaniAminabadi I think this is about mp_param_update. I'll add XGLM support code.

**Comment by gsakkas** [comment]
Hello @hyunwoongko, any updates on this?

I'm getting a similar error `'[1, -1, 10, 128]' is invalid for input of size 135135` when I try the above but using the much smaller Incoder-6B model.
