### ISSUE TITLE
[BUG] Cannot install deepspeed>=0.6 if tensorflow is not installed

### ISSUE THREAD

**Issue by PaperclipBadger** [microsoft/DeepSpeed#1865]
**Describe the bug**
Installing deepspeed without tensorflow (or alongside tensorflow in a fresh virtual environment) results in `NameError` since v0.6.0.

**To Reproduce**
```bash
$ python -m virtualenv venv
$ source venv/bin/activate
$ pip install tensorflow==2.8.0 deepspeed==0.6.0
Collecting tensorflow
  Downloading tensorflow-2.8.0-cp39-cp39-manylinux2010_x86_64.whl (497.6 MB)
     |████████████████████████████████| 497.6 MB 28 kB/s              
Collecting deepspeed==0.6.0
  Downloading deepspeed-0.6.0.tar.gz (548 kB)
     |████████████████████████████████| 548 kB 34.5 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/blaine-rogers/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u81fqarl
       cwd: /tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/
  Complete output (13 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/setup.py", line 35, in <module>
      from op_builder import ALL_OPS, get_default_compute_capabilities, OpBuilder
    File "/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/op_builder/__init__.py", line 4, in <module>
      from .cpu_adam import CPUAdamBuilder
    File "/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/op_builder/cpu_adam.py", line 5, in <module>
      from .builder import TorchCPUOpBuilder
    File "/tmp/pip-install-8bxuimxb/deepspeed_6dcd2afb481e4a2a9d47e71ce582e5a1/op_builder/builder.py", line 34, in <module>
      TORCH_MAJOR = int(torch.__version__.split('.')[0])
  NameError: name 'torch' is not defined
  [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
   [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
```

**Expected behavior**
pip should not crash when it runs setup.py to prepare metadata, even if tensorflow is not installed.

**ds_report output**
Please run `ds_report` to give us details about your setup.

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - GPU count and types: one NVIDIA 1050 Ti
 - Python version: 3.8.12

**Docker context**
Base image `python:3.8.12`

**Comment by mrwyattii** [comment]
I think the problem is that `torch` isn't available to this virtual environment. If you have `torch` installed on your system, a python virtual environment may not see that:
```bash
❯ python3 -c "import torch"
# No Error
❯ python3 -m virtualenv venv
❯ source venv/bin/activate
venv ❯ python3 -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

You will either need to [install torch](https://pytorch.org/get-started/locally/) in `venv` or use the `--system-site-packages` option when creating the virtual environment (read more about that [here](https://docs.python.org/3/library/venv.html)):
```bash
❯ python3 -m virtualenv --system-site-packages venv
❯ source venv/bin/activate
venv ❯ python3 -c "import torch"
# No Error
```
