### ISSUE TITLE
[BUG] ZeRO stage3, error while fetching submodule parameters.

### ISSUE THREAD

**Issue by lkm2835** [microsoft/DeepSpeed#1903]
**Describe the bug**

I want to test ZeRO stage3 for my large LM(transformers). In stage3, error happens. But, it works on deepspeed==0.5.10

And, It works on stage 1, 2 (deepspeed==0.6.1)

Error Message (deepspeed==0.6.1)
```
Traceback (most recent call last):
  File "rlhf_client.py", line 95, in <module>
    main(args)
  File "rlhf_client.py", line 71, in main
    rl_stats = ppo_trainer.step(rollouts)
  File "/home/kyungmin.lee/rlhf/rlhf/rl/ppo2.py", line 34, in step
    stats = self.train_minibatch(rollouts_mini_batch)
  File "/home/kyungmin.lee/rlhf/rlhf/rl/ppo2.py", line 91, in train_minibatch
    self.loss_backward(loss)
  File "/home/kyungmin.lee/rlhf/rlhf/rl/ppo2.py", line 125, in loss_backward
    self.lm_policy.backward(loss)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1667, in backward
    self.optimizer.backward(loss)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2793, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 53, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 510, in backward
    ctx.pre_backward_function(ctx.module)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1461, in _run_before_backward_function
    self.pre_sub_module_backward_function(sub_module)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1549, in pre_sub_module_backward_function
    self.param_coordinator.fetch_sub_module(sub_module)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/trl/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 358, in fetch_sub_module
    raise RuntimeError(
RuntimeError: tracing error at step 299: expected the next 2 parameters in the parameter fetch queue to be ({'id': 148, 'status': 'AVAILABLE', 'numel': 768, 'ds_numel': 768, 'shape': (1, 768), 'ds_shape': (1, 768), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {166}}, {'id': 149, 'status': 'AVAILABLE', 'numel': 1, 'ds_numel': 1, 'shape': (1,), 'ds_shape': (1,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {166}}) but got ().
```

deepspeed config (stage3)
```
{
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
        "device": "cpu",
        "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients": true,
    "stage3_max_live_parameters" : 1e9,
    "stage3_max_reuse_distance" : 1e9,
    "stage3_prefetch_bucket_size" : 5e8,
    "stage3_param_persistence_threshold" : 1e6,
    "sub_group_size" : 1e12,
    "elastic_checkpoint" : [true],
    "stage3_gather_16bit_weights_on_model_save": [false],
    "ignore_unused_parameters": [true],
    "round_robin_gradients": [false]
  },
"gradient_accumulation_steps": 1,
"gradient_clipping": 1.0,
"train_batch_size": 8,
"train_micro_batch_size_per_gpu": 4,
"steps_per_print":10000
}
```

ref: #1820

**Comment by tjruwase** [comment]
@lkm2835, thanks for creating this issue. Can you please try this PR #1901?

**Comment by lkm2835** [comment]
> @lkm2835, thanks for creating this issue. Can you please try this PR #1901?

Thanks for fixing this error!

It works on ```deepspeed == 0.6.2+ef17c895```
