### ISSUE TITLE
multiple deepspeed runs in a single machine

### ISSUE THREAD

**Issue by 1Konny** [microsoft/DeepSpeed#191]
Hi. 

I have a 8-gpu local machine and trying to run using deepspeed 2 separate experiments with 4 gpus for each. Also, I assigned two different master ports for each experiment like 

run 1
`deepspeed --include=localhost:0,1,2,3 --master_port 61000 train.py --deepspeed --deepspeed_config deepspeed_util/ds_config.json --dataset ...`

run 2
`deepspeed --include=localhost:4,5,6,7 --master_port 60000 train.py --deepspeed --deepspeed_config deepspeed_util/ds_config.json --dataset ...`

However, I find that one of the runs cannot be started with the errors like `RuntimeError: Address already in use`. Also, I checked if the ports are available and tried different port numbers as well. But still I couldn't make it work.

Do you have any ideas for this issue ?

(FYI, I'm using a docker image which was downloaded via `docker pull deepspeed/deepspeed`)

Thanks!

**Comment by tjruwase** [comment]
@1Konny Thanks for using DeepSpeed. 

I just tested the feature and it works, so I am unable to repro the bug. 

Can you please reduce your experiment size to use 1 GPU each and then share the resulting logs?

**Comment by 1Konny** [comment]
Here are the logs

- First run using port 60000 and gpu 0. This run works well

`deepspeed --include=localhost:0 --master_port 60000 train_ds.py --deepspeed --deepspeed_config deepspeed_util/ds_config_fp16_zero.json --dataset ...`
```
cmd=['/usr/bin/python', '-u', '-m', 'deepspeed.pt.deepspeed_launch', '--world_info=eyJsb2NhbGhvc3QiOiBbMF19', 'train_ds.py', '--deepspeed', '--deepspeed_config', 'deepspeed_util/ds_config_fp16_zero.json']                                                          
WORLD INFO DICT: {'localhost': [0]}                                                                                                                                                                                                                                   
nnodes=1, num_local_procs=1, node_rank=0                                                                                                                                                                                                                              
global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})                                                                                                                                                                                                   
dist_world_size=1                                                                                                                                                                                                                                                     
Setting CUDA_VISIBLE_DEVICES=0                                                                                                                                                                                                                                        
DeepSpeed info: version=0.1.0, git-hash=90017d3, git-branch=master                                                                                                                                                                                                    
 After Train batch 8 micro_batch 8 and grad_acc 1                                                                                                                                                                                                                     
1 1                                                                                                                                                                                                                                                                   
DeepSpeedLight configuration:                                                                                                                                                                                                                                         
  allgather_size ............... 500000000                                                                                                                                                                                                                            
  allreduce_always_fp32 ........ False                                                                                                                                                                                                                                
  disable_allgather ............ False                                                                                                                                                                                                                                
  dump_state ................... False                                                                                                                                                                                                                                
  dynamic_loss_scale_args ...... None                                                                                                                                                                                                                                 
  fp16_enabled ................. True                                                                                                                                                                                                                                 
  global_rank .................. 0                                                                                                                                                                                                                                    
  gradient_accumulation_steps .. 1                                                                                                                                                                                                                                    
  gradient_clipping ............ 0.0                                                                                                                                                                                                                                  
  initial_dynamic_scale ........ 4294967296                                                                                                                                                                                                                           
  loss_scale ................... 0                                                                                                                                                                                                                                    
  optimizer_legacy_fusion ...... True                                                                                                                                                                                                                                 
  optimizer_name ............... adam                                                                                                                                                                                                                                 
  optimizer_params ............. {'lr': 1e-06, 'betas': [0.9, 0.999], 'eps': 0.0001}                                                                                                                                                                                  
  prescale_gradients ........... False                                                                                                                                                                                                                                
  scheduler_name ............... None                                                                                                                                                                                                                                 
  scheduler_params ............. None                                                                                                                                                                                                                                 
  sparse_gradients_enabled ..... False                                                                                                                                                                                                                                
  steps_per_print .............. 100                                                                                                                                                                                                                                  
  tensorboard_enabled .......... False                                                                                                                                                                                                                                
  tensorboard_job_name ......... DeepSpeedJobName                                                                                                                                                                                                                     
  tensorboard_output_path ......                                                                                                                                                                                                                                      
  train_batch_size ............. 8                                                                                                                                                                                                                                    
  train_micro_batch_size_per_gpu  8                                                                                                                                                                                                                                   
  wall_clock_breakdown ......... False                                                                                                                                                                                                                                
  world_size ................... 1                                                                                                                                                                                                                                    
  zero_allow_untested_optimizer  False                                                                                                                                                                                                                                
  zero_enabled ................. False                                                                                                                                                                                                                                
  json = {                                                                                                                                                                                                                                                            
    "fp16":{                                                                                                                                                                                                                                                          
        "enabled":true                                                                                                                                                                                                                                                
    },                                                                                                                                                                                                                                                                
    "gradient_accumulation_steps":1,                                                                                                                                                                                                                                  
    "optimizer":{                                                                                                                                                                                                                                                     
        "params":{                                                                                                                                                                                                                                                    
            "betas":[                                                                                                                                                                                                                                                 
                0.9,                                                                                                                                                                                                                                                  
                0.999                                                                                                                                                                                                                                                 
            ],                                                                                                                                                                                                                                                        
            "eps":0.0001,                                                                                                                                                                                                                                             
            "lr":1e-06                                                                                                                                                                                                                                                
        },                                                                                                                                                                                                                                                            
        "type":"Adam"                                                                                                                                                                                                                                                 
    },                                                                                                                                                                                                                                                                
    "steps_per_print":100,                                                                                                                                                                                                                                            
    "train_batch_size":8,                                                                                                                                                                                                                                             
    "zero_optimization":false                                                                                                                                                                                                                                         
}  
```

- The second run with port 61000 and gpu 3. This run throws an error.

`deepspeed --include=localhost:3 --master_port 61000 train_ds.py --deepspeed --deepspeed_config deepspeed_util/ds_config_fp16_zero.json --dataset ...`
```
cmd=['/usr/bin/python', '-u', '-m', 'deepspeed.pt.deepspeed_launch', '--world_info=eyJsb2NhbGhvc3QiOiBbM119', 'train_ds.py', '--deepspeed', '--deepspeed_config', 'deepspeed_util/ds_config_fp16_zero.json']                                                          
WORLD INFO DICT: {'localhost': [3]}                                                                                                                                                                                                                                   
nnodes=1, num_local_procs=1, node_rank=0                                                                                                                                                                                                                              
global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})                                                                                                                                                                                                   
dist_world_size=1                                                                                                                                                                                                                                                     
Setting CUDA_VISIBLE_DEVICES=3                                                                                                                                                                                                                                        
DeepSpeed info: version=0.1.0, git-hash=90017d3, git-branch=master 
```

```
WARNING:root:Unable to find hostfile, will proceed with training with local resources only.
cmd=['/usr/bin/python', '-u', '-m', 'deepspeed.pt.deepspeed_launch', '--world_info=eyJsb2NhbGhvc3QiOiBbM119', 'train_ds.py', '--deepspeed', '--deepspeed_config', 'deepspeed_util/ds_config_fp16_zero.json']
WORLD INFO DICT: {'localhost': [3]}
nnodes=1, num_local_procs=1, node_rank=0
global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
dist_world_size=1
Setting CUDA_VISIBLE_DEVICES=3
DeepSpeed info: version=0.1.0, git-hash=90017d3, git-branch=master
[INFO 2020-04-14 04:07:13] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "train_ds.py", line 93, in <module>
    solver = Solver(opt)
  File "/data1/arxiv/solver_ds.py", line 60, in __init__
    self.init_models_optimizers_data()
  File "/data1/arxiv/solver_ds.py", line 178, in init_models_optimizers_data
    self.encoder, self.encoder_optimizer, train_loader, _ = ds.initialize(opt, model=self.encoder, model_parameters=encoder_params, training_data=train_data)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/__init__.py", line 96, in initialize
    collate_fn=collate_fn)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/pt/deepspeed_light.py", line 129, in __init__
    dist.init_process_group(backend=self.dist_backend)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
```

**Comment by tjruwase** [comment]
Thanks for sharing the log. 

The following warning in the log shows that problem is that deepspeed launcher is not being used, and so the master_port argument is ignored. 

> WARNING:root:Unable to find hostfile, will proceed with training with local resources only.
> cmd=['/usr/bin/python', '-u', '-m', 'deepspeed.pt.deepspeed_launch', '--world_info=eyJsb2Nh
> 

Can you please retry after creating and specifying a hostfile as described [here](https://github.com/microsoft/DeepSpeed#resource-configuration-multi-node)?

**Comment by tjruwase** [comment]
@1Konny Please reopen as needed

**Comment by tjruwase** [comment]
@afiaka87, @IndexFziQ 

Please see [here](https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node) for instructions on creating hostfile.  Also, it might be open a new ticket. The reason is that issue was closed as the original appeared to have been solved, and the code base and docs have changed significantly since then. Thanks!

**Comment by afiaka87** [comment]
@tjruwase 

That was fast! I actually resolved the issue already by specifying the needed `--master_port` argument. Sorry for the bother.

**Comment by BramVanroy** [comment]
I've had a similar issue on our cluster where users may want to run small experiments on the same node. For instance a node with 4 GPUs but two separate jobs with deepspeed that both use 2 GPUs. So their host file is identical. This triggers a "port already in use".

Is there a way to make deepspeed more robust in these scenarios, so that it automatically tries a range of ports? I am aware that we can specify a master port ourselves, but this is not always known to the user specifically. Instead, if we could specify (either in the command line or in an env var) the range of ports that deepspeed can try, that could be really helpful and improve usability.

**Comment by tjruwase** [comment]
@BramVanroy, can you share more details on your suggestion of trying different ports? 

Below are my initial thoughts on two possibilities, and concerns.
1. deepspeed checks if a port is busy before using it. My concerns are time of check/time of use race condition, and how to check in platform-agnostic way. 
2. deepspeed tries a port and recovers if port is busy. My concern is that recovery code could difficult to write correctly. 

Please share your thoughts. Thanks!

**Comment by tjruwase** [comment]
@BramVanroy, additionally it might make sense to open a new enhancement issue for easier tracking. Thanks!

**Comment by djaym7** [comment]
why is this closed ? I still can't run multiple deepspeed runs on same machine, getting same error in the post

**Comment by tjruwase** [comment]
Can you please try running the following, perhaps in a bash script?

```bash
deepspeed --master_port 29500 -i worker-0:0 /tmp/test.py &
deepspeed --master_port 29600 -i worker-0:2 /tmp/test.py &
```
Where /tmp/test.py is a below:
```python
import time
import torch
sleep_secs=5
while True:
    x=torch.empty(10).cuda()
    print(f'on device {x.device} gooing to sleep for {sleep_secs} secs')
    time.sleep(sleep_secs)
```

**Comment by nightlessbaron** [comment]
Thank you so much @tjruwase for the fast response! 
`deepspeed --master_port 12345 src/train_biencoder.py --deepspeed ds_config.json` instead of  `deepspeed src/train_biencoder.py --deepspeed ds_config.json  --master_port 12345` did the trick.
