### ISSUE TITLE
[BUG] ZeRO Stage 3, error while fetching submodule parameters

### ISSUE THREAD

**Issue by SeanNaren** [microsoft/DeepSpeed#1938]
**Describe the bug**

Same issue as https://github.com/microsoft/DeepSpeed/issues/1903 except using DeepSpeed 0.6.3

**To Reproduce**
Using https://github.com/SeanNaren/minGPT

```
pip install -r requirements.txt
python train.py --n_layer 4 --n_head 16 --n_embd 1024 --accelerator gpu --devices 1 --precision 16 --batch_size 1 --strategy deepspeed_stage_3
```

Error:

```
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    trainer.fit(model, train_loader)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 268, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 207, in advance
    self.optimizer_idx,
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    using_lbfgs=is_lbfgs,
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1644, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/deepspeed.py", line 70, in optimizer_step
    closure_result = closure()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/ddp.py", line 341, in training_step
    return self.model(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1568, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1147, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/strategies/deepspeed.py", line 80, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "train.py", line 117, in training_step
    logits = self(idx)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1136, in _call_impl
    result = hook(self, input)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/zero/stage3.py", line 1094, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/zero/stage3.py", line 1212, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 269, in fetch_sub_module
    f"tracing error at step {self.__step_id}: \n"
RuntimeError: tracing error at step 1:
module id: 1, training: True
expected the next 1 parameters in the parameter fetch queue to be ({'id': 0, 'status': 'AVAILABLE', 'numel': 131072, 'ds_numel': 131072, 'shape': (1, 128, 1024), 'ds_shape': (1, 128, 1024), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {1}},)
but got
 ({'id': 68, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 1024, 'shape': (0,), 'ds_shape': (1024,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': set()},).
```

**Expected behavior**
Training should begin!

**ds_report output**

DeepSpeed general environment info:
torch install path ............... ['/home/sean/anaconda3/lib/python3.7/site-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/sean/anaconda3/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.6.3, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3

Associated Lightning issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/12979

**Comment by tjruwase** [comment]
@SeanNaren, can you please try #1916?
