### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by noujaimc** [microsoft/DeepSpeed#199]
I'm trying simply to build the library under Windows 10. I ran the following command : python setup.py install
I got the following error :
C:\Users\noujach\Desktop\DeepSpeed-master>python setup.py install
```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from deepspeed import __version__ as ds_version
  File "C:\Users\noujach\Desktop\DeepSpeed-master\deepspeed\__init__.py", line 5, in <module>
    from deepspeed.pt.deepspeed_light import DeepSpeedLight
  File "C:\Users\noujach\Desktop\DeepSpeed-master\deepspeed\pt\deepspeed_light.py", line 14, in <module>
    from deepspeed.pt.deepspeed_zero_optimizer import FP16_DeepSpeedZeroOptimizer
  File "C:\Users\noujach\Desktop\DeepSpeed-master\deepspeed\pt\deepspeed_zero_optimizer.py", line 10, in <module>
    from torch.distributed.distributed_c10d import _get_global_rank
  File "C:\Users\noujach\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\distributed_c10d.py", line 9, in <module>
    from .rendezvous import rendezvous, register_rendezvous_handler  # noqa: F401
  File "C:\Users\noujach\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\rendezvous.py", line 7, in <module>
    from . import FileStore, TCPStore
ImportError: cannot import name 'FileStore' from 'torch.distributed' (C:\Users\noujach\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\__init__.py)
```

**Comment by tjruwase** [comment]
@noujaimc Thanks for using DeepSpeed. 

This looks like a torch issue, rather than DeepSpeed.  Can you please clarify?

**Comment by noujaimc** [comment]
I'm using Python 3.7.3 on Windows 10. I installed the the Torch version 1.2 and torchvision 0.4.0 using the command provided by Torch:

`pip install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

From the DeepSpeed repository(master). I ran this command for the requirements:
` pip install -r requirements.txt `

All was successful.

Than, I ran the setup.py from the  the DeepSpeed repository(master) like so:

`python setup.py install`

I encountered the error described in my last post. I tried using lastest Torch but no success...

**Comment by vidushv** [comment]
I had the same issue and did some research, looks like torch.distributed is still a work in progress for Windows: [pytorch/issues/37068](https://github.com/pytorch/pytorch/issues/37068).

I launched a vm with linux and it works well there.
