### ISSUE TITLE
[BUG] generate() with do_sample isn't done on multi-GPUs Stage3 at T5ForConditionalGeneration

### ISSUE THREAD

**Issue by lkm2835** [microsoft/DeepSpeed#2022]
**Describe the bug**
In multi-GPUs, finished `generate()` only 1 GPU.

But, when I used 1 GPU, it works well.

This bug happens with [T5ForConditionalGeneration](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L1456) but doesn't happens with [GPT2LMHeadModel](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L947)

```
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   40C    P0    92W / 400W |  24222MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   8  NVIDIA A100-SXM...  On   | 00000000:80:00.0 Off |                    0 |
| N/A   38C    P0    87W / 400W |  20572MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

`dist.barrier()` is persisted.

**To Reproduce**

``` python
    def generation_t5_from(self, encoded_example, max_tokens):
        #--------------------------- Tokenizing text of prompts -------------------------------#

        self.tokenizer_policy.padding_side = 'left'
        prompts = self.tokenizer( 
            encoded_example['inputs'],
            padding='longest',
            truncation=True,
            max_length=max_tokens,
            return_tensors="pt"
        ).to(self.device['lm'])
        self.tokenizer_policy.padding_side = 'right'

        #---------------------------- Generation from the prompts ------------------------------#

        generated_token_length = self.num_steps
        generations = self.lm.generate(
            prompts.input_ids,
            max_length=generated_token_length,
            do_sample=True,
        )
        dist.barrier()
```

**Expected behavior**
Every GPUs finished `generate()` and `dist.barrier()`.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/kyungmin.lee/anaconda3/envs/lib/python3.8/site-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 10.1
deepspeed install path ........... ['/home/kyungmin.lee/DeepSpeed/deepspeed']
deepspeed info ................... 0.6.6+ae198e20, ae198e20, master
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3
```
**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types: one machine with x2 A100s each
 - Python version 3.8.12
 - Transformers 4.19.4

**Comment by lkm2835** [comment]
### **Reproduce**

main code
``` python
from transformers import T5ForConditionalGeneration, AutoTokenizer
from torch.optim import Adam
import deepspeed

def main(args):

    tokenizer = AutoTokenizer.from_pretrained("t5-large")
    model = T5ForConditionalGeneration.from_pretrained("t5-large")

    optimizer = Adam(model.parameters(), lr=0.00001)

    engine, optimizer, _, _ = deepspeed.initialize(
                                            model=model, 
                                            optimizer=optimizer,
                                            args=args
                                            )


    prompt = ["local_rank for distributed training on gpus", 
              "local_rank for distributed training on gpus" ]

    tokenizer.padding_side = 'left'
    prompts = tokenizer(
        prompt,
        padding='longest',
        truncation=True,
        max_length=1024,
        return_tensors="pt"
    ).to(f"cuda:{args.local_rank}")
    tokenizer.padding_side = 'right'
    print(prompts)

    gen = engine.generate(
                prompts.input_ids,
                max_length=128,
                do_sample=True
                )

    print(gen)
    print("FINISH")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="rlhf")

    parser.add_argument("--local_rank", type=int,
                    default=0,
                    help="local_rank for distributed training on gpus")

    parser = deepspeed.add_config_arguments(parser)

    args = parser.parse_args()
    
    main(args)
```

config
``` json
{
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
        "device": "cpu",
        "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients": true,
    "stage3_max_live_parameters" : 1e9,
    "stage3_max_reuse_distance" : 1e9,
    "stage3_prefetch_bucket_size" : 5e8,
    "stage3_param_persistence_threshold" : 1e6,
    "sub_group_size" : 1e12,
    "elastic_checkpoint" : [true],
    "stage3_gather_16bit_weights_on_model_save": [false],
    "ignore_unused_parameters": [true],
    "round_robin_gradients": [false]
  },
"gradient_accumulation_steps": 1,
"gradient_clipping": 1.0,
"train_batch_size": 32,
"train_micro_batch_size_per_gpu": 16,
"steps_per_print":10000
}
```

script
```deepspeed --include localhost:7,8 --master_port 60500 rlhf_client.py --deepspeed --deepspeed_config "config/stage3_offload.json"```

**Comment by lkm2835** [comment]
```
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   39C    P0    91W / 400W |   9342MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   8  NVIDIA A100-SXM...  On   | 00000000:80:00.0 Off |                    0 |
| N/A   35C    P0    57W / 400W |    579MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```
GPU 8 is done But GPU 7 is not done.

**Comment by lkm2835** [comment]
``` python
    gen = engine.generate(
                #**prompts,
                prompts.input_ids,
                max_length=128,
                do_sample=False
                )
```
I find that `do_sample` = False works well.
But I need `do_sample` = True.

**Comment by lkm2835** [comment]
@tjruwase

Could anyone give me a feedback?

**Comment by stas00** [comment]
you must use `generate(..., synched_gpus=True)` when using ZeRO stage-3

**Comment by lkm2835** [comment]
@stas00 thanks!

But, I got TypeError: forward() got an unexpected keyword argumnet `synched_gpus`

transformers == 4.20.1

```
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    main(args)
  File "test.py", line 33, in main
    gen = engine.generate(
  File "/home/kyungmin.lee/anaconda3/envs/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/lib/python3.8/site-packages/transformers/generation_utils.py", line 1181, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/home/kyungmin.lee/anaconda3/envs/lib/python3.8/site-packages/transformers/generation_utils.py", line 525, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'synched_gpus'
```

**Comment by lkm2835** [comment]
Solution:

```
    gen = engine.generate(
                prompts.input_ids,
                max_length=128,
                do_sample=True,
                synced_gpus=True
                )
```
