### ISSUE TITLE
[BUG] import deepspeed error when building from source

### ISSUE THREAD

**Issue by kisseternity** [microsoft/DeepSpeed#2060]
In the latest release v0.6.5, I build from source using
 _pip install ._
in the DeepSpeed directory, installed successfully.
However, when I use it with Megatron, 
_import deepspeed_ 
reports error as shown:
Traceback (most recent call last):
  File "pretrain_bert.py", line 23, in <module>
    import deepspeed
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 13, in <module>
    from . import ops
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/__init__.py", line 1, in <module>
    from . import adam
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/__init__.py", line 1, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 9, in <module>
    from ..op_builder import CPUAdamBuilder
ModuleNotFoundError: No module named 'deepspeed.ops.op_builder'
    from megatron import get_args
  File "/home/notebook/code/personal/bert/Megatron-DeepSpeed-v3.0/megatron/__init__.py", line 17, in <module>
    from .global_vars import get_args
  File "/home/notebook/code/personal/bert/Megatron-DeepSpeed-v3.0/megatron/global_vars.py", line 27, in <module>
    from .arguments import parse_args
  File "/home/notebook/code/personal/bert/Megatron-DeepSpeed-v3.0/megatron/arguments.py", line 22, in <module>
    import deepspeed
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 13, in <module>
    from . import ops
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/__init__.py", line 1, in <module>
    from . import adam
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/__init__.py", line 1, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 9, in <module>
    from ..op_builder import CPUAdamBuilder
ModuleNotFoundError: No module named 'deepspeed.ops.op_builder'

Is this a bug?
![Image_20220628173023](https://user-images.githubusercontent.com/15059072/176145305-076d71c4-8782-4154-9d6f-00ceb215042c.png)

**Comment by mrwyattii** [comment]
@kisseternity Are you able to run if you install from pypi (`pip install deepspeed==0.6.5`)?

I've seen a similar issue in the past and it was likely due to the symlinks we create in `setup.py` - but I haven't been able to reproduce it in any system / environment I have access to.

**Comment by mrwyattii** [comment]
@kisseternity thanks for sharing! I think the issue is stemming from symbolic links we create in `setup.py` - but I'm unable to reproduce this behavior in my own environment. Could you share what OS you are using and what shell you use?

If you are running linux, you can share the output of:
```
lsb_release -a
echo $SHELL && $SHELL --version
```

**Comment by kisseternity** [comment]
> @kisseternity thanks for sharing! I think the issue is stemming from symbolic links we create in `setup.py` - but I'm unable to reproduce this behavior in my own environment. Could you share what OS you are using and what shell you use?
> 
> If you are running linux, you can share the output of:
> 
> ```
> lsb_release -a
> echo $SHELL && $SHELL --version
> ```
FYI
![image](https://user-images.githubusercontent.com/15059072/176586122-e65f683a-cb7d-4481-a1a3-5f09078082ee.png)

**Comment by wuQi-666** [comment]
May I ask how to solve the problem "ModuleNotFoundError: No module named 'deepspeed.op. op_builder'"?

**Comment by loadams** [comment]
@wuQi-666 - that usually means that you have not installed deepspeed properly.  Can you please share `pip list` and `python -c "import deepspeed; print('op_builder:', deepspeed.op.op_builder)"
