### ISSUE TITLE
[BUG] Can't install DeepSpeed, Unable to pre-compile sparse_attn

### ISSUE THREAD

**Issue by BrigandRo** [microsoft/DeepSpeed#2066]
**Describe the bug**
I can't install DeepSpeed, at `DS_BUILD_OPS=1 pip install deepspeed` throws `[ERROR]  Unable to pre-compile sparse_attn`

**To Reproduce**
```
conda create -n gpt1 python=3.7
conda activate gpt1
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
pip install --upgrade pip

git clone https://github.com/microsoft/DeepSpeed
cd DeepSpeed
DS_BUILD_OPS=1 pip install .
```

**Error log**
```
Processing /home/good/Desktop/gpt/DeepSpeed
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/good/Desktop/gpt/DeepSpeed/setup.py", line 153, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "/home/good/Desktop/gpt/DeepSpeed/setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile sparse_attn
      DS_BUILD_OPS=1
       [WARNING]  please install triton==1.0.0 if you want to use sparse attention
       [WARNING]  One can disable sparse_attn with DS_BUILD_SPARSE_ATTN=0
       [ERROR]  Unable to pre-compile sparse_attn
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**ds_report output**
`ds_report: command not found`

**System info:**
 - OS: Ubuntu 20.04.4 LTS   focal
 - Conda: 4.12.0
 - Python: 3.7.14
 - Pip: 22.1.2
 - Torch: 1.12.0

```
$ nvidia-smi
NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6
```

```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

**Comment by mrwyattii** [comment]
@BrigandRo the warning message tells you what you need to do:
`[WARNING]  please install triton==1.0.0 if you want to use sparse attention`

`pip install triton==1.0.0`

**Comment by BrigandRo** [comment]
@mrwyattii You are right, thanks.

**Comment by irg1008** [comment]
Sorry but how are we supposed to install a non-existant package?

Triton last version is 0.3.0

**Comment by mrwyattii** [comment]
> Sorry but how are we supposed to install a non-existant package?
> 
> Triton last version is 0.3.0

I'm not sure what you mean: https://pypi.org/project/triton/

**Comment by nikich340** [comment]
> > Sorry but how are we supposed to install a non-existant package?
> > Triton last version is 0.3.0
> 
> I'm not sure what you mean: https://pypi.org/project/triton/
Triton is unavailable for windows:
`ERROR: Could not find a version that satisfies the requirement triton (from versions: none)`
