### ISSUE TITLE
[BUG]Runtime error when enabling fp16 config with tasks using SyncBatchNorm

### ISSUE THREAD

**Issue by sangsang96** [microsoft/DeepSpeed#2102]
**Describe the bug**
Following runtime error when enabling fp16 config with tasks using model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model) and working with  multiple GPUs 

Is there another way of making my batchnorms synchronized when enabling fp16 config?

```python
2022-07-18 14:49:25,373 non_mp_trainer.py INFO]: ***** Running training *****
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Num examples = 889534
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Num Epochs = 60
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Instantaneous batch size per device = 96
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Total train batch size (w. parallel, distributed & accumulation) = 192
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Gradient Accumulation steps = 1
[2022-07-18 14:49:25,373 non_mp_trainer.py INFO]:   Total optimization steps = 277920
  0%|          | 0/277920 [00:00<?, ?it/s]start training epoch: 0
/usr/local/anaconda3/lib/python3.7/site-packages/PIL/Image.py:989: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    trainer.train()
  File "/media/cfs/nlp/vlp/magnus-models/vlp/magnus-api/magnus_api/magnus_trainer.py", line 109, in train
    return self._trainer.train()
  File "/media/cfs/nlp/vlp/magnus-models/vlp/magnus-core/magnus_core/trainer/non_mp_trainer.py", line 809, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1891, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1923, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1606, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/custom_model.py", line 271, in forward
    img_embeds = self.image_encoder(image).transpose(-1,-2)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/models/RepVGG/repvgg.py", line 181, in forward
    out = self.stage0(x)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/models/RepVGG/repvgg.py", line 55, in forward
    return self.nonlinearity(self.se(self.rbr_dense(inputs) + self.rbr_1x1(inputs) + id_out))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 758, in forward
    world_size,
File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/_functions.py", line 65, in forward
    count_all.view(-1)
RuntimeError: Expected counts to have type Half but got Float
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    trainer.train()
  File "/media/cfs/nlp/vlp/magnus-models/vlp/magnus-api/magnus_api/magnus_trainer.py", line 109, in train
    return self._trainer.train()
  File "/media/cfs/nlp/vlp/magnus-models/vlp/magnus-core/magnus_core/trainer/non_mp_trainer.py", line 809, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1891, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1923, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1606, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/custom_model.py", line 271, in forward
    img_embeds = self.image_encoder(image).transpose(-1,-2)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/models/RepVGG/repvgg.py", line 181, in forward
    out = self.stage0(x)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/vlp/magnus-models/vlp/models/RepVGG/repvgg.py", line 55, in forward
    return self.nonlinearity(self.se(self.rbr_dense(inputs) + self.rbr_1x1(inputs) + id_out))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 758, in forward
    world_size,
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/_functions.py", line 65, in forward
    count_all.view(-1)
RuntimeError: Expected counts to have type Half but got Float
  0%|          | 0/277920 [00:06<?, ?it/s]
[2022-07-18 14:49:34,803] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 10096
[2022-07-18 14:49:34,804] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 10097
```

**Comment by leonid-pishchulin** [comment]
facing the same issue. is there any update on that?

**Comment by akuxcw** [comment]
facing the same issue. is there any update on that?

**Comment by ShijieZZZZ** [comment]
Reproduced the issue. Investigating.

**Comment by ShijieZZZZ** [comment]
First, I do not think this is an issue in deepspeed. The issue turns out to be with this [function](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=%5Bmask%5D-,%23%20calculate%20global%20mean%20%26%20invstd,)), which requires _count_all, running_mean, running_var_ to have same dtype. In fp16 mode, r_unning_mean, running_var_ are fp16, but, count_all is fp32 because it has same dtype as [mean](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=(1)%2C-,dtype%3Dmean.dtype%2C,-device%3Dmean), which is computed [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=mean%2C%20invstd%20%3D%20torch.batch_norm_stats(input%2C%20eps)) (which return dtype is not fp16 although input's dtype is fp16). So one solution could be instead of assigning [dtype=mean.dtype](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=(1)%2C-,dtype%3Dmean.dtype%2C,-device%3Dmean),  let dtype=running_mean.dtype

**Comment by ShijieZZZZ** [comment]
Reproduced this issue without deepspeed. 
The following code runs well,
but If you uncomment this line, `model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)`, the issue shows up.


```
import torch
from torchvision import datasets, transforms
import os
from torch.utils.data.distributed import DistributedSampler
import torch.distributed as dist
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP

class SimpleModel(torch.nn.Module):
    def __init__(self, hidden_dim, empty_grad=False):
        super(SimpleModel, self).__init__()
        self.linear = torch.nn.Linear(hidden_dim, hidden_dim)
        self.BatchNorm1d = torch.nn.BatchNorm1d(hidden_dim)
        if empty_grad:
            self.layers2 = torch.nn.ModuleList([torch.nn.Linear(hidden_dim, hidden_dim)])
        self.cross_entropy_loss = torch.nn.CrossEntropyLoss()

    def forward(self, x, y):
        hidden = x
        hidden = self.linear(hidden)
        hidden = self.BatchNorm1d(hidden)

        return self.cross_entropy_loss(hidden, y)

def get_data_loader(model, total_samples, hidden_dim, device):
    batch_size = 8
    train_data = torch.randn(total_samples, hidden_dim, device=device).half()
    train_label = torch.empty(total_samples,
                              dtype=torch.long,
                              device=device).random_(hidden_dim)
    train_dataset = torch.utils.data.TensorDataset(train_data, train_label)
    sampler = DistributedSampler(train_dataset)
    train_loader = torch.utils.data.DataLoader(train_dataset,
                                               batch_size=batch_size,
                                               sampler=sampler)
    return train_loader

def main():
    dist.init_process_group("nccl")
    rank = dist.get_rank()

    hidden_dim = 4
    device_id = rank % torch.cuda.device_count()
    model = SimpleModel(hidden_dim, empty_grad=False).to(device_id)
    model = model.half()
    #model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
    ddp_model = DDP(model, device_ids=[device_id]).half()

    data_loader = get_data_loader(model=ddp_model,
                                  total_samples=1000,
                                  hidden_dim=hidden_dim,
                                  device=ddp_model.device)

    for n, batch in enumerate(data_loader):
        loss = ddp_model(batch[0], batch[1])
        if dist.get_rank() == 0:
            print("LOSS:", loss.item())

        if n == 1: break

if __name__ == "__main__":
    main()```

**Comment by leonid-pishchulin** [comment]
thanks for investigating this @ShijieZZZZ ! should we file a bug then with PyTorch?

**Comment by ShijieZZZZ** [comment]
Hi @leonid-pishchulin, yes please. The use of _torch.batch_norm_gather_stats_with_counts_ [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py) is problematic.

**Comment by akuxcw** [comment]
Great! Thanks a lot!

**Comment by ShijieZZZZ** [comment]
Closed now as this is a PyTorch issue.

**Comment by leonid-pishchulin** [comment]
opened issue with pytorch: https://github.com/pytorch/pytorch/issues/96203
