### ISSUE TITLE
[BUG][0.6.7]DeepSpeed is trying to load the whole model to 1 GPU instead of partitioning

### ISSUE THREAD

**Issue by lanking520** [microsoft/DeepSpeed#2169]
**Describe the bug**

OOM on GPU when running GPU = 4. My GPU have 40GB memory each (A100) and my CPU memory is 488GB. However, I am trying to load the OPT-30B model with 80GB size. In this case, after creating 4 processes using DeepSpeed launcher, the system goes GPU OOM after 10 min. 

In theory, if the model is loaded on CPU, DeepSpeed should slice each layer to one GPU so the load can be balanced. In that case, we would expect each GPU take 80 / 4 = 20GB. I also tested GPU=8, it falls into the same issue. It seemed the DeepSpeed.init() seemed to copy the whole CPU-memory model to 1 single GPU.

**To Reproduce**
I am running with 8 GPU instance with A100. 

```python
import os
import deepspeed
import torch
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model_name = 'facebook/opt-30b'
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-30b", use_fast=False)

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
                                           replace_method='auto',
					   replace_with_kernel_inject=True)

generator = pipeline(task='text-generation', model=model, tokenizer=tokenizer, device=local_rank)

string = generator("DeepSpeed is", do_sample=True, min_length=50)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)
```

```
deepspeed --num_gpus 8 test.py
```

**Expected behavior**

Should be just normal?

**ds_report output**

```
# ds_report
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.6.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.11, cuda 11.3
```
### Error message

```
[WARN ] - [1,1]<stderr>:Some weights of the model checkpoint at facebook/opt-30b were not used when initializing OPTForCausalLM: ['decoder.final_layer_norm.weight', 'decoder.final_layer_norm.bias']
[WARN ] - [1,1]<stderr>:- This IS expected if you are initializing OPTForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
[WARN ] - [1,1]<stderr>:- This IS NOT expected if you are initializing OPTForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[INFO ] - [1,1]<stdout>:[2022-08-02 18:48:56,535] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.7, git-hash=unknown, git-branch=unknown
[INFO ] - [1,1]<stdout>:[2022-08-02 18:48:56,535] [INFO] [engine.py:211:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[WARN ] - [1,0]<stderr>:Some weights of the model checkpoint at facebook/opt-30b were not used when initializing OPTForCausalLM: ['decoder.final_layer_norm.bias', 'decoder.final_layer_norm.weight']
[WARN ] - [1,0]<stderr>:- This IS expected if you are initializing OPTForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
[WARN ] - [1,0]<stderr>:- This IS NOT expected if you are initializing OPTForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[INFO ] - [1,0]<stdout>:[2022-08-02 18:49:00,938] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.7, git-hash=unknown, git-branch=unknown
[INFO ] - [1,0]<stdout>:[2022-08-02 18:49:00,939] [INFO] [engine.py:211:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[INFO ] - [1,0]<stdout>:[2022-08-02 18:49:00,942] [INFO] [comm.py:423:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[INFO ] - [1,0]<stdout>:Added key: store_based_barrier_key:1 to store for rank: 0
[INFO ] - [1,1]<stdout>:Added key: store_based_barrier_key:1 to store for rank: 1
[INFO ] - [1,1]<stdout>:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
[INFO ] - [1,0]<stdout>:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
[INFO ] - [1,1]<stdout>:[2022-08-02 18:49:02,103] [INFO] [torch.py:166:new_group] new group called with [0, 1]
[INFO ] - [1,1]<stdout>:Added key: store_based_barrier_key:2 to store for rank: 1
[INFO ] - [1,0]<stdout>:[2022-08-02 18:49:02,105] [INFO] [torch.py:166:new_group] new group called with [0, 1]
[INFO ] - [1,0]<stdout>:Added key: store_based_barrier_key:2 to store for rank: 0
[INFO ] - [1,0]<stdout>:Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 2 nodes.
[INFO ] - [1,1]<stdout>:Rank 1: Completed store-based barrier for key:store_based_barrier_key:2 with 2 nodes.
[INFO ] - [1,0]<stdout>:[2022-08-02 18:49:02,116] [INFO] [engine.py:144:__init__] Place model to device: 0
[INFO ] - [1,1]<stdout>:[2022-08-02 18:49:02,125] [INFO] [engine.py:144:__init__] Place model to device: 1
[INFO ] - [1,0]<stdout>:CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 39.41 GiB total capacity; 37.07 GiB already allocated; 310.56 MiB free; 37.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[INFO ] - [1,0]<stdout>:Traceback (most recent call last):
[INFO ] - [1,0]<stdout>:  File "/opt/djl/ds/model.py", line 28, in handle
[INFO ] - [1,0]<stdout>:    predictor = get_model()
[INFO ] - [1,0]<stdout>:  File "/opt/djl/ds/model.py", line 16, in get_model
[INFO ] - [1,0]<stdout>:    model = deepspeed.init_inference(model,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 288, in init_inference
[INFO ] - [1,0]<stdout>:    engine = InferenceEngine(model,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/inference/engine.py", line 145, in __init__
[INFO ] - [1,0]<stdout>:    self.module.to(device)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 907, in to
[INFO ] - [1,0]<stdout>:    return self._apply(convert)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 578, in _apply
[INFO ] - [1,0]<stdout>:    module._apply(fn)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 578, in _apply
[INFO ] - [1,0]<stdout>:    module._apply(fn)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 578, in _apply
[INFO ] - [1,0]<stdout>:    module._apply(fn)
[INFO ] - [1,0]<stdout>:  [Previous line repeated 2 more times]
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 601, in _apply
[INFO ] - [1,0]<stdout>:    param_applied = fn(param)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 905, in convert
[INFO ] - [1,0]<stdout>:    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
[INFO ] - [1,0]<stdout>:RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 39.41 GiB total capacity; 37.07 GiB already allocated; 310.56 MiB free; 37.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @lanking520,

Here, you are initiating the DeepSpeed-inference with the `replace_with_kernel_inject` and `replace_method` as auto, however there is no policy for this model yet. Thus, the injection system silently ignores both the kernel-injection as well as the sharding the model across the GPU. Fortunately, you can run the model sharded across the GPUs without kernel-injection. To do so, first you need to set `replace_with_kernel_inject` to False and remove the `replace_method` argument, and then provide a policy for the model-partitioning as follows:

```
import transformers
from transformers.models.opt.modeling_opt import OPTDecoderLayer

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=torch.float,
					   replace_with_kernel_inject=False,
                                          injection_policy={OPTDecoderLayer:  ('self_attn.out_proj', '.fc2')})
```
You can find more information about this [here](https://www.deepspeed.ai/tutorials/inference-tutorial/).
Btw, we are working on adding kernel support for this model. Please stay tuned! 
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
I also noticed that you loaded the model in FP16, but the dtype is passed as torch.float, so please change that to torch.half if you want to run the model in FP16.

**Comment by lanking520** [comment]
@RezaYazdaniAminabadi Thanks for the recommendation and I will test this out.

Regarding to this line:

```
injection_policy={OPTDecoderLayer:  ('self_attn.out_proj', '.fc2')}
```

Could you explain more of what it does and where should I find reference if I need to build my own customize partition logics?

**Comment by lanking520** [comment]
Hi @RezaYazdaniAminabadi The solution doesn't seemed to work out:

```
INFO ] - [1,0]<stdout>:  File "/opt/djl/ds/model.py", line 17, in get_model
[INFO ] - [1,0]<stdout>:    model = deepspeed.init_inference(model,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 288, in init_inference
[INFO ] - [1,0]<stdout>:    engine = InferenceEngine(model,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/inference/engine.py", line 123, in __init__
[INFO ] - [1,0]<stdout>:    self._apply_injection_policy(
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/inference/engine.py", line 318, in _apply_injection_policy
[INFO ] - [1,0]<stdout>:    replace_transformer_layer(client_module,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 763, in replace_transformer_layer
[INFO ] - [1,0]<stdout>:    replaced_module = replace_module(model=model,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 873, in replace_module
[INFO ] - [1,0]<stdout>:    replaced_module, _ = _replace_module(model, policy)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 900, in _replace_module
[INFO ] - [1,0]<stdout>:    _, layer_id = _replace_module(child, policies, layer_id=layer_id)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 900, in _replace_module
[INFO ] - [1,0]<stdout>:    _, layer_id = _replace_module(child, policies, layer_id=layer_id)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 900, in _replace_module
[INFO ] - [1,0]<stdout>:    _, layer_id = _replace_module(child, policies, layer_id=layer_id)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 890, in _replace_module
[INFO ] - [1,0]<stdout>:    replaced_module = policies[child.__class__][0](child,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 759, in replace_fn
[INFO ] - [1,0]<stdout>:    new_module = replace_wo_policy(child, _policy)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 738, in replace_wo_policy
[INFO ] - [1,0]<stdout>:    return _replace_module(module)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 735, in _replace_module
[INFO ] - [1,0]<stdout>:    _replace_module(child, name)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 730, in _replace_module
[INFO ] - [1,0]<stdout>:    linear_policies[child.__class__](child,
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/replace_module.py", line 679, in _replace
[INFO ] - [1,0]<stdout>:    return LinearLayer(data.to(torch.cuda.current_device()), bias_data)
[INFO ] - [1,0]<stdout>:  File "/usr/local/lib/python3.8/dist-packages/deepspeed/module_inject/layers.py", line 35, in __init__
[INFO ] - [1,0]<stdout>:    torch.empty(weight_shape,
[INFO ] - [1,0]<stdout>:TypeError: empty() received an invalid combination of arguments - got (Tensor, device=int, dtype=Tensor), but expected one of:
[INFO ] - [1,0]<stdout>: * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
[INFO ] - [1,0]<stdout>: * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

Code to reproduce:

```
import os
import deepspeed
import torch
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model_name = 'facebook/opt-30b'
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-30b", use_fast=False)

generator.model = deepspeed.init_inference(generator.model,
                                           mp_size=world_size,
                                           dtype=model.dtype,
                                           replace_with_kernel_inject=False,
                                          injection_policy={OPTDecoderLayer:  ('self_attn.out_proj', '.fc2')})

generator = pipeline(task='text-generation', model=model, tokenizer=tokenizer, device=local_rank)

string = generator("DeepSpeed is", do_sample=True, min_length=50)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(string)
```

**Comment by RezaYazdaniAminabadi** [comment]
Thanks for the script. I pushed a fix. Please try again

**Comment by lanking520** [comment]
@RezaYazdaniAminabadi How to test this out? Does DeepSpeed offer nightly pip package, or I should build from source

**Comment by RezaYazdaniAminabadi** [comment]
@lanking520, please build from source. You can run `pip install -e .` on the branch in this PR.

**Comment by RezaYazdaniAminabadi** [comment]
btw, I have changed your script to run this:
```
import os
import deepspeed
import torch
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer
from transformers.models.opt.modeling_opt import OPTDecoderLayer

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

model_name = 'facebook/opt-30b'
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-30b", use_fast=False)

model = deepspeed.init_inference(model,
                                                   mp_size=world_size,
                                                   dtype=model.dtype,
                                                   replace_with_kernel_inject=False,
                                                   injection_policy={OPTDecoderLayer:  ('self_attn.out_proj', '.fc2')})

generator = pipeline(task='text-generation', model=model, tokenizer=tokenizer, device=local_rank)
for _ in range(100):
    string = generator("DeepSpeed is", do_sample=True, min_length=50, max_length=50)
if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
        print(string)
```
Here is the generated text:
![image](https://user-images.githubusercontent.com/44502768/182721453-d68a9c18-5672-4ad3-8e62-be8709f9a95e.png)

Thanks,
Reza

**Comment by lanking520** [comment]
@RezaYazdaniAminabadi I managed to pass the test after taking the change from latest master. I will close this issue for now. Do you have any idea when 0.7.1 will come out?
