### ISSUE TITLE
[BUG] ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by Dipet** [microsoft/DeepSpeed#2266]
python3.6, master version
```
Traceback (most recent call last):
  File "/opt/conda/bin/ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/__init__.py", line 16, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 30, in <module>
    from deepspeed.runtime.bf16_optimizer import BF16_Optimizer
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/bf16_optimizer.py", line 5, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict'
```

**Comment by Dipet** [comment]
Dockerfile to reproduce
```docker
FROM nvcr.io/nvidia/pytorch:20.11-py3
RUN pip install deepspeed==0.7.2
RUN python -c "import deepspeed; print(deepspeed.__version__)"
```
