### ISSUE TITLE
ZeRO2 out of memory with Megtron-LM for less than 30B parameters

### ISSUE THREAD

**Issue by howellyoung-s** [microsoft/DeepSpeed#237]
## My system configure
Pytorch 1.3.1
CUDA 10.1
Python 3.6
Hardware : GPU:  each machine 8xV100 -32G memory
ZeRO-2 version
commit: abe2204ddd1d5f60cd3303ead4df22deb5303a5b （#232）
DeepSpeedExample version:
commit:  274787a189b265814ed75dd5ddeae2dce026ea88 （#22）

## Excute scripts
`python -m torch.distributed.launch $DISTRIBUTED_ARGS \
       pretrain_gpt2.py \
       --model-parallel-size 8 \
       --num-layers 60 \
       --hidden-size 6144 \
       --num-attention-heads 32 \
       --batch-size 8 \
       --seq-length 1024 \
       --max-position-embeddings 1024 \
       --train-iters 320000 \
       --train-data wikipedia \
       --lazy-loader \
       --tokenizer-type GPT2BPETokenizer \
       --cache-dir cache \
       --split 949,50,1 \
       --distributed-backend nccl \
       --lr 1e-4 \
       --no-load-optim \
       --lr-decay-style cosine \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --warmup .01 \
       --checkpoint-activations \
       --fp16 \
       --log-interval 10 \
       --deepspeed \
       --deepspeed_config scripts/ds_zero2_config.json`

and ds_zero2_config.json is 
`{
  "train_batch_size": 8,
  "gradient_accumulation_steps": 1,
  "steps_per_print": 1,
  "zero_optimization": {
    "stage":2,
    "reduce_bucket_size": 200000000,
    "allgather_bucket_size": 200000000,
    "reduce_scatter": true
  },
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00015,
      "max_grad_norm": 1.0
    }
  },
  "gradient_clipping": 1.0,
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "activation_checkpointing": {
    "partition_activations":true,
    "contiguous_memory_optimization":true
  },
  "wall_clock_breakdown": true
}`

## Problem
I tried a large gpt-like model with about less than 30B parameters, but it cannot initilialize successfully. The paper says even ZeRO1 can run GPT-like models with more than 40B parameters. My machine only have 8 GPUs on each node which is not comparable with DGX2 nodes, but it may could support a GPT-like models with just 40B params according to the chart in the paper. I just think something may be wrong with my setting or codes, could someone give me any advice?

(Another question is I tried both ZeRO1 and ZeRO2 with Megtron-LM (8B params), and I find ZeRO2 is not any faster than ZeRO1 nor cost less memory. The issue is already submitted by someone else)

## stderr log 
`
  0%|          | 0/1042301 [00:00<?, ?B/s]
 63%|██████▎   | 654336/1042301 [00:00<00:00, 5248914.36B/s]
100%|██████████| 1042301/1042301 [00:00<00:00, 6174817.06B/s]

0B [00:00, ?B/s]
98162B [00:00, 964125.86B/s]
334982B [00:00, 1167841.34B/s]
456318B [00:00, 1780242.02B/s]
[WARNING 2020-05-26 20:08:16] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:16] Set device to local rank 6 within node.
[INFO 2020-05-26 20:08:16] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:16] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:16] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:17] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:17] Set device to local rank 7 within node.
[INFO 2020-05-26 20:08:17] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:17] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:17] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:18] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:18] Set device to local rank 5 within node.
[INFO 2020-05-26 20:08:18] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:18] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:18] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:19] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:19] Set device to local rank 0 within node.
[INFO 2020-05-26 20:08:19] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:19] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:19] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:20] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:20] Set device to local rank 2 within node.
[INFO 2020-05-26 20:08:20] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:20] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:20] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:21] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:21] Set device to local rank 3 within node.
[INFO 2020-05-26 20:08:21] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:21] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:21] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:22] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:22] Set device to local rank 4 within node.
[INFO 2020-05-26 20:08:22] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:22] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:22] Creating fp16 ZeRO stage 2 optimizer
[WARNING 2020-05-26 20:08:23] DeepSpeedConfig: In FP16 mode, DeepSpeed will pass max_grad_norm:1.0 to FP16 wrapper
[INFO 2020-05-26 20:08:23] Set device to local rank 1 within node.
[INFO 2020-05-26 20:08:23] Using client Optimizer as basic optimizer
[INFO 2020-05-26 20:08:23] DeepSpeed Basic Optimizer = FusedAdam (
Parameter Group 0
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.01

Parameter Group 1
    betas: (0.9, 0.999)
    bias_correction: True
    eps: 1e-08
    lr: 0.0
    weight_decay: 0.0
)
[INFO 2020-05-26 20:08:23] Creating fp16 ZeRO stage 2 optimizer
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 5; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 6; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 7; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 0; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 2; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 708, in <module>
    main()
  File "pretrain_gpt2.py", line 656, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "pretrain_gpt2.py", line 171, in setup_model_and_optimizer
    dist_init_required=False
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/__init__.py", line 98, in initialize
    config_params=config_params)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 172, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 496, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_light.py", line 591, in _configure_zero_optimizer
    mpu=self.mpu)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 333, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/deepspeed/pt/deepspeed_zero_optimizer.py", line 357, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 129, in step
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 8.52 GiB (GPU 3; 31.72 GiB total capacity; 25.59 GiB already allocated; 5.39 GiB free; 14.59 MiB cached)
Traceback (most recent call last):
  File "/opt/conda/envs/python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/python3.6/bin/python', '-u', 'pretrain_gpt2.py', '--local_rank=7', '--model-parallel-size', '8', '--num-layers', '80', '--hidden-size', '6144', '--num-attention-heads', '32', '--batch-size', '8', '--seq-length', '1024', '--max-position-embeddings', '1024', '--train-iters', '320000', '--train-data', 'wikipedia', '--lazy-loader', '--tokenizer-type', 'GPT2BPETokenizer', '--cache-dir', 'cache', '--split', '949,50,1', '--distributed-backend', 'nccl', '--lr', '0.0001', '--no-load-optim', '--lr-decay-style', 'cosine', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--warmup', '.01', '--checkpoint-activations', '--fp16', '--log-interval', '10', '--deepspeed', '--deepspeed_config', 'scripts/ds_zero2_config.json']' returned non-zero exit status 1.
`

**Comment by samyam** [comment]
@howellyoung-s let me try to respond to both your questions:

1. Both ZeRO-2 and ZeRO-1 reduces memory footprint by partitioning model states across data parallel GPUs. With your setting, your data parallelism is 1, so there is no memory reduction here. The max you can fit on 8 GPUs with 32 GB of memory each is likely about 8B -10B model.  The 40B parameter models you refer to in the paper are run on 400 GPUs with 8-way model parallelism and 50 way data parallelism. The minimum number of GPUs for a 40B parameters would be around 48 GPUs with 32GB memory each.

2. For the 8B model, can you try setting "contiguous_gradients" to false inside the zero configuration in deepspeed config file. If that doesn't fix your issue, can you share us your logs for that model with "wall_clock_breakdown" enabled?

**Comment by howellyoung-s** [comment]
@samyam Thanks very much for the advices! 
I find I had a misunderstanding of ZeRO, the number of partition should be the data-parallel size but not the model-parallel size. For the first question, I tried a new experiment of 40B model training on 8x8 GPUS with ZeRO-2 and 'wall_clock_breakdown=true'. This time the initialization is successfully completed but after just several iterations the OOM problem occurs again.  I upload the stdout and stderr logs of my experiment, please take a look. Is there still something wrong with my setting?
[stderr.txt](https://github.com/microsoft/DeepSpeed/files/4694546/stderr.txt)
[stdout.txt](https://github.com/microsoft/DeepSpeed/files/4694548/stdout.txt)

**Comment by samyam** [comment]
With 40B you are running close to the edge on your setup. Here are few suggestions that may help:

1. Please turn on the deepspeed_activation_checkpointing in your launch script
2. Please try turning on partition_activations, contiguous_gradients, contiguous_memory_optimization and synchronize_checkpoint_boundary (https://www.deepspeed.ai/docs/config-json/)
3. Turn on communication overlap in zero and reduce the reduce_bucket_size to 50M down from 200M that you are using

**Comment by howellyoung-s** [comment]
I change the configures according to your advices and it seems works fine now, that's cool, thanks a lot!
