### ISSUE TITLE
[BUG] I can't using pip install deepspeed

### ISSUE THREAD

**Issue by Yeqishen** [microsoft/DeepSpeed#2406]
**Describe the bug**
I can't using pip install deepspeed

**To Reproduce**
To build wheel on Windows:
    1. torch 1.12.1+cu113 , CUDA 11.7
    2.exactly install visual cpp build tool
    3. Launch cmd console with Administrator privilege.
    4. using cmd execute "pip install deepspeed"

**System info (please complete the following information):**
 - OS: Windows10
 - one machines with Nvidia 3080ti
 - https://github.com/microsoft/DeepSpeed-0.7.3
 - (if applicable) Hugging Face 1.4 / Transformers 4.22.2/ Accelerate need to install deepspeed(So, I can't install accelerate)
 - Python version - 3.10.6

**Additional context**
(venv) G:\Download\DeepSpeed-0.7.3\DeepSpeed-0.7.3>python setup.py bdist_wheel
DS_BUILD_OPS=1
Traceback (most recent call last):
  File "G:\Download\DeepSpeed-0.7.3\DeepSpeed-0.7.3\setup.py", line 166, in <module>
    ext_modules.append(builder.builder())
  File "G:\Download\DeepSpeed-0.7.3\DeepSpeed-0.7.3\op_builder\builder.py", line 596, in builder
    assert_no_cuda_mismatch()
  File "G:\Download\DeepSpeed-0.7.3\DeepSpeed-0.7.3\op_builder\builder.py", line 87, in assert_no_cuda_mismatch
    cuda_major, cuda_minor = installed_cuda_version()
  File "G:\Download\DeepSpeed-0.7.3\DeepSpeed-0.7.3\op_builder\builder.py", line 40, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)

**Comment by MT010104** [comment]
Hi, I met the same problem. Did you solve it?

**Comment by Yeqishen** [comment]
> Hi, I met the same problem. Did you solve it?

No, I still haven't solved the problem. But I no longer choose to use deepspeed when installing accelerate.

**Comment by d8ahazard** [comment]
> Hi, I met the same problem. Did you solve it?

You need to install the proper Cuda Toolkit for your pytorch version, then add the CUDA_HOME environment variable to your windows path var. 

Even after that, you will have limited success in getting this to work.

**Comment by eltonzheng** [comment]
Yes, please install cuda toolkit before generating DeepSpeed wheel, following is the "cuda_home" in my machine, which is returned from torch.utils.cpp_extension.CUDA_HOME.

(py3.7) D:\git\ds>python setup.py bdist_wheel
DS_BUILD_OPS=1
> d:\git\ds\op_builder\builder.py(40)installed_cuda_version()
-> cuda_home = torch.utils.cpp_extension.CUDA_HOME
(Pdb) n
> d:\git\ds\op_builder\builder.py(41)installed_cuda_version()
-> assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
(Pdb) p cuda_home
**'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6'**
(

**Comment by eltonzheng** [comment]
I submitted a PR to fix build issues on Windows, @Yeqishen, @MT010104 and @dfyz could you help to check if it works on your Windows?

https://github.com/microsoft/DeepSpeed/pull/2428

**Comment by tjruwase** [comment]
Closing issue, please (re)open as needed.

**Comment by xxllp** [comment]
I meet the same problem  on linux system ~~~

**Comment by macabdul9** [comment]
@xxllp did you manage to fix it?

**Comment by 46319943** [comment]
Refer to this new issue https://github.com/microsoft/DeepSpeed/issues/2772#issuecomment-2151669077.
