### ISSUE TITLE
[BUG] Nvme offload raises error even with libaio-dev installed

### ISSUE THREAD

**Issue by VikParuchuri** [microsoft/DeepSpeed#2503]
**Describe the bug**
When using a config that offloads to `nvme`, it's possible to get the `RuntimeError: Unable to JIT load the async_io op due to it not being compatible...` error even with `libaio-dev` installed.

I think this is because [has_function](https://github.com/microsoft/DeepSpeed/blob/f2710bbe1dc19717b3c99e910cb453ea20ae8b08/op_builder/builder.py#L244) will return `False`.

Oddly, when you manually patch the `has_function` call on line 93 in [async_builder.py](https://github.com/microsoft/DeepSpeed/blob/master/op_builder/async_io.py#L93) to set`verbose=True`, like `aio_compatible = self.has_function('io_submit', ('aio', ), verbose=True)` then the issue goes away.  `has_function` will now return True.

**To Reproduce**
1. Open Google colab.
2. Install libaio-dev.
3. Install deepspeed.
4. Run this code, it will return False:

```
import deepspeed
from deepspeed.ops.aio import AsyncIOBuilder
AsyncIOBuilder().has_function('io_submit', ('aio', ))
```

5. Run this code, it will return True:

```
import deepspeed
from deepspeed.ops.aio import AsyncIOBuilder
AsyncIOBuilder().has_function('io_submit', ('aio', ), verbose=True)
```

**Expected behavior**
I expect that `has_function` returns `True` correctly when `libaio` is installed.  I also expect the function to behave identically whether `verbose` is passed in or not.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c /tmp/tmpux34luem/test.c -o /tmp/tmpux34luem/test.o
x86_64-linux-gnu-gcc -pthread /tmp/tmpux34luem/test.o -laio -o /tmp/tmpux34luem/a.out
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.7/dist-packages/torch']
torch version .................... 1.12.1+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.2
deepspeed install path ........... ['/usr/local/lib/python3.7/dist-packages/deepspeed']
deepspeed info ................... 0.7.4, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 18.04 (Google colab
 - GPU count and types [e.g. two machines with x8 A100s each]: A100
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version: 3.7
 - Any other relevant info about your setup

**Comment by tjruwase** [comment]
@VikParuchuri, thanks for reporting this issue. Unfortunately, I am unable to repro using the test code as shown below. 

```bash
async_io ............... [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/ptca/lib/python3.8/site-packages/torch']
torch version .................... 1.12.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/opt/conda/envs/ptca/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.7.5+unknown, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.3
# cat /tmp/aio_terse.py
import deepspeed
from deepspeed.ops.aio import AsyncIOBuilder
r=AsyncIOBuilder().has_function('io_submit', ('aio', ))
print(f'{r=}')
# python /tmp/aio_terse.py
r=True
# cat /tmp/aio_verbose.py
import deepspeed
from deepspeed.ops.aio import AsyncIOBuilder
r=AsyncIOBuilder().has_function('io_submit', ('aio', ), verbose=True)
print(f'{r=}')
# python /tmp/aio_verbose.py
gcc -pthread -B /opt/conda/envs/ptca/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -c /tmp/tmpu3vzynbq/test.c -o /tmp/tmpu3vzynbq/test.o
gcc -pthread -B /opt/conda/envs/ptca/compiler_compat -Wl,--sysroot=/ /tmp/tmpu3vzynbq/test.o -laio -o /tmp/tmpu3vzynbq/a.out
r=True

```

Can you please run one of the aio unit tests by doing the following?
1. Clone and install the master branch
2. From the root source folder run and share output of: 
```bash
pytest -sv tests/unit/ops/aio/test_aio.py::TestRead::test_parallel_read[True-True]
```

**Comment by VikParuchuri** [comment]
Sure, here's the output.  I can still repro the issue following the steps above on Colab.

Steps I followed to run the tests:

- Launch a Colab notebook with a premium gpu and high memory
- Clone the Deepspeed repo
- `python setup.py install`
- Ran the tests

```
/DeepSpeed# pytest -sv tests/unit/ops/aio/test_aio.py::TestRead::test_parallel_read[True-True]
==================== test session starts =====================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: tests/.pytest_cache
rootdir: /DeepSpeed/DeepSpeed/tests, inifile: pytest.ini
plugins: typeguard-2.7.1
collected 1 item                                             

tests/unit/ops/aio/test_aio.py::TestRead::test_parallel_read[True-True] [2022-11-14 23:36:19,026] [INFO] [comm.py:635:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeed/DeepSpeed/tests/unit/common.py", line 160, in _dist_init
    dist.barrier()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/comm.py", line 126, in log_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/comm.py", line 458, in barrier
    return cdb.barrier()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/torch.py", line 153, in barrier
    return torch.distributed.barrier()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 2784, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeed/DeepSpeed/tests/unit/common.py", line 160, in _dist_init
    dist.barrier()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/comm.py", line 126, in log_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/comm.py", line 458, in barrier
    return cdb.barrier()
  File "/usr/local/lib/python3.7/dist-packages/deepspeed/comm/torch.py", line 153, in barrier
    return torch.distributed.barrier()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 2784, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
FAILED

========================== FAILURES ==========================
___________ TestRead.test_parallel_read[True-True] ___________
Worker 0 exited with code 1
====================== warnings summary ======================
unit/ops/aio/test_aio.py::TestRead::()::test_parallel_read[True-True]
  /DeepSpeed/DeepSpeed/tests/conftest.py:36: UserWarning: Running test without verifying torch version, please provide an expected torch version with --torch_ver
    "Running test without verifying torch version, please provide an expected torch version with --torch_ver"
  /DeepSpeed/DeepSpeed/tests/conftest.py:44: UserWarning: Running test without verifying cuda version, please provide an expected cuda version with --cuda_ver
    "Running test without verifying cuda version, please provide an expected cuda version with --cuda_ver"

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============ 1 failed, 2 warnings in 8.71 seconds ============
```

**Comment by tjruwase** [comment]
@VikParuchuri, thanks for the sharing your log. However, the following snippet is an unrelated failure that is preventing the test from running: 

```bash
> File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 2784, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
> ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
> FAILED
```

Are you able to run any other unit test, such as 
`pytest -sv tests/unit/runtime/half_precision/test_fp16.py::TestFP16AdamTypes::test[False-AdamW]`

**Comment by tjruwase** [comment]
Closing for lack of response. Please re-open as appropriate.

**Comment by CurryRice233** [comment]
I found the same case in GPT-NeoX. The reason is sys.stderr was replaced by another object, and an exception is thrown when sys.stderr.fileno() is called.
