### ISSUE TITLE
multi_tensor_apply.py RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by xings19** [microsoft/DeepSpeed#2513]
```text
Traceback (most recent call last):
  File "main_deepspeed.py", line 614, in <module>
Traceback (most recent call last):
  File "main_deepspeed.py", line 614, in <module>
    main(args, config, ds_init)
  File "main_deepspeed.py", line 183, in main
    main(args, config, ds_init)
  File "main_deepspeed.py", line 183, in main
    model_parameters = optimizer_params,
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/__init__.py", line 129, in initialize
    model_parameters = optimizer_params,
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/__init__.py", line 129, in initialize
    config_params=config_params)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 294, in __init__
    config_params=config_params)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 294, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1150, in _configure_optimizer
    self._configure_optimizer(optimizer, model_parameters)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1150, in _configure_optimizer
    self.optimizer = self._configure_fp16_optimizer(basic_optimizer)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1288, in _configure_fp16_optimizer
    self.optimizer = self._configure_fp16_optimizer(basic_optimizer)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1288, in _configure_fp16_optimizer
    timers=timers,
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 111, in __init__
    timers=timers,
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 111, in __init__
    self.initialize_optimizer_states()
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 119, in initialize_optimizer_states
    self.initialize_optimizer_states()
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 119, in initialize_optimizer_states
    self.optimizer.step()
  File "/mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    self.optimizer.step()
  File "/mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/ops/adam/fused_adam.py", line 180, in step
    return func(*args, **kwargs)
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/ops/adam/fused_adam.py", line 180, in step
    group['weight_decay'])
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/ops/adam/multi_tensor_apply.py", line 15, in __call__
    group['weight_decay'])
  File "/mnt/lustre/xingsen/.local/lib/python3.7/site-packages/deepspeed/ops/adam/multi_tensor_apply.py", line 15, in __call__
    return op(self.chunk_size, noop_flag_buffer, tensor_lists, *args)
RuntimeError: CUDA error: an illegal memory access was encountered
    return op(self.chunk_size, noop_flag_buffer, tensor_lists, *args)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:172, unhandled cuda error, NCCL version 21.0.3
Process Group destroyed on rank 0
Exception raised from ncclCommAbort at ../torch/csrc/distributed/c10d/NCCLUtils.hpp:172 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f2f7242e7d2 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f2f7242ae6b in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x271894e (0x7f2fc54e894e in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x123 (0x7f2fc54ca413 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x9 (0x7f2fc54ca699 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #5: <unknown function> + 0x815336 (0x7f3027d5b336 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x7f88e5 (0x7f3027d3e8e5 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x1f57a0 (0x7f302773b7a0 in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x1f69ee (0x7f302773c9ee in /mnt/lustre/xingsen/.conda/envs/MAE/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xfc337 (0x55d41bac7337 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #10: PyDict_Clear + 0x141 (0x55d41bac70b1 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #11: <unknown function> + 0xfc179 (0x55d41bac7179 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #12: <unknown function> + 0x1638c6 (0x55d41bb2e8c6 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #13: _PyGC_CollectNoFail + 0x2a (0x55d41bbcc75a in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #14: PyImport_Cleanup + 0x4bc (0x55d41bb77f9c in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #15: Py_FinalizeEx + 0x64 (0x55d41bbec714 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #16: <unknown function> + 0x232e20 (0x55d41bbfde20 in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #17: _Py_UnixMain + 0x3c (0x55d41bbfe18c in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
frame #18: __libc_start_main + 0xf5 (0x7f30349903d5 in /lib64/libc.so.6)
frame #19: <unknown function> + 0x1d803a (0x55d41bba303a in /mnt/lustre/xingsen/.conda/envs/MAE/bin/python)
```
When I try to train a model with a parameter size of 3B, I get this error, training a smaller model will work fine, I think this problem is consistent with the problem in this [link](https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/249) how can I solve it when using deepspeed ?

**Comment by jomayeri** [comment]
@xings19 could you give your ds_config, reproduction code, and GPU setup so I can try to reproduce the error. Thanks.

**Comment by xings19** [comment]
Thank you for your reply!

My config.json:
```json
{
  "train_batch_size": 768,
  "train_micro_batch_size_per_gpu": 96,
  "steps_per_print": 1000, 
  "optimizer": {
    "type": "Adam",
    "adam_w_mode": true,
    "params": {
      "lr": 0.000125,
      "weight_decay": 0.05,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-08,
      "torch_adam": true
    }
  },
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 7,
    "loss_scale_window": 128
  }
}
```
If i set 'torch_adam' to 'false',the program will report an error, and I guess it is an error that occurred when using fused adam. When I use torch's optimizer or reduce the model size, the program works normally.

My initialization code is as follows, my model is halonet with 3B parameter amount
```python
optimizer_params = filter(lambda p: p.requires_grad, model.parameters())
        model, optimizer,_,_ = ds_init(
            args = args,
            model = model,
            model_parameters = optimizer_params
        )
```

My torch version is 1.11.0+cu113, deepspeed version is 0.5.8.

**Comment by jomayeri** [comment]
Closing the issue for now. Please reopen if there are additional questions or concerns.
