### ISSUE TITLE
Out of memory when training T5-large[BUG]

### ISSUE THREAD

**Issue by Pna2791** [microsoft/DeepSpeed#2563]
I try to train T5-large with max length of 1024 but A100 with 40GB is not enough memory.
I am using deepspeed to reduce memory when training, but it does not work.
How to config deepspeed to using less than memory during training a model?

I am using 8 A100 on Ubuntu 20.04
I use accelerator and deepspeed plugin to training. My script: [Test.py](https://github.com/microsoft/DeepSpeed/files/10137620/Test.py.txt)

Full my log: [logs.txt](https://github.com/microsoft/DeepSpeed/files/10137590/log.txt)
My log:
```
[2022-12-02 09:03:13,792] [INFO] [config.py:1011:print]   zero_enabled ................. True
[2022-12-02 09:03:13,792] [INFO] [config.py:1011:print]   zero_optimization_stage ...... 3
[2022-12-02 09:03:13,792] [INFO] [config.py:996:print_user_config]   json = {
    "optimizer": {
        "type": "AdamW", 
        "params": {
            "lr": 0.001, 
            "weight_decay": 0
        }
    }, 
    "activation_checkpointing": {
        "partition_activations": true, 
        "cpu_checkpointing": true, 
        "contiguous_memory_optimization": false, 
        "number_checkpoints": 0, 
        "synchronize_checkpoint_boundary": true, 
        "profile": true
    }, 
    "zero_optimization": {
        "stage": 3, 
        "contiguous_gradients": true, 
        "stage3_max_live_parameters": 1, 
        "stage3_max_reuse_distance": 1, 
        "stage3_prefetch_bucket_size": 1, 
        "stage3_param_persistence_threshold": 1, 
        "reduce_bucket_size": 1, 
        "sub_group_size": 1, 
        "offload_optimizer": {
            "device": "cpu"
        }, 
        "offload_param": {
            "device": "cpu"
        }
    }, 
    "gradient_accumulation_steps": 1, 
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_clipping": 1.0, 
    "steps_per_print": inf, 
    "train_batch_size": 1, 
    "memory_breakdown": true
}
Using /home/anhpn19/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0006728172302246094 seconds
2022-12-02 09:03:13.793756      Training...
[2022-12-02 09:03:13,850] [INFO] [utils.py:827:see_memory_usage] Engine before forward
[2022-12-02 09:03:13,851] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.42 GB         Max_CA 0 GB 
[2022-12-02 09:03:13,851] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 97.79 GB, percent = 9.7%
Traceback (most recent call last):
  File "acc.py", line 52, in <module>
    loss = model(input_ids=data, attention_mask=mask, labels=target).loss
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1676, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1611, in forward
    encoder_outputs = self.encoder(
File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1040, in forward
    layer_outputs = layer_module(
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 673, in forward
    self_attention_outputs = self.layer[0](
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 579, in forward
    attention_output = self.SelfAttention(
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 539, in forward
    attn_weights = nn.functional.softmax(scores.float(), dim=-1).type_as(
  File "/home/anhpn19/miniconda3/envs/DeepSpeed/lib/python3.8/site-packages/torch/nn/functional.py", line 1834, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 39.59 GiB total capacity; 31.26 GiB already allocated; 1.14 GiB free; 31.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3086372) of binary: /home/anhpn19/miniconda3/envs/DeepSpeed/bin/python
```

**Comment by tjruwase** [comment]
@Pna2791, thanks for reporting this issue.

Can you please double check your configuration as your log suggests you are running with 1 gpu not 8
<img width="395" alt="image" src="https://user-images.githubusercontent.com/4271600/205332400-6ecb348b-e92c-4eb8-8fc6-0a4677b29cf1.png">

**Comment by Pna2791** [comment]
> @Pna2791, thanks for reporting this issue.
> 
> Can you please double check your configuration as your log suggests you are running with 1 gpu not 8
> <img width="395" alt="image" src="https://user-images.githubusercontent.com/4271600/205332400-6ecb348b-e92c-4eb8-8fc6-0a4677b29cf1.png">
> 

Yes, I just using 1 GPU, but Deepspeed can train large model just use only 1 GPU.

**Comment by tjruwase** [comment]
The ZeRO memory optimizations of DeepSpeed are designed for multi-GPU runs. They memory savings come from memory deduplication across data parallel model replicas. Please see the following paper: https://arxiv.org/abs/1910.02054

**Comment by tjruwase** [comment]
Closing, please re-open as needed.
