### ISSUE TITLE
[BUG] Can not change input parameter value during inference runtime

### ISSUE THREAD

**Issue by zhazhn** [microsoft/DeepSpeed#2572]
Hello,
I followed this article, all thing goes well. However I can not change input value at runtime, for example, the in the first request width=512, it works fine, the second request width=640, it will throw the following exception,
......
#first call
image = ds_pipeline(prompt, height=512, width=512).images[0]
#second call
image = ds_pipeline(prompt, height=256, width=512).images[0]
......

I doubt some place cached shape size, and do you know how to reset it. thanks.

https://www.philschmid.de/stable-diffusion-deepspeed-inference

Traceback (most recent call last):
  File "/home/ubuntu/sdtest/ds-gen.py", line 80, in <module>
    ds_results = measure_latency(ds_pipeline,prompt)
  File "/home/ubuntu/sdtest/ds-gen.py", line 65, in measure_latency
    _ =  pipe(prompt, **generate_kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 564, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 532, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/deepspeed/module_inject/unet.py", line 35, in forward
    outputs = self._graph_replay(*inputs, **kwargs)
  File "/home/ubuntu/sdtest/sdtest-venv/lib/python3.9/site-packages/deepspeed/module_inject/unet.py", line 26, in _graph_replay
    self.static_inputs[i].copy_(inputs[i])
RuntimeError: The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 2

**Comment by zhazhn** [comment]
thanks for your response.
