### ISSUE TITLE
[BUG] Can't load OPT-2.7B and OPT-66B with DeepSpeed

### ISSUE THREAD

**Issue by anselmwang** [microsoft/DeepSpeed#2593]
Sorry, this is a "DeepSpeed Inference" issue, I misclassified it as "DeepSpeed Compression" issue.

**Describe the bug**
I use DeepSpeed Inference to launch OPT models, now I have tested OPT-2.7B and OPT-66B, both are not able to load.
I am using [Huggingface team's speed test code](https://github.com/anselmwang/transformers-bloom-inference/tree/fix-deadlock),

**To Reproduce**
python 3.7.7

```bash
git clone https://github.com/anselmwang/transformers-bloom-inference/
cd transformers-bloom-inference
git checkout fix-deadlock

pip install --upgrade pip
pip install transformers>=4.21.3 accelerate>=0.12.0
pip install deepspeed>=0.7.3
```

To avoid downloading model take too long, I first run following script to download
```python
from huggingface_hub import snapshot_download
snapshot_download(
    'facebook/opt-66b',
    local_files_only=False,
    cache_dir=None,
    ignore_patterns=["*.safetensors"],
    resume_download=True
)
```

OPT 2.7B Run command `deepspeed --num_gpus 16 bloom-inference-scripts/bloom-ds-inference.py --name facebook/opt-2.7b --batch_size 1`

```bash
Loading 1 checkpoint shards:   0%|                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                        
  File "bloom-inference-scripts/bloom-ds-inference.py", line 187, in <module>                                                                                                             
    **kwargs,                                                                                                                                                                             
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/__init__.py", line 311, in init_inference                                                       
    engine = InferenceEngine(model, config=ds_inference_config)                                                                                                                           
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 124, in __init__                                                     
    self._apply_injection_policy(config)                                                                                                                                                  
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 353, in _apply_injection_policy                                      
    self.config)                                                                                                                                                                          
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py", line 913, in replace_transformer_layer                        
    quantizer,                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 230, in load_model_with_checkpoint                      
    load_module_recursive(r_module)                                                                                                                                                       
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 228, in load_module_recursive                           
    level + 1)                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 228, in load_module_recursive                           
    level + 1)                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 223, in load_module_recursive                           
    layer_policies[child.__class__](child, prefix + name + '.')                                                                                                                           
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 35, in load                                             
    sd[0][prefix + 'weight'])                                                                                                                                                             
KeyError: 'decoder.embed_tokens.weight'                                                       `
```

OPT-66B, Run command `deepspeed --num_gpus 16 bloom-inference-scripts/bloom-ds-inference.py --name facebook/opt-66b --batch_size 1`
Here is the result
```bash
Loading 14 checkpoint shards:   0%|                                                                                                                                | 0/14 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                        
  File "bloom-inference-scripts/bloom-ds-inference.py", line 187, in <module>                                                                                                             
    **kwargs,                                                                                                                                                                             
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/__init__.py", line 311, in init_inference                                                       
    engine = InferenceEngine(model, config=ds_inference_config)                                                                                                                           
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 124, in __init__                                                     
    self._apply_injection_policy(config)                                                                                                                                                  
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 353, in _apply_injection_policy                                      
    self.config)                                                                                                                                                                          
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py", line 913, in replace_transformer_layer                        
    quantizer,                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 230, in load_model_with_checkpoint                      
    load_module_recursive(r_module)                                                                                                                                                       
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 228, in load_module_recursive                           
    level + 1)                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 228, in load_module_recursive                           
    level + 1)                                                                                                                                                                            
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 228, in load_module_recursive                           
    level + 1)                                                                                                                                                                            
  [Previous line repeated 2 more times]                                                                                                                                                   
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 223, in load_module_recursive                           
    layer_policies[child.__class__](child, prefix + name + '.')                                                                                                                           
  File "/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 35, in load                                             
    sd[0][prefix + 'weight'])                                                                                                                                                             
KeyError: 'decoder.layers.52.self_attn.k_proj.weight'                                                           
```

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
DeepSpeed C++/CUDA extension op report                                                                                              
--------------------------------------------------                                                                                 
NOTE: Ops not installed will be just-in-time (JIT) compiled at                    
      runtime if needed. Op compatibility means that your system                                                                                          
      meet the required dependencies to JIT install the op.                                                         
--------------------------------------------------
JIT compiled ops requires ninja                                                                                                              
ninja .................. [OKAY]                                                            
--------------------------------------------------
op name ................ installed .. compatible                                                                        
--------------------------------------------------        
cpu_adam ............... [NO] ....... [OKAY]            
cpu_adagrad ............ [NO] ....... [OKAY]                                                             
fused_adam ............. [NO] ....... [OKAY]                                                                      
fused_lamb ............. [NO] ....... [OKAY]                                                                       
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/torch']
torch version .................... 1.13.0+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed install path ........... ['/tmp/code/transformers-bloom-inference/venv/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.7.6, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types: 1 node with 16x V100.
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 ```
transformers             4.25.1
accelerate               0.15.0
deepspeed                0.7.6
torch                    1.13.0
```
 - Python version: 3.7.7
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?
Not use docker
**Additional context**

**Comment by anselmwang** [comment]
I find this is a bug in my code, For OPT like model, we are not able to load through checkpoint method, but has to load by Huggingface. Close the issue
