### ISSUE TITLE
[BUG] As soon as I run code, I got ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by 9B8DY6** [microsoft/DeepSpeed#2601]
```
[2022-12-13 10:10:54,376] [WARNING] [runner.py:179:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/home/da981116/.conda/envs/gfmn/bin/deepspeed", line 6, in <module>
    main()
  File "/home/da981116/.conda/envs/gfmn/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 392, in main
    active_resources = parse_inclusion_exclusion(resource_pool,
  File "/home/da981116/.conda/envs/gfmn/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 313, in parse_inclusion_exclusion
    return parse_resource_filter(active_resources,
  File "/home/da981116/.conda/envs/gfmn/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 258, in parse_resource_filter
    slots = [int(x) for x in slots.split(SLOT_SEP)]
  File "/home/da981116/.conda/envs/gfmn/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 258, in <listcomp>
    slots = [int(x) for x in slots.split(SLOT_SEP)]
ValueError: invalid literal for int() with base 10: ''
```
I wanted to fix it but i think it is not my code fault...so could you tell me what is wrong?

**Comment by 9B8DY6** [comment]
I solve it sorry for bothering you

**Comment by jomayeri** [comment]
No problem, thanks for letting us know.

**Comment by VoiceBeer** [comment]
Hi I was wondering how u fixed it, thx in advance xD

**Comment by 070110053** [comment]
@9B8DY6 I wonder how you solved this problem

**Comment by greenlight2124** [comment]
It could be due to extra spaces. If you write parameter as '--include localhost:1, 2' with a space, you'll encounter this problem.
The correct form is '--include localhost:1,2' without a space.
