### ISSUE TITLE
[BUG] deepspeed.init() with binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4

### ISSUE THREAD

**Issue by ChenQX1** [microsoft/DeepSpeed#2654]
Code snippets that cause errors.
```python

def main(cfgs, args):
    # ...

   model_engine, optimizer, train_loader, _ = deepspeed.initialize(args=args, model=model, model_parameters=parameters, training_data=train_set)

    # ...

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='CIFAR')
    parser.add_argument('--with_cuda',
                        default=False,
                        action='store_true',
                        help='use CPU in case there\'s no GPU support')

    parser.add_argument('--local_rank',
                        type=int,
                        default=-1,
                        help='local rank passed from distributed launcher')
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()
    
    hydra.initialize(version_base='1.2', config_path="./", job_name="test_app")
    cfgs = hydra.compose(config_name='cifar100')
    
    main(cfgs, args)
```

Full errors:

```shell
Traceback (most recent call last):
  File "trainer/vit_imgclassifier.py", line 142, in <module>
    main(cfgs, args)
  File "trainer/vit_imgclassifier.py", line 91, in main
    model_engine, optimizer, train_loader, _ = deepspeed.initialize(args=args, model=model, model_parameters=parameters, training_data=train_set)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 265, in __init__
    self._configure_with_arguments(args, mpu)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 926, in _configure_with_arguments
    self._config = DeepSpeedConfig(self.config, mpu)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/config.py", line 729, in __init__
    config_decoded = base64.urlsafe_b64decode(config).decode('utf-8')
  File "/opt/conda/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/opt/conda/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4
[2022-12-28 06:48:21,367] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2812
[2022-12-28 06:48:21,369] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python3.8', '-u', 'trainer/vit_imgclassifier.py', '--local_rank=0', '--with_cuda', '--deepspeed', '--deepspeed_config', 'ds_config.json'] exits with return code = 1
```

Command
```shell
deepspeed trainer/vit_imgclassifier.py --with_cuda --deepspeed --deepspeed_config ds_config.json
```

ds_config.json

```json
{
   "train_batch_size": 4,
   "steps_per_print": 2000,
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.001,
       "betas": [
         0.8,
         0.999
       ],
       "eps": 1e-8,
       "weight_decay": 3e-7
     }
   },
   "scheduler": {
     "type": "WarmupLR",
     "params": {
       "warmup_min_lr": 0,
       "warmup_max_lr": 0.001,
       "warmup_num_steps": 1000
     }
   },
   "wall_clock_breakdown": false
 }
```

**Comment by xiexbing** [comment]
@ChenQX1 , can you please provide full description of vit_imgclassifier.py and how to generate your dataset 'cifar100'. I want to repeat the bug but cannot do so till the full description and dataset is there. Thanks.

**Comment by ChenQX1** [comment]
> 



> @ChenQX1 , can you please provide full description of vit_imgclassifier.py and how to generate your dataset 'cifar100'. I want to repeat the bug but cannot do so till the full description and dataset is there. Thanks.

Well it's just a normal training script. I load CIFAR100 via torchvision.datasets, initialize a nn.Module object, and so on.

The difference is that I try to pass some arguments from the CLI, and the DeepSpeed’s configuration at the same time. But `deepspeed.initialize(args=args, ...)` will cause errors. If I don't pass the CLI arguments, everything goes well.

**Comment by xiexbing** [comment]
@ChenQX1, can you please post your vit_imgclassifier.py file in this thread?

**Comment by ChenQX1** [comment]
> 

```python
def train(cfgs: DictConfig, epoch: int, dataloader: DataLoader, model: Union[nn.Module, DeepSpeedEngine],
          optimizer, criterion) -> float:
    st = time()
    loss_epoch = 0.
    iter_n = 0
    local_rank = dist.get_rank()
    use_ds = isinstance(model, DeepSpeedEngine)
    for iter_n, (x, y) in enumerate(dataloader):
        if use_ds:
            x, y = x.to(model.local_rank), y.to(model.local_rank)
        outputs = model(x)
        loss = criterion(outputs, y)
        if use_ds:
            model.backward(loss)
            model.step()
        else:
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        loss_epoch += loss.detach().cpu().numpy()

    loss_epoch = round(loss_epoch / (iter_n + 1), 3)
    print(f"Epoch {epoch} / {cfgs.nepochs} device {local_rank} loss: {loss_epoch}, time: {round(time() - st, 1)}")
    if local_rank == 0:
        mlflow.log_metric('loss/train', loss_epoch, step=epoch)

    return loss_epoch

if __name__ == "__main__":
    if torch.cuda.is_available():
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
        torch.backends.cudnn.benchmark = True
        deepspeed.init_distributed(dist_backend='nccl')
        print('#' * 10, f'Init DeepSpeed at process {dist.get_rank()}', '#' * 10)

    parser = argparse.ArgumentParser(description='CIFAR')
    parser.add_argument(
        '--with_cuda',
        default=False,
        action='store_true',
        help='use CPU in case there\'s no GPU support'
    )

    parser.add_argument(
        '--local_rank',
        type=int,
        default=-1,
        help='local rank passed from distributed launcher'
    )
    parser = deepspeed.add_config_arguments(parser)
    ds_args = parser.parse_args()

    hydra.initialize(version_base='1.2', config_path="./", job_name="test_app")
    cfgs = hydra.compose(config_name='resnet_cifar100')

    use_gpu = torch.cuda.is_available()

    main(cfgs, ds_args)
```

**Comment by xiexbing** [comment]
@ChenQX1, thanks!

**Comment by xiexbing** [comment]
@ChenQX1 can you please also provide the imports in vit_imgclassifier.py? I am trying to add them in, but seems missing a lot of dependencies, triggering a lot of errors rather than showing the errors in your report. --thx, Bing

**Comment by cli99** [comment]
Hi, @ChenQX1, the error suggests that the `config` (https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/config.py#L707) does not exist, thus it proceeds to the `else` clause where it tries to decode the arg as base64 string. Can you check if `os.path.exists(config)` is True in your run? The quickest way is to go to the source file under /opt/conda/lib and add some printing statement.

**Comment by MrCrHaM** [comment]
> Hi, @ChenQX1, the error suggests that the `config` (https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/config.py#L707) does not exist, thus it proceeds to the `else` clause where it tries to decode the arg as base64 string. Can you check if `os.path.exists(config)` is True in your run? The quickest way is to go to the source file under /opt/conda/lib and add some printing statement.

I met the same error and checked that `os.path.exists(config)` is `False`. So maybe include `binascii.Error` in the `except` so that the error message would make much more sense?
