### ISSUE TITLE
[BUG] Caching op_builder kernels

### ISSUE THREAD

**Issue by tchaton** [microsoft/DeepSpeed#2735]
**Describe the bug**

Dear DeepSpeed Team, I have a quick question. I am trying to build a docker image with op_builder already compiled. However, I am facing the error added below. Would you have any idea ?

```python
from deepspeed.ops import op_builder

transformer_cuda_module = None
spatial_cuda_module = None

def load_transformer_module():
    global transformer_cuda_module
    if transformer_cuda_module is None:
        transformer_cuda_module = op_builder.InferenceBuilder().load()
    return transformer_cuda_module


def load_spatial_module():
    global spatial_cuda_module
    if spatial_cuda_module is None:
        spatial_cuda_module = op_builder.SpatialInferenceBuilder().load()
    return spatial_cuda_module


load_transformer_module()
load_spatial_module()
```

```python
#9 3.358 Installed CUDA version 11.5 does not match the version torch was compiled with 11.7 but since the APIs are compatible, accepting this combination    
#9 3.358 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'                                                                                          
#9 3.359 Traceback (most recent call last):                                                                                                                   
#9 3.359   File "deepspeed_load.py", line 20, in <module>                                                                                                     
#9 3.359     load_transformer_module()
#9 3.359   File "deepspeed_load.py", line 9, in load_transformer_module
#9 3.359     transformer_cuda_module = op_builder.InferenceBuilder().load()
#9 3.359   File "/home/zeus/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 462, in load
#9 3.359     return self.jit_load(verbose)
#9 3.359   File "/home/zeus/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 502, in jit_load
#9 3.359     extra_cuda_cflags=self.strip_empty_entries(self.nvcc_args()),
#9 3.359   File "/home/zeus/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 665, in nvcc_args
#9 3.359     args += self.compute_capability_args()
#9 3.359   File "/home/zeus/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 544, in compute_capability_args
#9 3.359     ccs[-1] += '+PTX'
#9 3.359 IndexError: list index out of range
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/bash -c TORCH_CUDA_ARCH_LIST=7.5 python deepspeed_load.py]: exit code:
```

**To Reproduce**
1. Simple inference script to reproduce
2. What packages are required and their versions
3. How to run the script
4. ...

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by lokoppakmsft** [comment]
@tchaton, please use following instructions to build Deepspeed ops 
https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops. Let us know if it works for you.
