### ISSUE TITLE
[BUG] NCCL Internal Check Failed

### ISSUE THREAD

**Issue by gabrielhuang** [microsoft/DeepSpeed#2767]
**Describe the bug**
I'm trying to finetune Codegen-16B on 4xA100-80GB gpus, and I get this error quite often (but not consistently). When there's no error, training proceeds normally, so it's quite mysterious to me.

```
  File "/home/toolkit/snapshots/5fcc189d48c417cb59137711d98a3fcd43f9d6a2/scripts/finetune.py", line 1171, in main
    accelerator.backward(loss)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1310, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 156, in backward
    self.engine.backward(loss)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1860, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2070, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 51, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1318, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1079, in reduce_independent_p_g_buckets_and_remove_grads
    self.__reduce_and_partition_ipg_grads()
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1136, in __reduce_and_partition_ipg_grads
    grad_partitions = self.__avg_scatter_grads(self.__params_in_ipg_bucket)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1159, in __avg_scatter_grads
    grad_partitions_for_rank = reduce_scatter_coalesced(full_grads_for_rank,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 87, in reduce_scatter_coalesced
    _torch_reduce_scatter_fn(tensor_partition_flat_buffer,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 22, in _torch_reduce_scatter_fn
    return instrument_w_nvtx(dist.reduce_scatter_fn)(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 267, in reduce_scatter_fn
    return reduce_scatter_base(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 126, in log_wrapper
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 301, in reduce_scatter_base
    return cdb.reduce_scatter_base(output_tensor=output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 102, in reduce_scatter_base
    return torch.distributed._reduce_scatter_base(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2854, in _reduce_scatter_base
    return reduce_scatter_tensor(output, input, op, group, async_op)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2821, in reduce_scatter_tensor
    work = group._reduce_scatter_base(output, input, opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Net : Call to recv from 10.210.64.125<34787> failed : Connection refused
```

and here's another probably related error
```
Error executing job with overrides: ['finetune=codegen_16B_mono', 'finetune.lr_scheduler_type=cosine', 'finetune.learning_rate=1e-4', 'finetune.train_batch_size=1', 'finetune.gradient_accumulation_passes=4']
Traceback (most recent call last):
  File "/home/toolkit/snapshots/5fcc189d48c417cb59137711d98a3fcd43f9d6a2/scripts/finetune.py", line 1171, in main
    accelerator.backward(loss)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1310, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 156, in backward
    self.engine.backward(loss)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1860, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2070, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 51, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1318, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1079, in reduce_independent_p_g_buckets_and_remove_grads
    self.__reduce_and_partition_ipg_grads()
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1136, in __reduce_and_partition_ipg_grads
    grad_partitions = self.__avg_scatter_grads(self.__params_in_ipg_bucket)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1159, in __avg_scatter_grads
    grad_partitions_for_rank = reduce_scatter_coalesced(full_grads_for_rank,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 87, in reduce_scatter_coalesced
    _torch_reduce_scatter_fn(tensor_partition_flat_buffer,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 22, in _torch_reduce_scatter_fn
    return instrument_w_nvtx(dist.reduce_scatter_fn)(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 267, in reduce_scatter_fn
    return reduce_scatter_base(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 126, in log_wrapper
    return func(*args, **kwargs)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 301, in reduce_scatter_base
    return cdb.reduce_scatter_base(output_tensor=output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 102, in reduce_scatter_base
    return torch.distributed._reduce_scatter_base(output_tensor,
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2854, in _reduce_scatter_base
    return reduce_scatter_tensor(output, input, op, group, async_op)
  File "/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2821, in reduce_scatter_tensor
    work = group._reduce_scatter_base(output, input, opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
[Proxy Service 0] Failed to execute operation Setup from rank 0, retcode 1
```

**Expected behavior**
For training to proceed normally

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
spatial_inference ...... [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/torch']
torch version .................... 1.13.1+cu117
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed install path ........... ['/home/toolkit/.conda/envs/llmdconda/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.7.7, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Single Node
 - Python 3.10

**Launcher context**
Using Deepspeed integration in Accelerate

**Docker context**
```
NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.6
```
Image based on `pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel`

**Additional context**

**Comment by gabrielhuang** [comment]
I just reran my script with `NCCL_DEBUG=INFO`

```

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] include/alloc.h:99 NCCL WARN Cuda failure 'out of memory'

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] include/alloc.h:105 NCCL WARN Failed to CUDA calloc 6291456 bytes
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] NCCL INFO transport/p2p.cc:430 -> 1
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] NCCL INFO proxy.cc:989 -> 1
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] NCCL INFO proxy.cc:1019 -> 1

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] proxy.cc:1119 NCCL WARN [Proxy Service 0] Failed to execute operation Setup from rank 0, retcode 1

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] misc/socket.cc:538 NCCL WARN Net : Connection closed by remote peer 2ea769d3-c838-4116-aa1f-1e9d185d0fab<55221>
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO misc/socket.cc:546 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO misc/socket.cc:558 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO proxy.cc:881 -> 6

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] proxy.cc:884 NCCL WARN Proxy Call to rank 0 failed (Setup)
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO transport/p2p.cc:261 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO transport.cc:33 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO transport.cc:98 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO init.cc:790 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO init.cc:1089 -> 6
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356135 [0] NCCL INFO group.cc:64 -> 6 [Async thread]
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356118 [0] NCCL INFO group.cc:421 -> 3
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356118 [0] NCCL INFO group.cc:106 -> 3
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355526:356136 [1] NCCL INFO Channel 20/0 : 1[47000] -> 2[4e000] via P2P/IPC/read
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355527:356137 [2] NCCL INFO Channel 20/0 : 2[4e000] -> 3[90000] via P2P/IPC/read

2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] include/alloc.h:98 NCCL WARN Cuda failure 'out of memory'
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] NCCL INFO transport/p2p.cc:430 -> 1
2ea769d3-c838-4116-aa1f-1e9d185d0fab:355525:356159 [0] NCCL INFO proxy.cc:989 -> 1
```

I guess ultimately it's an OOM error. I'll just try with more GPUs ...
