### ISSUE TITLE
[BUG] 'CUDA error: an illegal instruction was encountered' during GPT-NeoX inference

### ISSUE THREAD

**Issue by JiayiFeng** [microsoft/DeepSpeed#2813]
**Describe the bug**

I try to run a self-trained GPT-NeoX model inference with deepspeed. However it crash with following error message:

```
Free memory : 27.346863 (GigaBytes)  
Total memory: 39.587097 (GigaBytes)  
Requested memory: 0.750000 (GigaBytes) 
Setting maximum total tokens (input + output) to 1024
------------------------------------------------------
!!!! kernel execution error. (m: 7, n: 7, k: 80, error: 13) 
!!!! kernel execution error. (m: 80, n: 7, k: 7, error: 13) 
!!!! kernel execution error. (m: 2560, n: 7, k: 2560, error: 13) 
!!!! kernel execution error. (m: 10240, n: 7, k: 2560, error: 13) 
!!!! kernel execution error. (m: 2560, n: 7, k: 10240, error: 13) 
!!!! kernel execution error. (m: 7680, n: 7, k: 2560, error: 13) 
... many lines like this ...
!!!! kernel execution error. (m: 80, n: 7, k: 7, error: 13) 
!!!! kernel execution error. (m: 2560, n: 7, k: 2560, error: 13) 
!!!! kernel execution error. (m: 10240, n: 7, k: 2560, error: 13) 
!!!! kernel execution error. (m: 2560, n: 7, k: 10240, error: 13) 
Traceback (most recent call last):
  File "/root/workspace/./test.py", line 28, in <module>
    ds_out = ds_model(input_ids, labels=input_ids)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 514, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 654, in forward
    outputs = self.gpt_neox(
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 560, in forward
    hidden_states = self.final_layer_norm(hidden_states)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA error: an illegal instruction was encountered
[2023-02-10 10:36:24,097] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 25208
[2023-02-10 10:36:24,098] [ERROR] [launch.py:324:sigkill_handler] ['/root/miniconda3/envs/ds-infer-2/bin/python', '-u', './test_2.py', '--local_rank=0'] exits with return code = 1
```

**To Reproduce**
My script is :

```python
from transformers import AutoConfig, GPTNeoXForCausalLM, AutoTokenizer
import deepspeed
import os
import torch

world_size = int(os.getenv('WORLD_SIZE', '1'))
local_rank = int(os.getenv('LOCAL_RANK', '0'))

model = GPTNeoXForCausalLM.from_pretrained('/path/to/my/model')
tokenizer = AutoTokenizer.from_pretrained("/path/to/my/tokenizer")


ds_model = deepspeed.init_inference(model, 
    mp_size=world_size, 
    dtype=torch.float16, 
    replace_method='auto',
    replace_with_kernel_inject=True)

encodings = tokenizer('hello, this is a test text', return_tensors="pt")

input_ids = encodings.input_ids.cuda(local_rank)
ds_out = ds_model(input_ids)
if local_rank == 0:
    print(f"ds_out = {ds_out}")
```

And I run the script by:

```
CUDA_VISIBLE_DEVICES=0 CUDA_LAUNCH_BLOCKING=1 deepspeed ./test.py
```

Then it crash and show the above error message.

If I change the `dtype` argument of `deepspeed.init_inference` from `torch.float16` to `torch.float`, the issue disappears.

**ds_report output**

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
random_ltd ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
spatial_inference ...... [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/torch']
torch version .................... 1.12.1
deepspeed install path ........... ['/root/miniconda3/envs/ds-infer-2/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.8.0, unknown, unknown
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.6
```

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU: one machine with A100*4
 - Hugging Face Transformers: transformers       4.26.1
 - Python version: 3.9

**Docker context**
nvidia/cuda:11.6.0-devel-ubuntu18.04

**Comment by JiayiFeng** [comment]
I just tried the model `EleutherAI/gpt-neo-2.7B` used in the official model: https://www.deepspeed.ai/tutorials/inference-tutorial/#end-to-end-gpt-neo-27b-inference. It didn't crash, but the output result is totally incorrect.

My script is:

```python
from transformers import GPTNeoForCausalLM, AutoTokenizer
import deepspeed
import os
import torch

world_size = int(os.getenv('WORLD_SIZE', '1'))
local_rank = int(os.getenv('LOCAL_RANK', '0'))

model = GPTNeoForCausalLM.from_pretrained('EleutherAI/gpt-neo-2.7B')
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-2.7B")

ds_model = deepspeed.init_inference(model, 
    mp_size=world_size, 
    dtype=torch.float16, 
    replace_method='auto',
    replace_with_kernel_inject=True)

encodings = tokenizer('hello, this is a test text', return_tensors="pt")

input_ids = encodings.input_ids.cuda(local_rank)
ds_out = ds_model(input_ids)
if local_rank == 0:
    print(f"ds_out = {ds_out}")
```

launched by:

```
CUDA_VISIBLE_DEVICES=0 deepspeed ./run.py
```

**Comment by lokoppakmsft** [comment]
@JiayiFeng, is it possible to share the model in any way, for the issue 1 above?

**Comment by JiayiFeng** [comment]
Seems that problem is probably due to some error in my model converting process, so I close it for now. Thanks for your response @lokoppakmsft .
