### ISSUE TITLE
[BUG] RuntimeError: a leaf Variable that requires grad is being used in an in-place operation

### ISSUE THREAD

**Issue by lifeiteng** [microsoft/DeepSpeed#2818]
**Describe the bug**
https://github.com/lifeiteng/vall-e/pull/19/files#diff-389db6acad3c5ae1d09617e4e94e434e6f0a17e4878dac378d7d42cc94e43888R896

```
[2023-02-13 00:21:09,543] [INFO] [comm.py:657:init_distributed] Initializing TorchBackend in DeepSpeed with backend gloo
2023-02-13 00:21:09,544 INFO [distributed_c10d.py:319] Added key: store_based_barrier_key:1 to store for rank: 0
2023-02-13 00:21:09,544 INFO [distributed_c10d.py:353] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
[2023-02-13 00:21:09,544] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.8.0, git-hash=unknown, git-branch=unknown
2023-02-13 00:21:09,603 INFO [distributed_c10d.py:319] Added key: store_based_barrier_key:2 to store for rank: 0
2023-02-13 00:21:09,603 INFO [distributed_c10d.py:353] Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
Traceback (most recent call last):
  File "bin/trainer.py", line 1082, in <module>
    main()
  File "bin/trainer.py", line 1075, in main
    run(rank=0, world_size=1, args=args)
  File "bin/trainer.py", line 899, in run
    model, optimizer, _, scheduler = deepspeed.initialize(
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 301, in __init__
    self._configure_distributed_model(model)
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_distributed_model
    self._broadcast_model()
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1102, in _broadcast_model
    dist.broadcast(p,
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 127, in log_wrapper
    return func(*args, **kwargs)
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 232, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/feiteng/.local/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 70, in broadcast
    return torch.distributed.broadcast(tensor=tensor,
  File "/home/feiteng/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1408, in broadcast
    work.wait()
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```
error at: 'text_embedding.word_embeddings.weight'
https://github.com/lifeiteng/vall-e/blob/deepspeed/valle/modules/model.py#L66

```
self.text_embedding = TokenEmbedding(d_model, NUM_TEXT_TOKENS)
```

**To Reproduce**
```
git clone -b deepspeed https://github.com/lifeiteng/vall-e.git

cd egs/libritts

export PYTHONPATH=YOUR_PATH/k2-fsa/icefall:$PYTHONPATH
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

deepspeed bin/trainer.py \
    --decoder-dim 512 --nhead 8 --num-decoder-layers 8 \
    --deepspeed --deepspeed_config configs/ds_zero2.config \
    --exp-dir exp/valle_mini
```
* install reference: https://github.com/lifeiteng/vall-e/tree/deepspeed#installation

**Expected behavior**
Figure out the error `RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/feiteng/.local/lib/python3.8/site-packages/torch']
torch version .................... 1.13.0+cu116
deepspeed install path ........... ['/home/feiteng/.local/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.0, unknown, unknown
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6
```

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - GPU count and types GTX 3060
 - Python version 3.8
 - Any other relevant info about your setup

**Launcher context**
the `deepspeed` launcher

**Docker context**
Ubuntu 20.04 python3.8

**Additional context**

**Comment by lifeiteng** [comment]
`deepspeed.init_distributed(dist_backend="nccl")`

**Comment by lifeiteng** [comment]
> Thanks @lifeiteng - just to clarify, you were only seeing thsi issue with gloo not nccl?

I think so, also a small change in ds.config

**Comment by lxe** [comment]
What if you can't use nccl when on windows for example?

**Comment by xingchensong** [comment]
gloo fails with the same issue, nccl works perfect

**Comment by AngelTs** [comment]
gloo fails:
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by thorinf** [comment]
```python
def sync_params(params) -> None:
    with torch.no_grad():
        for i, p in enumerate(params):
            p_copy = p.detach()
            dist.broadcast(p_copy, 0)
            p.copy_(p_copy)
```

This seems to work for `gloo`. This could cause other issues, if anyone sees why this may be a bad workaround then let me know.

**Comment by loadams** [comment]
Hi @thorinf - do you want to PR that and we can review it that way?

**Comment by thorinf** [comment]
> Hi @thorinf - do you want to PR that and we can review it that way?

I've not actually been working on DeepSpeed. Had the same issue with gloo, so I went back and posted my workaround once I'd found something.

**Comment by shishijier** [comment]
> `deepspeed.init_distributed(dist_backend="nccl")`

Where to add this line of code?
