### ISSUE TITLE
[BUG] No module named 'torch._six'

### ISSUE THREAD

**Issue by parthmannan** [microsoft/DeepSpeed#2845]
Torch does not seem to support torch._six anymore and it has been removed.
Refer - https://github.com/pytorch/pytorch/pull/94709

DeepSpeed still has dependency on it. Example in `runtime/utils.py`

```
from torch._six import inf
```

Torch version to be precise - 2.0.0a0+git5a54537

**Comment by weiwangmeta** [comment]
Please apply fix " from torch import inf", please let us know if this does not fix your issue.

**Comment by styler00dollar** [comment]
I cloned git master (8be8c01) now, ran into same problem. I used `torch==2.0.0.dev20230217+cu118`.

**Comment by chintan-donda** [comment]
Uninstall the old version of deepspeed, and reinstall it without any version to let it pick up the latest one.

```
pip uninstall deepspeed
pip install deepspeed
```

This worked for me.

**Comment by sanyanliangyu** [comment]
> Uninstall the old version of deepspeed, and reinstall it without any version to let it pick up the latest one.
> 
> ```
> pip uninstall deepspeed
> pip install deepspeed
> ```
> 
> This worked for me.

WORK FOR ME TOO

**Comment by mclohrk** [comment]
not work for me

**Comment by bm777** [comment]
> not work for me in google colab

maybe restart your kernel and try again

**Comment by sebasmos** [comment]
> Please apply fix " from torch import inf", please let us know if this does not fix your issue.

Still works, thanks! tested over Pytorch2.0.0+cu118

**Comment by yaz94** [comment]
If you are using "timm", upgrade.

**Comment by KLL535** [comment]
python gradio/app.py
/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/colossalai/shardformer/layer/normalization.py:48: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused RMSNorm kernel
  warnings.warn("Please install apex from source (https://github.com/NVIDIA/apex) to use the fused RMSNorm kernel")
/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/colossalai/shardformer/layer/normalization.py:93: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused RMSNorm kernel
  warnings.warn(
/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.95s/it]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/layers/blocks.py", line 52, in get_layernorm
    from apex.normalization import FusedLayerNorm
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
**ModuleNotFoundError: No module named 'torch._six'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Open-Sora/gradio/app.py", line 195, in <module>
    vae, text_encoder, stdit, scheduler = build_models(
  File "/home/user/Open-Sora/gradio/app.py", line 104, in build_models
    stdit = STDiT3.from_pretrained(HF_STDIT_MAP[model_type], **model_kwargs)
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3404, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/stdit/stdit3.py", line 256, in __init__
    [
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/stdit/stdit3.py", line 257, in <listcomp>
    STDiT3Block(
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/stdit/stdit3.py", line 63, in __init__
    self.norm1 = get_layernorm(hidden_size, eps=1e-6, affine=False, use_kernel=enable_layernorm_kernel)
  File "/home/user/anaconda3/envs/opensora/lib/python3.9/site-packages/opensora/models/layers/blocks.py", line 56, in get_layernorm
    raise RuntimeError("FusedLayerNorm not available. Please install apex.")
**RuntimeError: FusedLayerNorm not available. Please install apex.**

Although I install apex
How to fix this?
