### ISSUE TITLE
[BUG] Get "exits with return code = -9" when Creating fp16 ZeRO stage 2 optimizer

### ISSUE THREAD

**Issue by sxthunder** [microsoft/DeepSpeed#2852]
I am training a 10B model using deepspeed with megatron on A100 GPUS(80G). Here is my ds_report

![image](https://user-images.githubusercontent.com/56537141/219829623-362d40e8-dc52-4f41-8384-cf76807b5728.png)

If I use 4 GPUS, the error is CUDA out of memory in deepspeed initialize, the traceback is :
`
Traceback (most recent call last):
  File "/workspace/bin/codegeex/megatron/tools/pretrain_codegeex.py", line 207, in <module>
    pretrain(
  File "/workspace/bin/codegeex/megatron/training.py", line 152, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider)
  File "/workspace/bin/codegeex/megatron/training.py", line 419, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 119, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 294, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1082, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1334, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 503, in __init__
    self.initialize_optimizer_states()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 586, in initialize_optimizer_states
    self.optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 149, in step
    state['exp_avg_sq'] = torch.zeros_like(p.data)
RuntimeError: CUDA out of memory. Tried to allocate 11.99 GiB (GPU 0; 79.35 GiB total capacity; 59.95 GiB already allocated; 8.52 GiB free; 59.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

When I use 8 GPUS, the error happens earlier, In "Creating fp16 ZeRO stage 2 optimizer", the log is : 
`[2023-02-18 11:14:26,616] [INFO] [logging.py:69:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2023-02-18 11:14:26,616] [INFO] [stage_1_and_2.py:132:__init__] Reduce bucket size 50000000
[2023-02-18 11:14:26,616] [INFO] [stage_1_and_2.py:133:__init__] Allgather bucket size 50000000
[2023-02-18 11:14:26,616] [INFO] [stage_1_and_2.py:134:__init__] CPU Offload: False
[2023-02-18 11:14:26,616] [INFO] [stage_1_and_2.py:135:__init__] Round robin gradient partitioning: False
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/py38_cu113/utils...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o 
[2/2] c++ flatten_unflatten.o -shared -L/opt/conda/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o utils.so
Loading extension module utils...
Time to load utils op: 17.926154613494873 seconds
Loading extension module utils...
Time to load utils op: 17.922656297683716 seconds
Loading extension module utils...
Time to load utils op: 17.92318892478943 seconds
Loading extension module utils...
Time to load utils op: 17.922754287719727 seconds
Loading extension module utils...
Loading extension module utils...
Time to load utils op: 17.922405004501343 seconds
Time to load utils op: 17.922232389450073 seconds
Loading extension module utils...
Time to load utils op: 17.92255711555481 seconds
Loading extension module utils...
Time to load utils op: 17.92217516899109 seconds
[2023-02-18 11:14:54,208] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 707
[2023-02-18 11:14:54,208] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 708
[2023-02-18 11:14:54,209] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 709
[2023-02-18 11:14:54,210] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 710
[2023-02-18 11:14:54,210] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 711
[2023-02-18 11:14:54,210] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 712
[2023-02-18 11:14:54,211] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 713
[2023-02-18 11:14:54,215] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 714`
then the process is end with a code=-9.

Why the error happens earlier when I increase the Gpu nums from 4 to 8? the latter error didn't happen when I use 4 GPUs

**Comment by zincnode** [comment]
Same error. I use 4 * 8 A100(80GB) to train the GPT-2 model of 100B.

**Comment by zincnode** [comment]
I think it probably stands for CPU OOM, as mentioned #2788 . I use the same environment and the same configuration, and only change the model size (100B->50B), there is no error.

**Comment by tjruwase** [comment]
@sxthunder, thanks for reporting this issue. Let's start with the 4 GPU case. Can you please share your ds_config and log prior to failure? Thanks!

**Comment by sxthunder** [comment]
> 

I solve this by setting tensor parallel = 2

**Comment by lecchon** [comment]
@sxthunder hello, i meet the same problem, could you please give me some solution ideas? i am new to deepspeed and i cannot find how to set tensor parallel in official document.
thanks.
