### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lanmower** [microsoft/DeepSpeed#2880]
**Describe the bug**
Deepspeed doesn't install

**To Reproduce**
On windows, attempt installation

**Expected behavior**
Deepspeed installs

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**
```A:\vall-e>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.8.1.tar.gz (759 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-2xliqc0s\deepspeed_6dafb10283b0475191a25142e9116e28\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\user\AppData\Local\Temp\pip-install-2xliqc0s\deepspeed_6dafb10283b0475191a25142e9116e28\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile sparse_attn
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=0
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  sparse_attn cuda is not available from torch
       [WARNING]  please install triton==1.0.0 if you want to use sparse attention
       [ERROR]  Unable to pre-compile sparse_attn
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**System info (please complete the following information):**
 - OS: Win 11
 - GPU count and types 3060
 - Interconnects (if applicable) n/a
 - Python version 3.10.9
 - Any other relevant info about your setup WPy64-31090

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
No
**Docker context**
Are you using a specific docker image that you can share?
No
**Additional context**
there's no tritons available when listing

**Comment by Taylan2134** [comment]
I have the exactly same problem.

**Comment by Taylan2134** [comment]
> How are you installing DeepSpeed? Are you running `pip install deepspeed` or building with [these directions](https://github.com/microsoft/DeepSpeed#windows)?

I am using pip install deepspeed command.

**Comment by mallorbc** [comment]
I am using Ubuntu 20.04.  Compiling version 0.8.1 with my docker image as you can see [here](https://github.com/mallorbc/Finetune_GPTNEO_GPTJ6B/blob/main/Dockerfile) also leads to issues.
This works:
```
DS_BUILD_OPS=1 pip install git+https://github.com/microsoft/DeepSpeed.git@v0.8.0
```
This does not:
```
DS_BUILD_OPS=1 pip install git+https://github.com/microsoft/DeepSpeed.git@v0.8.1
```

**Comment by Taylan2134** [comment]
> @Taylan2134 = you may also be able to build here by running `set DS_BUILD_SPARSE_ATTN=0` (and then same with AIO since that's also not supported on Windows) and then pip install, so that it won't try and pre-compile those. But you'd be better off with the other approaches. Can you let me know if those work? We'll work on getting a better Windows install process for this type of install if we can.

Hi again, I just tried it but it still doesn't work. This is the last error message

![image](https://user-images.githubusercontent.com/85124974/221109952-5b613bb4-5d6e-453e-914f-b6d126c7087b.png)

**Comment by mallorbc** [comment]
Hi @loadams.  I created an issue.  Please see it here #2914 
Thanks!

**Comment by xfd997700** [comment]
DO NOT use pip to install deepspeed directly on windows! Follow [https://github.com/microsoft/DeepSpeed#windows](url) to build the wheel and install the whl file.

**Comment by jve72** [comment]
1. I am in a conda env on Windows, created with: conda create --name valle python=3.10.8 anaconda
2. I have set my env vars per the instructions in this thread to bypass building aoi.lib (and even tried removing all ops)...
    (valle) D:\github\vall-e>set ds
    DS_BUILD_AIO=0
    DS_BUILD_OPS=0
    DS_BUILD_SPARSE_ATTN=0
3.  I still am unable to pip install deepspeed, because it tries to find the aio.lib (which was not built)...
(valle) D:\github\vall-e>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.9.5.tar.gz (809 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      [2023-06-30 10:44:44,408] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      [2023-06-30 10:44:45,361] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      No CUDA runtime is found, using CUDA_HOME='C:\Users\jason\miniconda3\envs\valle'
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jason\AppData\Local\Temp\pip-install-1oyp_47u\deepspeed_f58c153aaa114017bf27fea6947eeadd\setup.py", line 205, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\jason\AppData\Local\Temp\pip-install-1oyp_47u\deepspeed_f58c153aaa114017bf27fea6947eeadd\setup.py", line 197, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] Access is denied: '.\\deepspeed\\ops\\csrc'
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=0
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  sparse_attn cuda is not available from torch
       [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
       [WARNING]  please install triton==1.0.0 if you want to use sparse attention
      Install Ops={'async_io': False, 'cpu_adagrad': False, 'cpu_adam': False, 'fused_adam': False, 'fused_lamb': False, 'quantizer': False, 'random_ltd': False, 'sparse_attn': False, 'spatial_inference': False, 'transformer': False, 'stochastic_transformer': False, 'transformer_inference': False}

**Comment by jve72** [comment]
@loadams

This is a cmd based environment.  I gathered from this thread that aoi is not supported on Windows, so I set the recommended env vars (which I echo'd in my post above) , but something tried to link with it anyhow, right?

**Comment by flckv** [comment]
I can see there are a lot of issues with just the installation... there must be an easier way ....

**Comment by DevManPGP** [comment]
I'm stuck too! I tried using WSL, which Google says is the '[World Surf League - The global home of surfing]'. I don't se how surfing would assist the install. But it sure my be less challenging (and enjoyable :-) ).

**Comment by loadams** [comment]
Hi @DevManPGP - WSL is the Windows Subsystem for Linux and you can read more about it [here](https://learn.microsoft.com/en-us/windows/wsl/about).  It provides a Linux environment directly on Windows without the need for VMs or dual booting.  That allows some of the features that DeepSpeed leverages that are only available on Linux to work on a Windows machine.  Directions for install are [here ](https://learn.microsoft.com/en-us/windows/wsl/install)if you are interested.

**Comment by FurkanGozukara** [comment]
Windows is still not supported right?

so so sad

![image](https://github.com/microsoft/DeepSpeed/assets/19240467/374fdfef-a9e2-4bac-aefe-caf3b1f4e45b)

**Comment by loadams** [comment]
Hi @FurkanGozukara - Windows is not unsupported, however there are features that are unable to be used due to dependencies that do not support Windows.  

The install directions that we have used in the past are [here](https://github.com/microsoft/DeepSpeed#windows) - though due to the various nature of each users Windows setup, it is much more likely that one will hit issues.  

There is currently an active PR [here](https://github.com/microsoft/DeepSpeed/issues/4729) that lists steps in more detail that are likely more helpful than what is currently listed and might save you some time troubleshooting.

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara - Windows is not unsupported, however there are features that are unable to be used due to dependencies that do not support Windows.
> 
> The install directions that we have used in the past are [here](https://github.com/microsoft/DeepSpeed#windows) - though due to the various nature of each users Windows setup, it is much more likely that one will hit issues.
> 
> There is currently an active PR [here](https://github.com/microsoft/DeepSpeed/issues/4729) that lists steps in more detail that are likely more helpful than what is currently listed and might save you some time troubleshooting.

I am making tutorials and this is useless for me since average people can't make it work. 

I need pip install wheel_url

It shouldn't be that hard

**Comment by namangupta2001** [comment]
> There are a number of unsupported things on Windows that can make this harder. We do recommend using WSL if you are able to, as that removes a number of these hurdles.

WSL worked for me for the same issue ,thanks @loadams .

**Comment by FurkanGozukara** [comment]
even bitsandbytes are now officially supported on Windows!

**Comment by Karthikeyacs33** [comment]
C:\Users\mvska>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.14.4.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "C:\Users\mvska\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mvska\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mvska\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mvska\AppData\Local\Temp\pip-build-env-bmny89dw\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mvska\AppData\Local\Temp\pip-build-env-bmny89dw\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\mvska\AppData\Local\Temp\pip-build-env-bmny89dw\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\mvska\AppData\Local\Temp\pip-build-env-bmny89dw\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 149, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I have torch version 2.3.1 + cu121
i even tried running import torch and torch.__version__. Its showing that torch exists. What might be the issue??

**Comment by loadams** [comment]
Hi @Karthikeyacs33 - DeepSpeed support for Windows is improving but a Windows supported whl is not published to PyPI yet.  To get a whl you can install on Windows you can follow these steps: https://github.com/microsoft/DeepSpeed?tab=readme-ov-file#windows

**Comment by Rohith-Neeraje** [comment]
![image](https://github.com/user-attachments/assets/ea7f405e-c1a1-4a9c-ab92-d68cc8563470)
I am encountering the same issue in windows, and i cant use a WSL env.. could someone pls explain to me in detail how i would go about setting my AIO to 0, as i assume that works, and if that doesnt, what else could i try? It is a native windows system

**Comment by loadams** [comment]
Hi @Rohith-Neeraje - we currently do not support installing on Windows via `pip install deepspeed` yet, we hope to have this support soon.

In the meantime, to install deepspeed on Windows, you'll need to build from source, which means running the [build_win.bat](https://github.com/microsoft/DeepSpeed/blob/master/build_win.bat) script to install from source once you have cloned the repo.

**Comment by max-mena-SD** [comment]
Hello!

I was having the same issue, I tried installing `pip install deepspeed` but kept failling.
The project required pytorch in my case, then I installed `pip install torch=2.0.1` and then the `pip install -e .` and it worked.
