### ISSUE TITLE
[BUG] error use zero inference 

### ISSUE THREAD

**Issue by lambda7xx** [microsoft/DeepSpeed#2890]
- my deepspeed is 0.8.1 and my CPU has 500G memory. The below is my code to set zero. I modify the [code](https://github.com/microsoft/DeepSpeedExamples/blob/master/inference/huggingface/text-generation/inference-test.py) to run zero.
```
from argparse import ArgumentParser
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
import deepspeed
import math
import os
import torch
import time
from utils import DSPipeline
from deepspeed.runtime.utils import see_memory_usage

parser = ArgumentParser()

parser.add_argument("--name", required=True, type=str, help="model_name")
parser.add_argument("--checkpoint_path", required=False, default=None, type=str, help="model checkpoint path")
parser.add_argument("--save_mp_checkpoint_path", required=False, default=None, type=str, help="save-path to store the new model checkpoint")
parser.add_argument("--batch_size", default=1, type=int, help="batch size")
parser.add_argument("--dtype", default="float16", type=str, choices=["float32", "float16", "int8"], help="data-type")
parser.add_argument("--ds_inference", action='store_true', help="enable ds-inference")
parser.add_argument("--use_kernel", action='store_true', help="enable kernel-injection")
parser.add_argument("--replace_method", required=False, default='', type=str, help="replace method['', 'auto']")
parser.add_argument("--max_tokens", default=1024, type=int, help="maximum tokens used for the text-generation KV-cache")
parser.add_argument("--max_new_tokens", default=50, type=int, help="maximum new tokens to generate")
parser.add_argument("--greedy", action='store_true', help="greedy generation mode")
parser.add_argument("--use_meta_tensor", action='store_true', help="use the meta tensors to initialize model")
parser.add_argument("--use_cache", default=True, type=bool, help="use cache for generation")
parser.add_argument("--test_performance", action='store_true', help="enable latency, bandwidth, and throughout testing")
parser.add_argument("--local_rank", type=int, default=0, help="local rank")
parser.add_argument('--tp', type=int, default=1,help="tensor parallelism size")
args = parser.parse_args()

#print("args.dtype:",args.dtype)
def print_perf_stats(latency_set, config, warmup=3):
    # trim warmup queries
    latency_set = list(latency_set)
    latency_set = latency_set[warmup:]
    count = len(latency_set)

    if count > 0:
        latency_set.sort()
        avg = sum(latency_set) / count
        num_layers = getattr(config, "num_layers", config.num_hidden_layers)
        num_parameters = num_layers * config.hidden_size * config.hidden_size * 12
        if args.dtype == "float16":
            num_bytes = 2
        elif args.dtype == "float32":
            num_bytes = 4
        else:
            num_bytes = 1
        print("Avg Per Token Latency: {0:8.2f} ms".format(avg * 1000))
        print("Avg BW: {0:8.2f} GB/s".format(1/avg * num_parameters * num_bytes / 1e9))
        print("Avg flops: {0:8.2f} TFlops/s".format(1/avg * num_parameters * num_bytes * args.batch_size / 1e12))

world_size = int(os.getenv('WORLD_SIZE', '1'))
local_rank = int(os.getenv('LOCAL_RANK', '0'))

data_type = getattr(torch, args.dtype)

if local_rank == 0:
    see_memory_usage("before init", True)
#print("*************",local_rank)
# local_rank = 1 
dtype =  torch.float16

zero_config = {
    "fp16": {
        "enabled": dtype == torch.float16,
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": True,
        "contiguous_gradients": True,
        # "reduce_bucket_size": model_hidden_size * model_hidden_size,
        # "stage3_prefetch_bucket_size": 0.9 * model_hidden_size * model_hidden_size,
        # "stage3_param_persistence_threshold": 0,
    },
}

zero_config["zero_optimization"]["offload_param"] = dict(device="cpu", pin_memory=True)

t0 = time.time()
pipe = DSPipeline(model_name=args.name,
                  dtype=data_type,
                  is_meta=args.use_meta_tensor,
                  device=args.local_rank,
                  checkpoint_path=args.checkpoint_path)
if local_rank == 0:
    print(f"initialization time: {(time.time()-t0) * 1000}ms")
    see_memory_usage("after init", True)
if args.use_meta_tensor:
    ds_kwargs = dict(base_dir=pipe.repo_root, checkpoint=pipe.checkpoints_json)
else:
    ds_kwargs = dict()

if args.ds_inference:
    pipe.model = deepspeed.init_inference(pipe.model,
                                    dtype=data_type,
                                    tensor_parallel=args.tp,
                                    zero =zero_config,
                                    replace_with_kernel_inject=args.use_kernel,
                                    replace_method=args.replace_method,
                                    max_tokens=args.max_tokens,
                                    **ds_kwargs
                                    )
if local_rank == 0:
    see_memory_usage("after init_inference", True)


input_sentences = [
         "DeepSpeed is a machine learning framework",
         "He is working on",
         "He has a",
         "He got all",
         "Everyone is happy and I can",
         "The new movie that got Oscar this year",
         "In the far far distance from our galaxy,",
         "Peace is the only way",
         "Shanghai Jiao Tong University is a famous university ",#9
         "I Love UC Berkeley because it's ", #10
         "Paris is the captial of France and ",#11
         "History is very interesting," , #12 
         "It is the tears of the earth that keep here smiles in bloom", #13
         "If you shed tears when you miss the sun, you also miss the stars.", #14
         "Her wishful face haunts my dreams like the rain at night.",#15
         "I cannot choose the best. The best chooses me.",#16
         "Anything in life worth doing is worth overdoing.",#17
         "Life is like a box of chocolates, you never know what you are going to get",#18
         ". It is up to you to give life a meaning.",#19
         "Machine learning models are becoming", #20
         "Prediction serving systems often employ distributed ",#21
         "The primary differences between coded-computation and the traditional code is "#22
        "With this observation in mind", #23
        "We evaluate Alpa on training large models",#24
        "DL computation is commonly represented",#25
        "With the growing model size, deep neural networks (DNN) are " ,#26
        "We thank all the anonymous reviewers for",#27
        "we discuss the advantages and several limitations of",#28
        "The Serverless Computing is becoming increasingly popular",#29
        "Our experiment analysis shows that",#30
        "Serverless computing, also known as Function-as-a-Service (FaaS),"#31
        "We investigate the limitations of",#32
        "To reduce data movement overhead ",#33
         "we first introduce ",#34
         "I like xinyi because she ", #35
        "DNN training is extremely time-consuming,",#36
        "To address these challenges",#37
        "To improve statistical efficiency, ",#38
        "MSRA is awesome", #39
        "I am happy because",#40
        "Our results show that, by decoupling memory and CPU allocation,",#41
        "Furthermore, we demonstrate that" ,#42 
        "Minimizing data movement is key to ",#43
        "Because there is no generic or reliable way  for",#44
        "This paper explores a novel point in the design space by ",#45
        "we start by discussing",#46 
        "Figure 1 shows the main components of", #47
        "A key goal of successful is ",#48
        "we focus on two broad ",#49
        "It is a scarce resource",#50
]
#30
if args.batch_size > len(input_sentences):
    # dynamically extend to support larger bs by repetition
    input_sentences *= math.ceil(args.batch_size / len(input_sentences))

inputs = input_sentences[:args.batch_size]
#print("len(inputs):",len(inputs))
iters = 30 if args.test_performance else 2 #warmup
print("iters:",iters)
times = []
for i in range(iters):
    torch.cuda.synchronize()
    start = time.time()
    outputs = pipe(inputs,
            num_tokens=args.max_new_tokens,
            do_sample=(not args.greedy))
    #p#rint("i:",i, "len(output):",len(outputs))
    torch.cuda.synchronize()
    end = time.time()
    times.append(end - start)

if args.local_rank == 0:
    print(f"generation time is {times[1]} sec")

#print("finally, len(output):",len(outputs), " and len(inputs):",len(inputs))
if args.local_rank == 0:
    for i, o in zip(inputs, outputs):
        print(f"\nin={i}\nout={o}\n{'-'*60}")
    if args.test_performance:
        print_perf_stats(map(lambda t: t / args.max_new_tokens, times), pipe.model.config)


``` 

the command to run this code is below
```
    deepspeed --num_gpus 8  inference-test-zero.py --name bigscience/bloom  --batch_size 2  --ds_inference --use_kernel --use_meta_tensor --test_performance --replace_method=auto --dtype float16 --tp 2
```

The below is my error
```
Traceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    [2023-02-24 02:08:06,001] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.6, git-hash=unknown, git-branch=unknown
ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
Traceback (most recent call last):
pydantic.error_wrappers  File "inference-test-zero.py", line 95, in <module>
.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
[2023-02-24 02:08:06,007] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.6, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
[2023-02-24 02:08:06,010] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.6, git-hash=unknown, git-branch=unknown
[2023-02-24 02:08:06,010] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.6, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationErrorTraceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp
  value is not a valid dict (type=type_error.dict)
zero -> fp16
  extra fields not permitted (type=value_error.extra)
zero -> zero_optimization
  extra fields not permitted (type=value_error.extra)
[2023-02-24 02:08:06,027] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.6, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "inference-test-zero.py", line 95, in <module>
    pipe.model = deepspeed.init_inference(pipe.model,
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/home/lambda7xx/.local/lib/python3.8/site-packages/deepspeed/runtime/config_utils.py", line 55, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for DeepSpeedInferenceConfig
tp

```

**Comment by tjruwase** [comment]
@lambda7xx, please following this zero-inference example [script](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py).  That will show the correct ds_config to avoid the validation errors.

**Comment by lambda7xx** [comment]
I run this

> @lambda7xx, please following this zero-inference example [script](https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-zero-inference.py). That will show the correct ds_config to avoid the validation errors.

I run this script and I get this issue https://github.com/microsoft/DeepSpeed/issues/2892

**Comment by tjruwase** [comment]
Got it. Is it okay to close this issue now?

**Comment by loadams** [comment]
Closing this issue for now.
