### ISSUE TITLE
[BUG] Cannot install deepspeed when cuda is installed by a non-root user

### ISSUE THREAD

**Issue by jkhu29** [microsoft/DeepSpeed#2924]
**Describe the bug**

I have already installed the nvcc here (without root), but I get an error when `pip install deepspeed` .

```python
$ which nvcc
/home/ligq/cuda/bin/nvcc
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

OS:

```
Linux wchen 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

python == 3.8.0
torch == 1.10.0+cu111
triton == 1.1.1

The output:

```python
$ pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.8.1.tar.gz (759 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-93vyu374/deepspeed_9036210293f143469823f9fa30406028/setup.py", line 78, in <module>
          cupy = f"cupy-cuda{''.join(map(str,installed_cuda_version()))}"
        File "/tmp/pip-install-93vyu374/deepspeed_9036210293f143469823f9fa30406028/op_builder/builder.py", line 46, in installed_cuda_version
          output = subprocess.check_output([cuda_home + "/bin/nvcc",
        File "/home/ligq/miniconda3/envs/snn/lib/python3.8/subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/ligq/miniconda3/envs/snn/lib/python3.8/subprocess.py", line 489, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/ligq/miniconda3/envs/snn/lib/python3.8/subprocess.py", line 854, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/ligq/miniconda3/envs/snn/lib/python3.8/subprocess.py", line 1702, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: ':/home/ligq/cuda/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem识别该程序就是nvcc with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It seems like it can find the path of `nvcc`, but can't identify the program it finds as `nvcc`.

**Comment by Hang-Ant** [comment]
hello, did you solve it, I had the same problem.

**Comment by GalaxyHe2023** [comment]
pip install -r requirements.txt
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by GalaxyHe2023** [comment]
Mane your cuda too old.

**Comment by jkhu29** [comment]
> pip install -r requirements.txt conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

Thanks, I have already solved this question.

**Comment by bot2342** [comment]
how you fixed it can you provide me the detail solution sir it might help me as a begginner

**Comment by jkhu29** [comment]
> please inform me when your avaible sir

Perhaps you could try setting CUDA_HOME manually, like https://github.com/NVIDIA/apex/issues/1657#issuecomment-1538605830
