### ISSUE TITLE
encountering errorrs on CIFAR-10 example

### ISSUE THREAD

**Issue by mwolff31** [microsoft/DeepSpeed#295]
encountering the following errors when I try to run the Deepspeed CIFAR-10 example:

```
Files already downloaded and verified
Files already downloaded and verified
  dog plane  ship  ship
DeepSpeed info: version=0.1.0, git-hash=f690890, git-branch=shaden/conda
[INFO 2020-07-18 20:25:31] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "test.py", line 144, in <module>
    args=args, model=net, model_parameters=parameters, training_data=trainset)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/deepspeed/__init__.py", line 96, in initialize
    collate_fn=collate_fn)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/deepspeed/pt/deepspeed_light.py", line 132, in __init__
    dist.init_process_group(backend=self.dist_backend)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 144, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```
When I set ```dist_init_required=False``` (I'm running the program on a single machine) in the ```deepspeed.initialize``` line, that error disappears.

However, I run into a second error:

```
Files already downloaded and verified
Files already downloaded and verified
plane   cat   car   cat
DeepSpeed info: version=0.1.0, git-hash=f690890, git-branch=shaden/conda
Traceback (most recent call last):
  File "test.py", line 144, in <module>
    args=args, model=net, model_parameters=parameters, training_data=trainset, dist_init_required=False)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/deepspeed/__init__.py", line 96, in initialize
    collate_fn=collate_fn)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/deepspeed/pt/deepspeed_light.py", line 138, in __init__
    self._do_args_sanity_check(args)
  File "/home/max/miniconda3/envs/dl_work/lib/python3.7/site-packages/deepspeed/pt/deepspeed_light.py", line 391, in _do_args_sanity_check
    'DeepSpeed requires --deepspeed_config to specify configuration file'
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
```
OS: Ubuntu 20.04

What's gives?

Thank you for any help.

**Comment by ShadenSmith** [comment]
Thank you for your interest in DeepSpeed!

How are you executing the script? The errors suggest that the deepspeed launcher is not being used. Note that we need to initialize `torch.distributed` regardless of the number of machines.

To launch the CIFAR-10 example, it should be something like
```
deepspeed cifar10_deepspeed.py --deepspeed_config ds_config.json
```
(taken from this [tutorial](https://www.deepspeed.ai/tutorials/cifar-10/))

**Comment by mwolff31** [comment]
that seemed to have solved the issue. thank you!
