### ISSUE TITLE
[BUG] DeepSpeed + PT nightly

### ISSUE THREAD

**Issue by younesbelkada** [microsoft/DeepSpeed#2952]
**Describe the bug**

I have encountered this when installing `accelerate` (that installs `deepspeed` under the hood) together with PT nightlies

Getting:
```bash
Traceback (most recent call last):
File "/home/younes_huggingface_co/code/accelerate/src/accelerate/utils/other.py", line 27, in <module>
    from deepspeed import DeepSpeedEngine
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/__init__.py", line 14, in <module>
    from . import module_inject
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 1, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 15, in <module>
    from ..runtime.zero import GatheredParameters
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 22, in <module>
    from .linear import LinearModuleForZeroStage3, zero3_linear_wrap
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/runtime/zero/linear.py", line 20, in <module>
    from deepspeed.runtime.utils import noop_decorator
  File "/home/younes_huggingface_co/miniconda3/envs/bt-optimum/lib/python3.9/site-packages/deepspeed/runtime/utils.py", line 19, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'
```

when installing pytorch nightlies. To reproduce:
```
pip install transformers accelerate 
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu117
```

```
from deepspeed import DeepSpeedEngine
```

**Comment by jeffra** [comment]
Keep an eye for 0.8.2 release of deepspeed, should come tonight or tomorrow. This should fix this issue. Also you should be able to get around the issue now if you install from latest `master`.

**Comment by younesbelkada** [comment]
Perfect! Thanks a bunch @jeffra

**Comment by jeffra** [comment]
0.8.2 is out now, please re-open this issue if you are still experiencing problems.
