### ISSUE TITLE
[BUG] Sudden increase in CPU memory usage when engine.step() using zero-3

### ISSUE THREAD

**Issue by KaiLv69** [microsoft/DeepSpeed#2984]
**Describe the bug**
I'm trying to fine-tune 16B Codegen using zero-3 with 8*3090 and 500GB CPU memory. In the first few step, it works well. 
However, in the engine.step() of about step 20, the cpu memory occupation suddenly increased (from ~350G to OOM).

**To Reproduce**
1. My training code:
```python
from transformers.deepspeed import HfDeepSpeedConfig

from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
from transformers.models.codegen.modeling_codegen import CodeGenMLP
import argparse
import torch
import time, datetime
import deepspeed
from deepspeed.accelerator import get_accelerator
from torch.utils.data import Dataset
from transformers.activations import ClippedGELUActivation, LinearActivation
from lion_pytorch import Lion
from datasets import load_dataset
import os
import wandb


def collate_fn(batch, tknz):
    text = [e['text'] for e in batch]
    tknz_batch = tknz(
        text,
        max_length=args.seq_len,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )
    return tknz_batch['input_ids'], tknz_batch['attention_mask']


def train():
    print(f"[{datetime.datetime.today()}] Loading model.")

    ds_config = {
        "gradient_accumulation_steps": 1,
        "train_micro_batch_size_per_gpu": 1,
        "steps_per_print": 100,
        "wall_clock_breakdown": True,
        "fp16": {
            "enabled": True,
        },
        "optimizer": {
            "type": "Adam",
            "params": {
                "lr": 0.001,
                "betas": [
                    0.8,
                    0.999
                ],
                "eps": 1e-8,
                "weight_decay": 3e-7
            }
        },
        "zero_optimization": {
            "stage": 3,
            "contiguous_gradients": True,
            "overlap_comm": True,
            "reduce_scatter": True,
            "offload_optimizer": {
                "device": "cpu",
                "pin_memory": True
            }
        },
        "activation_checkpointing": {
            "partition_activations": True,
            "cpu_checkpointing": False,
            "contiguous_memory_optimization": False,
            "number_checkpoints": None,
            "synchronize_checkpoint_boundary": False,
            "profile": False
        }
    }

    dschf = HfDeepSpeedConfig(ds_config)  # keep this object alive

    model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-16B-mono")
    tknz = AutoTokenizer.from_pretrained("Salesforce/codegen-16B-mono")

    tknz.pad_token = tknz.eos_token

    print(f"[{datetime.datetime.today()}] Loading dataset.")
    dataset = load_dataset("NeelNanda/pile-10k")['train'].select(range(args.data_size))
    print(f"[{datetime.datetime.today()}] Initializing DeepSpeed Engine.")

    model_engine, optimizer, train_dl, _ = deepspeed.initialize(
        config=ds_config,
        model=model,
        model_parameters=model.parameters(),
        training_data=dataset,
        collate_fn=lambda x: collate_fn(x, tknz),
    )

    print(f"[{datetime.datetime.today()}] Entering training loop.")
    model.train()
    for epoch in range(args.epoch_num):
        for i, data in enumerate(train_dl):
            model_engine.zero_grad()
            optimizer.zero_grad()
            input_ids, attn_mask = data[0].cuda(), data[1].cuda()
            output = model_engine(input_ids=input_ids,
                                  attention_mask=attn_mask,
                                  labels=input_ids)

            model_engine.backward(output['loss'])
            if args.local_rank == 0:
                wandb.log({'loss': output['loss'].item()})
                print(f"[{datetime.datetime.today()}] Epoch {epoch} Iter {i} Loss {output['loss'].item()}")

            model_engine.step()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_rank', type=int, default=-1)
    parser.add_argument('--seq_len', type=int, default=-1)
    parser.add_argument('--data_size', type=int, default=-1)
    parser.add_argument('--epoch_num', type=int, default=-1)
    parser.add_argument('--project', type=str, default="my_project")
    parser.add_argument('--name', type=str, default="my_exps")

    args = parser.parse_args()
    if args.local_rank == 0:
        wandb.init(project=args.project, name=args.name, config=args)
    train()
```

3. My bash script to run the code:
```bash
WANDB_MODE=disabled \
deepspeed --include localhost:0,1,2,3,4,5,6,7 train_ds_zero3.py \
--seq_len 400 \
--data_size 80 \
--epoch_num 10 \
--project ds_zero3_0308 \
--name moss_seq-400_epoch-10 \
```

```
[2023-03-10 00:20:24,052] [INFO] [logging.py:77:log_dist] [Rank 0] rank=0 time (ms) | forward_microstep: 12194.39 | backward_microstep: 29023.27 | backward_in
ner_microstep: 28603.35 | backward_allreduce_microstep: 419.72 | step_microstep: 133.24
[2023-03-10 00:20:24,053] [INFO] [logging.py:77:log_dist] [Rank 0] rank=0 time (ms) | forward: 12194.39 | backward: 29023.29 | backward_inner: 28603.40 | back
ward_allreduce: 419.70 | step: 133.24
[2023-03-10 00:21:05.215802] Epoch 2 Iter 2 Loss 4.48046875
Traceback (most recent call last):
  File "train_ds_zero3.py", line 134, in <module>
    Traceback (most recent call last):
train()
  File "train_ds_zero3.py", line 116, in train
    model_engine.step()
  File "aaa/deepspeed/runtime/engine.py", line 2168, in step
  File "train_ds_zero3.py", line 134, in <module>
    train()
  File "train_ds_zero3.py", line 116, in train
    model_engine.step()
  File "aaa/deepspeed/runtime/engine.py", line 2168, in step
        self._take_model_step(lr_kwargs)
  File "aaa/deepspeed/runtime/engine.py", line 2070, in _take_model_step
self._take_model_step(lr_kwargs)
  File "aaa/deepspeed/runtime/engine.py", line 2070, in _take_model_step
    self.optimizer.step()
  File "aaa/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "aaa/deepspeed/runtime/zero/stage3.py", line 1942, in step
        self._reassign_or_swap_out_partitioned_parameters(sub_group_id)
  File "aaa/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "aaa/deepspeed/runtime/zero/stage3.py", line 1888, in _reassign_or_swap_out_partitioned_parameters
self.optimizer.step()
  File "aaa/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)    self.fp16_partitioned_groups_flat[sub_group_id].data.copy_(
  File "/remote-home/klv/anaconda3/envs/bbb/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
File "aaa/deepspeed/runtime/zero/stage3.py", line 1939, in step
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 41376) is killed by signal: Killed.
    self._optimizer_step(sub_group_id)
  File "aaa/deepspeed/runtime/zero/stage3.py", line 865, in _optimizer_step
    self.optimizer.step()
  File "/remote-home/klv/anaconda3/envs/bbb/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/remote-home/klv/anaconda3/envs/bbb/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "aaa/deepspeed/ops/adam/cpu_adam.py", line 200, in step
    self.ds_opt_adam.adam_update(self.opt_id,
  File "/remote-home/klv/anaconda3/envs/bbb/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 40533) is killed by signal: Killed.
[2023-03-10 00:22:03,715] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17083
[2023-03-10 00:22:08,118] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17084
[2023-03-10 00:22:12,553] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17085
[2023-03-10 00:22:12,556] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17086
[2023-03-10 00:22:16,946] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17087
[2023-03-10 00:22:16,947] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17088
[2023-03-10 00:22:21,094] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17089
[2023-03-10 00:22:25,977] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 17092
```

**Expected behavior**
The training loop should go on as the first few steps.

**ds_report output**
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/39761308/224089874-cb6d8850-2774-4e9d-9d85-9b641a2b3844.png">

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?  Yes, `deepspeed` launcher

**Comment by samadejacobs** [comment]
@4AKker, we are not able to reproduce reported issue on A100 and V100 GPU clusters. We would like to recommend that you use the memory usage utility to estimate memory allocation without and without pinned memory. Please provide full training log with your next response (update).

```
from deepspeed.runtime.utils import see_memory_usage
 
see_memory_usage(f"Before", force=True)
foo()
see_memory_usage(f"After", force=True)

```
