### ISSUE TITLE
[BUG] NVMe Offloading OOMs While Zero Stage 3 Offloading Runs

### ISSUE THREAD

**Issue by stanleyshly** [microsoft/DeepSpeed#3000]
I'm training Flan-t5-large(760M parameters) with deepspeed. I'm running RoCM(RX 5600XT, 8GB of Vram) with 16GB of Ram backing it on Ubuntu 22.04.

I'm using huggingface for simplicity.

I first attempted to train with Zero 3. While my performance was abysmal(10-44 s/iteration with Zero versus 3.9 iteration/s without deepspeed), I'm fairly sure that it's due to massive swapping of the RAM into the SSD.
This is my Zero 3 config
```
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
```
Since I my RAM was swapping so much, I figured I'd directly offloading into the NVMe drive instead. So I switched the offload device to NVMe and tried again with a new config
```
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "nvme",
            "nvme_path": "/nvme",
            "pin_memory": true
        },
        "offload_param": {
            "device": "nvme",
            "nvme_path": "/nvme",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
```
Now, my new config doesn't even run, and OOMs before the first iteration. Does anyone know why this is happening, and how I can fix this error? I already changed ownership on the cache folder for DeepSpeed, so I'm not sure why this is happening.

**Comment by tjruwase** [comment]
@stanleyshly, can you please share a stack trace?

**Comment by stanleyshly** [comment]
Of course, here is the stack trace:
```
time to load utils op: 0.058083534240722656 seconds
[2023-03-13 13:33:25,688] [INFO] [utils.py:829:see_memory_usage] DeepSpeedZeRoOffload initialize [begin]
[2023-03-13 13:33:25,688] [INFO] [utils.py:830:see_memory_usage] MA 0.12 GB         Max_MA 0.12 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-13 13:33:25,689] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.35 GB, percent = 34.7%
Parameter Offload: Total persistent parameters: 125952 in 124 params
[2023-03-13 13:33:25,921] [INFO] [utils.py:829:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
[2023-03-13 13:33:25,921] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.12 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-13 13:33:25,922] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.35 GB, percent = 34.7%
[2023-03-13 13:33:26,002] [INFO] [utils.py:829:see_memory_usage] Before creating fp16 partitions
[2023-03-13 13:33:26,003] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-13 13:33:26,003] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.35 GB, percent = 34.7%
[2023-03-13 13:33:27,409] [INFO] [utils.py:829:see_memory_usage] After creating fp16 partitions: 1
[2023-03-13 13:33:27,410] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-13 13:33:27,410] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 6.82 GB, percent = 44.2%
[2023-03-13 13:33:27,410] [INFO] [stage3.py:484:_configure_tensor_swapping] Tensor Swapping: Adding optimizer tensors
Traceback (most recent call last):
  File "/home/workstation/Desktop/transformers/examples/pytorch/translation/run_translation.py", line 664, in <module>
    main()
  File "/home/workstation/Desktop/transformers/examples/pytorch/translation/run_translation.py", line 581, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1631, in train
    return inner_training_loop(
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1700, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 336, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1294, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1595, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 266, in __init__
    self._configure_tensor_swapping(offload_optimizer_config, aio_config)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 488, in _configure_tensor_swapping
    self.optimizer_swapper = swapper_type(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/partitioned_optimizer_swapper.py", line 38, in __init__
    self).__init__(swap_config,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/optimizer_utils.py", line 149, in __init__
    self.swap_buffer_manager = SwapBufferManager(num_elems=self.largest_numel,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/utils.py", line 182, in __init__
    self.all_buffers = [
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/utils.py", line 183, in <listcomp>
    get_accelerator().pin_memory(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 216, in pin_memory
    return tensor.pin_memory()
RuntimeError: HIP error: out of memory
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

[2023-03-13 13:34:03,314] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 8852
[2023-03-13 13:34:03,344] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-u', 'examples/pytorch/translation/run_translation.py', '--local_rank=0', '--deepspeed', 'tests/deepspeed/ds_config_zeroinfinity.json', '--model_name_or_path', 'google/flan-t5-large', '--per_device_train_batch_size', '1', '--output_dir', 'output_dir', '--overwrite_output_dir', '--fp16', '--do_train', '--max_train_samples', '500', '--num_train_epochs', '1', '--dataset_name', 'wmt16', '--dataset_config', 'ro-en', '--source_lang', 'en', '--target_lang', 'ro'] exits with return code = 1
```

**Comment by tjruwase** [comment]
@stanleyshly, please try setting both instances of `pin_memory` to false.

**Comment by stanleyshly** [comment]
I tried that, here is a new stack trace:
```
1/1] c++ cpu_adam_hip.o custom_hip_kernel.cuda.o -shared -L/home/workstation/.local/lib/python3.10/site-packages/torch/lib -lc10 -lc10_hip -ltorch_cpu -ltorch_hip -ltorch -ltorch_python -L/opt/rocm-5.4.2/lib -lamdhip64 -o cpu_adam.so
Loading extension module cpu_adam...
Time to load cpu_adam op: 2.801124334335327 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000050, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2023-03-14 16:56:21,602] [INFO] [logging.py:77:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2023-03-14 16:56:21,644] [INFO] [logging.py:77:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2023-03-14 16:56:21,644] [INFO] [utils.py:55:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2023-03-14 16:56:21,644] [INFO] [logging.py:77:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 3 optimizer
[2023-03-14 16:56:21,724] [INFO] [utils.py:829:see_memory_usage] Stage 3 initialize beginning
[2023-03-14 16:56:21,724] [INFO] [utils.py:830:see_memory_usage] MA 0.12 GB         Max_MA 0.25 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-14 16:56:21,724] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.18 GB, percent = 33.6%
[2023-03-14 16:56:21,728] [INFO] [stage3.py:113:__init__] Reduce bucket size 1048576
[2023-03-14 16:56:21,728] [INFO] [stage3.py:114:__init__] Prefetch bucket size 943718
Using /home/workstation/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
Emitting ninja build file /home/workstation/.cache/torch_extensions/py310_cpu/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.05885648727416992 seconds
[2023-03-14 16:56:21,863] [INFO] [utils.py:829:see_memory_usage] DeepSpeedZeRoOffload initialize [begin]
[2023-03-14 16:56:21,864] [INFO] [utils.py:830:see_memory_usage] MA 0.12 GB         Max_MA 0.12 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-14 16:56:21,864] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.18 GB, percent = 33.6%
Parameter Offload: Total persistent parameters: 125952 in 124 params
[2023-03-14 16:56:22,093] [INFO] [utils.py:829:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
[2023-03-14 16:56:22,094] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.12 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-14 16:56:22,094] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.19 GB, percent = 33.6%
[2023-03-14 16:56:22,175] [INFO] [utils.py:829:see_memory_usage] Before creating fp16 partitions
[2023-03-14 16:56:22,175] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-14 16:56:22,175] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 5.19 GB, percent = 33.6%
[2023-03-14 16:56:23,528] [INFO] [utils.py:829:see_memory_usage] After creating fp16 partitions: 1
[2023-03-14 16:56:23,529] [INFO] [utils.py:830:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.31 GB         Max_CA 0 GB 
[2023-03-14 16:56:23,529] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 6.66 GB, percent = 43.2%
[2023-03-14 16:56:23,529] [INFO] [stage3.py:484:_configure_tensor_swapping] Tensor Swapping: Adding optimizer tensors
Traceback (most recent call last):
  File "/home/workstation/Desktop/transformers/examples/pytorch/translation/run_translation.py", line 664, in <module>
    main()
  File "/home/workstation/Desktop/transformers/examples/pytorch/translation/run_translation.py", line 581, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1631, in train
    return inner_training_loop(
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1700, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/workstation/.local/lib/python3.10/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 336, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1294, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1595, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 266, in __init__
    self._configure_tensor_swapping(offload_optimizer_config, aio_config)
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 488, in _configure_tensor_swapping
    self.optimizer_swapper = swapper_type(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/partitioned_optimizer_swapper.py", line 38, in __init__
    self).__init__(swap_config,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/optimizer_utils.py", line 149, in __init__
    self.swap_buffer_manager = SwapBufferManager(num_elems=self.largest_numel,
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/utils.py", line 182, in __init__
    self.all_buffers = [
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/utils.py", line 183, in <listcomp>
    get_accelerator().pin_memory(
  File "/home/workstation/.local/lib/python3.10/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 216, in pin_memory
    return tensor.pin_memory()
RuntimeError: HIP error: out of memory
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


```

**Comment by tjruwase** [comment]
Please try stage 2 instead of 3.

**Comment by stanleyshly** [comment]
I see, stage 2 offloading to the cpu device works fine.

I'm still a bit confused over why the zero 3 nvme offloading didn't work; is much more VRAM needed to NVMe offload versus CPU offload?

**Comment by tjruwase** [comment]
NVMe offloading requires pinned (page-locked) memory as swap buffers for transfers to/from NVMe. Pinned memory typically waste memory and easily cause OOM and stability issues with small DRAM.

**Comment by stanleyshly** [comment]
Makes sense to me! Closing the issue now.
