### ISSUE TITLE
[BUG] (NVMe Offload with Zero3) Not enough buffers 0 for swapping 1

### ISSUE THREAD

**Issue by srikanthmalla** [microsoft/DeepSpeed#3062]
Hi,
I am currently trying off the shelf tranformer example with deepspeed:
```
BS=4; PYTHONPATH=src USE_TF=0 deepspeed examples/pytorch/translation/run_translation.py \
--model_name_or_path t5-11b --output_dir /tmp/zero3 --overwrite_output_dir --max_train_samples 64 \
--max_eval_samples 64 --max_source_length 128 --max_target_length 128 --val_max_target_length 128 \
--do_train --num_train_epochs 8 --per_device_train_batch_size $BS --per_device_eval_batch_size $BS \
--learning_rate 3e-3 --warmup_steps 500 --predict_with_generate --logging_steps 10 --save_steps 0 \
--eval_steps 5 --group_by_length   --dataset_name wmt16 --dataset_config ro-en --source_lang en \
--target_lang ro --source_prefix "translate English to Romanian: " \
--deepspeed tests/deepspeed/ds_config_zero3_nvme_offload.json
```
The config file ds_config_zero3_nvme_offload.json has zero3 params from the main documentation (https://huggingface.co/docs/transformers/main_classes/deepspeed#zero3-example) website like this:
```
{
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "nvme",
            "nvme_path": "/local_nvme",
            "pin_memory": true,
            "buffer_count": 4,
            "fast_init": false
        },
        "offload_param": {
            "device": "nvme",
            "nvme_path": "/local_nvme",
            "pin_memory": true,
            "buffer_count": 5,
            "buffer_size": 1e8,
            "max_in_cpu": 1e9
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "aio": {
            "block_size": 262144,
            "queue_depth": 32,
            "thread_count": 1,
            "single_submit": false,
            "overlap_events": true
        },
}
```

I get the following error:
```File "/home/xxx/anaconda3/envs/profiler/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 813, in all_gather_coalesced
AssertionError: Not enough buffers 0 for swapping 1
    self._ensure_availability_of_partitioned_params(params)
  File "/home/xxx/anaconda3/envs/profiler/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 999, in _ensure_availability_of_partitioned_params
    swap_in_list[0].nvme_swapper.swap_in(swap_in_list, async_op=False)
  File "/home/xxx/anaconda3/envs/profiler/lib/python3.8/site-packages/deepspeed/runtime/swap_tensor/partitioned_param_swapper.py", line 308, in swap_in
    assert len(swap_in_paths) <= len(self.available_buffer_ids), f"Not enough buffers {len(self.available_buffer_ids)} for swapping {len(swap_in_paths)}"
AssertionError: Not enough buffers 0 for swapping 1
```

**I don't get this error if the offload_param device is set to cpu, instead of nvme**. I am curious why this is happening and how to fix this. Also, this happens regardless I add aio params or remove all of them. Please let me know.

Thank you!

**Comment by srikanthmalla** [comment]
Hi @HeyangQin and @tjruwase ,
Could you help me resolve this issue?

**Comment by tjruwase** [comment]
@srikanthmalla, did either of these changes help?

**Comment by srikanthmalla** [comment]
Hi @tjruwase, both didn't help.

**Comment by tjruwase** [comment]
Thanks for the update. I was able to reproduce the problem. My initial look suggests that this is due to the optimization of prefetching and caching layer parameters to reduce offload overheads.  The following error message shows that the `buffer_count:5` setting of `offload_param` is eventually exceeded:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/4271600/230621991-9f00a0c7-ad44-48e6-9d3c-9bbc4a9986de.png">

I was able to work around this issue by disabling caching (i.e., `"stage3_max_reuse_distance": 0`). But since that did not work for you, I am concerned perhaps I have reproduced a different problem. Can you please try the following to help this investigation?

1. Share how many GPUs you are using? I reproduced on 4xV100-16GB.
2. Use this branch: https://github.com/microsoft/DeepSpeed/tree/olruwase/issue_3062. Please note that this branch includes offload debug prints that will increase log size. 
3. Run your original failing configuration and share the log.
4. Run with disabled caching (`"stage3_max_reuse_distance": 0`) and disabled prefetching (`"stage3_prefetch_bucket_size": 0`) to see if that combination avoids the error.

**Comment by tjruwase** [comment]
@srikanthmalla, just to clarify, we recognize that there is an underlying issue that needs to be fixed. My requests above are just to help further understand this issue. Thanks!

**Comment by moussaba** [comment]
Has this issue been resolved? I am running into the same problem when using facebook/opt- 6.7 or 13b. It works fine once I hit 30b and above. I am on a system with 1x3090. I did try all the suggested options above but to no avail. This is just an exercise in understanding the behavior of DeepSpeed at these model sizes.

**Comment by chongxiaoc** [comment]
Hi, I'm getting same issue when using deepspeed 0.10.0 with huggingface transformers.
```
727AssertionError: Not enough buffers 0 for swapping 1726    assert len(swap_in_paths) <= len(725  File "/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/swap_tensor/partitioned_param_swapper.py", line 297, in swap_in
```

Deepspeed config:
```
    zero_optimization:
      stage: 3
      offload_optimizer:
        device: nvme
        nvme_path: /tmp/nvme_offoad
      offload_param:
        device: nvme
        nvme_path: /tmp/nvme_offoad
```

**Comment by mobilejammer** [comment]
does this issue resolved?

**Comment by mobilejammer** [comment]
@tjruwase I set "stage3_max_reuse_distance": 0, but assert len(swap_in_paths) <= len(self.available_buffer_ids) the same. one machine 8 nvidia 4090, deepspeed zero3. so I wonder this issue has resolved?

**Comment by Yacklin** [comment]
> Thanks for the update. I was able to reproduce the problem. My initial look suggests that this is due to the optimization of prefetching and caching layer parameters to reduce offload overheads. The following error message shows that the `buffer_count:5` setting of `offload_param` is eventually exceeded:
> 
> <img alt="image" width="468" src="https://user-images.githubusercontent.com/4271600/230621991-9f00a0c7-ad44-48e6-9d3c-9bbc4a9986de.png">
> 
> The meaning of the above message is that we are unable to add `param 258` to the offload cache because it is full, containing params `259, 233, 207, 246, 220`
> 
> I was able to work around this issue by disabling caching (i.e., `"stage3_max_reuse_distance": 0`). But since that did not work for you, I am concerned perhaps I have reproduced a different problem. Can you please try the following to help this investigation?
> 
> 1. Share how many GPUs you are using? I reproduced on 4xV100-16GB.
> 2. Use this branch: https://github.com/microsoft/DeepSpeed/tree/olruwase/issue_3062. Please note that this branch includes offload debug prints that will increase log size.
> 3. Run your original failing configuration and share the log.
> 4. Run with disabled caching (`"stage3_max_reuse_distance": 0`) and disabled prefetching (`"stage3_prefetch_bucket_size": 0`) to see if that combination avoids the error.

I encountered the same issue and your suggestion works for me, which is disabling both.

BUT!!!!!!!

it's too slow!!!!!

---------------update after several mins---------------------

training fails after i used what you suggested

here is the output:
deepspeed_aio:   open for read  failed on /data/home/xxx/ds_offload/offload_param/zero_stage_3/float32params/rank0/70_param.tensor.swp error = 24                                                    
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/home/xxx/projects/fine-tuning/lora_fine_tuning_with_ds.py", line 342, in <module>
[rank0]:   File "/data/home/xxx/projects/fine-tuning/lora_fine_tuning_with_ds.py", line 304, in start_train
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/trainer.py", line 2325, in train
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/trainer.py", line 2674, in _inner_training_loop
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/trl/trainer/sft_trainer.py", line 1190, in training_step
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/trainer.py", line 4020, in training_step
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/trl/trainer/sft_trainer.py", line 1103, in compute_loss
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/trainer.py", line 4110, in compute_loss
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/engine.py", line 2211, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/peft/peft_model.py", line 1923, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/peft/tuners/tuners_utils.py", line 308, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/utils/generic.py", line 918, in wrapper
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 480, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/utils/generic.py", line 1064, in wrapper
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 410, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/modeling_layers.py", line 93, in __call__
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/_compile.py", line 32, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/utils/checkpoint.py", line 489, in checkpoint
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/utils/checkpoint.py", line 264, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 260, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 229, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/peft/tuners/lora/layer.py", line 793, in forward
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1779, in inner
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 300, in _pre_forward_module_hook
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 475, in pre_sub_module_forward_function
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 317, in fetch_sub_module
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 475, in __all_gather_params
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 504, in __all_gather_params_
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1268, in all_gather_coalesced
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1588, in _ensure_availability_of_partitioned_params
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/swap_tensor/partitioned_param_swapper.py", line 318, in swap_in
[rank0]:   File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/runtime/swap_tensor/utils.py", line 22, in swap_in_tensors
[rank0]: AssertionError
Exception ignored in atexit callback: <function matmul_ext_update_autotune_table at 0x7fa1df301760>
Traceback (most recent call last):
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 480, in matmul_ext_update_autotune_table
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 457, in _update_autotune_table
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 180, in _update_autotune_table
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 90, in __init__
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 47, in warn_if_nfs
  File "/data/home/xxx/projects/fine-tuning/.venv/lib64/python3.11/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 30, in is_nfs_path
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
  File "/usr/lib64/python3.11/subprocess.py", line 992, in __init__
  File "/usr/lib64/python3.11/subprocess.py", line 1715, in _get_handles
OSError: [Errno 24] Too many open files
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib64/python3.11/weakref.py", line 666, in _exitfunc
[rank0]:     f()
[rank0]:   File "/usr/lib64/python3.11/weakref.py", line 590, in __call__
[rank0]:     return info.func(*info.args, **(info.kwargs or {}))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib64/python3.11/tempfile.py", line 933, in _cleanup
[rank0]:     cls._rmtree(name, ignore_errors=ignore_errors)
[rank0]:   File "/usr/lib64/python3.11/tempfile.py", line 929, in _rmtree
[rank0]:     _shutil.rmtree(name, onerror=onerror)
[rank0]:   File "/usr/lib64/python3.11/shutil.py", line 752, in rmtree
[rank0]:     _rmtree_safe_fd(fd, path, onerror)
[rank0]:   File "/usr/lib64/python3.11/shutil.py", line 647, in _rmtree_safe_fd
[rank0]:     onerror(os.scandir, path, sys.exc_info())
[rank0]:   File "/usr/lib64/python3.11/shutil.py", line 643, in _rmtree_safe_fd
[rank0]:     with os.scandir(topfd) as scandir_it:
[rank0]:          ^^^^^^^^^^^^^^^^^
[rank0]: OSError: [Errno 24] Too many open files: '/tmp/tmp408j404l'
 18%|███████████████████████████▊                                                                                                                                  | 104/592 [25:56<2:01:43, 14.97s/it]
[2025-11-23 22:36:08,403] [INFO] [launch.py:335:sigkill_handler] Killing subprocess 333398
[2025-11-23 22:36:08,403] [INFO] [launch.py:335:sigkill_handler] Killing subprocess 333399
[2025-11-23 22:36:10,890] [ERROR] [launch.py:341:sigkill_handler] ['/data/home/xxx/projects/fine-tuning/.venv/bin/python3', '-u', 'lora_fine_tuning_with_ds.py', '--local_rank=1'] exits with return code = 1

**Comment by Yacklin** [comment]
> Thanks for the update. I was able to reproduce the problem. My initial look suggests that this is due to the optimization of prefetching and caching layer parameters to reduce offload overheads. The following error message shows that the `buffer_count:5` setting of `offload_param` is eventually exceeded:
> 
> <img alt="image" width="468" src="https://user-images.githubusercontent.com/4271600/230621991-9f00a0c7-ad44-48e6-9d3c-9bbc4a9986de.png">
> 
> The meaning of the above message is that we are unable to add `param 258` to the offload cache because it is full, containing params `259, 233, 207, 246, 220`
> 
> I was able to work around this issue by disabling caching (i.e., `"stage3_max_reuse_distance": 0`). But since that did not work for you, I am concerned perhaps I have reproduced a different problem. Can you please try the following to help this investigation?
> 
> 1. Share how many GPUs you are using? I reproduced on 4xV100-16GB.
> 2. Use this branch: https://github.com/microsoft/DeepSpeed/tree/olruwase/issue_3062. Please note that this branch includes offload debug prints that will increase log size.
> 3. Run your original failing configuration and share the log.
> 4. Run with disabled caching (`"stage3_max_reuse_distance": 0`) and disabled prefetching (`"stage3_prefetch_bucket_size": 0`) to see if that combination avoids the error.

@tjruwase so do you mean that if cache is full and when program tries to add something in it then the error would occur? i think it should be an easy fix. i am wondering if someone like you is working on it?
