### ISSUE TITLE
bf16 optimizer and fp16 optimizer need more memory than fp32 optimizer

### ISSUE THREAD

**Issue by Stick-To** [microsoft/DeepSpeed#3114]
when I train a PipelineModule
fp16 optimizer and bf16 optimizer get a oom error when step(), but fp32 optimizer not
here is bf16 config
```
{
  "train_batch_size" : 1,
  "train_micro_batch_size_per_gpu" : 1,
   "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 0.0001,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-8
    }
  },
   "bf16": {
        "enabled": "auto"
  },
  "steps_per_print" : 10,
  "wall_clock_breakdown" : false
 }
```

here is fp32 config

```
{
  "train_batch_size" : 1,
  "train_micro_batch_size_per_gpu" : 1,
   "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 0.0001,
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-8
    }
  },
  "steps_per_print" : 10,
  "wall_clock_breakdown" : false
 }
```
```
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
```
```
DeepSpeed general environment info:
torch version .................... 2.0.0+cu117
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
```
```
Traceback (most recent call last):
  File stanford_alpaca-main/esm.py", line 102, in <module>
    engine, optim, dataloader, _ = deepspeed.initialize(
  File "python3.9/site-packages/deepspeed/__init__.py", line 138, in initialize
    engine = PipelineEngine(args=args,
  File "python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 60, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "python3.9/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "python3.9/site-packages/deepspeed/runtime/engine.py", line 1298, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "python3.9/site-packages/deepspeed/runtime/engine.py", line 1547, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 516, in __init__
    self.initialize_optimizer_states()
  File "python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 648, in initialize_optimizer_states
    self.optimizer.step()
  File "python3.9/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 170, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "python3.9/site-packages/deepspeed/ops/adam/multi_tensor_apply.py", line 14, in __call__
    return op(self.chunk_size, noop_flag_buffer, tensor_lists, *args)
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by li-yi-dong** [comment]
How did you solve this problem?🥺

**Comment by terrifyzhao** [comment]
I got same error, did you solve this problem

**Comment by Stick-To** [comment]
> I got same error, did you solve this problem

No， did you solve it?

**Comment by Stick-To** [comment]
> How did you solve this problem?🥺

No， did you solve it?
