### ISSUE TITLE
[BUG]CUDA OOM when calling `_setup_for_real_optimizer()` on 8*3090 24G, 6B model

### ISSUE THREAD

**Issue by chenyi-miaow** [microsoft/DeepSpeed#3132]
I'm training dolly(gpt-j, a 6B language model) on 8 * 3090 24G using zero-stage3.
When almost finished training, it reported a CUDA OOM ERROR.
The traceback shows that it occurred when calling `self._setup_for_real_optimizer()`.

```
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0011472702026367188 seconds
Parameter Offload: Total persistent parameters: 861408 in 115 params
2023-04-04 16:21:07 ERROR [__main__] main failed
Traceback (most recent call last):
  File "./training/trainer.py", line 263, in <module>
    main()
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./training/trainer.py", line 255, in main
    train(**kwargs)
  File "./training/trainer.py", line 218, in train
    trainer.train(resume_from_checkpoint='/HOME/scz0bkq/run/dolly-master/dolly_training/dolly/checkpoint-600')
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/transformers/trainer.py", line 1637, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/transformers/trainer.py", line 2022, in _inner_training_loop
    self._load_best_model()
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/transformers/trainer.py", line 2146, in _load_best_model
    resume_from_checkpoint=self.state.best_model_checkpoint,
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/__init__.py", line 135, in initialize
    config_params=config_params)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1298, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1626, in _configure_zero_optimizer
    communication_data_type=self.communication_data_type)
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/runtime/zero/stage3.py", line 312, in __init__
    self._setup_for_real_optimizer()
  File "/HOME/scz0bkq/.conda/envs/runQA/lib/python3.7/site-packages/deepspeed/runtime/zero/stage3.py", line 393, in _setup_for_real_optimizer
    device=self.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 1; 23.70 GiB total capacity; 21.28 GiB already allocated; 1.07 GiB free; 21.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Screenshots**

![image](https://user-images.githubusercontent.com/61866304/229746216-38fd1f27-9b57-4eaa-a83f-034d6ec01fbe.png)

 - OS: CentOS Linux release 7.9.2009 (Core)
 - 8 3090 24G
 - Transformers 4.27.3
 - DeepSpeed 0.8.3

**Comment by chenyi-miaow** [comment]
Is it because `_set_up_for_real_optimizer` called self.device to put the optimizer into the GPU, the original memory on the GPU was not released, so OOM appeared?

**Comment by tjruwase** [comment]
@chenyi-miaow, it is hard to tell without seeing the full log. In particular, it would be helpful to see memory profile logs such as [this](https://github.com/microsoft/DeepSpeed/blob/f2c9a827993d5e6e951a8ce920d55de810b2aab2/deepspeed/runtime/zero/stage3.py#L351).

**Comment by chenyi-miaow** [comment]
[slurm-366972.txt](https://github.com/microsoft/DeepSpeed/files/11155538/slurm-366972.txt)
@tjruwase Here is the full log, the error message start at line 552. 
But I can't find any memory profile logs in my log file, should I set some parameter to save it? Or it's already been saved, while I haven't found it.

**Comment by tjruwase** [comment]
Closing for now due to no response. Please re-open if needed. Thanks!
