### ISSUE TITLE
[BUG] RuntimeError: Failed to import transformers.models.opt.modeling_opt

### ISSUE THREAD

**Issue by alibabadoufu** [microsoft/DeepSpeed#3215]
When I ran the training, I encountered the following error:

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1146, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 31, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/opt/conda/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/opt/conda/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /opt/conda/lib/python3.8/site-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt8toSymIntENS_13intrusive_ptrINS_14SymIntNodeImplENS_6detail34intrusive_target_default_null_typeIS2_EEEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 328, in <module>
    main()
  File "main.py", line 202, in main
    model = create_hf_model(AutoModelForCausalLM, args.model_name_or_path,
  File "/home/work/Deepspeed/DeepSpeedExamples/applications/DeepSpeed-Chat/training/utils/model/model_utils.py", line 35, in create_hf_model
    model = model_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 602, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 616, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 561, in getattribute_from_module
    if hasattr(module, attr):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1136, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1148, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.opt.modeling_opt because of the following error (look up to see its traceback):
/opt/conda/lib/python3.8/site-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: `

**Comment by mrwyattii** [comment]
Hi @alibabadoufu can you please share information about your environment, using the following?
`ds_report`
`pip list | grep transformers`

**Comment by alibabadoufu** [comment]
> Hi @alibabadoufu can you please share information about your environment, using the following? `ds_report` `pip list | grep transformers`

I realized that its my environment issue. There is no issue anymore. Thanks :D

**Comment by ericzhou571** [comment]
> > Hi @alibabadoufu can you please share information about your environment, using the following? `ds_report` `pip list | grep transformers`
> 
> I realized that its my environment issue. There is no issue anymore. Thanks :D

hi, I face the same problem like you, could you tell me how you sovle the problem at the end? just reinstall transformers?
Thanks a lot

**Comment by alibabadoufu** [comment]
> > > Hi @alibabadoufu can you please share information about your environment, using the following? `ds_report` `pip list | grep transformers`
> > 
> > 
> > I realized that its my environment issue. There is no issue anymore. Thanks :D
> 
> hi, I face the same problem like you, could you tell me how you sovle the problem at the end? just reinstall transformers? Thanks a lot

What is your transformer version? You need to follow the guideline so that you have the same transformer version as what the code recommends.

**Comment by MohamedAliRashad** [comment]
I have the same problem, Any solutions ?

**Comment by alibabadoufu** [comment]
> I have the same problem, Any solutions ?

Did you do pip install `deepspeed` or `git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed && pip install .` ?

You should always install from the source.

**Comment by MohamedAliRashad** [comment]
@alibabadoufu 
Still the same problem

**Comment by MohamedAliRashad** [comment]
It is a problem with accelerate and it make me unable to use trlx

**Comment by mrwyattii** [comment]
@ericzhou571 @MohamedAliRashad If you are seeing the exact same error that was initially reported, can you please provide information about the package versions you have installed?

Share the output of
`ds_report` and `pip list | grep "deepspeed\|torch\|transformers\|accelerate"`

**Comment by wangshankun** [comment]
> pip list | grep "deepspeed\|torch\|transformers\|accelerate"

@mrwyattii  same error：
![image](https://github.com/microsoft/DeepSpeed/assets/3970271/c83acca3-87c5-4556-8e88-b00f255a681c)

**Comment by mrwyattii** [comment]
@wangshankun from my understanding of this problem, it is likely an issue in your environment related to the cuda and/or torch installs. Can you please share how you installed torch? Did you follow the recommended command for conda environments (`conda install pytorch pytorch-cuda=11.8 -c pytorch -c nvidia`)? If you did, are you able to run other transformer models on GPU (without DeepSpeed)?
