### ISSUE TITLE
[BUG] Autotp failed

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed#3357]
Model: THUDM/chatglm-6b

script: https://gist.github.com/frankxyy/8177aded8eb59c6bac8f0a4576d502e8

cmd: CUDA_VISIBLE_DEVICES=6,7 deepspeed inference-test.py --name THUDM/chatglm-6b --test_performance --ds_inference

hw: rtx3090

error msg:
```
Traceback (most recent call last):
  File "inference-test.py", line 135, in <module>
    outputs = pipe(inputs,
  File "/home/xuyangyang/dsexamples/inference/huggingface/text-generation/utils.py", line 82, in __call__
    outputs = self.generate_outputs(input_list, max_length=max_length, do_sample=do_sample)
  File "/home/xuyangyang/dsexamples/inference/huggingface/text-generation/utils.py", line 133, in generate_outputs
    outputs = self.model.generate(**input_tokens, **generate_kwargs)
  File "/home/xuyangyang/deepspeed/deepspeed/inference/engine.py", line 599, in _generate
    return self.module.generate(*inputs, **kwargs)
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xuyangyang/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xuyangyang/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xuyangyang/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/home/xuyangyang/miniconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xuyangyang/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/f83182484538e663a03d3f73647f10f89878f438/modeling_chatglm.py", line 452, in forward
    mixed_raw_layer = mixed_raw_layer.view(*new_tensor_shape)
RuntimeError: shape '[21, 1, 32, 384]' is invalid for input of size 129024
```

**Comment by molly-smith** [comment]
Hi @frankxyy, AutoTP does not currently support ChatGLM models.
