### ISSUE TITLE
[BUG] Unable to install deepspeed with M2 arm64

### ISSUE THREAD

**Issue by elcolie** [microsoft/DeepSpeed#3364]
I am trying train [gpt4all](https://github.com/nomic-ai/gpt4all)<br>
In the setup topic. It failed
`python -m pip install -r requirements.txt`

M2 OSX: 13.2

```
❯ pip3 install -r requirements.txt
Collecting accelerate
  Using cached accelerate-0.18.0-py3-none-any.whl (215 kB)
Collecting datasets
  Using cached datasets-2.11.0-py3-none-any.whl (468 kB)
Requirement already satisfied: torchmetrics in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (0.11.1)
Collecting evaluate
  Using cached evaluate-0.4.0-py3-none-any.whl (81 kB)
Collecting transformers>=4.28.0
  Using cached transformers-4.28.1-py3-none-any.whl (7.0 MB)
Collecting wandb
  Using cached wandb-0.15.0-py3-none-any.whl (2.0 MB)
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (23.0.1)
Collecting peft
  Using cached peft-0.2.0-py3-none-any.whl (40 kB)
Collecting nodelist-inflator
  Using cached nodelist_inflator-0.2.0-py3-none-any.whl (2.7 kB)
Collecting deepspeed
  Using cached deepspeed-0.9.1.tar.gz (766 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/h5/4mllfnsj3_z7pn72_yfp82qw0000gn/T/pip-install-d3t5r8ik/deepspeed_0f0458a1a4454321955dce07327eb52f/setup.py", line 30, in <module>
          import torch
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/__init__.py", line 220, in <module>
          _load_global_deps()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/__init__.py", line 180, in _load_global_deps
          raise err
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/__init__.py", line 175, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
          self._handle = _dlopen(self._name, mode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Question:<br>
Is it possible to install deepspeed on M2 mac?

**Comment by lam-ux** [comment]
Use this:https://gpt4all.io/installers/gpt4all-installer-darwin.dmg
