### ISSUE TITLE
[BUG] DeeperSpeed run error ModuleNotFoundError: No module named 'deepspeed.accelerator'

### ISSUE THREAD

**Issue by dataangel** [microsoft/DeepSpeed#3406]
DeeperSpeed
Traceback (most recent call last):
  File "/home/dataangel/anaconda3/bin/ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import ops
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/ops/__init__.py", line 6, in <module>
    from . import adam
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/ops/adam/__init__.py", line 6, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 8, in <module>
    from deepspeed.utils import logger
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/utils/__init__.py", line 10, in <module>
    from .groups import *
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/utils/groups.py", line 28, in <module>
    from deepspeed import comm as dist
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/comm/__init__.py", line 7, in <module>
    from .comm import *
  File "/home/dataangel/anaconda3/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 30, in <module>
    from deepspeed.accelerator import get_accelerator
ModuleNotFoundError: No module named 'deepspeed.accelerator'

**Comment by Aleluya009** [comment]
Copy the corresponding modules in the zip file to the python package directory can solve this problem

**Comment by bliu3650** [comment]
Copying the corresponding folders (accelerator, op_builder...) to the targeting paths (deepspeed, deepspeed/ops...) can walkaround this problem for local compilation.

**Comment by yang** [comment]
For posterity: if installing via a git source, check if your global gitconfig has core.symlinks = false, and retry with `pip --no-cache-dir`.
