### ISSUE TITLE
[BUG] Local rank mismatch error when training on nodes with different number of GPUs

### ISSUE THREAD

**Issue by byungsoo-oh** [microsoft/DeepSpeed#3408]
**Describe the bug**
When training Megatron-DeepSpeed models on nodes with different number of GPUs (e.g., node 0: 2 GPUs, node 1: 4 GPUs), local rank mismatch error (`AssertionError: expected local-rank to be the same as rank % device-count.`) occurs in https://github.com/microsoft/Megatron-DeepSpeed/blob/main/megatron/initialize.py#L207. 

I found that this is caused by local ranks set by DeepSpeed launcher **mismatching** the local ranks set by Megatron-DeepSpeed.
Specifically, while DeepSpeed assigns local ranks corresponding to global ranks sequentially (e.g., global ranks: [2, 3, 4, 5] -> local ranks: [0, 1, 2, 3]), Megatron-DeepSpeed decides each local rank as **global rank % device count of the node** (e.g., global ranks: [2, 3, 4, 5] -> local ranks: [2, 3, 0, 1]). 

**To Reproduce**
1. Clone https://github.com/microsoft/Megatron-DeepSpeed and prepare to run training scripts (e.g., https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/MoE/ds_pretrain_gpt_350M_dense.sh) as guided.
2. Prepare a cluster where each node has different number of GPUs (e.g., two nodes each with 2 and 4 GPUs, respectively).
3. Execute a training script.

**Expected behavior**
Training starts normally without an error in such setup. Because DeepSpeed document does not restrict that all nodes must be homogeneous (i.e., exacltly the same number of GPUs), I expected training to work properly for clusters where nodes have different number of GPUs.

**ds_report output**
```bash
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/.local/lib/python3.9/site-packages/torch']
torch version .................... 1.10.0+cu111
deepspeed install path ........... ['/home/ubuntu/.local/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.1
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
```

**Error log**
```bash
Traceback (most recent call last):
   File "/home/ubuntu/Megatron-DeepSpeed/examples/MoE/../../pretrain_gpt.py", line 345, in <module>
     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
   File "/home/ubuntu/Megatron-DeepSpeed/megatron/training.py", line 107, in pretrain
     initialize_megatron(extra_args_provider=extra_args_provider,
   File "/home/ubuntu/Megatron-DeepSpeed/megatron/initialize.py", line 79, in initialize_megatron
     finish_mpu_init()
   File "/home/ubuntu/Megatron-DeepSpeed/megatron/initialize.py", line 60, in finish_mpu_init
     _initialize_distributed()
   File "/home/ubuntu/Megatron-DeepSpeed/megatron/initialize.py", line 216, in _initialize_distributed
     assert args.local_rank == device, \
 AssertionError: expected local-rank to be the same as rank % device-count.
```

**System info**
 - OS: Ubuntu 18.04
 - GPU count and types: Two machines, each with 2 T4 GPUs and 4 T4 GPUs, respectively
 - Python version: 3.9.4

**Launcher context**
`deepspeed` launcher

**Docker context**
N/A. Did not use Docker images.

**Comment by byungsoo-oh** [comment]
I fixed this issue and checked it's working fine. If it's okay, I will submit a pull request for this.

**Comment by Godricly** [comment]
I faced a similar issue when trying Megatron-deepspeed demo of LLAMA2 13B using 2 nodes with 4 GPUS when PP is set to 8. The local rank on second node is different from the environment variable.

Megatron-Deepspeed git version: c08e2cc2579cf7ef5ce6ad58453e76a5710b7b6b
Deepspeed git version: 430510bfce5c8e2e8f2108b73824aef4a37fcaf1


A complete error log is like this.
```
Traceback (most recent call last):
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
Traceback (most recent call last):
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 137, in pretrain
Traceback (most recent call last):
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 137, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 581, in setup_model_and_optimizer
    pretrain(train_valid_test_datasets_provider,
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 137, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 581, in setup_model_and_optimizer
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 581, in setup_model_and_optimizer
    model, optimizer, _, opt_param_scheduler = deepspeed.initialize(
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/__init__.py", line 186, in initialize
    model, optimizer, _, opt_param_scheduler = deepspeed.initialize(
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/__init__.py", line 186, in initialize
    model, optimizer, _, opt_param_scheduler = deepspeed.initialize(
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/__init__.py", line 186, in initialize
    engine = PipelineEngine(args=args,
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/pipe/engine.py", line 67, in __init__
    engine = PipelineEngine(args=args,
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/pipe/engine.py", line 67, in __init__
    engine = PipelineEngine(args=args,
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/pipe/engine.py", line 67, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 237, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 237, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 237, in __init__
    self._do_args_sanity_check(args)
    self._do_args_sanity_check(args)  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 985, in _do_args_sanity_check

  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 985, in _do_args_sanity_check
    self._do_args_sanity_check(args)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 985, in _do_args_sanity_check
    env_local_rank == args.local_rank
    env_local_rank == args.local_rank
AssertionError: Mismatch in local rank setting, args.local_rank=7 but env['LOCAL_RANK']=3.
AssertionError: Mismatch in local rank setting, args.local_rank=6 but env['LOCAL_RANK']=2.
    env_local_rank == args.local_rank
AssertionError: Mismatch in local rank setting, args.local_rank=5 but env['LOCAL_RANK']=1.
 > number of parameters on (tensor, pipeline) model parallel rank (0, 4): 1586022400
Traceback (most recent call last):
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 137, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/beegfs_mount/yan_li/codes/Megatron-DeepSpeed/megatron/training.py", line 581, in setup_model_and_optimizer
    model, optimizer, _, opt_param_scheduler = deepspeed.initialize(
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/__init__.py", line 186, in initialize
    engine = PipelineEngine(args=args,
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/pipe/engine.py", line 67, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 237, in __init__
    self._do_args_sanity_check(args)
  File "/beegfs_mount/yan_li/codes/DeepSpeed/deepspeed/runtime/engine.py", line 985, in _do_args_sanity_check
    env_local_rank == args.local_rank
AssertionError: Mismatch in local rank setting, args.local_rank=4 but env['LOCAL_RANK']=0.

```

The log of network splitting.
```
stage=0 layers=7
     0: _to_float16
     1: EmbeddingPipe
     2: ParallelTransformerLayerPipe
     3: ParallelTransformerLayerPipe
     4: ParallelTransformerLayerPipe
     5: ParallelTransformerLayerPipe
     6: ParallelTransformerLayerPipe
stage=1 layers=5
     7: ParallelTransformerLayerPipe
     8: ParallelTransformerLayerPipe
     9: ParallelTransformerLayerPipe
    10: ParallelTransformerLayerPipe
    11: ParallelTransformerLayerPipe
stage=2 layers=5
    12: ParallelTransformerLayerPipe
    13: ParallelTransformerLayerPipe
    14: ParallelTransformerLayerPipe
    15: ParallelTransformerLayerPipe
    16: ParallelTransformerLayerPipe
stage=3 layers=5
    17: ParallelTransformerLayerPipe
    18: ParallelTransformerLayerPipe
    19: ParallelTransformerLayerPipe
    20: ParallelTransformerLayerPipe
    21: ParallelTransformerLayerPipe
stage=4 layers=5
    22: ParallelTransformerLayerPipe
    23: ParallelTransformerLayerPipe
    24: ParallelTransformerLayerPipe
    25: ParallelTransformerLayerPipe
    26: ParallelTransformerLayerPipe
stage=5 layers=5
    27: ParallelTransformerLayerPipe
    28: ParallelTransformerLayerPipe
    29: ParallelTransformerLayerPipe
    30: ParallelTransformerLayerPipe
    31: ParallelTransformerLayerPipe
stage=6 layers=5
    32: ParallelTransformerLayerPipe
    33: ParallelTransformerLayerPipe
    34: ParallelTransformerLayerPipe
    35: ParallelTransformerLayerPipe
    36: ParallelTransformerLayerPipe
stage=7 layers=8
    37: ParallelTransformerLayerPipe
    38: ParallelTransformerLayerPipe
    39: ParallelTransformerLayerPipe
    40: ParallelTransformerLayerPipe
    41: ParallelTransformerLayerPipe
    42: MixedFusedRMSNorm
    43: LMHeadPipe
    44: float16_to_fp32
  loss: CrossEntropy

``

**Comment by jrt-20** [comment]
I faced a similar issue when trying Megatron-deepspeed demo [/examples_deepspeed/generate_text.sh](https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/generate_text.sh) using 1node 8gpus.
My deepspeed version is 0.12.6

A complete error log is this: 
```
building GPT2BPETokenizer tokenizer ...
Traceback (most recent call last):
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 178, in <module>
    main()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 120, in main
    initialize_megatron(extra_args_provider=add_text_generate_args,
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 86, in initialize_megatron
    finish_mpu_init()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 66, in finish_mpu_init
    _initialize_distributed()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 212, in _initialize_distributed
    assert args.local_rank == device, \
AssertionError: expected local-rank to be the same as rank % device-count.
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
Traceback (most recent call last):
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 178, in <module>
    main()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/tools/generate_samples_gpt.py", line 120, in main
    initialize_megatron(extra_args_provider=add_text_generate_args,
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 86, in initialize_megatron
    finish_mpu_init()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 66, in finish_mpu_init
    _initialize_distributed()
  File "/mnt/VMSTORE/ygz/Megatron-DeepSpeed/megatron/initialize.py", line 212, in _initialize_distributed
    assert args.local_rank == device, \
AssertionError: expected local-rank to be the same as rank % device-count
```
