### ISSUE TITLE
fail to load checkpoints after zero3 initialize

### ISSUE THREAD

**Issue by Stick-To** [microsoft/DeepSpeed#3574]
```Traceback (most recent call last):
  File "/home/lxr/workspace/t5_train/esm5.py", line 66, in <module>
    engine.load_module_state_dict(torch.load("weight/mt5-small/pytorch_model.bin"))
  File "/home/lxr/workspace/t5_train/deepspeed/runtime/engine.py", line 2421, in load_module_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MT5ForConditionalGeneration:
        size mismatch for shared.weight: copying a param with shape torch.Size([250112, 512]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([250112, 512]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.SelfAttention.q.weight: copying a param with shape torch.Size([384, 512]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.SelfAttention.k.weight: copying a param with shape torch.Size([384, 512]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.SelfAttention.v.weight: copying a param with shape torch.Size([384, 512]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.SelfAttention.o.weight: copying a param with shape torch.Size([512, 384]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight: copying a param with shape torch.Size([32, 6]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for encoder.block.0.layer.0.layer_norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([0]).
```

**Comment by dittops** [comment]
@Stick-To I'm also facing this issue. Could you please share how you resolved it?

**Comment by tjruwase** [comment]
@dittops, please re-open and share repro steps including a stack trace. Thanks!

**Comment by Alchemy5** [comment]
im also facing this issue, any help would be great!

**Comment by iamsile** [comment]
I'm also facing this issue too, anyone who can help ?

**Comment by Alchemy5** [comment]
I actually found a solution to my problem in the Saving and Loading section of this article: https://huggingface.co/docs/accelerate/usage_guides/deepspeed#saving-and-loading

**Comment by yix-chen** [comment]
@Stick-To I'm also facing this issue. Could you please share how you resolved it?

**Comment by Stick-To** [comment]
I have not solve it

**Comment by jzy-123** [comment]
> I met the same problem and solved it by reinitialization. U can deepcopy an original model before u wrap it with `deepspeed.initialize`. Load your checkpoint to the original model, and run `deepspeed.initialize` to the loaded one.

Can you elaborate on how you do that, thank you very much

**Comment by yxchng** [comment]
any update on this? how to resolve this error?

**Comment by nricciardi** [comment]
If you are really desperate and you could ignore all programming best practices (and in AI world this happens continuously), then you can simply load your model out of zero3 context. Therefore, use some environment variables to load the model in a dedicated file or outside your model wrap class and finally setup like this:
```
self.model = GLOBAL_MODEL
```
