### ISSUE TITLE
[BUG] cpu_adam warning

### ISSUE THREAD

**Issue by SkyAndCloud** [microsoft/DeepSpeed#3613]
I encounterd a warning as the training begins:
```
cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
```
Here is my environments:

```
Ubuntu 18.04 LTS
CUDA 11.8
python=3.9
torch=2.0.0
deepspeed=0.9.2
python3.9-dev
```

ds_report:
<img width="713" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/12583017/a022defc-a469-45b1-9f62-04c1b5804a76">

I searched over all the issues and found no worked solutions.

**Comment by dqtran91** [comment]
I have this warning as well. 
Where can I find the log for deepspeed? I am quite new to this

**Comment by SkyAndCloud** [comment]
Hi, I have verified that the system installed cuda version matches the torch cuda, both cu118. I haven't set `DS_SKIP_CUDA_CHECK`.

**Comment by SkyAndCloud** [comment]
Sorry for the late reply. There is no other cuda installations, no prints from your referenced function. I still don't know what causes this warning. However, my code runs successfully.

**Comment by paveltonev** [comment]
I have same warning issue. In the end it leads to killing the finetuning(WizardCoder) subprocess and exiting the main process with return code -9

Here is my configuration:
Ubuntu 22.04 LTS
CUDA 12.1
python=3.10
torch=2.0.1+cu118
deepspeed=0.9.5

![DeepSpeedInfo](https://github.com/microsoft/DeepSpeed/assets/56412370/ca24395e-6765-452a-833d-fab2807c76bd)

**Comment by KeeratKG** [comment]
@loadams Hi. Wish to re-open this issue since I'm encountering the exact same problem as @SkyAndCloud, except my code is not working. 

Output of ds_config: 

```
[2023-08-24 18:01:15,632] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
Traceback (most recent call last):
  File "/opt/conda/envs/llama_etuning/bin/ds_report", line 6, in <module>
    cli_main()
  File "/opt/conda/envs/llama_etuning/lib/python3.10/site-packages/deepspeed/env_report.py", line 159, in cli_main
    main(hide_operator_status=args.hide_operator_status, hide_errors_and_warnings=args.hide_errors_and_warnings)
  File "/opt/conda/envs/llama_etuning/lib/python3.10/site-packages/deepspeed/env_report.py", line 153, in main
    op_report(verbose=not hide_errors_and_warnings)
  File "/opt/conda/envs/llama_etuning/lib/python3.10/site-packages/deepspeed/env_report.py", line 53, in op_report
    is_compatible = OKAY if builder.is_compatible(verbose) else no
  File "/opt/conda/envs/llama_etuning/lib/python3.10/site-packages/deepspeed/ops/op_builder/spatial_inference.py", line 29, in is_compatible
    sys_cuda_major, _ = installed_cuda_version()
  File "/opt/conda/envs/llama_etuning/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 41, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

Can you help me figure it out pls? Thanks!

**Comment by loadams** [comment]
@KeeratKG - the error is here:

```
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

It seems you'd need to set your CUDA_HOME env var.  However, this can sometimes be a symptom of CUDA not being installed correctly.  You may want to just re-install CUDA to be sure.

**Comment by KeeratKG** [comment]
> @KeeratKG - the error is here:
> 
> ```
> AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
> ```
> 
> It seems you'd need to set your CUDA_HOME env var. However, this can sometimes be a symptom of CUDA not being installed correctly. You may want to just re-install CUDA to be sure.

So I re-installed cudatoolkit via conda, and the issue persists in the `ds_report` output. I then ran the following: 
```
>>> import os 
>>> print(os.environ.get('CUDA_PATH'))
None
```
Clearly an issue with my CUDA installation still exists, but I'm not sure I know what it exactly is. Would you be able to suggest any diagnostic checks for this? It's okay if this lies beyond the purview of this issue. Thanks.

**Comment by loadams** [comment]
If you are using conda, we have an environment.yaml [here ](https://github.com/microsoft/DeepSpeed/blob/master/environment.yml)that you can use and has worked for others.

But to debug, I would try the following:

```
nvcc --version
python -c "import torch; print('torch:', torch.__version__, torch)"
python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

That should tell you more about your cuda/torch+cuda installs to then debug if they are installed or not seen by Python or what.

**Comment by amitportnoy** [comment]
[loadams](https://github.com/loadams) this still happens reproduced when installing pytorch through 'pip` with ` --index-url https://download.pytorch.org/whl/cu117', as is the default in pytorch's website.

**Comment by susht3** [comment]
> [loadams](https://github.com/loadams) This still happens reproduced when installing pytorch through `pip` with ` --index-url https://download.pytorch.org/whl/cu117`, as is the default in pytorch's website. (`CUDA_PATH` is not set in this installation process)

are you fix the error now? i get the same error

**Comment by loadams** [comment]
@amitportnoy  and @susht3 - I'm not sure I understand what your issue is, could you elaborate?

[Here ](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/.github/workflows/nv-torch110-v100.yml#L25C3-L30C1)is the sample of how we install a specific torch/cuda version in our CI tests.

`CUDA_PATH` wont be set in the torch install process, that should be set by the cuda install process.

**Comment by kiddyboots216** [comment]
Hi @loadams getting this warning w fresh install of deepspeed via pip install transformers[deepspeed], here's the output from the things you posted above

```
torch: 2.0.1 <module 'torch' from '/scratch/gpfs/ashwinee/envs/llm/lib/python3.8/site-packages/torch/__init__.py'>
CUDA available: True
```

and this is the output from ds_report

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/scratch/gpfs/ashwinee/envs/llm/lib/python3.8/site-packages/torch']
torch version .................... 2.0.1
deepspeed install path ........... ['/scratch/gpfs/ashwinee/envs/llm/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
shared memory (/dev/shm) size .... 503.50 GB
```

and this is the output after deepspeed.initialize
```
[2023-09-19 12:12:27,640] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.3, git-hash=unknown, git-branch=unknown                                  [1/1880]
[2023-09-19 12:12:27,642] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-19 12:12:27,642] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl                                                         
[2023-09-19 12:12:32,339] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False                                                                       
[2023-09-19 12:12:32,558] [WARNING] [cpu_adam.py:84:__init__] FP16 params for CPUAdam may not work on AMD CPUs                                                                   
[2023-09-19 12:12:32,558] [WARNING] [cpu_adam.py:84:__init__] FP16 params for CPUAdam may not work on AMD CPUs                                                                   
 [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled! [WARNING]  cpu_adam cuda is missing or is incompatible with installed
torch, only cpu ops can be compiled!

Using /home/ashwinee/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/ashwinee/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/ashwinee/.cache/torch_extensions/py38_cu117/cpu_adam/build.ninja...                                                                              
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)                                                                
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 0.864145040512085 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000050, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
[2023-09-19 12:12:34,209] [INFO] [logging.py:96:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adamw as basic optimizer
[2023-09-19 12:12:34,225] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2023-09-19 12:12:34,225] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeed
CPUAdam'>
[2023-09-19 12:12:34,225] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2023-09-19 12:12:34,225] [INFO] [stage_1_and_2.py:146:__init__] Reduce bucket size 200000000
[2023-09-19 12:12:34,225] [INFO] [stage_1_and_2.py:147:__init__] Allgather bucket size 200000000
[2023-09-19 12:12:34,225] [INFO] [stage_1_and_2.py:148:__init__] CPU Offload: True
[2023-09-19 12:12:34,225] [INFO] [stage_1_and_2.py:149:__init__] Round robin gradient partitioning: False
Loading extension module cpu_adam...
Time to load cpu_adam op: 0.9055325984954834 seconds
Adam Optimizer #0 is created with AVX2 arithmetic capability.
Config: alpha=0.000050, betas=(0.900000, 0.999000), weight_decay=0.000000, adam_w=1
Rank: 0 partition count [2] and sizes[(1387535360, False)]
Rank: 1 partition count [2] and sizes[(1387535360, False)]
[2023-09-19 12:12:40,323] [INFO] [utils.py:803:see_memory_usage] Before initializing optimizer states
[2023-09-19 12:12:40,324] [INFO] [utils.py:804:see_memory_usage] MA 5.54 GB         Max_MA 5.54 GB         CA 6.04 GB         Max_CA 6 GB
[2023-09-19 12:12:40,324] [INFO] [utils.py:811:see_memory_usage] CPU Virtual Memory:  used = 49.96 GB, percent = 5.0%
[2023-09-19 12:12:43,823] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 218608
[2023-09-19 12:12:44,781] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 218609
```

so it seems that the warning for cpu_adam cuda is missing is causing the initialization of optimizer states to fail?

**Comment by kiddyboots216** [comment]
> Hi @kiddyboots216 - the warning is thrown from [here ](https://github.com/microsoft/DeepSpeed/blob/78c3b148a8a8b6e60ab77a5c75849961f52b143d/op_builder/builder.py#L341)which is in the op_builder. Can you try, when you install DeepSpeed, running `DS_BUILD_CPU_ADAM=1 pip install deepspeed` so the ops will be pre-compiled and we can debug the error that way?

I tried a few more debugging things but the minimal example I provided above still results in deepspeed killing the subprocess. Let me know if you are able to repro.

**Comment by kiddyboots216** [comment]
Here is an (even more minimal example); this works for '1.3b' but will kill the subprocess for '2.7b' (but I can actually train that 2.7b param model, so I would be surprised if DS somehow can't let me initialize the engine for a 2.7b param model on 2 GPUs). 

```
import argparse 
from transformers import AutoModelForCausalLM
import deepspeed

def main(args):
    model = AutoModelForCausalLM.from_pretrained("facebook/opt-1.3b")
    model_engine, optimizer, _, _ = deepspeed.initialize(args=args,
                                                        model=model)
    print("Done initializing")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_rank', type=int, default=-1,
                    help='local rank passed from distributed launcher')
    # Include DeepSpeed configuration arguments
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()
    main(args)
```

**Comment by kiddyboots216** [comment]
Ok after messing around with some other things and reinstalling (there was some other errors with fusedADAM), I ended up just allocating more CPU memory. It seems that the CPUAdamOps were very memory hungry. Thanks for your help in the installation!

**Comment by loadams** [comment]
Interesting, thanks for the info @kiddyboots216 - could you share how much memory you needed?

**Comment by kiddyboots216** [comment]
> Interesting, thanks for the info @kiddyboots216 - could you share how much memory you needed?

I ended up needing 300G of CPU RAM! Which seemed quite high to me. But 32G didn't work and I kept doubling. If I changed "pin_memory": true -> false under offload_optimizer then I got some other errors due to improperly installed fused adam.

**Comment by wuhongyan123** [comment]
I meet the following error:
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
 [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
Using /root/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Traceback (most recent call last):
  File "/root/data/LMFlow/examples/finetune.py", line 62, in <module>
    main()
  File "/root/data/LMFlow/examples/finetune.py", line 58, in main
    tuned_model = finetuner.tune(model=model, dataset=dataset)
  File "/root/data/LMFlow/src/lmflow/pipeline/finetuner.py", line 298, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1708, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1198, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1254, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
    return self.jit_load(verbose)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
    op_module = load(name=self.name,
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1598, in _write_ninja_file_and_build_library
    get_compiler_abi_compatibility_and_version(compiler)
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 337, in get_compiler_abi_compatibility_and_version
    if not check_compiler_ok_for_platform(compiler):
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 291, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/opt/conda/envs/lmflow/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/lmflow/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f719dc2bb80>
Traceback (most recent call last):
  File "/opt/conda/envs/lmflow/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

How can I solve it?
the env: torch2.0.1+cuda11.7
the system cuda is 12.0

**Comment by loadams** [comment]
@wuhongyan123 - I'm not sure that is the full error, but it looks like something is wrong with your setup, since these errors aren't related to python/DeepSpeed, I'd check that the gcc/g++ compiler is properly installed on your system:

``` 
which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
File "/opt/conda/envs/lmflow/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/opt/conda/envs/lmflow/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
Exception ignored in: <function DeepSpeedCPUAdam.del at 0x7f719dc2bb80>
Traceback (most recent call last):
```

**Comment by Luowaterbi** [comment]
I upgrade deepspeed and this warning disappear.

**Comment by ArianKhorasani** [comment]
Hi @loadams - I'm reopening this issue because I face the same issue and I tried to follow your suggestions above and It's still not working ( I hope I didn't miss anything ) and I appreciate your help! 

I have installed `deepspeed==0.14.2` on my `conda` environment, and here is my `ds_report':

```
[2025-05-01 12:58:35,759] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The default cache directory for DeepSpeed Triton autotune, /home/ariankhorasani.usf/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
evoformer_attn ......... [NO] ....... [OKAY]
fp_quantizer ........... [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['.conda/envs/unlearned/lib/python3.10/site-packages/torch']
torch version .................... 2.1.2+cu121
deepspeed install path ........... ['.conda/envs/unlearned/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.14.2, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.8
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 1007.59 GB
```

Here are the installed packages as well:
The version of `torch == 2.1.2`
The version of `transformers == 4.51.3`
The version of `CUDA == 12.8.93`

Also, I have tried to install deepspeed by launching `DS_BUILD_CPU_ADAM=1 pip install deepspeed=0.14.2` but still see that `CPU_ADAM` is not available for my project! 

I appreciate any feedback!
