### ISSUE TITLE
[BUG] multi gpu inference tensor parallel does not work

### ISSUE THREAD

**Issue by CoinCheung** [microsoft/DeepSpeed#3628]
**Describe the bug**
Deepspeed did not split the model into shards amoung gpus, instead it launches two identical models on two gpus, without saving both gpu memory and cpu memory.

**To Reproduce**
code is like this:
```
import os
import time

import torch
import deepspeed
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM
from transformers import BloomConfig, BloomForCausalLM
from transformers import LlamaForCausalLM, LlamaTokenizer, LlamaConfig



#  model_name = 'bigscience/bloomz-7b1-mt'
model_name = 'decapoda-research/llama-7b-hf'


world_size = int(os.getenv('WORLD_SIZE', '1'))
local_rank = int(os.getenv('LOCAL_RANK', '0'))

config = AutoConfig.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, config=config)
#  tokenizer = LlamaTokenizer.from_pretrained(model_name, config=config)
model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.half,
        low_cpu_mem_usage=True,
)

## ds-inference
infer_config = dict(
        tensor_parallel={'tp_size': world_size},
        dtype=torch.half,
        replace_with_kernel_inject=True,
)
model = deepspeed.init_inference(model, config=infer_config)
model.eval()


prompt = '''Summarize this for a second-grade student:

Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history. It is named after the Roman god Jupiter.[19] When viewed from Earth, Jupiter can be bright enough for its reflected light to cast visible shadows,[20] and is on average the third-brightest natural object in the night sky after the Moon and Venus.'''

for _ in range(50):
    inputs = tokenizer(prompt, return_tensors="pt").to('cuda')
    gen_tokens = model.generate(
        **inputs,
        do_sample=True,
        temperature=0.5,
        max_new_tokens=300,
    )
    gen_text = tokenizer.decode(gen_tokens[0])
    print(gen_text)
```

I run two commands to run this:
```
 deepspeed --num_gpus 4 main.py
```
and 
```
 deepspeed --num_gpus 1 main.py
```

**Expected behavior**
The program with `--num_gpus 1` should use less gpu memory than that with `--num_gpus 4`. I mean that when the first program uses 4G memory on one gpu, the second should use 1G memory on each of the four gpus.

However, it seems that both launch uses same amount of memory on each gpu, that means no tensor parallel is carried out, and each gpu has identical program?

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/miniconda3/lib/python3.8/site-packages/torch']
torch version .................... 1.13.1+cu117
deepspeed install path ........... ['/root/miniconda3/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.9.2, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
```

**Screenshots**

**System info (please complete the following information):**
 - OS:  Ubuntu 18.04
 - GPU count and types  machine with x8 T4 each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using: 0.9.2
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions: 4.29.2
 - Python version: 3.8.15

**Comment by thies1006** [comment]
I think replace_with_kernel_inject=True doesn't work for LLaMa yet.
But you can set it to False, than it works fine (but slower).

**Comment by CoinCheung** [comment]
Hi @thies1006 ,

When I set `replace_with_kernel_inject=False`, I got the following error:
```
Traceback (most recent call last):
  File "infer.py", line 34, in <module>
    model = deepspeed.init_inference(model, config=infer_config)
  File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/__init__.py", line 333, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/inference/engine.py", line 197, in __init__
    parser_dict = AutoTP.tp_parser(model)
  File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/module_inject/auto_tp.py", line 112, in tp_parser
    assert len(policy_list), "AutoTP not supported for model. Please use kernel injection since container policy for model exists." \
AssertionError: Not able to determine model policy automatically. Please provide policy.
[2023-05-30 11:02:25,010] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 141803
[2023-05-30 11:02:25,011] [ERROR] [launch.py:434:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'infer.py', '--local_rank=0'] exits with return code = 1
```

**Comment by thies1006** [comment]
ok, sorry. You need to add the injection policy as well in this case. 
This works for me (note: replace_with_kernel_inject is `False` by default)
```
model = deepspeed.init_inference(model,
                                 dtype=torch.float16,
                                 mp_size=world_size,
                                 injection_policy={LlamaDecoderLayer: ('self_attn.o_proj', 'mlp.down_proj')}
                                 )
```
However, as far as I know, this 'only' does plain tensor parallelism and doesn't use the fused cuda kernels. 
(tested with DeepSpeed v0.9.2)

**Comment by zeyugao** [comment]
You can try this pr for fixed kernel inject https://github.com/microsoft/DeepSpeed/pull/3608. But I can only manage to run correctly on two GPUs with auto tensor parallelism with kernel injected, still debugging about why 4GPUs result in the wrong result.

Moreover, you could install the nightly version of deepspeed for better llama support with `pip install git+https://github.com/microsoft/DeepSpeed`. Which removes the need for suppling `injection_policy` parameter

**Comment by molly-smith** [comment]
Hi @CoinCheung, llama TP support was added in deepspeed v0.9.3 and it looks like you are using deepspeed v0.9.2. I tested your script with latest release and it seems to work. Please try again with a newer version. Thanks.

**Comment by xs1997zju** [comment]
Although set kernel_inject False, the inference speed is slower, but it also much faster than not using tensor paralle QAQ
