### ISSUE TITLE
[BUG] KeyError: 'RANK' in deepspeed/comm/comm.py

### ISSUE THREAD

**Issue by rraminen** [microsoft/DeepSpeed#3660]
This error is caused due to this commit https://github.com/microsoft/DeepSpeed/commit/1f72082fc0ea159d0de46886d8e713dda7df9ce2

os env vars for `RANK ` and `WORLD_SIZE `are defined in `mpi_discovery()`  (https://github.com/microsoft/DeepSpeed/blob/e02b8d0bd06fd5e3d65c4bc410708ee2443334c7/deepspeed/comm/comm.py#L630) in `deepspeed/comm/comm.py`

But using them here https://github.com/microsoft/DeepSpeed/blob/e02b8d0bd06fd5e3d65c4bc410708ee2443334c7/deepspeed/comm/comm.py#L148 before they are defined is causing the below error while running DeepSpeed Hugging Face BERT workloads.

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /workspace/transformers/examples/pytorch/language-modeling/run_mlm.py:618 in │
│ <module>                                                                     │
│                                                                              │
│   615                                                                        │
│   616                                                                        │
│   617 if __name__ == "__main__":                                             │
│ ❱ 618 │   main()                                                             │
│   619                                                                        │
│                                                                              │
│ /workspace/transformers/examples/pytorch/language-modeling/run_mlm.py:226 in │
│ main                                                                         │
│                                                                              │
│   223 │   │   # let's parse it to get our arguments.                         │
│   224 │   │   model_args, data_args, training_args = parser.parse_json_file( │
│   225 │   else:                                                              │
│ ❱ 226 │   │   model_args, data_args, training_args = parser.parse_args_into_ │
│   227 │                                                                      │
│   228 │   # Sending telemetry. Tracking the example usage helps us better al │
│   229 │   # information sent is the one passed as arguments along with your  │
│                                                                              │
│ /workspace/transformers/src/transformers/hf_argparser.py:332 in              │
│ parse_args_into_dataclasses                                                  │
│                                                                              │
│   329 │   │   │   inputs = {k: v for k, v in vars(namespace).items() if k in │
│   330 │   │   │   for k in keys:                                             │
│   331 │   │   │   │   delattr(namespace, k)                                  │
│ ❱ 332 │   │   │   obj = dtype(**inputs)                                      │
│   333 │   │   │   outputs.append(obj)                                        │
│   334 │   │   if len(namespace.__dict__) > 0:                                │
│   335 │   │   │   # additional namespace.                                    │
│ in __init__:109                                                              │
│                                                                              │
│ /workspace/transformers/src/transformers/training_args.py:1166 in            │
│ __post_init__                                                                │
│                                                                              │
│   1163 │   │   if (                                                          │
│   1164 │   │   │   self.framework == "pt"                                    │
│   1165 │   │   │   and is_torch_available()                                  │
│ ❱ 1166 │   │   │   and (self.device.type != "cuda")                          │
│   1167 │   │   │   and (get_xla_device_type(self.device) != "GPU")           │
│   1168 │   │   │   and (self.fp16 or self.fp16_full_eval)                    │
│   1169 │   │   ):                                                            │
│                                                                              │
│ /workspace/transformers/src/transformers/training_args.py:1550 in device     │
│                                                                              │
│   1547 │   │   The device used by this process.                              │
│   1548 │   │   """                                                           │
│   1549 │   │   requires_backends(self, ["torch"])                            │
│ ❱ 1550 │   │   return self._setup_devices                                    │
│   1551 │                                                                     │
│   1552 │   @property                                                         │
│   1553 │   def n_gpu(self):                                                  │
│                                                                              │
│ /workspace/transformers/src/transformers/utils/generic.py:57 in __get__      │
│                                                                              │
│    54 │   │   attr = "__cached_" + self.fget.__name__                        │
│    55 │   │   cached = getattr(obj, attr, None)                              │
│    56 │   │   if cached is None:                                             │
│ ❱  57 │   │   │   cached = self.fget(obj)                                    │
│    58 │   │   │   setattr(obj, attr, cached)                                 │
│    59 │   │   return cached                                                  │
│    60                                                                        │
│                                                                              │
│ /workspace/transformers/src/transformers/training_args.py:1485 in            │
│ _setup_devices                                                               │
│                                                                              │
│   1482 │   │   │   │   raise ImportError("--deepspeed requires deepspeed: `p │
│   1483 │   │   │   import deepspeed                                          │
│   1484 │   │   │                                                             │
│ ❱ 1485 │   │   │   deepspeed.init_distributed(timeout=timedelta(seconds=self │
│   1486 │   │   │                                                             │
│   1487 │   │   │   # workaround for setups like notebooks where the launcher │
│   1488 │   │   │   # but deepspeed requires a dist env.                      │
│                                                                              │
│ /opt/conda/envs/py_3.8/lib/python3.8/site-packages/deepspeed/comm/comm.py:59 │
│ 2 in init_distributed                                                        │
│                                                                              │
│   589 │   │   dist_init_required = cdb is None or not cdb.is_initialized()   │
│   590 │                                                                      │
│   591 │   if cdb is None:                                                    │
│ ❱ 592 │   │   init_deepspeed_backend(get_accelerator().communication_backend │
│   593 │   │   set_backend()                                                  │
│   594 │   │   utils.logger.info(f'cdb={cdb}')                                │
│   595 │   if cdb is None and torch.distributed.is_initialized():             │
│                                                                              │
│ /opt/conda/envs/py_3.8/lib/python3.8/site-packages/deepspeed/comm/comm.py:14 │
│ 8 in init_deepspeed_backend                                                  │
│                                                                              │
│   145 │   global mpi_backend                                                 │
│   146 │   global ccl_backend                                                 │
│   147 │                                                                      │
│ ❱ 148 │   rank = int(os.environ["RANK"])                                     │
│   149 │   size = int(os.environ["WORLD_SIZE"])                               │
│   150 │                                                                      │
│   151 │   if ds_backend == NCCL_BACKEND:                                     │
│                                                                              │
│ /opt/conda/envs/py_3.8/lib/python3.8/os.py:675 in __getitem__                │
│                                                                              │
│    672 │   │   │   value = self._data[self.encodekey(key)]                   │
│    673 │   │   except KeyError:                                              │
│    674 │   │   │   # raise KeyError with the original key value              │
│ ❱  675 │   │   │   raise KeyError(key) from None                             │
│    676 │   │   return self.decodevalue(value)                                │
│    677 │                                                                     │
│    678 │   def __setitem__(self, key, value):                                │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'RANK'

```

**ds_report output:**
Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn is not compatible with ROCM
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch']
torch version .................... 2.0.1+gitcb3d1d0
deepspeed install path ........... ['/opt/conda/envs/py_3.8/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.9.3+e02b8d0b, e02b8d0b, master
torch cuda version ............... None
torch hip version ................ 5.6.31101-0200244fe
nvcc version ..................... None
deepspeed wheel compiled w. ...... torch 2.0, hip 5.6

**Docker image:** rocm/pytorch:latest

**Comment by JamesBonddu** [comment]
```sh
Exception has occurred: KeyError
'RANK'
KeyError: b'RANK'

During handling of the above exception, another exception occurred:

  File "/data/aigc/DeepSpeed/deepspeed/comm/comm.py", line 148, in init_deepspeed_backend
    rank = int(os.environ["RANK"])
  File "/data/aigc/DeepSpeed/deepspeed/comm/comm.py", line 592, in init_distributed
    init_deepspeed_backend(get_accelerator().communication_backend_name(), timeout, init_method)
  File "/data/aigc/Open-Assistant/inference/worker/basic_hf_server.py", line 53, in <module>
    deepspeed.init_distributed("nccl")
KeyError: 'RANK'
```
deepspeed-0.9.3+cd4e473ee

**Comment by rraminen** [comment]
Also, it looks like all the HF Transformer UTs are skipped in the CI checks: https://github.com/microsoft/DeepSpeed/actions/runs/4982041871/jobs/8917134163

**Comment by jithunnair-amd** [comment]
> Also, it looks like all the HF Transformer UTs are skipped in the CI checks: https://github.com/microsoft/DeepSpeed/actions/runs/4982041871/jobs/8917134163
> 
> cc: @jithunnair-amd

Thanks for pointing that out @rraminen. Does that explain why this issue is/was not caught in the CUDA CI runs as well?

cc @loadams

**Comment by delock** [comment]
Hi, @rraminen do you know which launcher is used when this bug is exposed?  Is it default single node launcher or one of PDSH/OpenMPI/MPICH/IMPI launcher?

**Comment by delock** [comment]
Hi @rraminen, does this PR fix the failure you encountered?
https://github.com/microsoft/DeepSpeed/pull/3642

**Comment by rraminen** [comment]
Hi @delock, the fix in https://github.com/microsoft/DeepSpeed/pull/3642 PR works. Thank you.
