### ISSUE TITLE
[BUG] DeepSpeed ZeRO INIT with Stage 3 is failing with device mismatch error in v0.9.3. Works properly with v0.9.2

### ISSUE THREAD

**Issue by pacman100** [microsoft/DeepSpeed#3678]
**Describe the bug**
DeepSpeed ZeRO INIT with Stage 3 is failing with device mismatch error

**To Reproduce**
Run below command:
```
accelerate launch --num_processes=2 --num_machines=1 --machine_rank=0 --mixed_precision=fp16 --use_deepspeed --gradient_accumulation_steps=1 --gradient_clipping=1 --zero3_init_flag=True --zero3_save_16bit_model=True --zero_stage=3 --offload_optimizer_device=none --offload_param_device=none accelerate/src/accelerate/test_utils/scripts/external_deps/test_peak_memory_usage.py --output_dir=/tmp/tmpjw8nujjd --peak_memory_upper_bound=2800 --n_train=160 --n_val=160
```
See the failing slow tests here: https://github.com/huggingface/accelerate/actions/runs/5172590339/jobs/9317076815

**Expected behavior**
Normal training. 

**ds_report output**
```
Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/sourab/miniconda3/envs/ml/lib/python3.10/site-packages/torch']
torch version .................... 2.0.0
deepspeed install path ........... ['/home/sourab/miniconda3/envs/ml/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.9.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
```

**Launcher context**
Accelerate Launcher

**Comment by tjruwase** [comment]
@pacman100, I am trying to run the accelerate tests on my box but running into the following import issues. Can you help?
I presume that I missing some setup steps. Alternatively, you can test the linked PR on your side. Thanks! 

```bash
olruwase@BINGHYPC020:/tmp/accelerate$ make test_deepspeed
python -m pytest -s -v ./tests/deepspeed
=================================================================== test session starts ====================================================================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /opt/conda/bin/python
Setting ds_accelerator to cuda (auto detect)
cachedir: .pytest_cache
Using --randomly-seed=3851049330
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/accelerate/.hypothesis/examples')
rootdir: /tmp/accelerate
plugins: randomly-3.12.0, xdist-3.2.1, forked-1.3.0, pythonpath-0.7.3, cov-2.11.1, hypothesis-4.50.8
collecting ... 2023-06-06 04:23:49.607234: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
collected 0 items / 1 error

========================================================================== ERRORS ==========================================================================
____________________________________________________ ERROR collecting tests/deepspeed/test_deepspeed.py ____________________________________________________
ImportError while importing test module '/tmp/accelerate/tests/deepspeed/test_deepspeed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/deepspeed/test_deepspeed.py:28: in <module>
    from transformers.testing_utils import mockenv_context
/opt/conda/lib/python3.8/site-packages/transformers/testing_utils.py:39: in <module>
    from _pytest.doctest import (
E   ImportError: cannot import name 'Module' from '_pytest.doctest' (/opt/conda/lib/python3.8/site-packages/_pytest/doctest.py)
===================================================================== warnings summary =====================================================================
../../opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:511
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:511: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object,

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:553
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:553: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object,

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:563
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:563: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool,

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:108
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:108: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.object:

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:110
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:110: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.bool:

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

../../opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/numpy_ops/np_random.py:110
  /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/numpy_ops/np_random.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    def randint(low, high=None, size=None, dtype=onp.int):  # pylint: disable=missing-function-docstring

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================= short test summary info ==================================================================
ERROR tests/deepspeed/test_deepspeed.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================== 7 warnings, 1 error in 8.06s ===============================================================
make: *** [Makefile:40: test_deepspeed] Error 2

```

**Comment by pacman100** [comment]
Hello @tjruwase, Thank you so much for the quick PR to resolve the issue. It is working great! All slow tests are passing.
![Screenshot 2023-06-06 at 11 31 17 AM](https://github.com/microsoft/DeepSpeed/assets/13534540/b2309c00-1df9-4f20-8584-19a5c86d805d)

**Comment by 2018211801** [comment]
hello，I'm a little confused, is the problem " https://github.com/huggingface/transformers/issues/24040 " solved?

**Comment by 2018211801** [comment]
> hello，I'm a little confused, is the problem " [huggingface/transformers#24040](https://github.com/huggingface/transformers/issues/24040) " solved?

My problem is solved by your PR,thanks!!!

**Comment by 2018211801** [comment]
Hello,I meet a new issue! Can you help?

Traceback (most recent call last):                                                                                        [10/1911]  File "/mnt/data/wxc/workspace/release/qlora_train.py", line 197, in <module>                                                         train()                                                                                                                          File "/mnt/data/wxc/workspace/release/qlora_train.py", line 191, in train                                                            trainer.train()                                                                                                                  File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1661, in train                      return inner_training_loop(                                                                                                      File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1740, in _inner_training_loop       self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)                                           File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/deepspeed.py", line 343, in deepspeed_init            hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)                                                   AttributeError: 'HfDeepSpeedConfig' object has no attribute 'trainer_config_finalize'

**Comment by 2018211801** [comment]
Hello,I meet a new issue! Can you help?

Traceback (most recent call last):                                                                                        [10/1911]  File "/mnt/data/wxc/workspace/release/qlora_train.py", line 197, in <module>                                                         train()                                                                                                                          File "/mnt/data/wxc/workspace/release/qlora_train.py", line 191, in train                                                            trainer.train()                                                                                                                  File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1661, in train                      return inner_training_loop(                                                                                                      File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1740, in _inner_training_loop       self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)                                           File "/home/wxc/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/deepspeed.py", line 343, in deepspeed_init            hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)                                                   AttributeError: 'HfDeepSpeedConfig' object has no attribute 'trainer_config_finalize'

**Comment by 2018211801** [comment]
hi @loadams ,it is nice to hear your reply! I have opened it in #3733
