### ISSUE TITLE
Could not detect ROCm version

### ISSUE THREAD

**Issue by ZhenyaPav** [microsoft/DeepSpeed#3715]
When trying to install on [this Docker image](ghcr.io/evshiron/rocm_lab:rocm5.5-ub22.04-torch2.0.1), installation fails with the following output:
```
pip install -U deepspeed
Collecting deepspeed
  Using cached deepspeed-0.9.3.tar.gz (807 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      [W interface.cpp:47] Warning: Loading nvfuser library failed with: Error in dlopen: libnvfuser_codegen.so: cannot open shared object file: No such file or directory (function LoadingNvfuserLibrary)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7ixqakoi/deepspeed_9438a1b963954357aaf8943245ca098e/setup.py", line 42, in <module>
          rocm_version = OpBuilder.installed_rocm_version()
        File "/tmp/pip-install-7ixqakoi/deepspeed_9438a1b963954357aaf8943245ca098e/op_builder/builder.py", line 198, in installed_rocm_version
          assert False, "Could not detect ROCm version"
      AssertionError: Could not detect ROCm version
      Setting ds_accelerator to cuda (auto detect)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by sirus20x6** [comment]
I had this and added export ROCM_HOME=/opt/rocm to my .bashrc and restarted my terminal.

**Comment by ZhenyaPav** [comment]
@loadams
`rocm-smi --showhw`
returns
```
======================= ROCm System Management Interface =======================
============================ Concise Hardware Info =============================
GPU  DID   GFX RAS  SDMA RAS  UMC RAS  VBIOS          BUS           
0    744c  N/A      N/A       N/A      113-D70401-00  0000:09:00.0  
================================================================================
============================= End of ROCm SMI Log ==============================
```
Did as @sirus20x6 suggested, the error remained

**Comment by ZhenyaPav** [comment]
I don't think i can reopen the issue

**Comment by ZhenyaPav** [comment]
```
(venv) root@128438a0aebe:~/bark-gui# python -c "import torch; print('torch:', torch.__version__, torch)"
[W interface.cpp:47] Warning: Loading nvfuser library failed with: Error in dlopen: libnvfuser_codegen.so: cannot open shared object file: No such file or directory (function LoadingNvfuserLibrary)
torch: 2.0.1+gitd0d0524 <module 'torch' from '/root/venv/lib/python3.10/site-packages/torch/__init__.py'>
(venv) root@128438a0aebe:~/bark-gui# python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
[W interface.cpp:47] Warning: Loading nvfuser library failed with: Error in dlopen: libnvfuser_codegen.so: cannot open shared object file: No such file or directory (function LoadingNvfuserLibrary)
CUDA available: True
```

**Comment by ZhenyaPav** [comment]
```
(venv) root@bdd90e09ac96:~# pip list
Package               Version
--------------------- ----------------
accelerate            0.20.0.dev0
aiofiles              23.1.0
aiohttp               3.8.4
aiosignal             1.3.1
altair                5.0.1
anyio                 3.7.0
async-timeout         4.0.2
attrs                 23.1.0
auto-gptq             0.2.0+cu117
backoff               2.2.1
bitsandbytes          0.37.2
blinker               1.6.2
Brotli                1.0.9
certifi               2023.5.7
charset-normalizer    3.1.0
chromadb              0.3.26
click                 8.1.3
clickhouse-connect    0.6.2
colorama              0.4.6
coloredlogs           15.0.1
contourpy             1.0.7
cycler                0.11.0
datasets              2.12.0
dill                  0.3.6
duckdb                0.8.1
einops                0.6.1
exceptiongroup        1.1.1
fastapi               0.96.0
ffmpy                 0.3.0
filelock              3.12.0
Flask                 2.3.2
flask-cloudflared     0.0.13
Flask-Compress        1.13
Flask-Cors            3.0.10
flatbuffers           23.5.26
flexgen               0.1.7
fonttools             4.39.4
frozenlist            1.3.3
fsspec                2023.5.0
gradio                3.33.1
gradio_client         0.2.5
h11                   0.14.0
hnswlib               0.7.0
httpcore              0.17.2
httptools             0.5.0
httpx                 0.24.1
huggingface-hub       0.15.1
humanfriendly         10.0
idna                  3.4
itsdangerous          2.1.2
Jinja2                3.1.2
joblib                1.2.0
jsonschema            4.17.3
kiwisolver            1.4.4
linkify-it-py         2.0.2
llama-cpp-python      0.1.57
lz4                   4.3.2
Markdown              3.4.3
markdown-it-py        2.2.0
MarkupSafe            2.1.2
matplotlib            3.7.1
mdit-py-plugins       0.3.3
mdurl                 0.1.2
monotonic             1.6
mpmath                1.3.0
multidict             6.0.4
multiprocess          0.70.14
networkx              3.1
nltk                  3.8.1
numpy                 1.24.3
onnxruntime           1.15.0
orjson                3.9.0
overrides             7.3.1
packaging             23.1
pandas                2.0.2
peft                  0.4.0.dev0
Pillow                9.5.0
pip                   22.0.2
posthog               3.0.1
protobuf              4.23.2
psutil                5.9.5
PuLP                  2.7.0
pulsar-client         3.2.0
pyarrow               12.0.0
pydantic              1.10.9
pydub                 0.25.1
Pygments              2.15.1
pyparsing             3.0.9
pyrsistent            0.19.3
python-dateutil       2.8.2
python-dotenv         1.0.0
python-multipart      0.0.6
pytz                  2023.3
PyYAML                6.0
quant-cuda            0.0.0
regex                 2023.6.3
requests              2.30.0
responses             0.18.0
rouge                 1.0.1
safetensors           0.3.1
scikit-learn          1.2.2
scipy                 1.10.1
semantic-version      2.10.0
sentence-transformers 2.2.2
sentencepiece         0.1.99
setuptools            59.6.0
six                   1.16.0
sniffio               1.3.0
starlette             0.27.0
sympy                 1.11.1
threadpoolctl         3.1.0
tokenizers            0.13.3
toolz                 0.12.0
torch                 2.0.1+gitd0d0524
torchvision           0.15.2+6770a25
tqdm                  4.65.0
transformers          4.30.0.dev0
typing_extensions     4.5.0
tzdata                2023.3
uc-micro-py           1.0.2
urllib3               2.0.2
uvicorn               0.22.0
uvloop                0.17.0
watchfiles            0.19.0
websockets            11.0.3
webuiapi              0.9.3
Werkzeug              2.3.6
xxhash                3.2.0
yarl                  1.9.2
zstandard             0.21.0
```

**Comment by ZhenyaPav** [comment]
After installing official nightly build
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5`
deepspeed installs fine. 
However, when trying to launch text-generation-webui with --deepspeed, it fails to launch with the following error:
```
(venv) root@02ef5556c839:~/text-generation-webui# python server.py --api --listen --deepspeed
[2023-06-16 16:28:02,707] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/root/text-generation-webui/server.py", line 47, in <module>
    from modules import chat, shared, training, ui, utils
  File "/root/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (generate_reply, get_encoded_length,
  File "/root/text-generation-webui/modules/text_generation.py", line 17, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/root/text-generation-webui/modules/models.py", line 32, in <module>
    deepspeed.init_distributed()
  File "/root/venv/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 592, in init_distributed
    init_deepspeed_backend(get_accelerator().communication_backend_name(), timeout, init_method)
  File "/root/venv/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 148, in init_deepspeed_backend
    rank = int(os.environ["RANK"])
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```
