### ISSUE TITLE
[BUG] stage3: `assert len(set(t.device for t in tensors)) == 1`

### ISSUE THREAD

**Issue by tomaslaz** [microsoft/DeepSpeed#3771]
**Describe the bug**

When using stage 3 with FusedAdam optimiser the following error occurs:

```
Traceback (most recent call last):
  File "/home/azureuser/light_gpt_workspace/test/../lightning-GPT/train.py", line 145, in <module>
    main(args)
  File "/home/azureuser/light_gpt_workspace/test/../lightning-GPT/train.py", line 112, in main
    trainer.fit(model, train_loader)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
Traceback (most recent call last):
  File "/home/azureuser/light_gpt_workspace/lightning-GPT/train.py", line 145, in <module>
    call._call_and_handle_interrupt(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 92, in launch
    main(args)
    return function(*args, **kwargs)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
  File "/home/azureuser/light_gpt_workspace/lightning-GPT/train.py", line 112, in main
    trainer.fit(model, train_loader)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    self._run(model, ckpt_path=ckpt_path)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 911, in _run
    call._call_and_handle_interrupt(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    self.strategy.setup(self)
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 344, in setup
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self.init_deepspeed()
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 448, in init_deepspeed
    self._run(model, ckpt_path=ckpt_path)
    self._initialize_deepspeed_train(model)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 911, in _run
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 484, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 413, in _setup_model_and_optimizer
    self.strategy.setup(self)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 344, in setup
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/__init__.py", line 165, in initialize
    self.init_deepspeed()
    engine = DeepSpeedEngine(args=args,
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 448, in init_deepspeed
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1185, in _configure_optimizer
    self._initialize_deepspeed_train(model)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 484, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/lightning/pytorch/strategies/deepspeed.py", line 413, in _setup_model_and_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1475, in _configure_zero_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1185, in _configure_optimizer
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 596, in _create_fp16_partitions_with_defragmentation
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1475, in _configure_zero_optimizer
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 432, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 596, in _create_fp16_partitions_with_defragmentation
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 432, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
``` 

**To Reproduce**

1. Clone https://github.com/tomaslaz/lightning-GPT/tree/Trainer
2. Install dependecies
3. Run:
```
python train.py \
    --implementation mingpt \
    --strategy deepspeed_stage_3 \
    --model_type None \
    --precision 16 \
    --batch_size 64 \
    --n_layer 36 \
    --n_head 20 \
    --n_embd 1280 \
    --num_nodes 1 \
    --devices "auto" \
    --accelerator="gpu" \
    --logger False
```

**Expected behavior**
Initialisation should succeed.

**ds_report output**
```
[2023-06-19 12:43:25,273] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/torch']
torch version .................... 2.0.1+cu118
deepspeed install path ........... ['/home/azureuser/miniconda3/envs/lightGPT/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.9.4, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types: vm with 2x V100-PCIE-16GB 
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version: 3.9.16
 - Any other relevant info about your setup: pip freeze:

```
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.7.0
arrow==1.2.3
async-timeout==4.0.2
attrs==23.1.0
beautifulsoup4==4.12.2
blessed==1.20.0
certifi==2022.12.7
charset-normalizer==2.1.1
click==8.1.3
cmake==3.25.0
croniter==1.3.15
dateutils==0.6.12
deepdiff==6.3.0
deepspeed==0.9.4
exceptiongroup==1.1.1
fastapi==0.88.0
filelock==3.9.0
frozenlist==1.3.3
fsspec==2023.5.0
h11==0.14.0
hjson==3.1.0
idna==3.4
inquirer==3.1.3
itsdangerous==2.1.2
Jinja2==3.1.2
lightning==2.0.2
lightning-cloud==0.5.36
lightning-utilities==0.8.0
lit==15.0.7
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
mpmath==1.2.1
multidict==6.0.4
networkx==3.0
ninja==1.11.1
numpy==1.24.1
ordered-set==4.1.0
packaging==23.1
Pillow==9.3.0
psutil==5.9.5
py-cpuinfo==9.0.0
pydantic==1.10.8
Pygments==2.15.1
PyJWT==2.7.0
python-dateutil==2.8.2
python-editor==1.0.4
python-multipart==0.0.6
pytorch-lightning==2.0.2
pytz==2023.3
PyYAML==6.0
readchar==4.0.5
requests==2.28.1
rich==13.4.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
starlette==0.22.0
starsessions==1.3.0
sympy==1.11.1
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchmetrics==0.11.4
torchvision==0.15.2+cu118
tqdm==4.65.0
traitlets==5.9.0
triton==2.0.0
typing_extensions==4.4.0
urllib3==1.26.13
uvicorn==0.22.0
wcwidth==0.2.6
websocket-client==1.5.2
websockets==11.0.3
yarl==1.9.2
```

**Launcher context**
NA

**Docker context**
NA

**Additional context**
NA

**Comment by kisseternity** [comment]
Hello, I encountered the same error. I guess this is related to ZeRO Offload, as described in https://github.com/microsoft/DeepSpeed/issues/3561 ? I guess it's probably a bug introduced before v0.9.0.
