### ISSUE TITLE
[BUG] Issue with import deepspeed

### ISSUE THREAD

**Issue by agunapal** [microsoft/DeepSpeed#3791]
**Describe the bug**
After installing deepspeed, `import deepspeed` doesn't work because of dependency on `oneccl_bindings_for_pytorch`
This was working fine till yesterday.

**To Reproduce**
1. `python -m pip install deepspeed==0.9.4; python -c "import deepspeed"`

**Expected behavior**
No issue expected

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
(deepspeed) ubuntu@ip-172-31-2-198:~$ ds_report 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepspeed/bin/ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import ops
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/__init__.py", line 6, in <module>
    from . import adam
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/adam/__init__.py", line 6, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 8, in <module>
    from deepspeed.utils import logger
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/utils/__init__.py", line 10, in <module>
    from .groups import *
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/utils/groups.py", line 28, in <module>
    from deepspeed import comm as dist
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/comm/__init__.py", line 7, in <module>
    from .comm import *
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 34, in <module>
    from deepspeed.utils import timer, get_caller_func
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/utils/timer.py", line 21, in <module>
    class CudaEventTimer(object):
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/utils/timer.py", line 23, in CudaEventTimer
    def __init__(self, start_event: get_accelerator().Event, end_event: get_accelerator().Event):
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/accelerator/real_accelerator.py", line 103, in get_accelerator
    from .cpu_accelerator import CPU_Accelerator
  File "/home/ubuntu/anaconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/accelerator/cpu_accelerator.py", line 8, in <module>
    import oneccl_bindings_for_pytorch  # noqa: F401
ModuleNotFoundError: No module named 'oneccl_bindings_for_pytorch'
(deepspeed) ubuntu@ip-172-31-2-198:~$ 

```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04]
 - GPU count and types g5.12xlarge
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version: 3.10
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
N/A
**Docker context**
Are you using a specific docker image that you can share?
N/A
**Additional context**

**Comment by jeffra** [comment]
Interesting error @agunapal, thank you for reporting this. I was able to repro this but with some modifications to the code. Can you tell me if you have `intel_extension_for_pytorch` installed? It looks like this can happen if this import succeeds `intel_extension_for_pytorch` but if `oneccl_bindings_for_pytorch` is not installed.

https://github.com/microsoft/DeepSpeed/blob/master/accelerator/real_accelerator.py#L92-L93

@delock perhaps we should change this import check to ensure _both_ `intel_extension_for_pytorch` and `oneccl_bindings_for_pytorch` are importable?

**Comment by agunapal** [comment]
Great catch! I can confirm I have `intel_extension_for_pytorch`

Once i removed it, it works!
