### ISSUE TITLE
[BUG] Unable to reconstruct full weights from ZeRO-2 checkpoint when layers share weights

### ISSUE THREAD

**Issue by awaelchli** [microsoft/DeepSpeed#3824]
**Describe the bug**
There is an edge case in which a ZeRO-2 checkpoint is missing weights after running it through the `deepspeed.utils.zero_to_fp32.get_fp32_state_dict_from_zero_checkpoint` utility function. Layers that share weights can't be recovered, leading to a missing keys error when calling `model.load_state_dict()`.

**To Reproduce**
Save the below script into a file `repro.py`.
```py
import os
import argparse
import torch
import torch.nn as nn

import deepspeed
from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint


class ModelWithSharedWeights(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer0 = nn.Linear(100, 100)
        self.layer1 = nn.Linear(200, 200)
        self.layer2 = nn.Linear(300, 300)
        # tie layer 1 and layer 2
        self.layer1.weight = self.layer2.weight


config = {
    "train_micro_batch_size_per_gpu": 2,
    "zero_allow_untested_optimizer": True,
    "zero_optimization": {"stage": 2},
}


rank = int(os.environ["LOCAL_RANK"])

torch.cuda.set_device(rank)
model = ModelWithSharedWeights()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

deepspeed_engine, _, _, _ = deepspeed.initialize(
    args=argparse.Namespace(device_rank=rank),
    config=config,
    model=model,
    optimizer=optimizer,
)
deepspeed_engine.save_checkpoint("checkpoints_ds/checkpoint0.pt", tag="checkpoint")

if rank == 0:
    model = ModelWithSharedWeights()
    state_dict = get_fp32_state_dict_from_zero_checkpoint("checkpoints_ds/checkpoint0.pt", tag="checkpoint")

    # Fails with
    # RuntimeError: Error(s) in loading state_dict for ModelWithSharedWeights:
    # Missing key(s) in state_dict: "layer2.weight".
    model.load_state_dict(state_dict)

torch.distributed.barrier()

```
Run this command:
```bash
torchrun --nproc_per_node 2 repro.py
```
Error:
```
Traceback (most recent call last):
  File "/home/adrian/repositories/lightning/repro_ds.py", line 52, in <module>
    model.load_state_dict(state_dict)
  File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2056, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModelWithSharedWeights:
        Missing key(s) in state_dict: "layer2.weight". 
```

**Expected behavior**
The model should load the weights without error.

**ds_report output**

```
Setting ds_accelerator to cuda (auto detect)
Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0+7d1a95b046), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/torch']
torch version .................... 2.1.0.dev20230529+cu118
deepspeed install path ........... ['/home/adrian/repositories/DeepSpeed/deepspeed']
deepspeed info ................... 0.9.4+f483c034, f483c034, master
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.1, cuda 11.8
```

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] Ubuntu 18.04
 - GPU count and types [e.g. two machines with x8 A100s each] 8x A100
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version 3.10
 - Any other relevant info about your setup

**Launcher context**
See command above, it is using torchrun. 

**Docker context**
N/A

**Additional context**

Originally reported in Lightning: https://github.com/Lightning-AI/lightning/issues/15694

**Comment by chiragjn** [comment]
Just ran into the same problem and tried this out. This fixed my issue with `EleutherAI/pythia-6.9b` but not `EleutherAI/pythia-12b` - I am using Zero 2 with optimizer offload to cpu

I'll dive deeper if I find some time later today to try and get the traceback

**Comment by awaelchli** [comment]
@chiragjn Thanks for trying this out. Yes it would be helpful to know whether the new issue you ran into was caused by shared weights or not. The model I tried initially where this showed up was the `MBartForConditionalGeneration` from `transformers` (from user in linked PL issue).

**Comment by chiragjn** [comment]
Seems like deepspeed is not able to collect my embedding layer correctly here 🙃 

```
RuntimeError: Error(s) in loading state_dict for GPTNeoXForCausalLM:
        size mismatch for gpt_neox.embed_in.weight: copying a param with shape torch.Size([50278, 5120]) from checkpoint, the shape in current model is torch.Size([50688, 5120]).
        size mismatch for embed_out.weight: copying a param with shape torch.Size([50278, 5120]) from checkpoint, the shape in current model is torch.Size([50688, 5120])
```

**Comment by awaelchli** [comment]
@chiragjn The error you get is not the same as described here. You are facing a shape mismatch, specifically in the embedding layer. This is likely because you are loading a checkpoint from a different model, or a model trained with a different vocabulary size and not matching the configuration of the architecture. Make sure that these settings are correct before loading the checkpoint. 

I'm not sure what you did, but my guess is that you first encountered the problem I had, then tried my fix and you ran into this shape mismatch that is unrelated to what I'm trying to fix. If you could please confirm.
