### ISSUE TITLE
[BUG] Tring to use zero++  in hf model training 

### ISSUE THREAD

**Issue by Edisonals** [microsoft/DeepSpeed#3827]
deepspeed version == v0.9.5: Patch release
ValidationError: 3 validation errors for DeepSpeedZeroConfig
zero_hpz_partition_size
  extra fields not permitted (type=value_error.extra)
zero_quantized_gradients
  extra fields not permitted (type=value_error.extra)

**Comment by Lihengwannafly** [comment]
```
git clone https://github.com/microsoft/DeepSpeed.git
cd DeepSpeed
pip install .
```
it works.

**Comment by oolongoo** [comment]
get NCCL error with ZeRO++
```json
       # Zero++
        "zero_quantized_weights": true,
        "zero_hpz_partition_size": 4,
        "zero_quantized_gradients": true
```

deepspeed   version:    0.10.0+f8551b43

```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

Error log:
```bash
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166275:167285 [0] include/alloc.h:38 NCCL WARN Cuda failure 'misaligned address'
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166275:167285 [0] NCCL INFO comm 0x7fac8026db10 rank 0 nranks 4 cudaDev 0 busId 80 - Abort COMPLETE

192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166275:167285 [0] include/alloc.h:38 NCCL WARN Cuda failure 'misaligned address'
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166275:167285 [0] NCCL INFO comm 0x7fac8026db10 rank 0 nranks 4 cudaDev 0 busId 80 - Abort COMPLETE
192.168.1.51: 
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166277:167291 [2] include/alloc.h:38 NCCL WARN Cuda failure 'misaligned address'
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166277:167291 [2] NCCL INFO comm 0x7f4dc4197800 rank 2 nranks 4 cudaDev 2 busId a0 - Abort COMPLETE
192.168.1.51: 
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166278:167298 [3] include/alloc.h:38 NCCL WARN Cuda failure 'misaligned address'
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166278:167298 [3] NCCL INFO comm 0x7f5b9c19cbf0 rank 3 nranks 4 cudaDev 3 busId b0 - Abort COMPLETE
192.168.1.51: 
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166276:167284 [1] include/alloc.h:38 NCCL WARN Cuda failure 'misaligned address'
192.168.1.51: iZuf69i4pwuzuijxvre2qmZ:166276:167284 [1] NCCL INFO comm 0x7fa9001285c0 rank 1 nranks 4 cudaDev 1 busId 90 - Abort COMPLETE
192.168.1.51: Traceback (most recent call last):
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 341, in <module>
192.168.1.51:     main()
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 314, in main
192.168.1.51:     model.backward(loss)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
192.168.1.51:     self.optimizer.backward(loss, retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2040, in backward
192.168.1.51:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
192.168.1.51:     scaled_loss.backward(retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
192.168.1.51:     torch.autograd.backward(
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
192.168.1.51: Traceback (most recent call last):
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 341, in <module>
192.168.1.51:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
192.168.1.51: Traceback (most recent call last):
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 341, in <module>
192.168.1.51:     self.reduce_ready_partitions_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1331, in reduce_ready_partitions_and_remove_grads
192.168.1.51: Traceback (most recent call last):
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 341, in <module>
192.168.1.51:     self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1078, in reduce_independent_p_g_buckets_and_remove_grads
192.168.1.51:     self.__reduce_and_partition_ipg_grads()
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1126, in __reduce_and_partition_ipg_grads
192.168.1.51:     grad_partitions = self.__avg_scatter_grads(self.params_in_ipg_bucket)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1192, in __avg_scatter_grads
192.168.1.51:     main()
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 314, in main
192.168.1.51:     grad_partitions_for_rank = all_to_all_quant_reduce(full_grads_for_rank, self.all2all_process_group)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     model.backward(loss)
192.168.1.51:       File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51: ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     main()
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 314, in main
192.168.1.51:     return func(*args, **kwargs)    
192.168.1.51: ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 56, in all_to_all_quant_reduce
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
192.168.1.51:     all_to_all_single(local_output, intra_quant_int4, group=groups[f'local_{intra_idx}'])
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2977, in all_to_all_single
192.168.1.51:     model.backward(loss)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
192.168.1.51:     self.optimizer.backward(loss, retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2040, in backward
192.168.1.51:     self.optimizer.backward(loss, retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2040, in backward
192.168.1.51:         work = group.alltoall_base(
192.168.1.51: main()
192.168.1.51:   File "/mnt/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 314, in main
192.168.1.51: RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1670525541990/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
192.168.1.51: ncclInternalError: Internal check failed.
192.168.1.51: Last error:
192.168.1.51: Failed to CUDA calloc async 1920 bytes
192.168.1.51:     model.backward(loss)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
192.168.1.51:       File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
192.168.1.51: ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
192.168.1.51:     scaled_loss.backward(retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
192.168.1.51:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
192.168.1.51:     torch.autograd.backward(
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
192.168.1.51:     scaled_loss.backward(retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
192.168.1.51:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
192.168.1.51:     torch.autograd.backward(
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
192.168.1.51:     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:       File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
192.168.1.51: self.optimizer.backward(loss, retain_graph=retain_graph)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     self.reduce_ready_partitions_and_remove_grads(param, i)
192.168.1.51:       File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1331, in reduce_ready_partitions_and_remove_grads
192.168.1.51: ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2040, in backward
192.168.1.51:     self.reduce_ready_partitions_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1331, in reduce_ready_partitions_and_remove_grads
192.168.1.51:     self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1078, in reduce_independent_p_g_buckets_and_remove_grads
192.168.1.51:     self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1078, in reduce_independent_p_g_buckets_and_remove_grads
192.168.1.51:         self.__reduce_and_partition_ipg_grads()self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
192.168.1.51: 
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     scaled_loss.backward(retain_graph=retain_graph)    return func(*args, **kwargs)
192.168.1.51: 
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1126, in __reduce_and_partition_ipg_grads
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
192.168.1.51:     self.__reduce_and_partition_ipg_grads()
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     torch.autograd.backward(
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1126, in __reduce_and_partition_ipg_grads
192.168.1.51:         grad_partitions = self.__avg_scatter_grads(self.params_in_ipg_bucket)Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
192.168.1.51: 
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1192, in __avg_scatter_grads
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1043, in reduce_partition_and_remove_grads
192.168.1.51:     grad_partitions = self.__avg_scatter_grads(self.params_in_ipg_bucket)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1192, in __avg_scatter_grads
192.168.1.51:     grad_partitions_for_rank = all_to_all_quant_reduce(full_grads_for_rank, self.all2all_process_group)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 56, in all_to_all_quant_reduce
192.168.1.51:     self.reduce_ready_partitions_and_remove_grads(param, i)
192.168.1.51:       File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1331, in reduce_ready_partitions_and_remove_grads
192.168.1.51: all_to_all_single(local_output, intra_quant_int4, group=groups[f'local_{intra_idx}'])
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2977, in all_to_all_single
192.168.1.51:     grad_partitions_for_rank = all_to_all_quant_reduce(full_grads_for_rank, self.all2all_process_group)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 56, in all_to_all_quant_reduce
192.168.1.51:     all_to_all_single(local_output, intra_quant_int4, group=groups[f'local_{intra_idx}'])
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2977, in all_to_all_single
192.168.1.51:     self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1078, in reduce_independent_p_g_buckets_and_remove_grads
192.168.1.51:     work = group.alltoall_base(
192.168.1.51: RuntimeError    : self.__reduce_and_partition_ipg_grads()NCCL error in: /opt/conda/conda-bld/pytorch_1670525541990/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
192.168.1.51: ncclInternalError: Internal check failed.
192.168.1.51: Last error:
192.168.1.51: Failed to CUDA calloc async 1920 bytes
192.168.1.51: 
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1126, in __reduce_and_partition_ipg_grads
192.168.1.51:     work = group.alltoall_base(
192.168.1.51: RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1670525541990/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
192.168.1.51: ncclInternalError: Internal check failed.
192.168.1.51: Last error:
192.168.1.51: Failed to CUDA calloc async 1920 bytes
192.168.1.51:     grad_partitions = self.__avg_scatter_grads(self.params_in_ipg_bucket)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1192, in __avg_scatter_grads
192.168.1.51:     grad_partitions_for_rank = all_to_all_quant_reduce(full_grads_for_rank, self.all2all_process_group)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
192.168.1.51:     ret_val = func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
192.168.1.51:     return func(*args, **kwargs)
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 56, in all_to_all_quant_reduce
192.168.1.51:     all_to_all_single(local_output, intra_quant_int4, group=groups[f'local_{intra_idx}'])
192.168.1.51:   File "/opt/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2977, in all_to_all_single
192.168.1.51:     work = group.alltoall_base(
192.168.1.51: RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1670525541990/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
192.168.1.51: ncclInternalError: Internal check failed.
192.168.1.51: Last error:
192.168.1.51: Failed to CUDA calloc async 1920 bytes
```
