### ISSUE TITLE
[BUG] AdamW expects BFloat16, but found Float using mixed precision and accelerate

### ISSUE THREAD

**Issue by rostro36** [microsoft/DeepSpeed#3853]
**Describe the bug**
Backward pass found dtype Float but expected BFloat16.

When training my model through accelerate and bfloat16 mixed precision, the PyTorch AdamW optimizer I have given to accelerate does not work in the backwards pass. For ZeRO-Stage 0,1 and 2.

Bfloat16 is also logged as enabled.

I don't know if the error is on my side, as I have to cast input.bfloat16() in my model.

Let me know if you need more information and thanks for your help :)
<details>
  <summary>Traceback</summary>
  
```
Traceback (most recent call last):
  File "/home/jgut/GitHub/test-diffusion/accelerator_file.py", line 64, in <module>
    main()
  File "/home/jgut/GitHub/test-diffusion/accelerator_file.py", line 51, in main
    accelerator.backward(loss.bfloat16())
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/accelerate/accelerator.py", line 1815, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1874, in backward
    self.optimizer.backward(loss)
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/deepspeed/runtime/bf16_optimizer.py", line 267, in backward
    loss.backward(**bwd_kwargs)
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Float but expected BFloat16
```
</details>

<details>
  <summary>cut accelerator_file.py</summary>
  
```
from accelerate import Accelerator
from torch.optim import AdamW

def main():
    accelerator = Accelerator(log_with="wandb", gradient_accumulation_steps=4)
    model = model(init_args)
    training_dataloader = get_data_loader(batch_size=int(args.batchsize))
    optimizer = AdamW(model.parameters(),float(args.learningrate), betas=(0.9, 0.999), eps=1e-08, weight_decay=float(args.weightdecay))
    (model, optimizer, training_dataloader,) = accelerator.prepare(
        model,
        optimizer,
        training_dataloader,
    )
    for epoch in range(int(args.epochs)):
        for step, batch in enumerate(training_dataloader):
            optimizer.zero_grad()
            input, masks, guidances = batch
            loss = model(input, masks, guidances)
            accelerator.backward(loss.bfloat16())
            optimizer.step()
           
        global_steps += step

if __name__ == "__main__":
    main()
```
</details>

<details>
  <summary>accelerate_config.yaml</summary>
  
```
compute_environment: LOCAL_MACHINE                                                                            
deepspeed_config:
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 0
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
</details>

**To Reproduce**
1. Put `accelerate_config.yaml`, `accelerator_file.py` in place
2. Run the SLURM command: `srun accelerate launch --config_file accelerate_config.yaml accelerator_file.py`

**Expected behavior**
Backward pass to work properly with bfloat16.

**ds_report output**
<details>
  <summary>ds_report output</summary>
  
```
[2023-06-30 10:50:31,570] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/torch']
torch version .................... 2.0.1
deepspeed install path ........... ['/home/jgut/.conda/envs/test_diff/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.9.5, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```
</details>

**System info:**
 - OS: Rocky Linux 8 (RHEL 8)
 - GPU count and types SLURM setup with multiple A100s, one requested
 - Python version 3.11
 - Any other relevant info about your setup SLURM

**Launcher context**
Accelerate launcher through SLURM.

**Additional context**
Before coming to this point, I installed apex and xformers in another conda environment.

**Comment by rostro36** [comment]
Upon going over the model again, I found that the input to `F.mse_loss` and therefore also the output was float32. This was the root of my problem it is now solved.

The error was on my side; sorry for the inconvenience.

**Comment by wk989898** [comment]
I have the same problem, how to solve it? @rostro36
