### ISSUE TITLE
[BUG] Zero3 and Zero2 offload not working 

### ISSUE THREAD

**Issue by pchiang5** [microsoft/DeepSpeed#3869]
**Describe the bug**
I tried the offload function of zero3 and zero2 with the `transformers-bloom-inference`.
It went well with smaller datasets (fit VRAM) like mt0-small, but the following error jumped out with the larger dataset (mt0-xl)

**To Reproduce**
`deepspeed --num_gpus 1 bloom-inference-scripts/bloom-ds-zero-inference.py --name bigscience/mt0-xl --batch_size 8 --cpu_offload --benchmark`
**Expected behavior**
`deepspeed --num_gpus 1 bloom-inference-scripts/bloom-ds-zero-inference.py --name bigscience/mt0-xl --batch_size 8 --cpu_offload --benchmark` reach the end like with smaller models but the counterpart `deepspeed --num_gpus 1 bloom-inference-scripts/bloom-ds-zero-inference.py --name bigscience/mt0-xl --batch_size 8  --benchmark`  will not

**ds_report output**

> [2023-07-04 17:38:21,535] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> --------------------------------------------------
> DeepSpeed C++/CUDA extension op report
> --------------------------------------------------
> NOTE: Ops not installed will be just-in-time (JIT) compiled at
>       runtime if needed. Op compatibility means that your system
>       meet the required dependencies to JIT install the op.
> --------------------------------------------------
> JIT compiled ops requires ninja
> ninja .................. [OKAY]
> --------------------------------------------------
> op name ................ installed .. compatible
> --------------------------------------------------
> async_io ............... [YES] ...... [OKAY]
> cpu_adagrad ............ [YES] ...... [OKAY]
> cpu_adam ............... [YES] ...... [OKAY]
> fused_adam ............. [YES] ...... [OKAY]
> fused_lamb ............. [YES] ...... [OKAY]
> quantizer .............. [YES] ...... [OKAY]
> random_ltd ............. [YES] ...... [OKAY]
>  [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
>  [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
> sparse_attn ............ [NO] ....... [NO]
> spatial_inference ...... [YES] ...... [OKAY]
> transformer ............ [YES] ...... [OKAY]
> stochastic_transformer . [YES] ...... [OKAY]
> transformer_inference .. [YES] ...... [OKAY]
> --------------------------------------------------
> DeepSpeed general environment info:
> torch install path ............... ['/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch']
> torch version .................... 2.0.1+cu117
> deepspeed install path ........... ['/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed']
> deepspeed info ................... 0.9.5, unknown, unknown
> torch cuda version ............... 11.7
> torch hip version ................ None
> nvcc version ..................... 11.7
> deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
> 

**Screenshots**

> 
> [2023-07-04 17:30:35,469] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2023-07-04 17:30:36,186] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
> [2023-07-04 17:30:36,204] [INFO] [runner.py:555:main] cmd = /home/pc/miniconda3/envs/Transformers/bin/python3.11 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None bloom-inference-scripts/bloom-ds-zero-inference.py --name bigscience/mt0-xl --batch_size 8 --cpu_offload --benchmark
> [2023-07-04 17:30:38,008] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2023-07-04 17:30:38,745] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
> [2023-07-04 17:30:38,745] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
> [2023-07-04 17:30:38,745] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
> [2023-07-04 17:30:38,745] [INFO] [launch.py:163:main] dist_world_size=1
> [2023-07-04 17:30:38,745] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
> [2023-07-04 17:30:40,525] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> [2023-07-04 17:30:41,226] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
> [2023-07-04 17:30:41,226] [INFO] [comm.py:594:init_distributed] cdb=None
> [2023-07-04 17:30:41,226] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
> *** Loading the model bigscience/mt0-xl
> [2023-07-04 17:30:42,495] [INFO] [utils.py:785:see_memory_usage] pre-from-pretrained
> [2023-07-04 17:30:42,495] [INFO] [utils.py:786:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 0.0 GB         Max_CA 0 GB
> [2023-07-04 17:30:42,496] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 68.04 GB, percent = 30.9%
> [2023-07-04 17:30:50,003] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 3.74B parameters
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:25<00:00, 12.92s/it]
> [2023-07-04 17:31:16,710] [INFO] [utils.py:785:see_memory_usage] post-from-pretrained
> [2023-07-04 17:31:16,711] [INFO] [utils.py:786:see_memory_usage] MA 0.0 GB         Max_MA 1.91 GB         CA 2.87 GB         Max_CA 3 GB
> [2023-07-04 17:31:16,712] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 80.97 GB, percent = 36.8%
> {'fp16': {'enabled': True}, 'bf16': {'enabled': False}, 'zero_optimization': {'stage': 3, 'overlap_comm': True, 'contiguous_gradients': True, 'reduce_bucket_size': 4194304, 'stage3_prefetch_bucket_size': 3774873.6, 'stage3_param_persistence_threshold': 0, 'offload_param': {'device': 'cpu', 'pin_memory': False}}, 'steps_per_print': 2000, 'train_batch_size': 1, 'train_micro_batch_size_per_gpu': 1, 'stage3_max_live_parameters': 100000000.0, 'sub_group_size': 100000000.0, 'stage3_max_reuse_distance': 100000000.0, 'wall_clock_breakdown': False}
> [2023-07-04 17:31:16,715] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.5, git-hash=unknown, git-branch=unknown
> [2023-07-04 17:31:16,744] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
> [2023-07-04 17:31:16,749] [INFO] [logging.py:96:log_dist] [Rank 0] Creating ZeRO Offload
> [2023-07-04 17:31:16,836] [INFO] [utils.py:785:see_memory_usage] DeepSpeedZeRoOffload initialize [begin]
> [2023-07-04 17:31:16,836] [INFO] [utils.py:786:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 2.87 GB         Max_CA 3 GB
> [2023-07-04 17:31:16,837] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 80.97 GB, percent = 36.8%
> Parameter Offload: Total persistent parameters: 0 in 0 params
> [2023-07-04 17:31:16,978] [INFO] [utils.py:785:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
> [2023-07-04 17:31:16,979] [INFO] [utils.py:786:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 2.87 GB         Max_CA 3 GB
> [2023-07-04 17:31:16,979] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 80.97 GB, percent = 36.8%
> [2023-07-04 17:31:16,981] [INFO] [config.py:960:print] DeepSpeedEngine configuration:
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   activation_checkpointing_config  {
>     "partition_activations": false,
>     "contiguous_memory_optimization": false,
>     "cpu_checkpointing": false,
>     "number_checkpoints": null,
>     "synchronize_checkpoint_boundary": false,
>     "profile": false
> }
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   amp_enabled .................. False
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   amp_params ................... False
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   autotuning_config ............ {
>     "enabled": false,
>     "start_step": null,
>     "end_step": null,
>     "metric_path": null,
>     "arg_mappings": null,
>     "metric": "throughput",
>     "model_info": null,
>     "results_dir": "autotuning_results",
>     "exps_dir": "autotuning_exps",
>     "overwrite": true,
>     "fast": true,
>     "start_profile_step": 3,
>     "end_profile_step": 5,
>     "tuner_type": "gridsearch",
>     "tuner_early_stopping": 5,
>     "tuner_num_trials": 50,
>     "model_info_path": null,
>     "mp_size": 1,
>     "max_train_batch_size": null,
>     "min_train_batch_size": 1,
>     "max_train_micro_batch_size_per_gpu": 1.024000e+03,
>     "min_train_micro_batch_size_per_gpu": 1,
>     "num_tuning_micro_batch_sizes": 3
> }
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   bfloat16_enabled ............. False
> [2023-07-04 17:31:16,982] [INFO] [config.py:964:print]   checkpoint_parallel_write_pipeline  False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   checkpoint_tag_validation_enabled  True
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   checkpoint_tag_validation_fail  False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7f8945db8510>
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   communication_data_type ...... None
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   curriculum_enabled_legacy .... False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   curriculum_params_legacy ..... False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   data_efficiency_config ....... {'enabled': False, 'seed': 1234, 'data_sampling': {'enabled': False, 'num_epochs': 1000, 'num_workers': 0, 'curriculum_learning': {'enabled': False}}, 'data_routing': {'enabled': False, 'random_ltd': {'enabled': False, 'layer_token_lr_schedule': {'enabled': False}}}}
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   data_efficiency_enabled ...... False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   dataloader_drop_last ......... False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   disable_allgather ............ False
> [2023-07-04 17:31:16,983] [INFO] [config.py:964:print]   dump_state ................... False
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   dynamic_loss_scale_args ...... None
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_enabled ........... False
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_gas_boundary_resolution  1
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_layer_name ........ bert.encoder.layer
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_layer_num ......... 0
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_max_iter .......... 100
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_stability ......... 1e-06
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_tol ............... 0.01
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   eigenvalue_verbose ........... False
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   elasticity_enabled ........... False
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   flops_profiler_config ........ {
>     "enabled": false,
>     "recompute_fwd_factor": 0.0,
>     "profile_step": 1,
>     "module_depth": -1,
>     "top_modules": 1,
>     "detailed": true,
>     "output_file": null
> }
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   fp16_auto_cast ............... False
> [2023-07-04 17:31:16,984] [INFO] [config.py:964:print]   fp16_enabled ................. True
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   fp16_master_weights_and_gradients  False
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   global_rank .................. 0
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   grad_accum_dtype ............. None
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   gradient_accumulation_steps .. 1
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   gradient_clipping ............ 0.0
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   gradient_predivide_factor .... 1.0
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   hybrid_engine ................ enabled=False max_out_tokens=512 inference_tp_size=1 release_inference_cache=False pin_parameters=True tp_gather_partition_size=8
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   initial_dynamic_scale ........ 65536
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   load_universal_checkpoint .... False
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   loss_scale ................... 0
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   memory_breakdown ............. False
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   mics_hierarchial_params_gather  False
> [2023-07-04 17:31:16,985] [INFO] [config.py:964:print]   mics_shard_size .............. -1
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   monitor_config ............... tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed') csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') enabled=False
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   nebula_config ................ {
>     "enabled": false,
>     "persistent_storage_path": null,
>     "persistent_time_interval": 100,
>     "num_of_version_in_retention": 2,
>     "enable_nebula_load": true,
>     "load_path": null
> }
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   optimizer_legacy_fusion ...... False
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   optimizer_name ............... None
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   optimizer_params ............. None
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   pld_enabled .................. False
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   pld_params ................... False
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   prescale_gradients ........... False
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   scheduler_name ............... None
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   scheduler_params ............. None
> [2023-07-04 17:31:16,986] [INFO] [config.py:964:print]   sparse_attention ............. None
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   sparse_gradients_enabled ..... False
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   steps_per_print .............. 2000
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   train_batch_size ............. 1
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   train_micro_batch_size_per_gpu  1
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   use_node_local_storage ....... False
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   wall_clock_breakdown ......... False
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   world_size ................... 1
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   zero_allow_untested_optimizer  False
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   zero_config .................. stage=3 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=4194304 allgather_partitions=True allgather_bucket_size=500,000,000 overlap_comm=True load_from_fp32_weights=True elastic_checkpoint=False offload_param=DeepSpeedZeroOffloadParamConfig(device='cpu', nvme_path=None, buffer_count=5, buffer_size=100,000,000, max_in_cpu=1,000,000,000, pin_memory=False) offload_optimizer=None sub_group_size=1,000,000,000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=3774873 param_persistence_threshold=0 model_persistence_threshold=sys.maxsize max_live_parameters=1,000,000,000 max_reuse_distance=1,000,000,000 gather_16bit_weights_on_model_save=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False mics_shard_size=-1 mics_hierarchical_params_gather=False memory_efficient_linear=True
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   zero_enabled ................. True
> [2023-07-04 17:31:16,987] [INFO] [config.py:964:print]   zero_force_ds_cpu_optimizer .. True
> [2023-07-04 17:31:16,988] [INFO] [config.py:964:print]   zero_optimization_stage ...... 3
> [2023-07-04 17:31:16,988] [INFO] [config.py:950:print_user_config]   json = {
>     "fp16": {
>         "enabled": true
>     },
>     "bf16": {
>         "enabled": false
>     },
>     "zero_optimization": {
>         "stage": 3,
>         "overlap_comm": true,
>         "contiguous_gradients": true,
>         "reduce_bucket_size": 4.194304e+06,
>         "stage3_prefetch_bucket_size": 3.774874e+06,
>         "stage3_param_persistence_threshold": 0,
>         "offload_param": {
>             "device": "cpu",
>             "pin_memory": false
>         }
>     },
>     "steps_per_print": 2.000000e+03,
>     "train_batch_size": 1,
>     "train_micro_batch_size_per_gpu": 1,
>     "stage3_max_live_parameters": 1.000000e+08,
>     "sub_group_size": 1.000000e+08,
>     "stage3_max_reuse_distance": 1.000000e+08,
>     "wall_clock_breakdown": false
> }
> [2023-07-04 17:31:17,084] [INFO] [utils.py:785:see_memory_usage] start-of-generate
> [2023-07-04 17:31:17,084] [INFO] [utils.py:786:see_memory_usage] MA 0.0 GB         Max_MA 0.0 GB         CA 2.87 GB         Max_CA 3 GB
> [2023-07-04 17:31:17,085] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 80.97 GB, percent = 36.8%
> *** Starting to generate 100 tokens with bs=8
> Generate args {'max_new_tokens': 100, 'do_sample': False}
> *** Running generate
> Invalidate trace cache @ step 0: expected module 2, but got module 0
> Traceback (most recent call last):
>   File "/home/pc/transformers-bloom-inference/bloom-inference-scripts/bloom-ds-zero-inference.py", line 188, in <module>
>     pairs = generate()
>             ^^^^^^^^^^
>   File "/home/pc/transformers-bloom-inference/bloom-inference-scripts/bloom-ds-zero-inference.py", line 173, in generate
>     outputs = model.generate(**input_tokens, **generate_kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/generation/utils.py", line 1522, in generate
>     return self.greedy_search(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/generation/utils.py", line 2339, in greedy_search
>     outputs = self(
>               ^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
>     result = forward_call(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/models/mt5/modeling_mt5.py", line 1753, in forward
>     decoder_outputs = self.decoder(
>                       ^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
>     result = forward_call(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/models/mt5/modeling_mt5.py", line 1062, in forward
>     layer_outputs = layer_module(
>                     ^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
>     result = forward_call(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/models/mt5/modeling_mt5.py", line 617, in forward
>     hidden_states = self.layer[-1](hidden_states)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
>     result = forward_call(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/models/mt5/modeling_mt5.py", line 202, in forward
>     forwarded_states = self.DenseReluDense(forwarded_states)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
>     result = forward_call(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/transformers/models/mt5/modeling_mt5.py", line 169, in forward
>     hidden_gelu = self.act(self.wi_0(hidden_states))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     result = hook(self, args)
>              ^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 371, in _pre_forward_module_hook
>     self.pre_sub_module_forward_function(module)
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 483, in pre_sub_module_forward_function
>     param_coordinator.fetch_sub_module(sub_module)
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 338, in fetch_sub_module
>     self.__all_gather_params(params_to_prefetch)
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 386, in __all_gather_params
>     handle = partitioned_params[0].all_gather_coalesced(partitioned_params)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 899, in all_gather_coalesced
>     return _no_gather_coalesced(params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 612, in _no_gather_coalesced
>     return NoGatherCoalescedHandle(params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pc/miniconda3/envs/Transformers/lib/python3.11/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 66, in __init__
>     param.data = param.ds_tensor.data.to(device=get_accelerator().current_device_name(),
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 978.00 MiB (GPU 0; 4.00 GiB total capacity; 1.68 GiB already allocated; 0 bytes free; 2.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> [2023-07-04 17:31:27,755] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 953850
> [2023-07-04 17:31:27,755] [ERROR] [launch.py:321:sigkill_handler] ['/home/pc/miniconda3/envs/Transformers/bin/python3.11', '-u', 'bloom-inference-scripts/bloom-ds-zero-inference.py', '--local_rank=0', '--name', 'bigscience/mt0-xl', '--batch_size', '8', '--cpu_offload', '--benchmark'] exits with return code = 1
> 

**System info (please complete the following information):**
 - OS: [WSL2, Ubuntu 20.04]
 - GPU count and types [GTX1650 4G]
 
 - Python 3.11.4
 - Any other relevant info about your setup

**Launcher context**
deepspeed

**Docker context**
Are you using a specific docker image that you can share? No

**Additional context**

**Comment by pchiang5** [comment]
resolved by #2977
