### ISSUE TITLE
[BUG] When exec deepspeedchat step3_rlhf_finetuning training with config zero3, hybrid_engine, There is deepspeed   init error. The traceback info is "deepspeed/module_inject/containers/llama.py   get_hidden_heads   self.client_module.self_attn.q_proj.weight.shape[1],  IndexError: tuple index out of range   " 

### ISSUE THREAD

**Issue by stevewein** [microsoft/DeepSpeed#3937]
**Describe the bug**
When exec deepspeedchat step3_rlhf_finetuning training with config zero3, hybrid_engine, There is deepspeed   init error. The traceback info is "deepspeed/module_inject/containers/llama.py  line 119, in get_hidden_heads     return self.client_module.self_attn.q_proj.weight.shape[1], \ Traceback (most recent call last):  " 

**To Reproduce**
 deepspeed --master_port 12449 main.py \
   --data_path    Dahoas/rm-static    \
   --data_split 499,499,2 \
   --actor_model_name_or_path $ACTOR_MODEL_PATH \
   --critic_model_name_or_path $CRITIC_MODEL_PATH \
   --num_padding_at_beginning 0 \
   --actor_weight_decay 0.\
   --critic_weight_decay 0. \
   --per_device_train_batch_size 3 \
   --per_device_mini_train_batch_size 3 \
   --generation_batch_numbers 1 \
   --ppo_epochs 1 \
   --max_answer_seq_len 1024 \
   --max_prompt_seq_len 1024 \
   --actor_learning_rate ${Actor_Lr} \
   --critic_learning_rate ${Critic_Lr} \
   --num_train_epochs 1 \
   --lr_scheduler_type cosine \
   --gradient_accumulation_steps 1 \
   --num_warmup_steps 10 \
   --deepspeed --seed 1234 \
   --inference_tp_size 1 \
   --enable_hybrid_engine \
   --actor_zero_stage $ACTOR_ZERO_STAGE \
   --critic_zero_stage $CRITIC_ZERO_STAGE \
   --actor_gradient_checkpointing \
   --critic_gradient_checkpointing \
   --disable_actor_dropout \
   --offload_reference_model \
   --actor_lora_dim 128 \
   --actor_lora_module_name layers \
   --critic_lora_dim 128 \
   --critic_lora_module_name layers \
   --output_dir $OUTPUT \
    &> $OUTPUT/training.log

**Expected behavior**
train   successfully

**ds_report output**
 
   actor_engine, *_ = deepspeed.initialize(model=actor_model,
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/__init__.py", line 153, in initialize
    engine = DeepSpeedHybridEngine(args=args,
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 52, in __init__
    self.create_inference_module()
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 359, in create_inference_module
    self.create_inference_containers(self.module)
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 308, in create_inference_containers
    self.create_inference_containers(child, layer_id=layer_id)
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 308, in create_inference_containers
    self.create_inference_containers(child, layer_id=layer_id)
Traceback (most recent call last):
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 288, in create_inference_containers
    self._inference_containers.append(self.inference_policies[child.__class__][0](
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/runtime/hybrid_engine.py", line 109, in new_inference_container
    _container.create_ds_model_config()
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/module_inject/containers/base.py", line 84, in create_ds_model_config
    self.set_hidden_heads(*self.policy.get_hidden_heads())
  File "/opt/conda/envs/deepspeed_095/lib/python3.10/site-packages/deepspeed/module_inject/containers/llama.py", line 119, in get_hidden_heads
    return self.client_module.self_attn.q_proj.weight.shape[1], \
Traceback (most recent call last):
IndexError: tuple index out of range

 
```[tasklist]
### Tasks
```

**Comment by Charlie-Xiaoqi** [comment]
Same error, anyone looking at this?

**Comment by Charlie-Xiaoqi** [comment]
Same error, anyone find out why?

**Comment by sarahpannn** [comment]
I am also experiencing this issue. Is there a solution?

**Comment by shyustc** [comment]
same issue here
