### ISSUE TITLE
[BUG] deepspeed ignores transformers library in venv, uses system transformers instead

### ISSUE THREAD

**Issue by moruga123** [microsoft/DeepSpeed#3941]
**Describe the bug**
deepspeed ignores transformers library in venv, uses system transformers instead. Using huggingface Trainer. Launching with: deepspeed training.py

Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
  File "/home/ubuntu/project/openalpaca_training/training.py", line 6, in <module>
        from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfigfrom transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

ImportErrorImportError: : cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)cannot import name 'LlamaTokenizer' from 'transformers' (/home/ubuntu/.local/lib/python3.10/site-packages/transformers/__init__.py)

The above error is a common error when the transformers library is too old. Within the venv, I installed the latest transformers via

but when I invoke the training in the venv with deepspeed like this:

deepspeed training.py

It gives the error message.

When I invoke the script with ( python3 training.py ), it proceeds without errors.

**To Reproduce**
Run: deepspeed training.py

**Expected behavior**
It should use the transformers library that is in the venv.

**ds_report output**
[2023-07-13 00:26:45,791] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ubuntu/venvs/qlora/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/ubuntu/venvs/qlora/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/venvs/qlora/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/home/ubuntu/venvs/qlora/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.9.5, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7

**System info (please complete the following information):**
 - OS: Ubuntu
 - GPU count and types: x8 A100
 - Interconnects (if applicable) 
 - Python version: 3.10.6

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
deepspeed launcher

**Comment by moruga123** [comment]
This problem disappeared after reloading the environment (starting from new ssh session). This can be closed.
