### ISSUE TITLE
[BUG] LLaMA2 - TypeError: multi_tensor_adam(): incompatible function arguments 

### ISSUE THREAD

**Issue by ikergarcia1996** [microsoft/DeepSpeed#4024]
**Describe the bug**
I am trying to use Deespeed to train LLaMA2-7B with the Huggingface Trainer. 

**To Reproduce**
The full traceback is here
```
Invoked with: 65536, tensor([0], device='cuda:1', dtype=torch.int32), [[tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:1')], [tensor([-0.0193,  0.0586,  0.0036,  ..., -0.0147, -0.0059, -0.0038],
       device='cuda:1')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:1')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:1')]], '1e-5', 0.9, 0.999, 1e-08, 1, 1, 1, 0
Traceback (most recent call last):
  File "/ikerlariak/igarcia945/ll/src/run.py", line 291, in <module>
    train_model(
  File "/ikerlariak/igarcia945/ll/src/run.py", line 121, in train_ll
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/transformers/trainer.py", line 1526, in train
    return inner_training_loop(
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/transformers/trainer.py", line 1646, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1209, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1505, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 322, in __init__
    self._setup_for_real_optimizer()
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 419, in _setup_for_real_optimizer
    self.initialize_optimizer_states()
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 929, in initialize_optimizer_states
    self._optimizer_step(i)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 854, in _optimizer_step
    self.optimizer.step()
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 191, in step
    multi_tensor_applier(self.multi_tensor_adam, self._dummy_overflow_buf, [g_32, p_32, m_32, v_32],
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/deepspeed/ops/adam/multi_tensor_apply.py", line 17, in __call__
    return op(self.chunk_size, noop_flag_buffer, tensor_lists, *args)
TypeError: multi_tensor_adam(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: torch.Tensor, arg2: List[List[torch.Tensor]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, arg8: int, arg9: int, arg10: float) -> None

Invoked with: 65536, tensor([0], device='cuda:0', dtype=torch.int32), [[tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')], [tensor([ 1.2517e-06, -1.7881e-06, -4.3511e-06,  ...,  1.1826e-03,
        -7.2327e-03, -1.1719e-02], device='cuda:0')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')]], '1e-5', 0.9, 0.999, 1e-08, 1, 1, 1, 0
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2161225 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2161224) of binary: /ikerlariak/osainz006/venvs/ll/bin/python
Traceback (most recent call last):
  File "/ikerlariak/osainz006/venvs/ll/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0.dev20230523+cu117', 'console_scripts', 'torchrun')())
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/ikerlariak/osainz006/venvs/ll/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-24_13:20:22
  host      : u036042.si.ehu.es
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2161224)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

The DeeSpeed config I am using is the following one:
```
{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupDecayLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto",
      "warmup_type": "cosine",
      "total_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

**ds_report output**
```
[2023-07-24 13:30:47,174] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0+7d1a95b046), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/torch']
torch version .................... 2.1.0.dev20230523+cu117
deepspeed install path ........... ['/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.10.1+23a11a39, 23a11a39, master
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.1, cuda 11.7
shared memory (/dev/shm) size .... 503.61 GB
```

**System info (please complete the following information):**
 - OS: Rocky Linux 8.8
 - GPU count and types: I am using 2xA100 80GB
 - Interconnects (if applicable) NVLINK
 - Python version: Python 3.9.7
 - Pytorch version: 2.1.0.dev
 - Cuda version 11.7

**Launcher context**
`torchrun --standalone --nproc_per_node=2 src/run.py`

**Comment by RookieGamer-Wang** [comment]
I have get the same problem. It seems that the learning rate is not a float, int or bflaot. So I tried to modify the learning rate (group['lr']) to 0.001 in fused_adam.py. Then it works. When initializing the optimizer, it is necessary to ensure that the format of learning is correct.
<img width="630" alt="image" src="https://github.com/microsoft/DeepSpeed/assets/79565691/565e471e-6002-4b37-b98b-94ce7d442fd6">

**Comment by ikergarcia1996** [comment]
@RookieGamer-Wang You are right, in my case the learning rate and adam_eps are strings instead of floats. I am using the Hugging Face Trainer, so it seems that there is a bug in the Trainer and not in DeepSpeed. I will close the issue

**Comment by robinsonmhj** [comment]
You need to change auto to some float value for the optimizer parameter, for example
`"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "betas": [
        0.8,
        0.999
      ],
      "eps": 1e-8,
      "weight_decay": 3e-7
    }
  }`
