### ISSUE TITLE
[BUG] `matmul_ext_update_autotune_table` error at exit

### ISSUE THREAD

**Issue by Benjamin-eecs** [microsoft/DeepSpeed#4060]
**Describe the bug**

```shell
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "python3.8/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "python3.8/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "python3.8/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 145, in _update_autotune_table
    autotune_table = cache_manager.load()
  File "python3.8/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 73, in load
    with open(self.file_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/.triton/autotune/Fp16Matmul_4d_kernel.pickle'
``` 

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/microsoft/DeepSpeed/assets/32269413/92dfb120-2199-4314-a2b6-f8da280657f6)

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types: one machine with x8 A100s
 - Python version 3.8.10

**Comment by kennymckormick** [comment]
Hi, @Benjamin-eecs, I also encountered the same problem, did you solve it?

**Comment by loadams** [comment]
Closing due to lack of a repro.  If others hit this, please comment here or open a new issue with a repro script and we can take a look.

**Comment by zigzagcai** [comment]
I also meet this error on `deepspeed==0.10.0`
```
Traceback (most recent call last):
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 145, in _update_autotune_table
    autotune_table = cache_manager.load()
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 73, in load
    with open(self.file_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/zigzagcai/.triton/autotune/Fp16Matmul_4d_kernel.pickle'
  0%|          | 0/68 [01:31<?, ?it/s]
```
