### ISSUE TITLE
[BUG] BF16 training with FP32 gradient accumulation - Zero Stage 1 CPU - DeepSpeedCPUAdam

### ISSUE THREAD

**Issue by balachandarsv** [microsoft/DeepSpeed#4083]
I am trying to train a model with bf16,  fp32 gradient accumulation and zero stage 1. Using DeepSpeedCPUAdam as optimizer. 

**Config**
```json
{
    "steps_per_print":10000,
    "wall_clock_breakdown":true,
    "train_batch_size": 1024,
    "gradient_accumulation_steps": 16,
    "train_micro_batch_size_per_gpu": 2,
    "fp32_allreduce": true,
    "data_types": {
        "grad_accum_dtype":"fp32"
    },
    "bf16": {
        "enabled": true
    },
    "optimizer": {
        "type": "DeepSpeedCPUAdam",
        "params": {
            "lr": 0.001
        }
    },
    "gradient_clipping": 1.0,
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 0.001,
            "warmup_num_steps": 1000
        }
    },

    "zero_optimization": {
        "stage": 1,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
          },
      "allgather_partitions": true,
      "reduce_bucket_size": 5e8,
      "allgather_bucket_size": 5e8,
      "reduce_scatter": true,
      "overlap_comm": true,
      "round_robin_gradients":true,
      "contiguous_gradients": true,
      "sub_group_size": 1e9
    },
  }
```

**ds_report output**
```[2023-08-03 03:07:32,395] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [YES] ...... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
random_ltd ............. [YES] ...... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0+9e3e10c5ed), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/work2/conda/envs/env/lib/python3.11/site-packages/torch']
torch version .................... 2.1.0.dev20230725+cu121
deepspeed install path ........... ['/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.10.0+unknown, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.0
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
```

**Error message**
CPUAdam param is on cuda:7 and must be 'cpu', make sure you enabled 'offload_optimizer': 'cpu' in your ZeRO config.

But offload_optimizer is already set in our config. 
Same config works if I change the grad_accum_dtype to "bf16" with zero code changes.

```Traceback (most recent call last):
    self._configure_optimizer(optimizer, model_parameters)
           ^^^^^^^^^^^^^^^^^^
  File "/work2/dragoon_deepspeed/deepspeed_trainer.py", line 320, in <module>
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1220, in _configure_optimizer
AssertionError: CPUAdam param is on cuda:5 and must be 'cpu', make sure you enabled 'offload_optimizer': 'cpu' in your ZeRO config.```


Can someone help by letting me know how to solve this?

**Comment by jomayeri** [comment]
Could you try this branch: https://github.com/microsoft/DeepSpeed/pull/4084

**Comment by balachandarsv** [comment]
@jomayeri Tried that, now facing another error. Here is the trace. 

``` File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1917, in backward
    self.allreduce_gradients()
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1844, in allreduce_gradients
    self.optimizer.reduce_gradients(pipeline_parallel=self.pipeline_parallelism)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 671, in reduce_gradients
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1318, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 887, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1265, in reduce_ipg_grads
    self.average_tensor(self.extra_large_param_to_reduce.grad.view(-1))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'view'
```

**Comment by balachandarsv** [comment]
@jomayeri tried the branch build. Facing a different error.

Here is the stack trace.

``` File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1916, in backward
    self.allreduce_gradients()
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1843, in allreduce_gradients
    self.optimizer.reduce_gradients(pipeline_parallel=self.pipeline_parallelism)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 671, in reduce_gradients
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1318, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 887, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1265, in reduce_ipg_grads
    self.average_tensor(self.extra_large_param_to_reduce.grad.view(-1))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'view'
```

**Comment by jomayeri** [comment]
Can you provide a script so I can repro it.

**Comment by jomayeri** [comment]
I was able to exercise the code path, another fix was pushed.

**Comment by balachandarsv** [comment]
Thanks @jomayeri , I tried from the branch again. Now facing error at a different location and here are my observation.

```if not self.overlap_comm:
            for i, group in enumerate(self.bit16_groups):
                for param in group:
                    grad_reduc = self.get_gradient_for_reduction(param)
                    if grad_reduc is not None:
                        self.reduce_ready_partitions_and_remove_grads(param, i)
```

this call to `self.get_gradient_for_reduction(param)` has param.grad_accum but  when this calls `self.reduce_ready_partitions_and_remove_grads(param, i)`
```
def reduce_independent_p_g_buckets_and_remove_grads(self, param, i):
        grad_reduc = self.get_gradient_for_reduction(param) ->This call to the function has None for param.grad_accum
```
```    def get_gradient_for_reduction(self, param):
        return param.grad_accum.to(self.dtype) if self.use_grad_accum_for_reduction else param.grad
```


Stack trace

```File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1843, in allreduce_gradients
    self.optimizer.reduce_gradients(pipeline_parallel=self.pipeline_parallelism)
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 669, in reduce_gradients
    grad_reduc = self.get_gradient_for_reduction(param)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/conda/envs/env/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 840, in get_gradient_for_reduction
    return param.grad_accum.to(self.dtype) if self.use_grad_accum_for_reduction else param.grad
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by balachandarsv** [comment]
Also if this helps, 
Zero stage 2 works for the same config from the #4084 , issue happens only in stage 1. 
The same zero stage 2 doesn't work from 0.10.0.

**Comment by jomayeri** [comment]
That should be fixed now as well.

**Comment by hhhhpaaa** [comment]
This is a strange issue, I want to test stage0 and this issue appears. But it works fine on stage1.
