### ISSUE TITLE
[BUG] an illegal memory access was encountered in optimizer.step() using Zero stage 2

### ISSUE THREAD

**Issue by yikedouer** [microsoft/DeepSpeed#4091]
**Describe the bug**
An illegal memory access was encountered in optimizer.step() when using 3 gpus,but it works well using 4 or 5 gpus. 

**Script**
using transformers
deepspeed --num_gpus=3 --master_port 25678 src/train_bash.py \
    --stage sft \
    --model_name_or_path ${LLM_PATH} \
    --do_train \
    --dataset alpaca_gpt4_en,alpaca_gpt4_zh \
    --dataset_dir ${DATA_DIR} \
    --finetuning_type full \
    --output_dir car_output \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --num_train_epochs 2.0 \
    --dev_ratio 0.01 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --bf16 \
    --deepspeed configs/ds_config.json

**Deepspeed config**
{
    "train_micro_batch_size_per_gpu": "auto",
    "zero_allow_untested_optimizer": true,
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "initial_scale_power": 16, 
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },  
    "bf16": {
        "enabled": "auto"
    },
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": false,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients" : true
    }
}

**ds_report**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.9/dist-packages/torch']
torch version .................... 2.0.0+cu117
deepspeed install path ........... ['/usr/local/lib/python3.9/dist-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
```

**Traceback Info:**
Traceback (most recent call last):
  File "/opt/tiger/LLM/src/train_bash.py", line 23, in <module>
    main()
  File "/opt/tiger/LLM/src/train_bash.py", line 10, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/opt/tiger/LLM/src/llmtuner/tuner/sft/workflow.py", line 61, in run_sft
    train_result = trainer.train()
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
    result = self._prepare_deepspeed(*args)
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
    self._configure_optimizer(optimizer, model_parameters)
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1444, in _configure_zero_optimizer
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 489, in __init__
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 624, in initialize_optimizer_states
    self.optimizer.step()
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 171, in step
    adamw(
    func(
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 496, in _multi_tensor_adamw
    torch._foreach_mul_(device_params, 1 - lr * weight_decay)
RuntimeError: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/opt/tiger/LLM/src/train_bash.py", line 23, in <module>
    main()
  File "/opt/tiger/LLM/src/train_bash.py", line 10, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
    train_result = trainer.train()
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1656, in _inner_training_loop
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1444, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 489, in __init__
  File "/home/tiger/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 624, in initialize_optimizer_states
    self.optimizer.step()
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 171, in step
    adamw(
    func(
  File "/usr/local/lib/python3.9/dist-packages/torch/optim/adamw.py", line 496, in _multi_tensor_adamw
    torch._foreach_mul_(device_params, 1 - lr * weight_decay)
RuntimeError: CUDA error: an illegal memory access was encountered

**GPU Info: **
A100-80G

**Comment by jomayeri** [comment]
@yikedouer Can you provide the train_bash.py script?

**Comment by yikedouer** [comment]
> 

```
deepspeed --num_gpus=3 --master_port 25678 src/train_bash.py \
    --stage sft \
    --model_name_or_path ${LLM_PATH} \
    --do_train \
    --dataset alpaca_gpt4_en,alpaca_gpt4_zh \
    --dataset_dir ${DATA_DIR} \
    --finetuning_type full \
    --output_dir car_output \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --num_train_epochs 2.0 \
    --dev_ratio 0.01 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --bf16 \
    --deepspeed configs/ds_config.json
```

**Comment by yikedouer** [comment]
> @yikedouer Can you provide the train_bash.py script?

```
deepspeed --num_gpus=3 --master_port 25678 src/train_bash.py \
    --stage sft \
    --model_name_or_path ${LLM_PATH} \
    --do_train \
    --dataset alpaca_gpt4_en,alpaca_gpt4_zh \
    --dataset_dir ${DATA_DIR} \
    --finetuning_type full \
    --output_dir car_output \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --num_train_epochs 2.0 \
    --dev_ratio 0.01 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --bf16 \
    --deepspeed configs/ds_config.json
```

**Comment by jomayeri** [comment]
I need the actual python script that has the training loop, model, data, etc; not just the command.

**Comment by yikedouer** [comment]
> I need the actual python script that has the training loop, model, data, etc; not just the command.

Code and data is from this repo: [LLaMA-Efficient-Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning/blob/main/src/train_bash.py)

**Comment by chiragjn** [comment]
This was marked as completed, I recently ran into this issue, what is the solution?
