### ISSUE TITLE
[BUG] Out of Memory error when loading relatively small model

### ISSUE THREAD

**Issue by samvoisin** [microsoft/DeepSpeed#4153]
**Describe the bug**
I am running into Out of Memory errors when attempting to finetune the 7B version of Llama2. I am using two NVIDIA TITAN RTX GPUs with 24GB of memory each. As I understand it, this model should only require about 13GB of memory, but both GPUs spike in memory usage when I attempt to load the model with the `transformers.Trainer` object.

**To Reproduce**
Here is a simple version of the script I'm running:

```python
import logging
from pathlib import Path
import evaluate
import numpy as np
from transformers import LlamaTokenizer, LlamaForCausalLM
import deepspeed as ds
from transformers import Trainer, TrainingArguments

from datasets import load_dataset

checkpoint_dir = Path("checkpoints/llama-2-7b/").expanduser()
tokenizer_path = checkpoint_dir / "tokenizer.model"


ds_config = Path("finetune/ds_config.json")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

metric = evaluate.load("accuracy")


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)


def main():
    dataset = load_dataset("yelp_review_full")

    tokenizer = LlamaTokenizer.from_pretrained(str(tokenizer_path))

    def tokenize_function(examples):
        return tokenizer(examples["text"], padding="max_length", truncation=True)

    tokenized_datasets = dataset.map(tokenize_function, batched=True)

    small_train_dataset = (
        tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
    )
    small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

    model = LlamaForCausalLM.from_pretrained(str(checkpoint_dir))
    model.gradient_checkpointing_enable()

    training_args = TrainingArguments(
        output_dir="test_trainer", evaluation_strategy="epoch"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=small_train_dataset,
        eval_dataset=small_eval_dataset,
        compute_metrics=compute_metrics,
    )

    logger.info("Begin training")

    trainer.train()


if __name__ == "__main__":
    main()

```

and here is my DS config file:

```json
{
    "zero_optimization": {
        "stage": 3,
        "offload_param": {
            "device": "cpu"
        },
        "offload_optimizer": {
            "device": "cpu"
        }
    },
    "train_batch_size": 1,
    "gradient_accumulation_steps": 1,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 1e-4
        }
    },
    "fp16": {
        "enabled": true
    }
}
```

I am running my entrypoint script with this command:

```sh
deepspeed finetune/llama2_ds.py --deepspeed finetune/ds_config.json
```

The result is this error:

```sh
$ deepspeed finetune/llama2_ds.py --deepspeed finetune/ds_config.json
[2023-08-15 19:59:36,599] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-15 19:59:37,808] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-08-15 19:59:37,809] [INFO] [runner.py:555:main] cmd = /data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/bin/python3.8 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None finetune/llama2_ds.py --deepspeed finetune/ds_config.json
[2023-08-15 19:59:40,245] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-15 19:59:41,442] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-08-15 19:59:41,442] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-08-15 19:59:41,442] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-08-15 19:59:41,442] [INFO] [launch.py:163:main] dist_world_size=2
[2023-08-15 19:59:41,442] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-08-15 19:59:45,623] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-15 19:59:45,645] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1743: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1743: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:21<00:00, 40.77s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:21<00:00, 40.80s/it]
Traceback (most recent call last):
  File "finetune/llama2_ds.py", line 65, in <module>
Traceback (most recent call last):
  File "finetune/llama2_ds.py", line 65, in <module>
    main()
  File "finetune/llama2_ds.py", line 51, in main
        main()trainer = Trainer(

  File "finetune/llama2_ds.py", line 51, in main
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/trainer.py", line 499, in __init__
    trainer = Trainer(
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/trainer.py", line 499, in __init__
    self._move_model_to_device(model, args.device)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/trainer.py", line 741, in _move_model_to_device
    self._move_model_to_device(model, args.device)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/trainer.py", line 741, in _move_model_to_device
    model = model.to(device)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1900, in to
    model = model.to(device)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1900, in to
    return super().to(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
    return super().to(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    return self._apply(convert)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
      File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
module._apply(fn)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 1 has a total capacty of 23.64 GiB of which 61.56 MiB is free. Including non-PyTorch memory, this process has 23.58 GiB memory in use. Of the allocated memory 23.42 GiB is allocated by PyTorch, and 1.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 0 has a total capacty of 23.64 GiB of which 51.56 MiB is free. Including non-PyTorch memory, this process has 23.58 GiB memory in use. Of the allocated memory 23.42 GiB is allocated by PyTorch, and 1.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-08-15 20:02:20,652] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1014542
[2023-08-15 20:02:20,689] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1014543
[2023-08-15 20:02:20,736] [ERROR] [launch.py:321:sigkill_handler] ['/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/bin/python3.8', '-u', 'finetune/llama2_ds.py', '--local_rank=1', '--deepspeed', 'finetune/ds_config.json'] exits with return code = 1
```

**Expected behavior**
Model should load and training should begin. In the case of my script, `Begin training` is not logged before the OoM error is raised.

**ds_report output**

```sh
$ ds_report
[2023-08-15 20:03:06,225] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0+9e3e10c5ed), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch']
torch version .................... 2.1.0.dev20230728+cu118
deepspeed install path ........... ['/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.10.0, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.1, cuda 11.8
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - One machine. Two NVIDIA TITAN RTX GPUs with 24GB of memory each
 - Python version: Python 3.8.17

**Comment by jomayeri** [comment]
@samvoisin Thanks for the script but unfortunately I will not be able to repro this error because I don't have access to any 24GB GPUs.

It appears the issue is that zero.Init() is not being called when partitioning the model. Can you look at [this section](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/deepspeed#constructing-massive-models) of the HuggingFace documentation to ensure it is being called.

**Comment by ashwin-js** [comment]
I am also getting the same error when I am trying to load a Peft fine tuned and quantized "meta-llama/Llama-2-13b-chat-hf". The final model size is around 12GB and I am trying to deploy it in a aws g5.12xlarge
