### ISSUE TITLE
[BUG] llm zero2 training 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by YooSungHyun** [microsoft/DeepSpeed#4183]
**Describe the bug**
when i used bf16 or fp16 and zero2. error strange error accured. (for full-finetune llama-2-7b)

``` json
{
    "bf16": {
        "enabled": "auto"
    },
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": "auto",
            "adam_w_mode": true
        }
    },
    "scheduler": {
        "type": "OneCycle",
        "params": {
            "cycle_first_step_size": 100,
            "cycle_max_lr": 3e-5,
            "cycle_min_lr": 3e-6
        }
    },
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e7,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e7,
        "contiguous_gradients": true,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true,
            "buffer_count": 4,
            "fast_init": false
        }
    },
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "wall_clock_breakdown": false
}
```

huggingface llm example,
not using peft lora. i just want to full finetune

llama-2-7b
`circulus/Llama-2-7b-orca-v1`

accured error
``` python3
Traceback (most recent call last):
  File "/data/workspace/train/train_dpo.py", line 133, in <module>
    main(model_args=model_args, dataset_args=dataset_args, training_args=training_args)
  File "/data/workspace/train/train_dpo.py", line 119, in main
    dpo_trainer.train()
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/transformers/trainer.py", line 2665, in training_step
    self.accelerator.backward(loss)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1891, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1941, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 859, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1318, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 887, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1305, in reduce_ipg_grads
    self.copy_grads_in_partition(param)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1226, in copy_grads_in_partition
    self.async_accumulate_grad_in_cpu_via_gpu(param)
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1130, in async_accumulate_grad_in_cpu_via_gpu
    accumulate_gradients()
  File "/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1109, in accumulate_gradients
    param.grad_accum.data.view(-1).add_(dest_buffer)
AttributeError: 'NoneType' object has no attribute 'data'
```

how can i fix it?

**To Reproduce**
1. just find llm full-finetuning example
2. run zero2 (must fp16 or bf16)
3. error accured

**Expected behavior**
training success

**ds_report output**
Please run `ds_report` to give us details about your setup.
``` bash
[2023-08-21 11:28:22,048] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/data/workspace/.bart_venv/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu118
deepspeed install path ........... ['/data/workspace/.bart_venv/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.1+85dc854b, 85dc854b, master
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
shared memory (/dev/shm) size .... 167.19 GB
```

**System info (please complete the following information):**
 - OS: ubuntu 22.04
 - GPU count and types A100 80GB * 2EA
 - Interconnects just 1 nodes
 - Python version 3.10
 - Any other relevant info about your setup
deepspeed==0.10.1+85dc854b
torch 2.0.1 cu118
transformers==4.31.0

**Comment by hijkzzz** [comment]
Related issue #4188

**Comment by jp1924** [comment]
These are some of the things we have found about this issue
1. the issue occurs when cpu is offloaded, regardless of bf16 or fp16, and gradient accumulation is above 2.
2. it started happening after the 0.10.1 patch, i.e. the above issue did not occur in 0.10.0.
3. speculation is that the implementation of the `[ZeRO Gradient Accumulation Dtype.](https://github.com/microsoft/DeepSpeed/pull/2847)` pr has become incomplete.

**Comment by jp1924** [comment]
Here is the code to implement the issue.

```python
from transformers import (
    RobertaTokenizerFast,
    RobertaForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    HfArgumentParser,
)
from datasets import load_dataset


def example_fn(examples):
    outputs = tokenizer(examples["document"], padding=True, max_length=256, truncation=True)
    return {"input_ids": outputs["input_ids"], "labels": examples["label"]}


parser = HfArgumentParser([TrainingArguments])
args, _ = parser.parse_args_into_dataclasses(return_remaining_strings=True)

tokenizer = RobertaTokenizerFast.from_pretrained("klue/roberta-base")
model = RobertaForSequenceClassification.from_pretrained("klue/roberta-base")

dataset = load_dataset("nsmc", split="train")
dataset = dataset.train_test_split(0.01)["test"]
dataset = dataset.map(example_fn, remove_columns=["id", "document", "label"])

collator = DataCollatorWithPadding(tokenizer=tokenizer)
trainer = Trainer(
    model=model,
    args=args,
    data_collator=collator,
    train_dataset=dataset,
    tokenizer=tokenizer,
)

trainer.train()
```
```json
{
    "bf16": {
        "enabled": "auto"
    },
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true,
            "buffer_count": 4,
            "fast_init": false
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 5e7,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e7,
        "contiguous_gradients": true
    },
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "wall_clock_breakdown": false
}
```

run script
```
deepspeed --include=localhost:0 [EXAMPLE_CODE] --output_dir=./ --per_device_train_batch_size=1 --gradient_accumulation_steps=2 --num_train_epochs=1 --deepspeed=[DEEPSPEED_CONFIG]
```
package version
- transformers==4.28.1
- datasets==2.13.1
- deepspeed==0.10.1

**Comment by jomayeri** [comment]
Please try this branch https://github.com/microsoft/DeepSpeed/pull/4214
