### ISSUE TITLE
Error Inference via command line for CPU

### ISSUE THREAD

**Issue by Dayananda-Akaike-Tech** [microsoft/DeepSpeed#4190]
**Describe the bug**
I am trying to run an inference on colab using only CPU

**Using Deepspeed CMD for inference**
i am using the below command with my **transcribe.py** file and **whisper-medium-hi_alldata_multigpu** saved model folder
 `!deepspeed --include= localhost:0 "/content/vistaar/transcribe.py" "/content/manifest.json" "/content/drive/MyDrive/Indic_Whisper (Vistar Bench_mark)/whisper-medium-hi_alldata_multigpu/" "Hindi" 1 "/content/output_path.txt".` 

**Required Output**
what should i specify the parameter for device `"--include"` or `"--exclude"` or install [intel-extension-for-deepspeed](https://github.com/intel/intel-extension-for-deepspeed)

**Existing output**
```
[INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-22 11:30:51,120] [WARNING] [runner.py:201:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/usr/local/bin/deepspeed", line 6, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/launcher/runner.py", line 420, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available
```

**Comment by mrwyattii** [comment]
Take a look at our CPU Inference workflow for an idea of how to setup your environment for CPU inference. For example, you will need to build and install the intel-extension-for-pytorch:
https://github.com/microsoft/DeepSpeed/blob/5e16eb2c939707d0d0062a458d77998fccb3afad/.github/workflows/cpu-inference.yml#L25

**Comment by mrwyattii** [comment]
@Dayananda-Akaike-Tech what does `ds_report` output when you run it?

Also can you share the output of `numactl --hardware`? Thanks
