### ISSUE TITLE
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

### ISSUE THREAD

**Issue by tekntrash** [microsoft/DeepSpeed#4257]
Trying to fine-tune a Falcon model with the command deepspeed train.py --per_device_train_batch_size 1 --do_train --max_train_samples 500 --num_train_epochs 1

I have 4 [NVIDIA A100-SXM4-80GB]
deepspeed-0.10.2
Python 3.9.12
Pytorch 2.0.1+cu117

Getting the error "AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'"

Below the whole thing, if anyone cares to read it :)

Loading extension module cpu_adam...
Traceback (most recent call last):
  File "/32Tb/train.py", line 23, in <module>
Loading extension module cpu_adam...
    main()
  File "/32Tb/train.py", line 13, in main
    happy_gen.train(train_txt_path, args=train_args, eval_filepath=eval_txt_path)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_generation.py", line 92, in train
Traceback (most recent call last):
  File "/32Tb/train.py", line 23, in <module>
Loading extension module cpu_adam...
    main()
  File "/32Tb/train.py", line 13, in main
    happy_gen.train(train_txt_path, args=train_args, eval_filepath=eval_txt_path)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_generation.py", line 92, in train
    super(HappyGeneration, self).train(input_filepath, args, eval_filepath)
    super(HappyGeneration, self).train(input_filepath, args, eval_filepath)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 110, in train
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 110, in train
        self._run_train(train_tok_data, eval_tok_data, args,  self._data_collator)self._run_train(train_tok_data, eval_tok_data, args,  self._data_collator)

  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 272, in _run_train
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 272, in _run_train
        trainer.train()trainer.train()

  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
Traceback (most recent call last):
  File "/32Tb/train.py", line 23, in <module>
    main()
  File "/32Tb/train.py", line 13, in main
    happy_gen.train(train_txt_path, args=train_args, eval_filepath=eval_txt_path)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_generation.py", line 92, in train
    super(HappyGeneration, self).train(input_filepath, args, eval_filepath)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 110, in train
    self._run_train(train_tok_data, eval_tok_data, args,  self._data_collator)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 272, in _run_train
    trainer.train()
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
            return inner_training_loop(return inner_training_loop(return inner_training_loop(

  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
            model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(

  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
            result = self._prepare_deepspeed(*args)result = self._prepare_deepspeed(*args)result = self._prepare_deepspeed(*args)

  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1531, in _prepare_deepspeed
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1531, in _prepare_deepspeed
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1531, in _prepare_deepspeed
            optimizer = DeepSpeedCPUAdam(optimizer.param_groups, **defaults)optimizer = DeepSpeedCPUAdam(optimizer.param_groups, **defaults)optimizer = DeepSpeedCPUAdam(optimizer.param_groups, **defaults)

  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
    self.ds_opt_adam = CPUAdamBuilder().load()  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 446, in load

  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 446, in load
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 446, in load
            return self.jit_load(verbose)return self.jit_load(verbose)return self.jit_load(verbose)

  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
            op_module = load(name=self.name,op_module = load(name=self.name,op_module = load(name=self.name,

  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
        return _jit_compile(return _jit_compile(

      File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile
return _jit_compile(  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile

  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
        return _import_module_from_library(name, build_directory, is_python_module)  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
return _import_module_from_library(name, build_directory, is_python_module)

  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
    module = importlib.util.module_from_spec(spec)
module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
ImportError: /root/anaconda3/lib/python3.9/site-packages/snappy/../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so)
ImportError: /root/anaconda3/lib/python3.9/site-packages/snappy/../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so)
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /root/anaconda3/lib/python3.9/site-packages/snappy/../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so)
Loading extension module cpu_adam...
Traceback (most recent call last):
  File "/32Tb/train.py", line 23, in <module>
    main()
  File "/32Tb/train.py", line 13, in main
    happy_gen.train(train_txt_path, args=train_args, eval_filepath=eval_txt_path)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_generation.py", line 92, in train
    super(HappyGeneration, self).train(input_filepath, args, eval_filepath)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 110, in train
    self._run_train(train_tok_data, eval_tok_data, args,  self._data_collator)
  File "/root/anaconda3/lib/python3.9/site-packages/happytransformer/happy_transformer.py", line 272, in _run_train
    trainer.train()
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 1531, in _prepare_deepspeed
    optimizer = DeepSpeedCPUAdam(optimizer.param_groups, **defaults)
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 446, in load
    return self.jit_load(verbose)
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
    op_module = load(name=self.name,
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /root/anaconda3/lib/python3.9/site-packages/snappy/../../.././libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so)
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f7b7b8cf430>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7fa3010cf430>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f1dce6cf430>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7fbf16ccf430>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by loadams** [comment]
Hi @tekntrash - this looks to be the underlying error:

```
ImportError: /root/anaconda3/lib/python3.9/site-packages/snappy/../../.././libstdc++.so.6: version GLIBCXX_3.4.29' not found (required by /root/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so)
```

This is related to the gcc installed on the system.  Can you share if you're using conda or what gcc version you are using?  Alternatively, could you try re-installing or updating gcc/libstdc++?

**Comment by loadams** [comment]
Hi @tekntrash - any updates on this?

**Comment by chenfengshijie** [comment]
same error after I use `sudo apt upgrade`

**Comment by loadams** [comment]
@chenfengshijie - could you apt remove and re-install?  That might help more here.  Also possible worth `sudo apt-get upgrade libstdc++6`.  This [link](https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29) might help as well, can you try that and let us know if that works?

**Comment by chenfengshijie** [comment]
I just use the previous docker,and I this switching  to another image  is a good choice .[This](https://github.com/microsoft/DeepSpeed/issues/3969#issuecomment-1732849143) my help

**Comment by loadams** [comment]
Thanks for the confirmation that you had a workaround.  I'll close this issue for now, but if others hit this in the future and cannot work around it, please either comment on this issue and reopen or open a new issue and link this one, thanks.

**Comment by circlecrystal** [comment]
For anyone still encountered the same error, please refer to my solution in https://github.com/microsoft/DeepSpeed/issues/1687
