### ISSUE TITLE
[BUG] Running inference on llama2 with meta tensor

### ISSUE THREAD

**Issue by agunapal** [microsoft/DeepSpeed#4447]
**Describe the bug**
I am using meta tensor and skip init and loading from checkpoints

This doesn't seem to work with Llama2

This works with OPT models
**To Reproduce**
```
pip install transformers accelerate bitsandbytes
```
Install mpi4py . Can this work without mpi4py?

```


import torch
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
import deepspeed
from pathlib import Path
import json

model_name = "meta-llama/Llama-2-7b-hf"
model_path = < path to model snapshot> 
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
config = AutoConfig.from_pretrained(model_name)
with torch.device("meta"):
    model = AutoModelForCausalLM.from_config(
        config, torch_dtype=torch.float16
    )
model = model.eval()

ds_config = {
  "dtype": "torch.float16",
  "replace_with_kernel_inject": True,
  "tensor_parallel": {
    "tp_size": 1
  }
}
checkpoints_json = "checkpoints.json"

checkpoint_files = file_list = [
        str(entry)
        for entry in Path(model_path).rglob("*.[bp][it][n]")
        if entry.is_file()
    ]
data = {"type": "ds_model", "checkpoints": checkpoint_files, "version": 1.0}
print(f"Creating deepspeed checkpoint file {checkpoints_json}")
json.dump(data, open(checkpoints_json, "w"))

ds_engine = deepspeed.init_inference(
            model,
            config=ds_config, 
            base_dir=model_path,
            checkpoint=checkpoints_json,
        )
```

**Expected behavior**
Model should load

**ds_report output**
Please run `ds_report` to give us details about your setup.
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch']
torch version .................... 2.1.0+cu121
deepspeed install path ........... ['/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.1
shared memory (/dev/shm) size .... 93.35 GB

```

**Screenshots**

```
[2023-10-03 19:30:44,350] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Creating deepspeed checkpoint file checkpoints.json
[2023-10-03 19:30:47,800] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.3, git-hash=unknown, git-branch=unknown
[2023-10-03 19:30:47,800] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Traceback (most recent call last):
  File "/home/ubuntu/serve/test1.py", line 36, in <module>
    ds_engine = deepspeed.init_inference(
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 151, in __init__
    self._apply_injection_policy(config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 391, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 312, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 555, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 623, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 623, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 599, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 289, in replace_fn
    new_module = replace_with_policy(child,
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 232, in replace_with_policy
    _container.initialize_tensors()
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/containers/features/hybrid_engine.py", line 30, in initialize_tensors
    super().initialize_tensors(enable_training=enable_training)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/containers/base.py", line 141, in initialize_tensors
    self.check_meta_tensor_support()
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/module_inject/containers/base.py", line 132, in check_meta_tensor_support
    assert self.ckpt_load_enabled, "Meta tensors are not supported for this model currently."
AssertionError: Meta tensors are not supported for this model currently.

```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types [e.g. two machines with x8 A100s each] 4 A10
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version 3.10
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by mrwyattii** [comment]
Hi @agunapal as the error message indicates, we do not support loading the llama2 models with your current setup (i.e., with kernel injection and using meta tensors):
```bash
AssertionError: Meta tensors are not supported for this model currently.
```

Additionally, you are loading with `"tp_size": 1`, so the meta tensor loading would offer no benefit. Loading with meta tensor is really only useful for loading on multiple GPUs in order to avoid loading the model checkpoints more than once.

I will also note that we DO support loading llama2 models with meta tensor in the case where you are using multiple GPUs (i.e., `tp_size > 1`) and kernel injection is turned off (i.e., `replace_with_kernel_inject=False`).

**Comment by agunapal** [comment]
Hi @mrwyattii 

Can you please tell me what is missing from my code to get it working with `tp_size` > 1

I got the following error with `tp_size` = 4. Hence I changed it to 1.

It thinks the world_size is 1 where as my instance has 4 GPUs. I am not sure where I should be specifying this.?



```
[2023-10-03 19:27:04,909] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Creating deepspeed checkpoint file checkpoints.json
[2023-10-03 19:27:09,604] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.3, git-hash=unknown, git-branch=unknown
[2023-10-03 19:27:09,604] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[2023-10-03 19:27:09,605] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2023-10-03 19:27:09,607] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-03 19:27:09,607] [INFO] [comm.py:652:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2023-10-03 19:27:10,117] [INFO] [comm.py:702:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=172.31.2.198, master_port=29500
[2023-10-03 19:27:10,118] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/home/ubuntu/serve/test1.py", line 48, in <module>
    ds_engine = deepspeed.init_inference(
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 116, in __init__
    self._create_model_parallel_group(config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 235, in _create_model_parallel_group
    self.mp_group = dist.new_group(ranks)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 185, in new_group
    return cdb.new_group(ranks)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 328, in new_group
    return torch.distributed.new_group(ranks)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3881, in new_group
    return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3921, in _new_group_with_tag
    raise RuntimeError(
RuntimeError: the new group's world size should be less or equal to the world size set by init_process_group
```
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                     On | 00000000:00:1B.0 Off |                    0 |
|  0%   30C    P0               43W / 300W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10G                     On | 00000000:00:1C.0 Off |                    0 |
|  0%   30C    P0               57W / 300W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A10G                     On | 00000000:00:1D.0 Off |                    0 |
|  0%   30C    P0               44W / 300W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A10G                     On | 00000000:00:1E.0 Off |                    0 |
|  0%   30C    P0               57W / 300W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

Also, when i turned off kernel_injection, I got this error

```
[2023-10-03 19:29:53,924] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Traceback (most recent call last):
  File "/home/ubuntu/serve/test1.py", line 48, in <module>
    ds_engine = deepspeed.init_inference(
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 164, in __init__
    self.module.to(device)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2058, in to
    return super().to(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

```

**Comment by agunapal** [comment]
@mrwyattii Also, if you could give me pointers on what change is needed to get this example working with `meta` tensor and kernel_injection, that would be great. I can try to send a PR

**Comment by agunapal** [comment]
Hi @mrwyattii 

Thanks, I tried your code. It gives me this error
```
[2023-10-04 20:44:43,717] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 59861.62it/s]
[2023-10-04 20:44:47,259] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.3, git-hash=unknown, git-branch=unknown
[2023-10-04 20:44:47,260] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Traceback (most recent call last):
  File "/home/ubuntu/deepspeed_inference/test2.py", line 31, in <module>
    ds_engine = deepspeed.init_inference(
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 164, in __init__
    self.module.to(device)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2058, in to
    return super().to(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/ds_py210/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

I remember seeing this error when I tried this with `facebook/opt-6.7b` and when I set `"replace_with_kernel_inject": False`, that worked.

However with llama2, I get errors whether I set `"replace_with_kernel_inject": False` or `"replace_with_kernel_inject": True`

**Comment by agunapal** [comment]
Example:

The following code works
```
import torch
import os
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import snapshot_download
import deepspeed
from pathlib import Path
import json

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

model_name = "facebook/opt-6.7b"
model_path = snapshot_download(model_name, ignore_patterns=["*.safetensors"])
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
config = AutoConfig.from_pretrained(model_name)
with deepspeed.OnDevice(dtype=torch.float16, device="meta", enabled=True):
    model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.float16)

ds_config = {
    "dtype": "torch.float16",
    "replace_with_kernel_inject": True,
    "tensor_parallel": {"tp_size": world_size},
}

checkpoint_files = file_list = [
    str(entry) for entry in Path(model_path).rglob("*.[bp][it][n]") if entry.is_file()
]
checkpoint_dict = {"type": "ds_model", "checkpoints": checkpoint_files, "version": 1.0}

ds_engine = deepspeed.init_inference(
    model,
    config=ds_config,
    base_dir=model_path,
    checkpoint=checkpoint_dict,
)

```

The following code errors
```
import torch
import os
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import snapshot_download
import deepspeed
from pathlib import Path
import json

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

model_name = "facebook/opt-6.7b"
model_path = snapshot_download(model_name, ignore_patterns=["*.safetensors"])
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
config = AutoConfig.from_pretrained(model_name)
with deepspeed.OnDevice(dtype=torch.float16, device="meta", enabled=True):
    model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.float16)

ds_config = {
    "dtype": "torch.float16",
    "replace_with_kernel_inject": False,
    "tensor_parallel": {"tp_size": world_size},
}

checkpoint_files = file_list = [
    str(entry) for entry in Path(model_path).rglob("*.[bp][it][n]") if entry.is_file()
]
checkpoint_dict = {"type": "ds_model", "checkpoints": checkpoint_files, "version": 1.0}

ds_engine = deepspeed.init_inference(
    model,
    config=ds_config,
    base_dir=model_path,
    checkpoint=checkpoint_dict,
)

```

**Comment by mrwyattii** [comment]
@agunapal are you running the llama example I provided with multiple GPUs (i.e., with `deepspeed --num_gpus 2`)?

**Comment by agunapal** [comment]
@mrwyattii That worked! But how do I do it if i cant use `deepspeed --num_gpus 2`, i.e use deepspeed as a library

I am a maintainer of TorchServe. Sometime ago we added this example with [DeepSpeed + opt model](https://github.com/pytorch/serve/blob/master/examples/large_models/deepspeed/custom_handler.py#L46-L55)

https://github.com/pytorch/serve/blob/master/ts/handler_utils/distributed/deepspeed.py#L22

**Comment by agunapal** [comment]
I figured it out. This is being achieved using torchrun in our case and for some reason there is an issue with the world size. I'll look more. Thanks!

**Comment by agunapal** [comment]
@mrwyattii Thank you for your help. I figured out the problem! Will close the issue once i merge the example in our repo and share the link here
