### ISSUE TITLE
Using DeepSpeed with the latest version of Megatron-ML

### ISSUE THREAD

**Issue by msmolyak** [microsoft/DeepSpeed#445]
In the [DeepSpeedExamples](https://github.com/microsoft/DeepSpeedExamples) repository you helpfully provided the example of wrapping Megatron-ML model in DeepSpeed. The version of Megratron-ML used there dates to February, 2020. Are there plans to update the version of Megatron-ML in DeepSpeedExamples? Alternatively, is there a guidance on integrating the latest Megatron-ML version with DeepSpeed?

**Comment by samyam** [comment]
Hi @msmolyak, updating the version of Megatron-LM in DeepSpeedExamples in our pipeline, but we do not have an ETA yet. 

In the meantime, you can follow the instructions in this tutorial: https://www.deepspeed.ai/tutorials/megatron/  on integrating DeepSpeed with the latest Megatron. We are happy to help if you run into any issues.

**Comment by msmolyak** [comment]
Hi @samyam,

I took a stab at integrating DeepSpeed with the latest version of Megatron-LM. I forked the latter project in my personal repo and created a branch for the DeepSpeed changes. The code modifications are based on my analysis of the code in DeepSpeedExamples repo.

I would be grateful if someone on the Microsoft DeepSpeed team could review my changes and provide feedback. I hope that my effort will benefit not just my team, but yours as well.   

The PR containing my changes is at https://github.com/msmolyak/Megatron-LM/pull/1.

Please let me know if I need to do anything to give you ability to see and comment on this pull request.

Thank you,

Michael

**Comment by samyam** [comment]
Hi @msmolyak ,

This is amazing. Thank you so much for putting the time and effort into this, we really appreciate it. 

After receiving your request, we realized that we should probably prioritize this a bit and Cheng (@cli99 ) from our team put some time to finish up porting the updated Megatron-LM, and we have a working branch with correctness verified as well. Currently the code is here: https://github.com/cli99/Megatron-LM/tree/deepspeed

We were planning on pushing that into the master soon, but since you have also put a tremendous amount of effort into this as well, if you are interested we can figure out a way to split the PR between you and Cheng. 

I am concerned about the overhead of repeating some of the correctness test if we do the split, but we are open to your suggestions.

What do you think?

**Comment by msmolyak** [comment]
Hi @samyam,

I appreciate very much your team's effort in completing Megatron-LM integration. I would be totally fine if you went ahead and merged your code. I am a big proponent of the "sunk cost fallacy". You are the experts in DeepSpeed integration, all that matters is the end result and I expect your team to be in a much better position than I am to deliver well-tested integration of Megatron-LM with DeepSpeed code. But if you see a value in using my code, do let me know I will be happy to assist with the integration effort.

A few questions:

- Do you expect to complete the effort within days?
- Is https://github.com/cli99/Megatron-LM/ going to be the permanent home of this integration effort (after you merge the branch back into main or master)?
- I noticed that Cheng's branch is 44 commit's behind the latest Nvidia code. Are there plans to get current before merging?

Michael

**Comment by samyam** [comment]
Hi Michael,

The integration will be in DeepSpeedExamples. 

Btw, your questions are inspiring some detailed discussions within the team on how we should move forward with this. :) We do want to get the Megatron-LM current before merging, and make it easy to pull from Megatron-LM as Megatron-LM gets new updates. Hopefully the effort will be completed within a few days to a week, but we will know more about the precise timeline in a day or so. Will keep you posted.

Best,
Samyam

**Comment by gcooper-isi** [comment]
Hi @samyam ,
Thanks for being so helpful with this update. Michael and I are on the same team, and I thought I would provide some context on the work we're doing, which will hopefully inform how you decide to update DeepSpeedExamples. We are working on a project that uses a modified version of MegatronLM with a modified version of DeepSpeed. In order to do that, we have been working off of our own fork of DeepSpeedExamples and our own fork of DeepSpeed. However, since DeepSpeedExamples uses a copy of MegatronLM rather than a fork, this makes it difficult for us to periodically integrate the latest changes from MegatronLM into our project. We could alternatively work off of a fork of MegatronLM which we manually change to enable DeepSpeed, but that would make it difficult for us to periodically integrate updates from DeepSpeedExamples other than incorporating the latest version of MegatronLM. We are very grateful that you are going through all this effort to get DeepSpeedExamples to integrate the latest version of MegatronLM, but we wouldn't want to have to trouble you every time we want to do the same in the future. In particular, one of the things we plan to do in the very near future is submit the changes we have made to MegatronLM that are not specific to our project as pull requests to NVIDIA, and we would of course like those merged back into our project's fork once they have been merged into the NVIDIA repository. The best way for us to manage all these repositories would be if Microsoft maintained its DeepSpeed-enabled version of MegatronLM as a fork of MegatronLM, which we could then fork off of for our project. We see that you are already working off of https://github.com/cli99/Megatron-LM/, and we could fork off of that, but we're not sure if all updates to MegatronLM in DeepSpeedExamples are copied from this fork, or if you are just using it for this one update. Again, your cooperation in this is extremely appreciated.
Thanks,
George

**Comment by ShadenSmith** [comment]
Hi @gcooper-isi , thanks for the great feedback. We feel the same about DeepSpeedExamples and have been working on better a better way to track these changes. Your request is very timely :-). We aren't going the route of forks in a GitHub sense, but instead maintaining examples as git branches that can be rebased to either a baseline branch. Each example has some baseline branch (such as Megatron-LM's upstream), and then the DeepSpeed-specific changes are tracked in branches.

@jeffra and I have a small working prototype [here](https://github.com/jeffra/DSE/tree/cifar10-tut/cifar10). The [view changes](https://github.com/jeffra/DSE/pull/6/files) link is the key new feature; you can view the integration like you would any other pull request. @cli99 is working to get the Megatron-LM example running in this prototype as a non-trivial test.

Any comments are appreciated :-).

**Comment by msmolyak** [comment]
Hi @ShadenSmith,
We are looking forward to working with the latest Megatron-LM integrated with DeepSpeed using your Git branch approach.
Do you have a timeline for releasing this addition to DeepSpeedExamples?
Thank you,
Michael

**Comment by msmolyak** [comment]
@ShadenSmith and @samyam 
I have a question regarding DeepSpeed/Megatron-LM integration, which your team might have already solved.

I am trying to find a Docker-based runtime for training the model. I tried running the latest Megatron-LM using deepspeed/deepspeed:latest image. I was getting the error below. It appears that the deepspeed image has an older version of pytorch (1.2) than Megatron-LM needs (1.5).

I was able to run model training in the image recommended by Megatron-LM team, nvcr.io/nvidia/pytorch:20.03-py3. The latter image does not have deepspeed module, however.

Are there plans to update the deepspeed Docker image? Would is the best way to configure an image where I can run DeepSpeed with the latest version of Megatron-LM? Would you recommend installing deepspeed in Nvidia image or upgrading pytorch in DeepSpeed one?

Thank you.

```
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 26, in <module>
    from megatron.model import GPT2Model
  File "/Megatron-LM/megatron/model/__init__.py", line 17, in <module>
    from .bert_model import BertModel
  File "/Megatron-LM/megatron/model/bert_model.py", line 22, in <module>
    from megatron.model.language_model import parallel_lm_logits
  File "/Megatron-LM/megatron/model/language_model.py", line 24, in <module>
    from megatron.model.transformer import ParallelTransformer
  File "/Megatron-LM/megatron/model/transformer.py", line 27, in <module>
    from megatron.model.fused_bias_gelu import bias_gelu_impl
  File "/Megatron-LM/megatron/model/fused_bias_gelu.py", line 19, in <module>
    torch._C._jit_set_profiling_executor(False)
AttributeError: module 'torch._C' has no attribute '_jit_set_profiling_executor'
```

**Comment by ShadenSmith** [comment]
> Hi @ShadenSmith,
> We are looking forward to working with the latest Megatron-LM integrated with DeepSpeed using your Git branch approach.
> Do you have a timeline for releasing this addition to DeepSpeedExamples?
> Thank you,
> Michael

Hi @msmolyak , @cli99 did the hard work on that and just submitted a PR here: https://github.com/jeffra/DSE/pull/8  -- this is our WIP development repo until we have parity with the current DeepSpeedExamples.

**Comment by ShadenSmith** [comment]
> @ShadenSmith and @samyam
> I have a question regarding DeepSpeed/Megatron-LM integration, which your team might have already solved.
> 
> I am trying to find a Docker-based runtime for training the model. I tried running the latest Megatron-LM using deepspeed/deepspeed:latest image. I was getting the error below. It appears that the deepspeed image has an older version of pytorch (1.2) than Megatron-LM needs (1.5).
> 
> I was able to run model training in the image recommended by Megatron-LM team, nvcr.io/nvidia/pytorch:20.03-py3. The latter image does not have deepspeed module, however.
> 
> Are there plans to update the deepspeed Docker image? Would is the best way to configure an image where I can run DeepSpeed with the latest version of Megatron-LM? Would you recommend installing deepspeed in Nvidia image or upgrading pytorch in DeepSpeed one?
> 
> Thank you.
> 
> ```
> Traceback (most recent call last):
>   File "pretrain_gpt2.py", line 26, in <module>
>     from megatron.model import GPT2Model
>   File "/Megatron-LM/megatron/model/__init__.py", line 17, in <module>
>     from .bert_model import BertModel
>   File "/Megatron-LM/megatron/model/bert_model.py", line 22, in <module>
>     from megatron.model.language_model import parallel_lm_logits
>   File "/Megatron-LM/megatron/model/language_model.py", line 24, in <module>
>     from megatron.model.transformer import ParallelTransformer
>   File "/Megatron-LM/megatron/model/transformer.py", line 27, in <module>
>     from megatron.model.fused_bias_gelu import bias_gelu_impl
>   File "/Megatron-LM/megatron/model/fused_bias_gelu.py", line 19, in <module>
>     torch._C._jit_set_profiling_executor(False)
> AttributeError: module 'torch._C' has no attribute '_jit_set_profiling_executor'
> ```

Let me ping @jeffra as he owns the Docker.

As for your working container, @jeffra has been hard at work rewriting our build system and are now hosted on PyPI. You should be able to `pip install deepspeed` now. It's only a development release at this point, but should go official as we wrap up the PR (https://github.com/microsoft/DeepSpeed/pull/476). Please let us know if you have any issues :-).

**Comment by msmolyak** [comment]
Hi @ShadenSmith,

I am looking at the DeepSpeed tutorial and I do not see any information on generating text after training the model using DeepSpeed. 

I trained a model in the latest version of Megatron-LM in DeepSpeedExamples. The Megatron-LM original script generate_text.sh returns an error reading the checkpoint file generated by DeepSpeed. When I tried to modify the text generation script to use 'deepspeed' command, I also received an error below.

Are there guidelines for doing text generation with Megatron-LM model after training it with DeepSpeed?

Thank you.

 > number of parameters on model parallel rank 0: 354823168
Traceback (most recent call last):
  File "generate_samples.py", line 277, in <module>
    main()
  File "generate_samples.py", line 267, in main
    model = setup_model(args)
  File "generate_samples.py", line 81, in setup_model
    model, None, None, args)
  File "/DeepSpeedExamples/Megatron-LM/Megatron-LM/utils.py", line 281, in load_checkpoint
    checkpoint_name, sd = model.load_checkpoint(args.load, iteration)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'load_checkpoint'

**Comment by msmolyak** [comment]
Hi @ShadenSmith and @samyam,

Has there been any progress in moving the DeepSpeed wrapper of the current Megatron-LM code towards a release?

Thank you,

Michael
