### ISSUE TITLE
[BUG] DeepSpeed 0.11.0 requires `torch` is already installed

### ISSUE THREAD

**Issue by tgaddair** [microsoft/DeepSpeed#4473]
**Describe the bug**
The latest DeepSpeed version requires that PyTorch is installed as part of its package setup process, meaning the two packages cannot be installed together (for example, in a requirements file).

**To Reproduce**
From clean virtual environment with neither torch nor deepspeed installed:

```
$ pip install torch deepspeed

Collecting torch
  Downloading torch-2.1.0-cp38-none-macosx_10_9_x86_64.whl (146.7 MB)
     |████████████████████████████████| 146.7 MB 12.0 MB/s 
Collecting deepspeed
  Downloading deepspeed-0.11.0.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 22.8 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /test_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/setup.py'"'"'; __file__='"'"'/private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-pip-egg-info-wrnd5erq
         cwd: /private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/setup.py", line 37, in <module>
        from op_builder import get_default_compute_capabilities, OpBuilder
      File "/private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/op_builder/__init__.py", line 48, in <module>
        module = importlib.import_module(f".{module_name}", package=op_builder_dir)
      File "/Users/tgaddair/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/private/var/folders/8l/t2djbql92qvcf9_jjf4gv6040000gn/T/pip-install-xmpjnq2o/deepspeed/op_builder/async_io.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
     [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
It should be possible to install torch and deepspeed together.

**Comment by mrwyattii** [comment]
This will be fixed by #4468. We will push out a patch release today.

**Comment by mrwyattii** [comment]
@tgaddair We just release v0.11.1 - can you please confirm that this fixes the error you were seeing?

**Comment by tgaddair** [comment]
Thanks @mrwyattii, can confirm that the issue is resolved. Thanks for the fast turnaround!
