### ISSUE TITLE
[BUG] Unable to install Deepspeed >= 0.11.0 when building Docker image

### ISSUE THREAD

**Issue by KyleMylonakisProtopia** [microsoft/DeepSpeed#4495]
Pip installing deepspeed when building a Docker image fails when using Deepspeeds versions 0.11.0 or greater when using `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel` as the base image. The image builds successfully when using Deepspeed version 10.3.0.

```
#0 0.643 Collecting deepspeed                                                                                                                                                                            
#0 0.713   Downloading deepspeed-0.11.1.tar.gz (1.1 MB)                                                                                                                                                  
#0 0.756      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 26.2 MB/s eta 0:00:00                                                                                                                  
#0 0.912   Preparing metadata (setup.py): started                                                                                                                                                        
#0 3.398   Preparing metadata (setup.py): finished with status 'error'
#0 3.407   error: subprocess-exited-with-error
#0 3.407   
#0 3.407   × python setup.py egg_info did not run successfully.
#0 3.407   │ exit code: 1
#0 3.407   ╰─> [22 lines of output]
#0 3.407       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#0 3.407       Traceback (most recent call last):
#0 3.407         File "<string>", line 2, in <module>
#0 3.407         File "<pip-setuptools-caller>", line 34, in <module>
#0 3.407         File "/tmp/pip-install-0j5kzube/deepspeed_ed67b424775a4eeebd1f552e959ea2f6/setup.py", line 182, in <module>
#0 3.407           abort(f"Unable to pre-compile {op_name}")
#0 3.407         File "/tmp/pip-install-0j5kzube/deepspeed_ed67b424775a4eeebd1f552e959ea2f6/setup.py", line 52, in abort
#0 3.407           assert False, msg
#0 3.407       AssertionError: Unable to pre-compile evoformer_attn
#0 3.407       [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
#0 3.407       DS_BUILD_OPS=1
#0 3.407        [WARNING]  async_io attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  async_io attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_adam attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_adam attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_adagrad attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_adagrad attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_lion attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  cpu_lion attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 3.407        [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
#0 3.407        [WARNING]  One can disable evoformer_attn with DS_BUILD_EVOFORMER_ATTN=0
#0 3.407        [ERROR]  Unable to pre-compile evoformer_attn
#0 3.407       [end of output]
#0 3.407   
#0 3.407   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 3.409 error: metadata-generation-failed
#0 3.409 
#0 3.409 × Encountered error while generating package metadata.
#0 3.409 ╰─> See above for output.
#0 3.409 
#0 3.409 note: This is an issue with the package mentioned above, not pip.
#0 3.409 hint: See above for details.
------
Dockerfile:7
--------------------
   5 |     # Install Deepspeed
   6 |     RUN apt-get -y install libaio-dev
   7 | >>> RUN DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed" did not complete successfully: exit code: 1
```

**To Reproduce**
1. Create the following Dockerfile
```
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

RUN apt-get -y update

# Install Deepspeed
RUN apt-get -y install libaio-dev
RUN DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 pip install deepspeed
```

2. Execute `docker build -t test_deepspeed_pytorch .`

**Expected behavior**
The image should build without error.

**ds_report output**
This is the report from the system being used to create the Docker image.

```
[2023-10-10 14:18:34,630] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/kyle/.conda/envs/llama2-chat/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/home/kyle/.conda/envs/llama2-chat/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.11.1, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
shared memory (/dev/shm) size .... 62.82 GB
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - GPU count and types: 4x NVIDIA RTX A6000
 - Interconnects (if applicable): N/A
 - Python version: 3.10
 - Docker version 23.0.5, build bc4487a

**Comment by mrwyattii** [comment]
`[ERROR]  Unable to pre-compile evoformer_attn` is the error message. Are you intending to build the [EvoFormerAttention](https://www.deepspeed.ai/tutorials/ds4sci_evoformerattention/)?

If so, you should follow this warning: `[WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH`

Otherwise, you should avoid trying to compile it. You can do this by either removing `DS_BUILD_OPS=1` and [only specifying which things you need to precompile](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops). Or you can add `DS_BUILD_EVOFORMER_ATTN=0` to your current install line:
```
RUN DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 DS_BUILD_EVOFORMER_ATTN=0 pip install deepspeed
```

**Comment by KyleMylonakisProtopia** [comment]
No I was not. Missed that warning since my eye wan on where the actual exception was raised.

It looks to be fixed now.
Thanks for the quick response

**Comment by mrwyattii** [comment]
Glad we could find a solution so quickly! Closing this issue
