### ISSUE TITLE
Error installing deepspeed

### ISSUE THREAD

**Issue by Frosty2100** [microsoft/DeepSpeed#4580]
I tried to install the deepspeed package as a dependencies for a program. I originally installed wsl because I am running on windows 11 however I got an error witch i assumed would be solved if i installed  cuda toolkit for windows 11 (cuda_12.3.0_545.84_windows) but after I attempted to install deepspeed again I got this error:
```
----- Installing 'deepspeed' -----
Defaulting to user installation because normal site-packages is not writeable

Collecting deepspeed
  Using cached deepspeed-0.11.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [17 lines of output]
  No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'
  [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
  DS_BUILD_OPS=1
  test.c
  LINK : fatal error LNK1181: cannot open input file 'aio.lib'
  [93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
  [93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
  [93m [WARNING] [0m One can disable async_io with DS_BUILD_AIO=0
  [31m [ERROR] [0m Unable to pre-compile async_io
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\TD_wi\AppData\Local\Temp\pip-install-fbyzwzca\deepspeed_5cf730cd57c049d58aad1b46031a8963\setup.py", line 182, in <module>
      abort(f"Unable to pre-compile {op_name}")
    File "C:\Users\TD_wi\AppData\Local\Temp\pip-install-fbyzwzca\deepspeed_5cf730cd57c049d58aad1b46031a8963\setup.py", line 52, in abort
      assert False, msg
  AssertionError: Unable to pre-compile async_io
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
----- Failed to install 'deepspeed' -----
```
Are there any ideas on what I need to resolve this?

**Comment by haadirakhangi** [comment]
I faced the same error. Is there a way to install it without using WSL?
