### ISSUE TITLE
[BUG]couldn't install deepspeed-chat

### ISSUE THREAD

**Issue by advancingsweet** [microsoft/DeepSpeed#4658]
(torchGpu) D:\Shiyan\AIbasic\wenet-main\DeepSpeed-0.11.0>python setup.py bdist_wheel
DS_BUILD_OPS=1
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
 [WARNING]  cpu_adagrad cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
 [WARNING]  cpu_lion cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  One can disable evoformer_attn with DS_BUILD_EVOFORMER_ATTN=0
 [ERROR]  Unable to pre-compile evoformer_attn
Traceback (most recent call last):
  File "D:\Shiyan\AIbasic\wenet-main\DeepSpeed-0.11.0\setup.py", line 182, in <module>
    abort(f"Unable to pre-compile {op_name}")
  File "D:\Shiyan\AIbasic\wenet-main\DeepSpeed-0.11.0\setup.py", line 52, in abort
    assert False, msg
AssertionError: Unable to pre-compile evoformer_attn

**Comment by advancingsweet** [comment]
I'm carrzy since it speed my much time and didn't work well.  Hope it could be soluted. thanks

**Comment by loadams** [comment]
Hi @advancingsweet - what system are you building on (Windows?), and is there a reason you are building the wheel this way rather than installing via pip?

Your error has to do with the ops being pre-compiled, which isn't necessary, and you can pass the [various DS build strings](https://www.deepspeed.ai/tutorials/advanced-install/#pre-install-deepspeed-ops) like `DS_BUILD_EVOFORMER_ATTN=0` and `DS_BUILD_AIO=0` to not pre-compile them.

**Comment by loadams** [comment]
Hi @advancingsweet - any updates on this?

**Comment by loadams** [comment]
Hi @advancingsweet - closing this for now, if you are still having issues, please reply or re-open the issue, thanks!

**Comment by gitshaozhong** [comment]
According to your tips, I have set DS_BUILD_EVOFORMER_ATTN=0 and DS_BUILD_AIO=0, but now it have a new problem, please help ，thanks！
【my computer environment：windows10、GPU A4000、pytorch 2.1.1、VS2022】
the error：
Collecting deepspeed
  Using cached deepspeed-0.12.4.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\issuser\AppData\Local\Temp\pip-install-yjaclsor\deepspeed_6bc529f3cc1f4e6b8905635d592b92a3\setup.py", line 192, in <module>
          ext_modules.append(builder.builder())
        File "C:\Users\issuser\AppData\Local\Temp\pip-install-yjaclsor\deepspeed_6bc529f3cc1f4e6b8905635d592b92a3\op_builder\builder.py", line 637, in builder
          extra_link_args=self.strip_empty_entries(self.extra_ldflags()))
        File "C:\Users\issuser\AppData\Local\Temp\pip-install-yjaclsor\deepspeed_6bc529f3cc1f4e6b8905635d592b92a3\op_builder\inference_cutlass_builder.py", line 71, in extra_ldflags
          import dskernels
      ModuleNotFoundError: No module named 'dskernels'
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  cpu_adam requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  cpu_adam requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  cpu_adagrad requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  cpu_adagrad requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
       [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
       [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
       [WARNING]  Filtered compute capabilities ['6.0', '6.1', '7.0']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
