### ISSUE TITLE
[BUG] matmul_ext_update_autotune_table error

### ISSUE THREAD

**Issue by CokeDong** [microsoft/DeepSpeed#4672]
**Describe the bug**
also encoutered this on `deepspeed 0.12.2`
```

Evaluating iter 1/1
Exception ignored in atexit callback: <function matmul_ext_update_autotune_table at 0x7f548c0d0550>
Traceback (most recent call last):
  File "/mnt/petrelfs/dkx/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/mnt/petrelfs/dkx/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 421, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/mnt/petrelfs/dkx/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 145, in _update_autotune_table
    autotune_table = cache_manager.load()
  File "/mnt/petrelfs/dkx/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 73, in load
    with open(self.file_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/petrelfs/dkx/.triton/autotune/Fp16Matmul_2d_kernel.pickle'
------------------------------------------------------------------------------------------------------------------------------------
 validation loss at iteration 10 on 16-sample draw from validation set | lm loss value: 1.096040E+01 | lm loss PPL: 5.754944E+04 | 
------------------------------------------------------------------------------------------------------------------------------------

### end of training.
```

this problem seems arise from `deepspeed/__init__.py`:

```
try:
    import triton  # noqa: F401 # type: ignore
    HAS_TRITON = True
except ImportError:
    HAS_TRITON = False

```

change this to :
```
try:
    import triton  # noqa: F401 # type: ignore
    HAS_TRITON = False
except ImportError:
    HAS_TRITON = False

```
or 
```
pip unintall triton
```

solve this. but donnot know does this affect the training results?

**To Reproduce**
pre-training gpt3 on megtron-deepspeed using scripts from `https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/pretrain_gpt3_175B.sh`

**Expected behavior**
near finishing, the error arises.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 but detected 2.0
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
No CUDA runtime is found, using CUDA_HOME='/mnt/petrelfs/share_data/llm_env/dep//cuda-11.7'
DeepSpeed general environment info:
torch install path ............... ['/mnt/petrelfs/share_data/llm_env/miniconda3-py39_4/lib/python3.9/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/mnt/petrelfs/share_data/llm_env/miniconda3-py39_4/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.8.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types : 8 machines with x8 A800s each
 - Python version:3.10.0

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
`srun`

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by CokeDong** [comment]
does this affect any training results? seems not.

**Comment by CokeDong** [comment]
related issue: https://github.com/microsoft/DeepSpeed/issues/4060

**Comment by loadams** [comment]
No, missing the pickle file shouldn't impact your results, but it is a bug I'd recommend trying to solve.  If uninstalling triton fixes it, I'd guess it is related to the triton installation, making sure that matches your torch version.  

I'd guess you're not using any triton features in your training?

**Comment by CokeDong** [comment]
> No, missing the pickle file shouldn't impact your results, but it is a bug I'd recommend trying to solve. If uninstalling triton fixes it, I'd guess it is related to the triton installation, making sure that matches your torch version.
> 
> I'd guess you're not using any triton features in your training?

ok, thx. No exactly.

**Comment by loadams** [comment]
@CokeDong - are you still hitting this with the latest DeepSpeed and after uninstalling triton?

**Comment by loadams** [comment]
@CokeDong - closing this for now, if you're still having issues, please reply and we can take a closer look.

**Comment by zigzagcai** [comment]
I also meet this error on `deepspeed==0.10.0`
```
Traceback (most recent call last):
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 145, in _update_autotune_table
    autotune_table = cache_manager.load()
  File "/mnt/zigzagcai/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 73, in load
    with open(self.file_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/zigzagcai/.triton/autotune/Fp16Matmul_4d_kernel.pickle'
  0%|          | 0/68 [01:31<?, ?it/s]
```

**Comment by jp1924** [comment]
Removing the .lock files in the .triton/autotune/ folder has been helpful for me.
