### ISSUE TITLE
Fail to install deepspeed through ./install.sh : ModuleNotFoundError: No module named 'deepspeed'

### ISSUE THREAD

**Issue by visionscaper** [microsoft/DeepSpeed#472]
Hello,

When on the master branch of Deepspeed, installing Deepspeed using `./install.sh` in a virtual python environment fails.
I already tried to use the code at tag `v0.3.0`, but that failed too in another way, as reported [here](https://github.com/microsoft/DeepSpeed/issues/431#issuecomment-708673313).

The result is : 
```
...
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Pygments-2.7.1 alabaster-0.7.12 appdirs-1.4.4 attrs-20.2.0 babel-2.8.0 certifi-2020.6.20 cfgv-3.2.0 chardet-3.0.4 clang-format-9.0.0 commonmark-0.9.1 distlib-0.3.1 docutils-0.16 filelock-3.0.12 identify-1.5.6 idna-2.10 imagesize-1.2.0 importlib-metadata-2.0.0 iniconfig-1.1.1 nodeenv-1.5.0 packaging-20.4 pluggy-0.13.1 pre-commit-2.7.1 py-1.9.0 pyparsing-2.4.7 pytest-6.1.1 pytest-forked-1.3.0 pytz-2020.1 pyyaml-5.3.1 recommonmark-0.6.0 requests-2.24.0 snowballstemmer-2.0.0 sphinx-3.2.1 sphinx-rtd-theme-0.5.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 toml-0.10.1 urllib3-1.25.10 virtualenv-20.0.34 zipp-3.3.0
Removed build tracker: '/tmp/pip-req-tracker-4_ygrx7k'
Traceback (most recent call last):
  File "basic_install_test.py", line 19, in <module>
    raise err
  File "basic_install_test.py", line 16, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'
Error on line 204
Fail to install deepspeed
```

My machine runs Ubuntu:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

This is how I set up the virtual env.
```
$ which python3.7
/usr/bin/python3.7

$ virtualenv -p /usr/bin/python3.7 ~/.virtualenvs/deepspeed

$ source ~/.virtualenvs/deepspeed/bin/activate
```

Cloned Deepspeed:
```
$ git clone git@github.com:microsoft/DeepSpeed.git
$ cd DeepSpeed/
```

I'm at this commit:
```
$ git log HEAD^..HEAD
commit 7ddfda85263890615791b63955b9f5ed28ea2eff (HEAD -> master, origin/master, origin/HEAD)
Author: Jeff Rasley <jerasley@microsoft.com>
Date:   Wed Oct 14 10:44:16 2020 -0700

    Add support for p100 in transformer kernels (#470)
    
    add compute cap of 6.0, support p100
```

**How can I resolve this?**

**Comment by tjruwase** [comment]
@visionscaper, we have recently improved our installation. Can you please retry to see if this issue is now fixed? Thanks.
