### ISSUE TITLE
Triton import error

### ISSUE THREAD

**Issue by renmengjie7** [microsoft/DeepSpeed#4756]
My environment is
```
transformers                  4.34.0
transformers-stream-generator 0.0.4
torch                         2.0.1
flash-attn                    2.0.4
deepspeed                     0.12.2
```

when I try
``` 
import deepspeed
```

I encountered the following error message
```
[2023-12-01 14:33:39,161] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/__init__.py", line 21, in <module>
    from . import ops
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/__init__.py", line 13, in <module>
    from . import transformer
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/__init__.py", line 7, in <module>
    from .inference.config import DeepSpeedInferenceConfig
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/__init__.py", line 7, in <module>
    from ....model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/model_implementations/__init__.py", line 6, in <module>
    from .transformers.ds_transformer import DeepSpeedTransformerInference
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 17, in <module>
    from deepspeed.ops.transformer.inference.triton.mlp import TritonMLP
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/__init__.py", line 10, in <module>
    from .ops import *
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/ops.py", line 8, in <module>
    import deepspeed.ops.transformer.inference.triton.matmul_ext as matmul_ext
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 428, in <module>
    fp16_matmul = Fp16Matmul()
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 177, in __init__
    __class__._read_autotune_table()
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 411, in _read_autotune_table
    TritonMatmul._read_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 133, in _read_autotune_table
    table = cache_manager.load()
  File "/home/.conda/envs/fschat2/lib/python3.9/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 74, in load
    loaded_dict = pickle.load(handle)
EOFError: Ran out of input
```

I can't find the solution. Any suggestions ?
Thank you for your help.

**Comment by loadams** [comment]
Hi @renmengjie7 - how did you install deepspeed?  Also can you try with the latest deepspeed 0.12.5?

**Comment by renmengjie7** [comment]
I just run
```
pip install deepspeed==0.12.2
```

I delete the ~/.triton cache directory, I can run successfully .
But After running some times, the same error occurred. 
Then I delete  the ~/.triton cache directory again, it can run again ...

**Comment by loadams** [comment]
Hi @renmengjie7 - that looks more like a triton issue than a DeepSpeed issue then to me.  Though could you try with the latest DeepSpeed and Triton and see if you see any changes there?

**Comment by loadams** [comment]
Closing this for now as it seems to be more triton related than DeepSpeed related.  Please re-open or comment if more assistance is needed.
