### ISSUE TITLE
[BUG] Compatibility Issue with Pydantic 2.5.2 in DeepSpeed 0.12.5

### ISSUE THREAD

**Issue by tscholak** [microsoft/DeepSpeed#4839]
**Describe the bug**

Encountered a compatibility issue with Pydantic version 2.5.2 when importing DeepSpeedMonitorConfig from DeepSpeed version 0.12.5. The error suggests conflicts with Pydantic's updated configuration keys and a potential namespace conflict with the field "model_persistence_threshold". Additionally, there's an error related to the @root_validator decorator in Pydantic, indicating a need for a change in the implementation to match Pydantic's latest specifications.

**To Reproduce**

1. Environment: Python 3.10.
2. Install DeepSpeed version 0.12.5.
3. Install Pydantic version 2.5.2.
4. Run the following Python code: `from deepspeed.monitor.config import DeepSpeedMonitorConfig`
5. Observe the compatibility warnings and the `PydanticUserError`.

**Expected behavior**

Expected the import of `DeepSpeedMonitorConfig` to work without compatibility issues with Pydantic.

**Screenshots**
```python
>>> from deepspeed.monitor.config import DeepSpeedMonitorConfig
/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 3, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 803, in <module>
    from ..pipe import PipelineModule
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 3, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 3, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 16, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 30, in <module>
    from ..monitor.config import get_monitor_config
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/monitor/config.py", line 70, in <module>
    class DeepSpeedMonitorConfig(DeepSpeedConfigModel):
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/deepspeed/monitor/config.py", line 82, in DeepSpeedMonitorConfig
    def check_enabled(cls, values):
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/home/toolkit/.conda/envs/llmd2/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
>>> 
```

**Comment by mrwyattii** [comment]
Thank you for reporting this @tscholak. We started work to add proper support for pydanticV2 in #3902 but this was delayed due to higher priority tasks. 

I hope to revisit this soon and finish the work. In the meantime, we will likely restrict pydantic to <2.5.0 in our requirements. Can you confirm that older versions work? Thanks!

**Comment by mrwyattii** [comment]
@tscholak I just did a quick test and I'm not able to replicate this error:
```python
.venv ❯ python
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepspeed.monitor.config import DeepSpeedMonitorConfig
>>> DeepSpeedMonitorConfig()
DeepSpeedMonitorConfig(tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName'), wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed'), csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName'), enabled=False)
>>> exit()
.venv ❯ pip list | grep "deepspeed\|pydantic"
deepspeed                0.12.5
pydantic                 2.5.2
pydantic_core            2.14.5

**Comment by tscholak** [comment]
thank you for the feedback! Let me try to replicate it in a fresh environment as well. Best outcome would be if my local env was bust somehow and no change in deepspeed is needed 😉

**Comment by tscholak** [comment]
update: I cannot reproduce it in a fresh environment. I am closing this issue until I can figure out the steps to reproduce. Thanks!
