### ISSUE TITLE
[BUG] Lock file not being released, 2d, 4d kernel line .triton/autotune/Fp16Matmul_2d_kernel.pickle.lock

### ISSUE THREAD

**Issue by vyomakesh09** [microsoft/DeepSpeed#4869]
was just runing pytest on python 3.10 
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 421, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 262, in __enter__
    self.acquire()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 219, in acquire
    _LOGGER.debug("Attempting to acquire lock %s on %s", lock_id, lock_filename)
Message: 'Attempting to acquire lock %s on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 421, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 262, in __enter__
    self.acquire()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 222, in acquire
    _LOGGER.debug("Lock %s acquired on %s", lock_id, lock_filename)
Message: 'Lock %s acquired on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 421, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 278, in __exit__
    self.release()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 251, in release
    _LOGGER.debug("Attempting to release lock %s on %s", lock_id, lock_filename)
Message: 'Attempting to release lock %s on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 421, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 278, in __exit__
    self.release()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 254, in release
    _LOGGER.debug("Lock %s released on %s", lock_id, lock_filename)
Message: 'Lock %s released on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 262, in __enter__
    self.acquire()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 219, in acquire
    _LOGGER.debug("Attempting to acquire lock %s on %s", lock_id, lock_filename)
Message: 'Attempting to acquire lock %s on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 262, in __enter__
    self.acquire()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 222, in acquire
    _LOGGER.debug("Lock %s acquired on %s", lock_id, lock_filename)
Message: 'Lock %s acquired on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 278, in __exit__
    self.release()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 251, in release
    _LOGGER.debug("Attempting to release lock %s on %s", lock_id, lock_filename)
Message: 'Attempting to release lock %s on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 444, in matmul_ext_update_autotune_table
    fp16_matmul._update_autotune_table()
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 422, in _update_autotune_table
    TritonMatmul._update_autotune_table(__class__.__name__ + "_4d_kernel", __class__._4d_kernel)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 150, in _update_autotune_table
    cache_manager.put(autotune_table)
  File "/home/v/.local/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 66, in put
    with FileLock(self.lock_path):
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 278, in __exit__
    self.release()
  File "/home/v/.local/lib/python3.10/site-packages/filelock/_api.py", line 254, in release
    _LOGGER.debug("Lock %s released on %s", lock_id, lock_filename)
Message: 'Lock %s released on %s'
Arguments: (140563492973792, '/home/v/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock')
```

**Comment by mrwyattii** [comment]
Hi @vyomakesh09 can you provide a script and instructions for how to reproduce this error? Thanks

**Comment by vyomakesh09** [comment]
Thank you for reaching back but the issue was resolved

**Comment by vyomakesh09** [comment]
just re-cloned my repo
