### ISSUE TITLE
[BUG] Error: Attempting to get amgpu ISA Details 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by unavailableun** [microsoft/DeepSpeed#4891]
**Describe the bug**

It works well when I install it on a machine with AMD GPUs, while failed to build docker image on a non-gpu machine.
It returns None in triton get_arch_info, then throw below exception:
```
>>> import triton._C.libtriton.triton as _triton
>>> _triton.get_arch_info()
```
 
```log
#17 [14/15] RUN pip install deepspeed==0.12.4
#17 0.825 Collecting deepspeed==0.12.4
#17 0.879   Downloading deepspeed-0.12.4.tar.gz (1.2 MB)
#17 3.489     ERROR: Command errored out with exit status 1:
#17 3.489      command: /opt/conda/envs/ptca/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4icq4j45/deepspeed/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4icq4j45/deepspeed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o11xsn63
#17 3.489          cwd: /tmp/pip-install-4icq4j45/deepspeed/
#17 3.489     Complete output (21 lines):
#17 3.489     Traceback (most recent call last):
#17 3.489       File "<string>", line 1, in <module>
#17 3.489       File "/tmp/pip-install-4icq4j45/deepspeed/setup.py", line 37, in <module>
#17 3.489         from op_builder import get_default_compute_capabilities, OpBuilder
#17 3.489       File "/tmp/pip-install-4icq4j45/deepspeed/op_builder/__init__.py", line 18, in <module>
#17 3.489         import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
#17 3.489       File "/tmp/pip-install-4icq4j45/deepspeed/deepspeed/__init__.py", line 16, in <module>
#17 3.489         import triton  # noqa: F401 # type: ignore
#17 3.489       File "/opt/conda/envs/ptca/lib/python3.8/site-packages/triton/__init__.py", line 20, in <module>
#17 3.489         from .runtime import (
#17 3.489       File "/opt/conda/envs/ptca/lib/python3.8/site-packages/triton/runtime/__init__.py", line 1, in <module>
#17 3.489         from .autotuner import Config, Heuristics, autotune, heuristics
#17 3.489       File "/opt/conda/envs/ptca/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 7, in <module>
#17 3.489         from ..compiler import OutOfResources
#17 3.489       File "/opt/conda/envs/ptca/lib/python3.8/site-packages/triton/compiler.py", line 2025, in <module>
#17 3.489         @static_vars(amdgcn_bitcode_paths = _get_amdgcn_bitcode_paths())
#17 3.489       File "/opt/conda/envs/ptca/lib/python3.8/site-packages/triton/compiler.py", line 2004, in _get_amdgcn_bitcode_paths
#17 3.489         gfx_arch = _get_amdgcn_bitcode_paths.discovered_gfx_arch_fulldetails[1]
#17 3.489     TypeError: 'NoneType' object is not subscriptable
#17 3.489     Error: Attempting to get amgpu ISA Details 'NoneType' object has no attribute 'group'
```

What's the impact of ``HAS_TRITON = False`` only for installing?
```
try:
    import triton  # noqa: F401 # type: ignore
    HAS_TRITON = True
except ImportError:
    HAS_TRITON = False
```
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/__init__.py#L15C1-L20C1

**To Reproduce**
```Docker
RUN  pip install https://download.pytorch.org/whl/rocm5.6/torch-2.1.1%2Brocm5.6-cp38-cp38-linux_x86_64.whl
RUN pip install deepspeed==0.12.4
```

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by loadams** [comment]
@unavailableun - we know that the op_builder has issues with building on machines with a different configuration than the hardware that you are running on.   But a few other questions, what is on the machine you have, any GPUs or just a CPU?  Outside of docker are you able to `pip install deepspeed` on that machine?

**Comment by unavailableun** [comment]
@loadams the installation failure happens on a CPU-only machine. 
Outside of docker, below command succeed.
```bash
pip install pytorch-triton-rocm
pip install deepspeed==0.12.4
```
```log
(test_deepspeed) root@9962e7a8b505:/home/local_git_sources/deeprank/lightning# pip install pytorch-triton-rocm
Collecting pytorch-triton-rocm
  Downloading pytorch_triton_rocm-2.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (169.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.3/169.3 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: cmake>=3.20 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pytorch-triton-rocm) (3.25.0)
Collecting lit
  Downloading lit-17.0.6.tar.gz (153 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.0/153.0 kB 5.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pytorch-triton-rocm) (1.13.0)
Requirement already satisfied: filelock in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pytorch-triton-rocm) (3.8.2)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->pytorch-triton-rocm) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->pytorch-triton-rocm) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->pytorch-triton-rocm) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->pytorch-triton-rocm) (11.7.99)
Requirement already satisfied: typing-extensions in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->pytorch-triton-rocm) (4.8.0)
Requirement already satisfied: setuptools in /opt/conda/envs/ptca/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->pytorch-triton-rocm) (59.5.0)
Requirement already satisfied: wheel in /opt/conda/envs/ptca/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->pytorch-triton-rocm) (0.37.0)
Building wheels for collected packages: lit
  Building wheel for lit (pyproject.toml) ... done
  Created wheel for lit: filename=lit-17.0.6-py3-none-any.whl size=93255 sha256=73e2131c90b28ca6fcce5f4d14fd8ec817a6262dacad65bc78fa5ed29de9365d
  Stored in directory: /root/.cache/pip/wheels/c0/1b/ae/c752907c50ad9673ab23730ee731ce853f2cf69b2d98019dcd
Successfully built lit
Installing collected packages: lit, pytorch-triton-rocm
Successfully installed lit-17.0.6 pytorch-triton-rocm-2.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(test_deepspeed) root@9962e7a8b505:/home/local_git_sources/deeprank/lightning# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
Error: Attempting to get amgpu ISA Details 'NoneType' object has no attribute 'group'
Error: Attempting to get amgpu ISA Details 'NoneType' object has no attribute 'group'
>>> 
(test_deepspeed) root@9962e7a8b505:/home/local_git_sources/deeprank/lightning# pip install deepspeed==0.12.4
Collecting deepspeed==0.12.4
  Using cached deepspeed-0.12.4-py3-none-any.whl
Requirement already satisfied: psutil in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (5.8.0)
Requirement already satisfied: ninja in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (1.11.1)
Requirement already satisfied: packaging>=20.0 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (22.0)
Requirement already satisfied: pydantic in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (2.5.0)
Collecting pynvml
  Downloading pynvml-11.5.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 567.1 kB/s eta 0:00:00
Requirement already satisfied: py-cpuinfo in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (8.0.0)
Requirement already satisfied: tqdm in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (4.64.1)
Requirement already satisfied: hjson in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (3.1.0)
Requirement already satisfied: numpy in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (1.22.3)
Requirement already satisfied: torch in /opt/conda/envs/ptca/lib/python3.8/site-packages (from deepspeed==0.12.4) (1.13.0)
Requirement already satisfied: pydantic-core==2.14.1 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pydantic->deepspeed==0.12.4) (2.14.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pydantic->deepspeed==0.12.4) (4.8.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from pydantic->deepspeed==0.12.4) (0.6.0)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->deepspeed==0.12.4) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->deepspeed==0.12.4) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->deepspeed==0.12.4) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/envs/ptca/lib/python3.8/site-packages (from torch->deepspeed==0.12.4) (11.7.99)
Requirement already satisfied: wheel in /opt/conda/envs/ptca/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->deepspeed==0.12.4) (0.37.0)
Requirement already satisfied: setuptools in /opt/conda/envs/ptca/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->deepspeed==0.12.4) (59.5.0)
Installing collected packages: pynvml, deepspeed
  Attempting uninstall: deepspeed
    Found existing installation: deepspeed 0.7.3
    Uninstalling deepspeed-0.7.3:
      Successfully uninstalled deepspeed-0.7.3
Successfully installed deepspeed-0.12.4 pynvml-11.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

**Comment by loadams** [comment]
So to be sure, this only fails when building a docker image on a CPU only machine?  Can you run pip list before and share that or can you share the whole dockerfile you're attempting to build (or the smallest one that at least repros) so we can take a look?

**Comment by unavailableun** [comment]
Yes, this only fails when building a docker image on a CPU machine.

Here is my docker file, the fbgemm part might be un-necessary for repro:

```docker
FROM singularitybase.azurecr.io/base/job/pytorch/acpt-rocm5.6.1_ubuntu20.04_py3.8_pytorch_2.0.1:20230925T234619269

##########################################################################
# Install Torch 2.1.1
##########################################################################
RUN pip uninstall torch torchvision torchaudio -y && \
    pip install https://download.pytorch.org/whl/rocm5.6/torch-2.1.1%2Brocm5.6-cp38-cp38-linux_x86_64.whl

RUN pip install torchrec==0.5.0 --index-url https://download.pytorch.org/whl/cu118
RUN pip uninstall fbgemm-gpu-cpu fbgemm-gpu -y
RUN python -m pip install pip==20.2.4

##########################################################################
# Build FBGEMM from source, ref: https://pytorch.org/FBGEMM/general/BuildInstructions.html#set-up-for-rocm-build
ENV FBGEMM_VERSION=v0.5.0
ENV WORKSPACE_DIR=/workspace
RUN mkdir -p $WORKSPACE_DIR
WORKDIR $WORKSPACE_DIR
RUN git clone --recursive -b $FBGEMM_VERSION https://github.com/pytorch/FBGEMM.git fbgemm_$FBGEMM_VERSION && \
    cd fbgemm_$FBGEMM_VERSION/fbgemm_gpu && \
    pip install -r requirements.txt && \
    python setup.py clean

# Build and install the library into the Conda environment
WORKDIR $WORKSPACE_DIR
RUN cd fbgemm_$FBGEMM_VERSION/fbgemm_gpu && \
    export ROCM_PATH=/opt/rocm && \
    export PYTORCH_ROCM_ARCH="gfx900;gfx906;gfx908;gfx90a;gfx1030" && \
    python setup.py install \
    -DHIP_ROOT_DIR="${ROCM_PATH}" \
    -DCMAKE_C_FLAGS="-DTORCH_USE_HIP_DSA" \
    -DCMAKE_CXX_FLAGS="-DTORCH_USE_HIP_DSA"

##########################################################################
# Install dependencies
RUN pip install \
        addict==2.4.0 \
        autoflake==1.4 \
        azureml-core==1.50.0 \
        azureml-mlflow==1.50.0 \
        azure-mgmt-core==1.3.2 \
        black==21.7b0 \
        click==8.0.4 \
        confluent-kafka==1.9.0 \
        deepspeed==0.12.4 \
        faiss-cpu==1.7.2 \
        flake8==3.9.2 \
        flatbuffers==22.9.24 \
        hydra-core==1.1.1 \
        importlib_resources==5.12.0 \
        isort==5.7.0 \
        mlflow==2.8.1 \
        numpy==1.22.3 \
        omegaconf==2.1.1 \
        onnx==1.12 \
        onnxruntime==1.12.1 \
        protobuf==3.19.4 \
        psutil==5.8.0 \
        pylint==2.10.2 \
        pytorch-lightning==2.1.2 \
        sentencepiece==0.1.96 \
        sort-requirements==1.3.0 \
        tdigest==0.5.2.2 \
        torch-tb-profiler==0.4.0 \
        torchmetrics==1.0.3 \
        transformers==4.19.1 \
        zstd==1.5.2.5 \
        mmh3==3.0.0 \
        pyarrow==10.0.1 \
        polars==0.17.0


# Dump package list
RUN pip list
```

**Comment by loadams** [comment]
Hi @unavailableun - are you still hitting this with the latest DeepSpeed?  And if so could you let us know?
