### ISSUE TITLE
[BUG] async_io error on Ubuntu during installation of deepspeed version 0.11.0

### ISSUE THREAD

**Issue by ViEm-ccy** [microsoft/DeepSpeed#4968]
I can't install DeepSpeed 0.11.0 because an async_io error.
I have tried to install it from pip or from the source code, like:
`DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 DS_BUILD_EVOFORMER_ATTN=0 pip install deepspeed==0.11.0`
`DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 DS_BUILD_EVOFORMER_ATTN=0 python setup.py bdist_wheel`

And they throw the same error:
```
Collecting deepspeed==0.11.0
  Using cached deepspeed-0.11.0.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      [2024-01-17 19:02:00,848] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      [2024-01-17 19:02:01,854] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jon5mrdm/deepspeed_34216c31896a40589d6b0a9bd14c6008/setup.py", line 182, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "/tmp/pip-install-jon5mrdm/deepspeed_34216c31896a40589d6b0a9bd14c6008/setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
[2024-01-17 18:48:07,445] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-17 18:48:08,184] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
DS_BUILD_OPS=1
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
Traceback (most recent call last):
  File "setup.py", line 182, in <module>
    abort(f"Unable to pre-compile {op_name}")
  File "setup.py", line 52, in abort
    assert False, msg
AssertionError: Unable to pre-compile async_io
```

I'm sure that I have installed the libaio-dev library by apt-get:
```
$ sudo apt-get install libaio-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libaio-dev
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
Need to get 0 B/13.7 kB of archives.
After this operation, 64.5 kB of additional disk space will be used.
Selecting previously unselected package libaio-dev:amd64.
(Reading database ... 114659 files and directories currently installed.)
Preparing to unpack .../libaio-dev_0.3.112-5_amd64.deb ...
Unpacking libaio-dev:amd64 (0.3.112-5) ...
Setting up libaio-dev:amd64 (0.3.112-5) ...
Processing triggers for man-db (2.9.1-1) ...
```

And I have tried to append my library path to CPATH and LD_LIBRARY_PATH, but it still dosen't work.
I have no idea how to fix it.

**System info :**
 - OS: Ubuntu 20.04
 - GPU count and types： 8x A800
 - Python version: Python 3.8.17
 - Pytorch Version:  '2.1.0+cu121'

And for cuda-toolkit version:
```
$ conda list | grep cuda                                                                                                             
cuda-cccl                 12.1.109                      0    nvidia/label/cuda-12.1.1                    
cuda-command-line-tools   12.1.1                        0    nvidia/label/cuda-12.1.1
cuda-compiler             12.1.1                        0    nvidia/label/cuda-12.1.1                    
cuda-cudart               12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-cudart-dev           12.1.105                      0    nvidia/label/cuda-12.1.1
cuda-cudart-static        12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-cuobjdump            12.3.101                      0    nvidia                                  
cuda-cupti                12.1.105                      0    nvidia/label/cuda-12.1.1
cuda-cupti-static         12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-cuxxfilt             12.3.101                      0    nvidia                  
cuda-documentation        12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-driver-dev           12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-gdb                  12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-libraries            12.1.1                        0    nvidia/label/cuda-12.1.1
cuda-libraries-dev        12.1.1                        0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-libraries-static     12.1.1                        0    nvidia/label/cuda-12.1.1
cuda-nsight               12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-nsight-compute       12.1.1                        0    nvidia/label/cuda-12.1.1                    
cuda-nvcc                 12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-nvdisasm             12.1.105                      0    nvidia/label/cuda-12.1.1
cuda-nvml-dev             12.1.105                      0    nvidia/label/cuda-12.1.1 
cuda-nvml-dev             12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                      
cuda-nvprof               12.1.105                      0    nvidia/label/cuda-12.1.1
cuda-nvprune              12.3.101                      0    nvidia                                                                                                                                                
cuda-nvrtc                12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-nvrtc-dev            12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-nvrtc-static         12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-nvtx                 12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-nvvp                 12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-opencl               12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-opencl-dev           12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-profiler-api         12.1.105                      0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-sanitizer-api        12.1.105                      0    nvidia/label/cuda-12.1.1                    
cuda-toolkit              12.1.1                        0    nvidia/label/cuda-12.1.1                                                                                                                              
cuda-tools                12.1.1                        0    nvidia/label/cuda-12.1.1                    
cuda-visual-tools         12.1.1                        0    nvidia/label/cuda-12.1.1                                                                                                     
gds-tools                 1.6.1.9                       0    nvidia/label/cuda-12.1.1             
libcublas                 12.1.3.1                      0    nvidia/label/cuda-12.1.1                    
libcublas-dev             12.1.3.1                      0    nvidia/label/cuda-12.1.1              
libcublas-static          12.1.3.1                      0    nvidia/label/cuda-12.1.1                    
libcufft                  11.0.2.54                     0    nvidia/label/cuda-12.1.1
libcufft-dev              11.0.2.54                     0    nvidia/label/cuda-12.1.1                    
libcufft-static           11.0.2.54                     0    nvidia/label/cuda-12.1.1                    
libcufile                 1.6.1.9                       0    nvidia/label/cuda-12.1.1                    
libcufile-dev             1.6.1.9                       0    nvidia/label/cuda-12.1.1                                                                                                                              
libcufile-static          1.6.1.9                       0    nvidia/label/cuda-12.1.1
libcurand                 10.3.2.106                    0    nvidia/label/cuda-12.1.1
libcurand-dev             10.3.2.106                    0    nvidia/label/cuda-12.1.1
libcurand-static          10.3.2.106                    0    nvidia/label/cuda-12.1.1
libcusolver               11.4.5.107                    0    nvidia/label/cuda-12.1.1
libcusolver-dev           11.4.5.107                    0    nvidia/label/cuda-12.1.1
libcusolver-static        11.4.5.107                    0    nvidia/label/cuda-12.1.1
libcusparse               12.1.0.106                    0    nvidia/label/cuda-12.1.1
libcusparse-dev           12.1.0.106                    0    nvidia/label/cuda-12.1.1
libcusparse-static        12.1.0.106                    0    nvidia/label/cuda-12.1.1
libnpp                    12.1.0.40                     0    nvidia/label/cuda-12.1.1
libnpp-dev                12.1.0.40                     0    nvidia/label/cuda-12.1.1
libnpp-static             12.1.0.40                     0    nvidia/label/cuda-12.1.1
libnvjitlink              12.1.105                      0    nvidia/label/cuda-12.1.1
libnvjitlink-dev          12.1.105                      0    nvidia/label/cuda-12.1.1
libnvjpeg                 12.2.0.2                      0    nvidia/label/cuda-12.1.1
libnvjpeg-dev             12.2.0.2                      0    nvidia/label/cuda-12.1.1
libnvjpeg-static          12.2.0.2                      0    nvidia/label/cuda-12.1.1
libnvvm-samples           12.1.105                      0    nvidia/label/cuda-12.1.1
nsight-compute            2023.1.1.4                    0    nvidia/label/cuda-12.1.1
nvidia-cuda-nvrtc-cu12    12.3.107                 pypi_0    pypi 
```

**Comment by loadams** [comment]
@ViEm-ccy - two questions, do you need to be using DeepSpeed 0.11.0?  Could you try with the latest as well so we could more easily test this?  And second, are you using/do you need to precompile the DS_BUILD_AIO op?

**Comment by ViEm-ccy** [comment]
> @ViEm-ccy - two questions, do you need to be using DeepSpeed 0.11.0? Could you try with the latest as well so we could more easily test this? And second, are you using/do you need to precompile the DS_BUILD_AIO op?

I use deepspeed to accelerate the inference, and 0.11.0 is compatible for my training environment torch 2.1.0 which complie with cuda 12.1.1.

**Comment by ViEm-ccy** [comment]
@loadams  Thanks for your advice.
I tried to install with DS_BUILD_AIO=0, and it still failed because I missed some libraries like g++.
After I installed these libraries, the error above never occurred again, even when I set DS_BUILD_AIO to 1.
I should have checked the compiler first as soon as it threw a 'pre-compile error'.

**Comment by weibo021** [comment]
> @loadams Thanks for your advice. I tried to install with DS_BUILD_AIO=0, and it still failed because I missed some libraries like g++. After I installed these libraries, the error above never occurred again, even when I set DS_BUILD_AIO to 1. I should have checked the compiler first as soon as it threw a 'pre-compile error'.

System info :

OS: Ubuntu 18.04
GPU count and types： 2x 3090
Python version: Python 3.8918
Pytorch Version: '2.1.0+cu118'
g++：7.5.0
cmake: 3.25.0

Apart from sparce_attn, which won't install because of the high pytorch version, it's mainly an AIO issue, although I've installed libaio-dev and tried installing the conda version of libaio. i'd like to know what other libraries you've installed, apart from g++.

**Comment by ViEm-ccy** [comment]
> > @loadams Thanks for your advice. I tried to install with DS_BUILD_AIO=0, and it still failed because I missed some libraries like g++. After I installed these libraries, the error above never occurred again, even when I set DS_BUILD_AIO to 1. I should have checked the compiler first as soon as it threw a 'pre-compile error'.
> 
> System info :
> 
> OS: Ubuntu 18.04 GPU count and types： 2x 3090 Python version: Python 3.9.18 Pytorch Version: '2.1.0+cu118' g++：7.5.0 cmake: 3.25.0
> 
> Apart from sparce_attn, which won't install because of the high pytorch version, it's mainly an AIO issue, although I've installed libaio-dev and tried installing the conda version of libaio. i'd like to know what other libraries you've installed, apart from g++.


I don't remember other libs I installed.

Sometimes the message in the installtion program is confused if you chooes too many ops to install.
I recommend you to install with only the ops you need, and find more accurate error messages.
