### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'numel'

### ISSUE THREAD

**Issue by Ino4811** [microsoft/DeepSpeed#5019]
when i was training llama2-7b-chat with peft(lora), AttributeError occurs.
 
```
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    trainer.train()
  File "usr/.local/lib/python3.8/site-packages/trl/trainer/sft_trainer.py", line 323, in train
    output = super().train(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "usr/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "usr/.local/lib/python3.8/site-packages/transformers/trainer.py", line 2744, in training_step
    self.accelerator.backward(loss)
  File "usr/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 1899, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1964, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 2152, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "usr/.local/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "usr/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "usr/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "usr/.local/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "usr/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "usr/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1129, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1422, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1163, in reduce_independent_p_g_buckets_and_remove_grads
    self.__reduce_and_partition_ipg_grads()
  File "usr/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "usr/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 1193, in __reduce_and_partition_ipg_grads
    if param.grad.numel() != param.ds_numel:
AttributeError: 'NoneType' object has no attribute 'numel'
``` 
I can load model and start training.
However, during execution, an error occurs at the same step and the program stops.
```
{'loss': 0.8804, 'learning_rate': 0.0009444444444444445, 'epoch': 0.22}
{'loss': 0.51, 'learning_rate': 0.0008888888888888888, 'epoch': 0.44}
{'loss': 0.4295, 'learning_rate': 0.0008333333333333334, 'epoch': 0.67}
{'loss': 0.3746, 'learning_rate': 0.0007777777777777778, 'epoch': 0.89}
{'loss': 0.3622, 'learning_rate': 0.0007222222222222222, 'epoch': 1.11}
{'loss': 0.3326, 'learning_rate': 0.0006666666666666666, 'epoch': 1.33}
{'loss': 0.3409, 'learning_rate': 0.0006111111111111112, 'epoch': 1.56}
{'loss': 0.3235, 'learning_rate': 0.0005555555555555556, 'epoch': 1.78}
{'loss': 0.3473, 'learning_rate': 0.0005, 'epoch': 2.0}
{'loss': 0.3, 'learning_rate': 0.0004444444444444444, 'epoch': 2.22}
{'loss': 0.3098, 'learning_rate': 0.0003888888888888889, 'epoch': 2.44}
 66%|██████████████████████████████████████████████████████████████▏                               | 119/180 [18:45<09:56,  9.77s/it]
``` 
this is zero3's config 

```
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "eps": 1e-8
        }
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

please help me!

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python 3.8
 - GPU V100(32GB) & QuadroRTX8000(48GB)

**Comment by Ino4811** [comment]
this is because of my training code error. I adopt NVMe 's example but this is not my expected work.

**Comment by thkimYonsei** [comment]
Hello, I got the same error. Can you explain to me what causes this error?
I don't use any custom trainer and in the for loop I create new trainer with new datalist (with the same model) and call trainer.train().
It works well for the first iteration, but for the second iteration, I got the same error as yours. 
Can you help me??

**Comment by Ino4811** [comment]
I forgot where I modified the code, but I still remember that my training code was wrong. To repair the error, I read huggingface docs and changed train.py. 

this is my train.py that was modified and works correctly.
