### ISSUE TITLE
[BUG] after build deepspeed on windows,there is no deepspeed entry

### ISSUE THREAD

**Issue by zxy1123** [microsoft/DeepSpeed#5069]
OS:  windows 10
Problem : after build deepspeed on windows,there is no deepspeed entry , i know deepspeed do not support training on windows,but why?

**Comment by ZJDATY** [comment]
大兄弟，你是怎么构建的 。 windows下 使用` pip install deepspeed` 。会报错 找不到 “aio.lib” 。然后我把源码 git 到本地后 。运行`build_win.bat  ` ，会继续报错

Big brother, how did you build it. Use 'pip install deepspeed' under Windows. An error message will appear indicating that "aio. lib" cannot be found. Then I git the source code locally. Run ` build_ Win. bat `, will continue to report errors

```
(chat) D:\pyworkspaces\DeepSpeed>build_win.bat
Administrative permissions required. Detecting permissions...
Success: Administrative permissions confirmed.
DS_BUILD_OPS=1
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
系统找不到指定的文件。
 [WARNING]  cpu_adam requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
系统找不到指定的文件。
 [WARNING]  cpu_adam requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
系统找不到指定的文件。
 [WARNING]  cpu_adagrad requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
系统找不到指定的文件。
 [WARNING]  cpu_adagrad requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
系统找不到指定的文件。
 [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
系统找不到指定的文件。
 [WARNING]  cpu_lion requires the 'lscpu' command, but it does not exist!
 [WARNING]  cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  One can disable evoformer_attn with DS_BUILD_EVOFORMER_ATTN=0
 [ERROR]  Unable to pre-compile evoformer_attn
Traceback (most recent call last):
  File "D:\pyworkspaces\DeepSpeed\setup.py", line 182, in <module>
    abort(f"Unable to pre-compile {op_name}")
  File "D:\pyworkspaces\DeepSpeed\setup.py", line 52, in abort
    assert False, msg
AssertionError: Unable to pre-compile evoformer_attn
(chat) D:\pyworkspaces\DeepSpeed>
```
所以我做错了哪里，应该怎么构建？

So where did I go wrong and how should I build it?

**Comment by loadams** [comment]
DeepSpeed for Windows is not well supported.  Some features, such as AIO and DeepSpeed-Kernels require linux.  There are other open issues where users have shared workarounds, but we have not yet had the bandwidth to support it fully.

If you are able to, using WSL on Windows will allow full DeepSpeed features and is much easier to install currently.
