### ISSUE TITLE
[BUG] FP32 gradient accumulation result in crash.

### ISSUE THREAD

**Issue by torshie** [microsoft/DeepSpeed#5174]
**Describe the bug**
* Enable BF16 training
* Set gradient accumulation types to FP32
* Enable ZeRO-1, and CPU offload
* Enable overlap_comm
* Tune train batch size so that gradient accumulation step is 1

Training crashes with the following log:
```
Traceback (most recent call last):
  File "/tmp/bug.py", line 49, in <module>
    engine.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1974, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2062, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 899, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1412, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 946, in reduce_independent_p_g_buckets_and_remove_grads
    new_grad_tensor.copy_(grad_reduc.view(-1))
AttributeError: 'NoneType' object has no attribute 'view'
```

**To Reproduce**
Source code:
```python
import torch
import deepspeed


ds_config = {
    'bf16': {
        'enabled': True
    },
    'zero_optimization': {
        'stage': 1,
        'overlap_comm': True,
        'offload_param': {
            "device": "cpu",
            "pin_memory": True,
            "max_in_cpu": 4e11
        },
        'offload_optimizer': {
            "device": "cpu",
            "pin_memory": True
        }
    },
    'data_types': {
        'grad_accum_dtype': 'fp32'
    },
    'train_batch_size': 2,
    'train_micro_batch_size_per_gpu': 1
}


class Bug(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.p = torch.nn.Parameter(torch.tensor(1.0))

    def forward(self, x):
        return torch.sum(x + self.p)


model = Bug()

engine, optimizer, *_ = deepspeed.initialize(
        model=model,
        optimizer=deepspeed.ops.adam.DeepSpeedCPUAdam(model.parameters()),
        config=ds_config)

x = torch.tensor([1.0, 2.0, 3.0], device=model.p.device)
loss = engine(x)
engine.backward(loss)
engine.step()
```

Startup command:
```
torchrun --nnode=1 --node-rank=0 --nproc-per-node=2 bug.py
```

**Expected behavior**
Nice and smooth training

**ds_report output**
```
[2024-02-22 16:44:16,482] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.10/dist-packages/torch']
torch version .................... 2.1.0a0+32f93b1
deepspeed install path ........... ['/usr/local/lib/python3.10/dist-packages/deepspeed']
deepspeed info ................... 0.13.2, unknown, unknown
torch cuda version ............... 12.2
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.2
shared memory (/dev/shm) size .... 512.00 GB
```

**Launcher context**
launch with `torchrun`

**Comment by ononoki1** [comment]
The same happens with FP16. I set `gradient_accumulation_steps` to 2 as a temporary solution.

**Comment by tjruwase** [comment]
@torshie, can you please try with zero stage 2?

**Comment by torshie** [comment]
@tjruwase Just tested, zero stage 2 is fine.

**Comment by tjruwase** [comment]
@torshie, thanks for the update. We have only tested cpu-offload with zero stage 2, but not with stage 1. I hope you zero stage 2 can work for your scenario, as we currently lack bandwidth to support zero stage 1.
