### ISSUE TITLE
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

### ISSUE THREAD

**Issue by robinsonmhj** [microsoft/DeepSpeed#5179]
**Describe the bug**
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

**To Reproduce**
1. Load llama2 70b using  model = AutoModelForSequenceClassification.from_pretrained(model_name,return_dict=True, device_map='auto')
2. After the model is loaded into RAM, use deepspeed to initialize, see the code below

```
model, optimizer, _, lr_scheduler = deepspeed.initialize(
        model=model,
        model_parameters=model.parameters(),
        config=deepspeed_config,
    )
```
```
deepspeed_config = {
    "optimizer": {
          "type": "Adam",
            "params": {
                "lr": 0.001,
                "betas": [0.8,0.999],
                "eps": 1e-8,
                "weight_decay": 3e-7
            },
    },
    "scheduler": {"type": "WarmupLR", "params": {"warmup_num_steps": 100}},
    "fp16": {
        "enabled": False,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {"enabled": True},  # Turn this on if using AMPERE GPUs.
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": True
        },
        "stage3_gather_16bit_weights_on_model_save": True,
    },
    "gradient_accumulation_steps": 1,
    "gradient_clipping": True,
    "steps_per_print": 10,
    "train_micro_batch_size_per_gpu": 16,
    "wall_clock_breakdown": False,
}
```
3. get the error below
```
(RayTrainWorker pid=7426, ip=10.68.15.27) WARNING:accelerate.big_modeling:You shouldn't move a model when it is dispatched on multiple devices.
2024-02-23 11:57:22,590 ERROR tune_controller.py:1374 -- Trial task failed for trial TorchTrainer_6306b_00000
Traceback (most recent call last):
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::_Inner.train() (pid=7340, ip=10.68.15.27, actor_id=de0788af67de4716ef5e7cec04000000, repr=TorchTrainer)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 43, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(RuntimeError): ray::_RayTrainWorker__execute.get_next() (pid=7426, ip=10.68.15.27, actor_id=8d63a99cb9e465d80c44aac604000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f716a288be0>)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 118, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/tmp/ray/session_2024-02-23_11-40-12_197437_1/runtime_resources/working_dir_files/_ray_pkg_1ad453e1c1b1c642/llama_ray_2.9.py", line 138, in train_func
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/opt/conda/envs/domino-ray/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1113, in _configure_distributed_model
    self.module.to(self.device)
  File "/tmp/ray/session_2024-02-23_11-40-12_197437_1/runtime_resources/pip/d655feed06e5b3f74aa75e5904ec6ae8a9ca09f8/virtualenv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 447, in wrapper
    raise RuntimeError("You can't move a model that has some modules offloaded to cpu or disk.")
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.
```

**Expected behavior**
deepspeed initlization finished

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Two nodes with 8 NVIDIA Tesla V100 GPU
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python 3.10
 - Deepspeed==0.13.2

**Comment by robinsonmhj** [comment]
@lekurile can you take a look this issue?

**Comment by loadams** [comment]
Hi @robinsonmhj are you still seeing this issue?

**Comment by loadams** [comment]
@Phocuser - we've published updated Windows whls for the latest release, otherwise closing this issue as it appears to have no repsonses.
