### ISSUE TITLE
[BUG]Cannot install deepspeed when cuda is installed by a non-root user

### ISSUE THREAD

**Issue by cooper12121** [microsoft/DeepSpeed#5189]
**Describe the bug**
I have already installed the nvcc here (without root), but I get an error when pip install deepspeed .
```
$  which nvcc
/mnt/nlp/gaoqiang/cuda/cuda-12.0/bin/nvcc
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

$ echo $CUDA_HOME
/mnt/nlp/gaoqiang/cuda/cuda-12.0/

$echo $PATH
/home/gaoqiang/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/remote-cli:/mnt/nlp/gaoqiang/miniconda3/envs/deepseekMoE1/bin:/mnt/nlp/gaoqiang/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/mnt/nlp/gaoqiang/cuda/cuda-12.0/bin:/mnt/nlp/gaoqiang/cuda/cuda-12.0/bin
```

**OS**
```Linux AuroraStation 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```

**output**

```
pip install deepspeed
Defaulting to user installation because normal site-packages is not writeable
Collecting deepspeed
  Using cached deepspeed-0.13.3.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-46kb5itk/deepspeed_83bd7c100d41430c9a3b2422c7d61dfd/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-46kb5itk/deepspeed_83bd7c100d41430c9a3b2422c7d61dfd/op_builder/builder.py", line 52, in installed_cuda_version
          output = subprocess.check_output([cuda_home + "/bin/nvcc", "-V"], universal_newlines=True)
        File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: ':/mnt/nlp/gaoqiang/cuda/cuda-12.0:/mnt/nlp/gaoqiang/cuda/cuda-12.0/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I don't understand why the paths are nested when looking for nvcc
No such file or directory: ':/mnt/nlp/gaoqiang/cuda/cuda-12.0:/mnt/nlp/gaoqiang/cuda/cuda-12.0/bin/nvcc'

**Comment by Vicent0205** [comment]
Same issue!

**Comment by Y-Helios** [comment]
Same issue! 
And when I use ` python -c "import torch.utils.cpp_extension; print(torch.utils.cpp_extension.CUDA_HOME)"`, it outputs "none"
