### ISSUE TITLE
[BUG]when i use deepspeed to finetune a model, the cuda memory oom because input a 128k data. How can i start training.

### ISSUE THREAD

**Issue by MarsMeng1994** [microsoft/DeepSpeed#5295]
error
`Traceback (most recent call last):
  File "/cpfs01/shared/public/msm/workspace/LLaMA-Factory/exp/minicpm-longrope/src/train_bash.py", line 14, in <module>
    main()
  File "/cpfs01/shared/public/msm/workspace/LLaMA-Factory/exp/minicpm-longrope/src/train_bash.py", line 5, in main
    run_exp()
  File "/cpfs01/shared/public/msm/workspace/LLaMA-Factory/exp/minicpm-longrope/src/llmtuner/train/tuner.py", line 31, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/cpfs01/shared/public/msm/workspace/LLaMA-Factory/exp/minicpm-longrope/src/llmtuner/train/sft/workflow.py", line 75, in run_sft
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2772, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2795, in compute_loss
    outputs = model(**inputs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/cpfs01/shared/public/msm/workspace/software/miniconda3/envs/llama_factory/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/cpfs01/shared/public/msm/workspace/software/miniconda3/envs/llama_factory/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/cpfs01/shared/public/msm/workspace/software/miniconda3/envs/llama_factory/lib/python3.10/site-packages/peft/peft_model.py", line 1083, in forward
    return self.base_model(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/cpfs01/shared/public/msm/workspace/software/miniconda3/envs/llama_factory/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/huchuanrui/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-bf16-128k/modeling_minicpm.py", line 1199, in forward
    outputs = self.model(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huchuanrui/.cache/huggingface/modules/transformers_modules/MiniCPM-2B-dpo-bf16-128k/modeling_minicpm.py", line 1051, in forward
    attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 398, in _prepare_4d_causal_attention_mask_for_sdpa
    expanded_4d_mask = attn_mask_converter.to_4d(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 121, in to_4d
    causal_4d_mask = self._make_causal_mask(
  File "/home/huchuanrui/.local/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 158, in _make_causal_mask
    mask.masked_fill_(mask_cond < (mask_cond + 1).view(mask.size(-1), 1), 0)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 GiB. GPU 1 has a total capacty of 79.35 GiB of which 3.99 GiB is free. Process 2733 has 75.35 GiB memory in use. Of the allocated memory 72.68 GiB is allocated by PyTorch, and 308.96 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-03-18 06:54:54,984] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 2783226
[2024-03-18 06:54:55,722] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 2783227`

train.sh

deepspeed --include localhost:0,1 --master_port 29000 src/train_bash.py \
    --deepspeed ds_config.json \
    --stage sft \
    --do_train \
    --model_name_or_path $path_to_llama_model \
    --dataset $dataset \
    --template default \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir $path_to_checkpoint \
    --overwrite_output_dir \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 50 \
    --learning_rate 1e-6 \
    --num_train_epochs 2 \
    --plot_loss \
    --streaming \
    --max_steps 400 \
    --cutoff_len 131072 \
    --fp16

deepspeed ds_config.json 
{
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_optimization": {
    "stage": 2,
    "offload_optimizer": {      
      "device": "cpu"
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "overlap_comm": false,
    "contiguous_gradients": true
  }
}

**Comment by vuyelwadr** [comment]
I have the same, did you find a solution
