### ISSUE TITLE
On the training problem of mixed-precision fp16

### ISSUE THREAD

**Issue by Ist-Zhy** [microsoft/DeepSpeed#5331]
json = {
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 1, 
    "optimizer": {
        "type": "Adam", 
        "params": {
            "lr": 0.001, 
            "betas": [0.8, 0.999], 
            "eps": 1e-08, 
            "weight_decay": 3e-07
        }
    }, 
    "scheduler": {
        "type": "WarmupLR", 
        "params": {
            "warmup_min_lr": 0, 
            "warmup_max_lr": 0.001, 
            "warmup_num_steps": 1000
        }
    }, 
    "activation_checkpointing": {
        "partition_activations": true, 
        "cpu_checkpointing": true, 
        "contiguous_memory_optimization": false, 
        "number_checkpoints": null, 
        "synchronize_checkpoint_boundary": false, 
        "profile": true
    }, 
    "fp16": {
        "enabled": "auto", 
        "loss_scale": 0, 
        "initial_scale_power": 16, 
        "loss_scale_window": 1000, 
        "hysteresis": 2, 
        "consecutive_hysteresis": false, 
        "min_loss_scale": 1
    }, 
    "zero_optimization": {
        "stage": 3, 
        "offload_param": {
            "device": "cpu", 
            "pin_memory": true
        }, 
        "offload_optimizer": {
            "device": "cpu", 
            "pin_memory": true
        }, 
        "contiguous_gradients": true, 
        "overlap_comm": true
    }
}
Traceback (most recent call last):
  File "/home/ubuntu/BLIP2/distributed_training.py", line 129, in <module>
    train_fusion(logger)
  File "/home/ubuntu/BLIP2/distributed_training.py", line 87, in train_fusion
    data_fuse = model_engine(data_VIS, data_IR)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/BLIP2/Net.py", line 755, in forward
    x_vi, x_ir = self.forward_features(x_vi, x_ir)
  File "/home/ubuntu/BLIP2/Net.py", line 728, in forward_features
    x_vi, x_ir = layer(x_vi, x_ir, x_vi_size, x_ir_size)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/BLIP2/Net.py", line 594, in forward
    out_vi, out_ir = self.FSAS_MMF(unembed_result_vi, unembed_result_ir)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/BLIP2/Net.py", line 501, in forward
    output_1 = self.project_out_1(output_1)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/BLIP-2/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by superhero-7** [comment]
do you solve this problem?

**Comment by sfc-gh-truwase** [comment]
Closing due to lack of further activity. The stack trace suggests that input should be down-casted to fp16 for mixed-precision training. Please re-open if needed.
