### ISSUE TITLE
pip install deepspeed error ：Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by DreamPuNi** [microsoft/DeepSpeed#5335]
(venv) D:\test_pograming\Yi-main>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.14.0.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "D:\test_pograming\Yi-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\test_pograming\Yi-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\test_pograming\Yi-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HeSongsheng\AppData\Local\Temp\pip-build-env-25w0rr_x\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HeSongsheng\AppData\Local\Temp\pip-build-env-25w0rr_x\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\HeSongsheng\AppData\Local\Temp\pip-build-env-25w0rr_x\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\HeSongsheng\AppData\Local\Temp\pip-build-env-25w0rr_x\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 148, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
my system is windows10, and this enviroment`s cuda version is 11.7, my pytorch version is 2.0.0, so why it cannot install ,god please help me QAQ,

**Comment by DreamPuNi** [comment]
pleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleasepleaseplease help help me TAT

**Comment by risedangel** [comment]
can you run the following commands in the same venv? it seems there is a problem with your torch installation

`torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.get_device_name(0)
`

**Comment by DreamPuNi** [comment]
thanks, it looks like there`s something wrong with my cuda enviroment, i will reinstall my system, it`s too confusing
