### ISSUE TITLE
Pip failure subprocess-exited-with-error

### ISSUE THREAD

**Issue by cityduck0707** [microsoft/DeepSpeed#5344]
I can't figure it out .. Plz Help me!! I am going CRAZY!!! 

===========<BELOW>================
![캡처](https://github.com/microsoft/DeepSpeed/assets/165686631/bd46286f-0c86-41fc-8e85-893d474021b2)

![캡처2](https://github.com/microsoft/DeepSpeed/assets/165686631/048d5efc-62c1-4144-b415-59f3b2653f0f)

$ pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.14.0.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "C:\Users\ORORI\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ORORI\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ORORI\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ORORI\AppData\Local\Temp\pip-build-env-hz1h05nk\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ORORI\AppData\Local\Temp\pip-build-env-hz1h05nk\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ORORI\AppData\Local\Temp\pip-build-env-hz1h05nk\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ORORI\AppData\Local\Temp\pip-build-env-hz1h05nk\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 148, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by loadams** [comment]
@cityduck0707 - can you share more details on your system?  It looks like you have torch installed, but then this isn't being found by DeepSpeed?  Additionally, at your terminal can you run these commands?

```
python -c "import torch; print('torch:', torch.__version__, torch)"
python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

**Comment by cityduck0707** [comment]
@loadams 
Oh, I have something else to tell you. 
Someone told me that it works if I run the code with the Anaconda prompt. 
So I tried running the code on the Anaconda prompt as shown in the following picture, 
but the subprocess error occurred again this time. 
But the error was a little different. 
<Python setup.py egg_infodid not successfully.>
![아나콘다_딥스피드](https://github.com/microsoft/DeepSpeed/assets/165686631/79a14110-e646-4646-939e-4a29b222bd98)

**Comment by loadams** [comment]
@cityduck0707 - my guess is that your python path is not set in each of these, and then that perhaps each has its own version of python/its own virtual environment so torch may not be installed in each.  Unfortunately, working with Python on Windows can be tricky.  If you're able, using WSL should resolve many of these issues.  If not, I'd pick which environment you want to install DeepSpeed in, and ensure that you have torch installed there (via pip list and the two commands listed above).  If those pass, then try installing DeepSpeed and if you hit errors, please share those with us.

**Comment by loadams** [comment]
Hi @cityduck0707 - closing this as stale, please comment if you are still hitting this and need it re-opened.
