### ISSUE TITLE
Deepspeed module not being able to install in the WSL environment

### ISSUE THREAD

**Issue by SAMARTH-VAGRAWAL** [microsoft/DeepSpeed#5441]
Collecting deepspeed==0.13.0
  Using cached deepspeed-0.13.0.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      Traceback (most recent call last):
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/xpu/builder.py", line 14, in <module>
          from op_builder.builder import OpBuilder, TORCH_MAJOR, TORCH_MINOR
      ImportError: cannot import name 'TORCH_MAJOR' from 'op_builder.builder' (/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/builder.py)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/setup.py", line 37, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/__init__.py", line 48, in <module>
          module = importlib.import_module(f".{module_name}", package=op_builder_dir)
        File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/xpu/__init__.py", line 6, in <module>
          from .cpu_adam import CPUAdamBuilder
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/xpu/cpu_adam.py", line 6, in <module>
          from .builder import SYCLOpBuilder
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/op_builder/xpu/builder.py", line 16, in <module>
          from deepspeed.ops.op_builder.builder import OpBuilder, TORCH_MAJOR, TORCH_MINOR
        File "/tmp/pip-install-eodl07kr/deepspeed_82bf4b0c5fa04480b3c1d668526665e6/deepspeed/__init__.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by loadams** [comment]
Hi @SAMARTH-VAGRAWAL - this error looks like python isn't able to find torch installed in your environment.  Can you please run and share the output of `pip list` or `python -c "import torch; print('torch:', torch.__version__, torch)"`?

**Comment by loadams** [comment]
Closing due to no reply - @SAMARTH-VAGRAWAL, I believe my above comment is likely the source of the issue, not anything in DeepSpeed, but if you are still having problems, please comment and we can reopen.
