### ISSUE TITLE
Cannot create wheel for version 0.14.2

### ISSUE THREAD

**Issue by thanhchauns2** [microsoft/DeepSpeed#5442]
I tried to build wheel on my local computer but it failed due to some unknown error. 
OS: Windows 11

```
PS C:\Users\Admin\Documents\work\mrq-tortoise-TTS\prerequisites\DeepSpeed> python setup.py bdist_wheel 
[2024-04-21 02:53:46,166] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-04-21 02:53:46,168] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2024-04-21 02:53:46,514] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-04-21 02:53:46,515] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
[2024-04-21 02:53:46,786] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
DS_BUILD_OPS=1
Install Ops={'deepspeed_not_implemented': 1, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
version=0.14.2+99951caa, git_hash=99951caa, git_branch=master
install_requires=['hjson', 'ninja', 'numpy', 'packaging>=20.0', 'psutil', 'py-cpuinfo', 'pydantic', 'pynvml', 'torch', 'tqdm']
ext_modules=[<setuptools.extension.Extension('deepspeed.ops.comm.deepspeed_not_implemented_op') at 0x18807a48af0>, <setuptools.extension.Extension('deepspeed.ops.comm.deepspeed_ccl_comm_op') at 0x18807a48a90>, <setuptools.extension.Extension('deepspeed.ops.comm.deepspeed_shm_comm_op') at 0x1882ce36e20>, <setuptools.extension.Extension('deepspeed.ops.adam.cpu_adam_op') at 0x1882d91c790>, <setuptools.extension.Extension('deepspeed.ops.adam.fused_adam_op') at 0x1882d91c730>]
running bdist_wheel
running build
running build_py
copying deepspeed\git_version_info_installed.py -> build\lib.win-amd64-cpython-39\deepspeed
running egg_info
writing deepspeed.egg-info\PKG-INFO
writing dependency_links to deepspeed.egg-info\dependency_links.txt
writing entry points to deepspeed.egg-info\entry_points.txt
writing requirements to deepspeed.egg-info\requires.txt
writing top-level names to deepspeed.egg-info\top_level.txt
reading manifest file 'deepspeed.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST_win.in'
warning: no previously-included files matching '*.cpp' found under directory 'deepspeed\ops\csrc'
warning: no previously-included files matching '*.h' found under directory 'deepspeed\ops\csrc'
warning: no previously-included files matching '*.cu' found under directory 'deepspeed\ops\csrc'
warning: no previously-included files matching '*.cuh' found under directory 'deepspeed\ops\csrc'
warning: no previously-included files matching '*.cc' found under directory 'deepspeed\ops\csrc'
no previously-included directories found matching 'op_builder'
no previously-included directories found matching 'accelerator'
adding license file 'LICENSE'
writing manifest file 'deepspeed.egg-info\SOURCES.txt'
running build_ext
D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'deepspeed.ops.comm.deepspeed_not_implemented_op' extension
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\work\mrq-tortoise-TTS\prerequisites\DeepSpeed\setup.py", line 293, in <module>
    setup(name='deepspeed',
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
    self.run_command("build")
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
    _build_ext.run(self)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\torch\utils\cpp_extension.py", line 871, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 572, in build_extension
    self.compiler.link_shared_object(
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\ccompiler.py", line 752, in link_shared_object
    self.link(
  File "D:\Users\Admin\anaconda3\envs\tortoise-tts-py39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 498, in link
    build_temp = os.path.dirname(objects[0])
IndexError: list index out of range
```

**Comment by loadams** [comment]
Hi @thanhchauns2 - Windows support is sometimes difficult given issues with pytorch/cuda/async_io and other libs on Windows.  I assume you've followed the steps [here](https://github.com/microsoft/DeepSpeed?tab=readme-ov-file#windows), but there are other issues that can make this difficult to debug.  If you're able to, I would recommend using WSL on Windows, as that will allow you an easier build flow and the ability to use all DeepSpeed features.
