### ISSUE TITLE
[BUG] import deepspeed, MissingCUDAException

### ISSUE THREAD

**Issue by zsaladin** [microsoft/DeepSpeed#5497]
**Describe the bug**

It seems that deepspeed doesn't use cuda installed in virtual environment.

**To Reproduce**

1. Remove your nvcc installed globally.
2. Create new virtual environment and activate it.
3. Install `deepspeed==0.14.2`
4. Write codes below and run it.
    ### source code
    ```py
    import deepspeed
    ```

    ### error log
    ```
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/.venv/lib/python3.9/site-packages/deepspeed/__init__.py", line 25, in <module>
        from . import ops
      File "/.venv/lib/python3.9/site-packages/deepspeed/ops/__init__.py", line 15, in <module>
        from ..git_version_info import compatible_ops as __compatible_ops__
      File "/.venv/lib/python3.9/site-packages/deepspeed/git_version_info.py", line 29, in <module>
        op_compatible = builder.is_compatible()
      File "/.venv/lib/python3.9/site-packages/deepspeed/ops/op_builder/fp_quantizer.py", line 29, in is_compatible
        sys_cuda_major, _ = installed_cuda_version()
      File "/.venv/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 50, in installed_cuda_version
        raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
    deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
    ```

    But cuda is located in virtual environment.
    
    ```sh
    ls .venv/lib/python3.9/site-packages/nvidia -al | grep cuda
    
    drwxr-xr-x  4 irteam irteam  67 Apr 21 03:05 cuda_cupti
    drwxr-xr-x  4 irteam irteam  67 Apr 21 03:05 cuda_nvrtc
    drwxr-xr-x  4 irteam irteam  67 Apr 21 03:05 cuda_runtime
    ```

**Expected behavior**
deepspeed should use cuda in virtual environment.

Assume that cuda runtime is installed globally 11.6 and torch uses cuda runtime 12.1. In this case deepspeed and pytorch don't use same version of cuda. It can cause confusion.

And current deepspeed require cuda installed globally and torch install cuda in virtual environment. It increase docker image size.

**System info (please complete the following information):**
 - OS: centos 7
 - GPU count and types  single machine with x8 V100s each]
 - Python 3.9.17

**Comment by loadams** [comment]
Hi @zsaladin - the cuda runtime version and the cuda version that is bundled with torch can be different, so that is the reason why we need to be able to check the actual cuda runtime version that is installed.

**Comment by zsaladin** [comment]
@loadams Thanks for replying. I have some questions about your answer.

1. As you mentioned versions of cuda runtime installed globally and bundled with torch can be different. The cuda runtime bundled with torch is in virtual environment. 
Does deepspeed use cuda runtime in virtual environment? If deepspeed uses cuda runtime in virtual environment then the version conflict cannot happen. Actually It doesn't mean using cuda bundled with torch. It means that it would be great that deepspeed will bundle cuda runtime.

2. When I use `deepspeed==0.12.6` it doesn't require `nvcc`. `nvcc` is a compiler not for checking version.
I'm not sure that but deepspeed needs to complie cuda code?

**Comment by loadams** [comment]
@zsaladin - closing this as it is quite stale now.  Please comment if you need this re-opened or have any other questions.
