### ISSUE TITLE
[BUG] tortoise_tts.py fails on deepspeed/pydantic error

### ISSUE THREAD

**Issue by tholonia** [microsoft/DeepSpeed#5641]
**Describe the bug**
When running `./scripts/tortoise_tts.py` it fails in `deepspeed/runtime/config_utils.py` from what looks like a pyndantic conflict.

**To Reproduce**
Install as per instructions
run `./scripts/tortoise_tts.py`

**Expected behavior**
non-fatal output

**ds_report output**
ds_report

/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/jw/miniforge3/envs/TTSF/bin/ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 732, in <module>
    from ..pipe import PipelineModule
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 28, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 569, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 571, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/home/jw/miniforge3/envs/TTSF/lib/python3.10/site-packages/deepspeed/runtime/config_utils.py", line 116, in get_config_default
    field_name).required, f"'{field_name}' is a required field and does not have a default value"
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?

**Screenshots**

**System info (please complete the following information):**
 - OS: Debian GNU/Linux 12
 - GPU 1 Nvidia GeForce RTX 4090Ti
 - Python 3.10.14
 - Running in a conda env dedicated to tortoise-tts-fastest

This was a fresh install into a new environment.

I have seen related issues (https://github.com/microsoft/DeepSpeed/issues/4105), but the solution of downgrading pedantic to <2.0.0 does not work as it creates a slew of other errors.  

Currently running 
pydantic                  2.7.3
pydantic_core             2.18.4
deepspeed                 0.9.0

**Comment by loadams** [comment]
Hi @tholonia - we don't quite support pydantic 2+ yet, that is listed in our requirements file, are you able to run with pydantic 1?

**Comment by loadams** [comment]
Hi @tholonia - our latest release, v0.15.0 supports pydantic 2, so please try again with that.  Closing this issue but if you are still hitting problems, please comment and we can re-open.
