### ISSUE TITLE
[BUG] fp16 not supported for CPU?

### ISSUE THREAD

**Issue by mscheong01** [microsoft/DeepSpeed#5718]
**Describe the bug**
Hi, I'm not sure if it's a bug, but I get this error:
```
line 75, in __init__
    raise ValueError("Type fp16 is not supported.")
```
when trying to run deepspeed inference on cpu (target model: Qwen2-7B-Instruct)
**To Reproduce**
1.
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import deepspeed

# Load the model and tokenizer
model_name = "models/Qwen2-7B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Initialize DeepSpeed
ds_engine = deepspeed.init_inference(model,
                                     mp_size=1,
                                     dtype=torch.half,
                                     replace_with_kernel_inject=True)

# Tokenize the input text
input_text = "What is the capital of France?"
inputs = tokenizer(input_text, return_tensors="pt")

# Perform inference
with torch.no_grad():
    outputs = ds_engine.module.generate(**inputs, max_length=50)

# Decode the output
output_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(output_text)
```
**Expected behavior**
no error

**ds_report output**
```
[2024-07-02 09:04:19,993] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
deepspeed_not_implemented  [NO] ....... [OKAY]
deepspeed_ccl_comm ..... [NO] ....... [OKAY]
deepspeed_shm_comm ..... [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.10/dist-packages/torch']
torch version .................... 2.3.1+cu121
deepspeed install path ........... ['/usr/local/lib/python3.10/dist-packages/deepspeed']
deepspeed info ................... 0.14.4, unknown, unknown
deepspeed wheel compiled w. ...... torch 0.0 
shared memory (/dev/shm) size .... 64.00 MB
```

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - GPU count and types [none]
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version [Python 3.10.12]
 - Any other relevant info about your setup

**Comment by mscheong01** [comment]
Ok, so actually Qwen2-7B-Instruct is bfloat16, and using torch.bfloat16 instead of torch.float16 resulted in another error:
```
[INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Traceback (most recent call last):
  File "/workspace/test-deepspeed.py", line 18, in <module>
    inputs = tokenizer(input_text, return_tensors="pt").to('cuda')
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 803, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 803, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```

dunno why it's looking for cuda even though the cpu_accelerator was selected

`[INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)`
