### ISSUE TITLE
[BUG] PipelineEngine calculates loss with outputs and labels from different batches.

### ISSUE THREAD

**Issue by limjcst** [microsoft/DeepSpeed#5729]
**Describe the bug**

My samples (tensors) have varying shapes. As a result, I customize `Dataset` to ensure that each batch contains samples with the same shape.
With pipeline parallelism, the training process terminated due to mismatched tensor sizes during loss calculation, **as if it compares the output of the first batch but the labels of the second batch**.

```
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    _main()
  File "train.py", line 103, in _main
    _train(args)
  File "train.py", line 86, in _train
    loss = engine.train_batch(training_iter)
  File "/root/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 378, in train_batch
    self._exec_schedule(sched)
  File "/root/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 1439, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/root/.local/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 759, in _exec_forward_pass
    self.loss = self.module.loss_fn(outputs, labels)
  File "train.py", line 39, in loss_fn
    return torch.nn.functional.mse_loss(output, label)
  File "/root/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3291, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/root/.local/lib/python3.8/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (8) must match the size of tensor b (12) at non-singleton dimension 1
```

**To Reproduce**

I prepare a [repo](https://github.com/limjcst/debug-deepspeed) to reproduce the behavior.
Execute `bash run.sh`, and the logs above as well as others will arise.

- `NaiveModule` consists of two linear layers and two `torch.nn.TransformerEncoderLayer`.
- `NaiveModule.batch_fn` takes one tensor as both the input and the label. I pass it to `deepspeed.PipelineEngine.set_batch_fn`.
- `NaiveModule.loss_fn` is simply `torch.nn.functional.mse_loss`, used to create `deepspeed.PipelineModule`.
- `MyDataset` consists two batched samples, with the shape of `(64, 8, 32)` and `(64, 12, 32)`, respectively.
- The pipeline has two stages, running with two gpus on the same node.

I also enclose the output in my [repo](https://github.com/limjcst/debug-deepspeed), i.e., `run.log`.
Lines including `pid` are produced by the inserted logging statements in `deepspeed/runtime/pipe/engine.py`.
Notice that when the first stage (`pid = 102709`) enters `_exec_load_micro_batch` for the second time, the shape of the loaded inputs are `torch.Size([64, 12, 32])`.
When the last stage (`pid = 102710`) enters `_exec_recv_activations` for the second time, the shape of the received data is `torch.Size([64, 8, 1024])`.
The last dimension changes because of the first linear layer. However, **it is weird that the second dimension also changes, and the shape is the same as that of the received data for the first time**.

```
% grep pid run.log 
[2024-07-05 14:57:06,737] [INFO] [engine.py:899:_exec_load_micro_batch] first stage, pid = 102709, loaded.shape = torch.Size([64, 8, 32])
[2024-07-05 14:57:07,331] [INFO] [engine.py:1169:_exec_recv_activations] pid = 102710, recvd.shape = torch.Size([64, 8, 1024])
[2024-07-05 14:57:07,333] [INFO] [engine.py:915:_exec_load_micro_batch] last stage, pid = 102710, loaded.shape = torch.Size([64, 8, 32])
[2024-07-05 14:57:07,948] [INFO] [engine.py:758:_exec_forward_pass] before computing loss, pid = 102710, labels.shape = torch.Size([64, 8, 32])
[2024-07-05 14:57:08,101] [INFO] [engine.py:899:_exec_load_micro_batch] first stage, pid = 102709, loaded.shape = torch.Size([64, 12, 32])
[2024-07-05 14:57:08,102] [INFO] [engine.py:1169:_exec_recv_activations] pid = 102710, recvd.shape = torch.Size([64, 8, 1024])
[2024-07-05 14:57:08,103] [INFO] [engine.py:915:_exec_load_micro_batch] last stage, pid = 102710, loaded.shape = torch.Size([64, 12, 32])
[2024-07-05 14:57:08,104] [INFO] [engine.py:758:_exec_forward_pass] before computing loss, pid = 102710, labels.shape = torch.Size([64, 12, 32])
```

**Expected behavior**

The training process should continue without errors.

**ds_report output**

```
[2024-07-05 14:56:50,937] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m please install triton==1.0.0 if you want to use sparse attention
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [92m[OKAY][0m
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [93m[NO][0m ....... [93m[NO][0m
fused_adam ............. [93m[NO][0m ....... [92m[OKAY][0m
cpu_adam ............... [93m[NO][0m ....... [92m[OKAY][0m
cpu_adagrad ............ [93m[NO][0m ....... [92m[OKAY][0m
cpu_lion ............... [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [93m[NO][0m ....... [93m[NO][0m
fp_quantizer ........... [93m[NO][0m ....... [92m[OKAY][0m
fused_lamb ............. [93m[NO][0m ....... [92m[OKAY][0m
fused_lion ............. [93m[NO][0m ....... [92m[OKAY][0m
inference_core_ops ..... [93m[NO][0m ....... [92m[OKAY][0m
cutlass_ops ............ [93m[NO][0m ....... [92m[OKAY][0m
transformer_inference .. [93m[NO][0m ....... [92m[OKAY][0m
quantizer .............. [93m[NO][0m ....... [92m[OKAY][0m
ragged_device_ops ...... [93m[NO][0m ....... [92m[OKAY][0m
ragged_ops ............. [93m[NO][0m ....... [92m[OKAY][0m
random_ltd ............. [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [93m[NO][0m ....... [93m[NO][0m
spatial_inference ...... [93m[NO][0m ....... [92m[OKAY][0m
transformer ............ [93m[NO][0m ....... [92m[OKAY][0m
stochastic_transformer . [93m[NO][0m ....... [92m[OKAY][0m
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/.local/lib/python3.8/site-packages/torch']
torch version .................... 1.13.1+cu117
deepspeed install path ........... ['/root/.local/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.14.4, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.7
shared memory (/dev/shm) size .... 64.00 GB
```

**Screenshots**

Not applicable.

**System info (please complete the following information):**

 - OS: Ubuntu 18.04
 - GPU count and types: one machines with x2 A800s
 - Interconnects (if applicable): not applicable
 - Python version: 3.8.19

**Launcher context**

`deepspeed` launcher

**Docker context**

The docker image and the environment out of docker are invisible to me.

**Additional context**

I tried `dist.barrier()` suggested by @jiashu-z, but it failed to help.
https://github.com/microsoft/DeepSpeed/issues/4708

**Comment by limjcst** [comment]
`deepspeed` will "communicate metadata about upcoming p2p transfers." See `PipelineEngine._send_tensor_meta`.
I have to call `PipelineEngine.reset_activation_shape()` in the training loop.

```python
    for step in range(args.steps):
        loss = engine.train_batch(training_iter)
        engine.reset_activation_shape()  # This line is new
```

When I set `gradient_accumulation_steps` larger than one, the error arose again.
I guess **PipelineEngine requires samples have the same shape not only in one micro batch (configured by `train_micro_batch_size_per_gpu`), but also in a pipeline (configured by `gradient_accumulation_steps`)**.
I change my customized dataset accordingly, and the issue is solved.
