### ISSUE TITLE
[BUG] sequence parallel alltoall with batch size > 1

### ISSUE THREAD

**Issue by zeyugao** [microsoft/DeepSpeed#5808]
**Describe the bug**

The all_to_all_single in sequence parellel seems does not support batch size > 1

The example in this pr https://github.com/microsoft/DeepSpeed/pull/5664 uses batch size == 1

**To Reproduce**

```python
import torch
from torch import distributed as dist
from deepspeed.sequence.layer import _SeqAllToAll
from torch.distributed import get_rank
from deepspeed.comm import init_distributed

init_distributed(dist_backend='nccl')


device = f'cuda:{get_rank()}'

scatter_idx = 2
gather_idx = 1

# [b, s, h]
input_tensor = torch.tensor([
    [  # the first sentence
        [  # the first sentence, the first token
            i for i in range(0, 4)
        ],
        [  # the first sentence, the second token
            i for i in range(4, 8)
        ],
    ],
    [  # the second sentence
        [  # the second sentence, the first token
            i for i in range(8, 12)
        ],
        [  # the second sentence, the second token
            i for i in range(12, 16)
        ],
    ]
], device=device) \
    + get_rank() * 16  # The third token and the fourth token


def print_on_rank0(*args, **kwargs):
    if get_rank() == 0:
        print(*args, **kwargs)


print_on_rank0('[b, s, h, d]')
print_on_rank0(input_tensor)

ret = _SeqAllToAll.apply(
    None,
    input_tensor,
    scatter_idx,
    gather_idx,
)

print_on_rank0('after scatter')
print_on_rank0(ret)

ret = _SeqAllToAll.apply(
    None,
    ret,
    gather_idx,
    scatter_idx,
)

print_on_rank0('after gather')
print_on_rank0(ret)
```

Run with `torchrun --nproc-per-node=2 ./test.py`

**Expected behavior**

Scatter and gather correctly, expected output

More specifically, [0, 1, 2, 3] are the 4 heads of the first token in the first sentence, and [16, 17, 18, 19] are the 4 heads of the third token in the first sentence. So after scatter, [0, 1] and [16, 17] should construct the first sentence in the first gpu. The same applies to other situations.

```
[b, s, h, d]
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]], device='cuda:0')
after scatter
tensor([[[ 0,  1],
         [ 4,  5],
         [16, 17],
         [20, 21]],

        [[ 8,  9],
         [12, 13],
         [24, 25],
         [28, 29]]], device='cuda:0')
after gather
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]], device='cuda:0')
```

**Actual behavior**

```
2024-07-30 10:34:23,806] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-30 10:34:23,806] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-30 10:34:23,806] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[b, s, h, d]
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]], device='cuda:0')
[rank1]: Traceback (most recent call last):
[rank1]:   File ".........../elsa/llava/./test copy.py", line 56, in <module>
[rank1]:     ret = _SeqAllToAll.apply(
[rank1]:           ^^^^^^^^^^^^^^^^^^^
[rank1]:   File ".........../miniconda3/envs/training/lib/python3.11/site-packages/torch/autograd/function.py", line 598, in apply
[rank1]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File ".........../miniconda3/envs/training/lib/python3.11/site-packages/deepspeed/sequence/layer.py", line 53, in forward
[rank1]:     return single_all_to_all(input, scatter_idx, gather_idx, group)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File ".........../miniconda3/envs/training/lib/python3.11/site-packages/deepspeed/sequence/layer.py", line 20, in single_all_to_all
[rank1]:     input_t = input.reshape(
[rank1]:               ^^^^^^^^^^^^^^
[rank1]: RuntimeError: shape '[2, 2, 2]' is invalid for input of size 16
```

**Additional context**

If there is only one sentence, it works well

**ds_report output**

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fp_quantizer ........... [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['......./miniconda3/envs/training/lib/python3.11/site-packages/torch']
torch version .................... 2.3.0+cu121
deepspeed install path ........... ['......./miniconda3/envs/training/lib/python3.11/site-packages/deepspeed']
deepspeed info ................... 0.14.4, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.3, cuda 12.1
shared memory (/dev/shm) size .... 1007.58 GB
```

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU count and types A100 80g
 - Interconnects (if applicable) N.A.
 - Python version 3.11
 - Any other relevant info about your setup

**Take away**

This is an (but complicated) example that will support batch size > 1, but only with scatter_idx == 1 and gather_idx == 2, vice versa.

```python
 def single_all_to_all(input, scatter_idx, gather_idx, group):
     seq_world_size = dist.get_world_size(group)
     inp_shape = list(input.shape)
     inp_shape[scatter_idx] = inp_shape[scatter_idx] // seq_world_size
     if scatter_idx < 2:  # scatter_idx == 1, scatter sequence dim
         input_t = input.reshape(
             inp_shape[: scatter_idx] +  # the batch size dim
             [seq_world_size, inp_shape[scatter_idx]] +  # scatter the sequence dim
             inp_shape[scatter_idx + 1:]
         ).transpose(0, 1).contiguous()
     else:  # scatter_idx == 2, scatter heads dim
         input_t = input.reshape(
             [-1] +  # flatten batch size and sequence dim
             [seq_world_size, inp_shape[scatter_idx]] +  # scatter the heads
             inp_shape[scatter_idx + 1:]
         ).transpose(0, 1).contiguous()

     output = torch.empty_like(input_t)
     dist.all_to_all_single(output, input_t, group=group)

     if scatter_idx < 2:
         output = output.reshape(
             [
                 seq_world_size,
                 -1,  # batch size dim
                 inp_shape[scatter_idx]  # sequence dim (scattered)
             ] + inp_shape[gather_idx:]  # heads dim, and the rest
         ).permute(
             1, 2, 0, *list(range(3, len(output.shape)))
         )
     else:
         output = output.reshape(
             [
                 seq_world_size,
                 -1,  # batch size dim
                 inp_shape[gather_idx]  # sequence dim
             ] + inp_shape[scatter_idx:]  # heads dim (scattered), and the rest
         ).transpose(
             0, 1
         )

     return output.reshape(
         inp_shape[:gather_idx] +
         [seq_world_size * inp_shape[gather_idx]] +
         inp_shape[gather_idx + 1:]
     ).contiguous()
```

**Comment by samadejacobs** [comment]
@zeyugao, thanks for bringing this issue to our attention. We are aware of the issue, and a fix is in the works to be pushed soon. Please note that this issue is mostly related to scenarios where qkv tensors are batch first, that is, `batch_size, seq_len, num_heads, head_dim` (i.e., CUDA flash attention). The code should work where qkv tensors are sequence first, that is, `seq_len, batch_size, num_heads, head_dim` (i.e., Triton flash attention).

**Comment by zeyugao** [comment]
Thank you. I have referred to implement of megatron-deepspeed for the usage of DistributionAttention.

https://github.com/microsoft/Megatron-DeepSpeed/blob/3afd267e1e50b1410beb606c5625cc232a55417a/megatron/model/transformer.py#L814-L818

But I get confused. In the previous code, when `self.use_flash_attn_triton` is `False`, that means that the shape passed into `self.dist_attn` will be `[b, s, h, d]`, which is broken for the DistributedAttention. So does it mean that there are some flaws?

Moreover, the `gather_idx` and `scatter_idx` of dist_attn do not change according to which flash attention is used (CUDA flash attention vs Triton flash attention).

https://github.com/microsoft/Megatron-DeepSpeed/blob/3afd267e1e50b1410beb606c5625cc232a55417a/megatron/model/transformer.py#L599-L602

**Comment by samadejacobs** [comment]
Good point. [This PR](https://github.com/microsoft/Megatron-DeepSpeed/pull/406) (just merged) fixes the second issue you raised. Generally speaking, it is important to be pass appropriate sequence index (dimension) as `gather_idx` because of differences in CUDA flash vs Triton flash input shape.

**Comment by zeyugao** [comment]
@samadejacobs So, whether will this line https://github.com/huggingface/transformers/pull/32305/files#diff-9b3b96ae74d788adf085c903002dc7a49ec9873cc2ad110b514e2697c8e53036R317 be affected by this issue?

**Comment by samadejacobs** [comment]
@zeyugao, please take a look at [this PR](https://github.com/microsoft/DeepSpeed/pull/5823)

**Comment by zeyugao** [comment]
I think that this pr is enough, thanks
