### ISSUE TITLE
[BUG] Error when running ds_report on Windows

### ISSUE THREAD

**Issue by yanfeiwong** [microsoft/DeepSpeed#6473]
**ds_report output**
```
C:\Users\Yan>ds_report
[2024-09-02 13:44:07,415] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Scripts\\ds_report", line 3, in <module>
    from deepspeed.env_report import cli_main
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\__init__.py", line 25, in <module>
    from . import ops
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\__init__.py", line 11, in <module>
    from . import transformer
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\__init__.py", line 7, in <module>
    from .inference.config import DeepSpeedInferenceConfig
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\__init__.py", line 7, in <module>
    from ....model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\model_implementations\__init__.py", line 6, in <module>
    from .transformers.ds_transformer import DeepSpeedTransformerInference
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py", line 17, in <module>
    from deepspeed.ops.transformer.inference.triton.mlp import TritonMLP
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\__init__.py", line 10, in <module>
    from .ops import *
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\ops.py", line 8, in <module>
    import deepspeed.ops.transformer.inference.triton.matmul_ext as matmul_ext
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 457, in <module>
    fp16_matmul = Fp16Matmul()
                  ^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 206, in __init__
    __class__._read_autotune_table()
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 440, in _read_autotune_table
    TritonMatmul._read_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 161, in _read_autotune_table
    cache_manager = AutotuneCacheManager(cache_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 82, in __init__
    self.cache_dir = os.environ.get('TRITON_CACHE_DIR', TritonCacheDir.default_cache_dir())
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 45, in default_cache_dir
    if is_nfs_path(tmp_path) and not TritonCacheDir._warning_printed:
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 27, in is_nfs_path
    output = subprocess.check_output(['df', '-T', path], encoding='utf-8')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2]
```

**System info:**
 - OS: Windows 11
 - GPU count and types: 1*3090Ti
 - Python version: 3.11.9
 - Torch version: 2.4.0+cu124

**Comment by yanfeiwong** [comment]
Is this a TRITON problem? I do have a 2.1.0 triton installed on windows...

```python
from deepspeed.launcher.runner import DEEPSPEED_ENVIRONMENT_NAME
```

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
----> [1](vscode-notebook-cell:?execution_count=1&line=1) from deepspeed.launcher.runner import DEEPSPEED_ENVIRONMENT_NAME

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\__init__.py:25
     [22](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/__init__.py:22) else:
     [23](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/__init__.py:23)     HAS_TRITON = False
---> [25](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/__init__.py:25) from . import ops
     [26](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/__init__.py:26) from . import module_inject
     [28](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/__init__.py:28) from .accelerator import get_accelerator

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\__init__.py:11
      [9](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/__init__.py:9) from . import lion
     [10](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/__init__.py:10) from . import sparse_attention
---> [11](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/__init__.py:11) from . import transformer
     [12](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/__init__.py:12) from . import fp_quantizer
     [13](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/__init__.py:13) from .transformer import DeepSpeedTransformerLayer, DeepSpeedTransformerConfig

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\__init__.py:7
      [1](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:1) # Copyright (c) Microsoft Corporation.
      [2](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:2) # SPDX-License-Identifier: Apache-2.0
      [3](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:3) 
      [4](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:4) # DeepSpeed Team
      [6](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:6) from .transformer import DeepSpeedTransformerLayer, DeepSpeedTransformerConfig
----> [7](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:7) from .inference.config import DeepSpeedInferenceConfig
      [8](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:8) from ...model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
      [9](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/__init__.py:9) from .inference.moe_inference import DeepSpeedMoEInferenceConfig, DeepSpeedMoEInference

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\__init__.py:7
      [1](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:1) # Copyright (c) Microsoft Corporation.
      [2](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:2) # SPDX-License-Identifier: Apache-2.0
      [3](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:3) 
      [4](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:4) # DeepSpeed Team
      [6](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:6) from .config import DeepSpeedInferenceConfig
----> [7](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:7) from ....model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
      [8](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/__init__.py:8) from .moe_inference import DeepSpeedMoEInferenceConfig, DeepSpeedMoEInference

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\model_implementations\__init__.py:6
      [1](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:1) # Copyright (c) Microsoft Corporation.
      [2](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:2) # SPDX-License-Identifier: Apache-2.0
      [3](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:3) 
      [4](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:4) # DeepSpeed Team
----> [6](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:6) from .transformers.ds_transformer import DeepSpeedTransformerInference
      [7](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/__init__.py:7) from .transformers.clip_encoder import DSClipEncoder

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py:17
     [15](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py:15) import deepspeed
     [16](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py:16) if deepspeed.HAS_TRITON:
---> [17](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py:17)     from deepspeed.ops.transformer.inference.triton.mlp import TritonMLP
     [18](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py:18)     from deepspeed.ops.transformer.inference.triton.attention import TritonSelfAttention
     [20](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py:20) inference_module = None

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\__init__.py:10
      [8](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/__init__.py:8) from .gelu import gelu
      [9](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/__init__.py:9) from .softmax import softmax
---> [10](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/__init__.py:10) from .ops import *
     [11](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/__init__.py:11) from .matmul_ext import fp16_matmul, matmul_4d, score_4d_matmul, context_4d_matmul

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\ops.py:8
      [6](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/ops.py:6) import deepspeed
      [7](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/ops.py:7) from deepspeed.ops.op_builder import InferenceBuilder
----> [8](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/ops.py:8) import deepspeed.ops.transformer.inference.triton.matmul_ext as matmul_ext
      [9](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/ops.py:9) from deepspeed.ops.transformer.inference.triton.layer_norm import layer_norm, layer_norm_residual
     [11](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/ops.py:11) inference_module = None

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py:457
    [454](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:454) # -----------------------------------------------------------------------------
    [455](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:455) # mapping
    [456](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:456) if deepspeed.HAS_TRITON:
--> [457](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:457)     fp16_matmul = Fp16Matmul()
    [458](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:458)     matmul = MatmulExt.forward
    [459](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py:459)     matmul_4d = fp16_matmul._matmul_4d

File c:\Users\Yan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\ops\transformer\inference\triton\matmul_ext.py:206, in Fp16Matmul.__init__(self, read_cache)
...
   [1553](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/subprocess.py:1553)     self._close_pipe_fds(p2cread, p2cwrite,
   [1554](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/subprocess.py:1554)                          c2pread, c2pwrite,
   [1555](file:///C:/Users/Yan/AppData/Local/Programs/Python/Python311/Lib/subprocess.py:1555)                          errread, errwrite)

FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by yanfeiwong** [comment]
Yep, uninstall the old triton solves the problem..
