### ISSUE TITLE
[BUG] AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.

### ISSUE THREAD

**Issue by umarbutler** [microsoft/DeepSpeed#6568]
When I run `pip install deepspeed` on my Windows 11 machine in a virtual environment with Python 3.12.4, PyTorch 2.4.1 and CUDA 12.4 installed, I get the below error:
```
Collecting deepspeed
  Downloading deepspeed-0.15.1.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "D:\[REDACTED]\[REDACTED]\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\[REDACTED]\[REDACTED]\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\[REDACTED]\[REDACTED]\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-bsf_1y1b\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-bsf_1y1b\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-bsf_1y1b\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-env-bsf_1y1b\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 155, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by umarbutler** [comment]
@loadams

**Comment by loadams** [comment]
Hi @umarbutler - looks like you're on Windows.  The wheel we publish on Windows has a specific set of requirements, and it looks like you are pulling down the linux wheel.  

See the Windows version here, you may need to modify your python version to get it to grab this

https://pypi.org/project/deepspeed/0.15.0/#files

**Comment by loadams** [comment]
Hi @umarbutler - did that resolve your issue?

**Comment by Universal-Invariant** [comment]
Same issues on Win11x64. I've downloaded the whl it says. ERROR: deepspeed-0.15.0-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

```
python -c "import platform; print(platform.architecture())"
('64bit', 'WindowsPE')
```

I'm trying to build llava: https://github.com/haotian-liu/LLaVA

I created a fresh env for python3.13 and installed torch and then deepspeed and it still fails. I tried multiple methods such as trying to use older versions.

I was finally able to find a version for python3.10: pip install deepspeed-0.16.5-cp310-cp310-win_amd64.whl

but llava uses deepspeed 0.12 so all these issues are due to version issues and there not being any whl's for windows.
