### ISSUE TITLE
[BUG] Long sequence parallelism (Ulysses) got error list index out of range

### ISSUE THREAD

**Issue by Lzhang-hub** [microsoft/DeepSpeed#6618]
**Describe the bug**
test ulysses got error list index out of range

**To Reproduce**
test ulysses with [test_ulysses.py](https://github.com/microsoft/DeepSpeedExamples/blob/uly-hf/post_training/sequence_parallelism/test_ulysses.py)
torchrun  --nproc_per_node=8 test_ulysses.py

**Expected behavior**
work fine

**ds_report output**
```
collect2: error: ld returned 1 exit status
gds .................... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.10/site-packages/torch']
torch version .................... 2.3.0+cu121
deepspeed install path ........... ['/opt/conda/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.15.2, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.3, cuda 12.1
shared memory (/dev/shm) size .... 100.00 GB
```

**Screenshots**
got error: list index out of range
```
[rank6]: Traceback (most recent call last):
[rank6]:   File "/data1/nfs15/nfs/zhanglei335/mlsys/train/long-context-train/llm-train/uly_sp_test.py", line 166, in <module>
[rank6]:     get_loss(model, data_loader, DS_CONFIG)
[rank6]:   File "/data1/nfs15/nfs/zhanglei335/mlsys/train/long-context-train/llm-train/uly_sp_test.py", line 112, in get_loss
[rank6]:     model, _, _, _ = deepspeed.initialize(model=model,
[rank6]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank6]:     engine = DeepSpeedEngine(args=args,
[rank6]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 269, in __init__
[rank6]:     self._configure_distributed_model(model)
[rank6]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1188, in _configure_distributed_model
[rank6]:     self.data_parallel_group = groups._get_data_parallel_group()
[rank6]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/groups.py", line 405, in _get_data_parallel_group
[rank6]:     return mesh_device.get_group(mesh_dim="data_parallel")
[rank6]:   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/device_mesh.py", line 423, in get_group
[rank6]:     _find_pg_by_ranks_and_tag(*self._dim_group_infos[mesh_dim][:2])
[rank6]: IndexError: list index out of range
[rank7]: Traceback (most recent call last):
[rank7]:   File "/data1/nfs15/nfs/zhanglei335/mlsys/train/long-context-train/llm-train/uly_sp_test.py", line 166, in <module>
[rank7]:     get_loss(model, data_loader, DS_CONFIG)
[rank7]:   File "/data1/nfs15/nfs/zhanglei335/mlsys/train/long-context-train/llm-train/uly_sp_test.py", line 112, in get_loss
[rank7]:     model, _, _, _ = deepspeed.initialize(model=model,
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank7]:     engine = DeepSpeedEngine(args=args,
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 269, in __init__
[rank7]:     self._configure_distributed_model(model)
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1188, in _configure_distributed_model
[rank7]:     self.data_parallel_group = groups._get_data_parallel_group()
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/groups.py", line 405, in _get_data_parallel_group
[rank7]:     return mesh_device.get_group(mesh_dim="data_parallel")
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/device_mesh.py", line 423, in get_group
[rank7]:     _find_pg_by_ranks_and_tag(*self._dim_group_infos[mesh_dim][:2])
[rank7]: IndexError: list index out of range
```

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Comment by conver334** [comment]
I think that we should make a bit modification to line 39~50 of [test_ulysses.py](https://github.com/microsoft/DeepSpeedExamples/blob/5fbc57c6a347efb03349c4ac8e39a5ca5eeca03c/post_training/sequence_parallelism/test_ulysses.py#L44) like below. Because the new version of deepspeed acquires `sub_group_size`,  `stage3_prefetch_bucket_size`, `stage3_max_live_parameters`, `stage3_max_reuse_distance` to be int type, and default `model_persistence_threshold` may exceed the range.

```
    'zero_optimization': {
        'stage': 1,
        'overlap_comm': True,
        'contiguous_gradients': True,
        'sub_group_size': 1e9,
        'sub_group_size': 1000000000,
        'reduce_bucket_size': 16777216,
        'stage3_prefetch_bucket_size': 15099494,
        'stage3_max_live_parameters': 1000000000,
        'stage3_max_reuse_distance': 1000000000,
        'stage3_gather_16bit_weights_on_model_save': True,
        'model_persistence_threshold': 1e18
    }
```

then you can run this script like this: 
```
pip install deepspeed
deepspeed --num_gpus=8 test_ulysses.py
```

**Comment by Lzhang-hub** [comment]
I test with new `zero_optimization` still got same error, deepspeed versiuon is 0.15.2

**Comment by LetsGoFir** [comment]
how do you fix it?
