### ISSUE TITLE
Issue with deepspeed installation through pip requirements

### ISSUE THREAD

**Issue by baijumeswani** [microsoft/DeepSpeed#663]
I am trying to install deepspeed using pip through a requirements.txt file.

Contents of the requirements.txt file:
```
--pre
-f https://download.pytorch.org/whl/torch_stable.html
torch==1.6.0+cu101
torchvision==0.7.0+cu101
torchtext==0.7.0
deepspeed
```

When I try to run ```pip install -r requirements.txt```, I get the error:
```
ERROR: Command errored out with exit status 1:
     command: /home/bmeswani/anaconda3/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mr3spwnm/deepspeed_f25fb2385d494aa3a282ec5481159c40/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mr3spwnm/deepspeed_f25fb2385d494aa3a282ec5481159c40/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v85pfl_r
         cwd: /tmp/pip-install-mr3spwnm/deepspeed_f25fb2385d494aa3a282ec5481159c40/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-mr3spwnm/deepspeed_f25fb2385d494aa3a282ec5481159c40/setup.py", line 18, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mr3spwnm/deepspeed_f25fb2385d494aa3a282ec5481159c40/setup.py", line 21, in <module>
        raise ImportError('Unable to import torch, please visit https://pytorch.org/ '
    ImportError: Unable to import torch, please visit https://pytorch.org/ to see how to properly install torch on your system.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It would appear that ```deepspeed``` setup.py depends on ```torch``` which prevents me from installing ```torch``` and ```deepspeed``` through a single ```requirements.txt``` file.

Because of this, I need two ```requirements.txt``` files (which is a work around), but would be great if this issue could be addressed.

**Comment by afiaka87** [comment]
Thanks @baijumeswani - this helped me.
