### ISSUE TITLE
deepspeed report keyword errors

### ISSUE THREAD

**Issue by rubickkcibur** [microsoft/DeepSpeed#6644]
When I using deepspeed through accelerate, error happens:

Traceback (most recent call last):
  File "/home/rubickjiang/miniconda3/envs/deepspeed/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1067, in launch_command
    deepspeed_launcher(args)
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/accelerate/commands/launch.py", line 734, in deepspeed_launcher
    from deepspeed.launcher.runner import DEEPSPEED_ENVIRONMENT_NAME
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/__init__.py", line 25, in <module>
    from . import ops
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/__init__.py", line 15, in <module>
    from ..git_version_info import compatible_ops as __compatible_ops__
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/git_version_info.py", line 29, in <module>
    op_compatible = builder.is_compatible()
  File "/home/rubickjiang/miniconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/ops/op_builder/gds.py", line 42, in is_compatible
    gds_compatible = self.has_function(funcname="cuFileDriverOpen",
TypeError: OpBuilder.has_function() got an unexpected keyword argument 'library_dirs'

My deepspeed version is: 0.14.3+69adeab6

**Comment by IrinaArmstrong** [comment]
Same issue appears after running `ds_report` with the following output:
```
[2024-10-21 11:22:16,671] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)

DeepSpeed C++/CUDA extension op report

NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.

JIT compiled ops requires ninja
ninja .................. [OKAY]

op name ................ installed .. compatible

 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [YES] ...... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
 [WARNING]  FP Quantizer is using an untested triton version (2.0.0), only 2.3.(0, 1) and 3.0.0 are known to be compatible with these kernels
fp_quantizer ........... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
Traceback (most recent call last):
  File "/home/user/conda/envs/internvl_env1/bin/ds_report", line 6, in <module>
    cli_main()
  File "/home/user/conda/envs/internvl_env1/lib/python3.10/site-packages/deepspeed/env_report.py", line 190, in cli_main
    main(hide_operator_status=args.hide_operator_status, hide_errors_and_warnings=args.hide_errors_and_warnings)
  File "/home/user/conda/envs/internvl_env1/lib/python3.10/site-packages/deepspeed/env_report.py", line 184, in main
    op_report(verbose=not hide_errors_and_warnings)
  File "/home/user/conda/envs/internvl_env1/lib/python3.10/site-packages/deepspeed/env_report.py", line 53, in op_report
    is_compatible = OKAY if builder.is_compatible(verbose) else no
  File "/home/user/conda/envs/internvl_env1/lib/python3.10/site-packages/deepspeed/ops/op_builder/gds.py", line 58, in is_compatible
    gds_compatible = self.has_function(funcname="cuFileDriverOpen",
TypeError: OpBuilder.has_function() got an unexpected keyword argument 'library_dirs'
```
Deepspeed version (installed from source): 0.13.5+bc0d2465
Accelerate version: 1.0.0

**Comment by jomayeri** [comment]
Can you try updating to the latest deepspeed? Those version numbers appear to old to have this functionality and it certainly exists in deepspeed main branch: https://github.com/microsoft/DeepSpeed/blob/40bde528bcac79f765dc8f15d6d1512b3415199f/op_builder/builder.py#L308

**Comment by rubickkcibur** [comment]
I found that it may have something to do with slurm. This error happens when I install deepspeed from source in the login node. But after I try again on a GPU node, the function works.
