### ISSUE TITLE
[BUG] CUDA out-of-memory when using DISK-OFFLOAD, but CPU-OFFLOAD is fine

### ISSUE THREAD

**Issue by MagnesiumAlloy** [microsoft/DeepSpeed#6651]
CUDA out-of-memory when using DISK-OFFLOAD, but CPU-OFFLOAD is fine
command:
~/DeepSpeedExamples$ deepspeed ./inference/huggingface/zero_inference/run_model.py --model facebook/opt-6.7b --batch-size 4 --prompt-len 512 --gen-len 32 --disk-offload --quant_bits 4

it seems that there's omthing wrong when deepspeed uses pin-mem in gpu
after change "return tensor.pin_memory()" to "return tensor", it finishes inference successfully

[2024-10-22 20:35:12,903] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-10-22 20:35:12,903] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
load model
[2024-10-22 20:36:53,218] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 1
Installed CUDA version 12.2 does not match the version torch was compiled with 12.1 but since the APIs are compatible, accepting this combination
Traceback (most recent call last):
  File "/home/xiaoguo/DeepSpeedExamples/./inference/huggingface/zero_inference/run_model.py", line 383, in <module>
    run_generation(
  File "/home/xiaoguo/DeepSpeedExamples/./inference/huggingface/zero_inference/run_model.py", line 224, in run_generation
    model = get_ds_model(
  File "/home/xiaoguo/DeepSpeedExamples/./inference/huggingface/zero_inference/run_model.py", line 148, in get_ds_model
    model = OPTForCausalLM.from_pretrained(
  File "/home/xiaoguo/anaconda3/envs/awq/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3451, in from_pretrained
    init_contexts = [deepspeed.zero.Init(config_dict_or_path=deepspeed_config())] + init_contexts
  File "/home/xiaoguo/anaconda3/envs/awq/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1021, in __init__
    self.param_swapper = param_swapper or AsyncPartitionedParameterSwapper(_ds_config, self.dtype)
  File "/home/xiaoguo/anaconda3/envs/awq/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/partitioned_param_swapper.py", line 44, in __init__
    self._configure_aio(ds_config)
  File "/home/xiaoguo/anaconda3/envs/awq/lib/python3.10/site-packages/deepspeed/runtime/swap_tensor/partitioned_param_swapper.py", line 126, in _configure_aio
    self.buffers = get_accelerator().pin_memory(torch.empty(int(self.aligned_elements_per_buffer *
  File "/home/xiaoguo/anaconda3/envs/awq/lib/python3.10/site-packages/deepspeed/accelerator/cuda_accelerator.py", line 293, in pin_memory
    return tensor.pin_memory()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-10-22 20:36:56,877] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 80369
[2024-10-22 20:36:56,878] [ERROR] [launch.py:325:sigkill_handler] ['/home/xiaoguo/anaconda3/envs/awq/bin/python', '-u', './inference/huggingface/zero_inference/run_model.py', '--local_rank=0', '--model', 'facebook/opt-6.7b', '--batch-size', '4', '--prompt-len', '512', '--gen-len', '32', '--disk-offload', '--quant_bits', '4'] exits with return code = 1

**Comment by MagnesiumAlloy** [comment]
after change "return tensor.pin_memory()" to "return tensor", it finishes inference successfully
but got wrong answer:
**0: Paris is the capital city of<s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s>**

**Comment by MagnesiumAlloy** [comment]
after change "return tensor.pin_memory()" to "return tensor", it finishes inference successfully
**but got wrong answer**

**Comment by jomayeri** [comment]
Have you installed the dependencies in the directory `DeepSpeedExamples/inference/huggingface/zero_inference/` using `pip install -r requirements.txt`?
