### ISSUE TITLE
[BUG] While  submodule forward process in different gpu is not same， loss.backward get stuck

### ISSUE THREAD

**Issue by fuzuoyi** [microsoft/DeepSpeed#6667]
**Describe the bug**

For example, there is a two-gpu task and model has three part
- VIT-1
- VIT-2
- LLM

model‘s graph may not always same in training
```
# model forward pseudocode

def forward(self, inputs, labels):
    labels = inputs['labels']
    img_1 = inputs['img']
    img_2 = inputs.get('img2', None)

    x1 = self.vit1(img_1)
    if img_2 is not None: 
        x2 = self.vit2(img_2)
        x1 += x2
    out = self.llm(x1)
    return self.loss_func(out, labels)
```

and using zero-stage2/stage3 to train model

in gpu0：
VIT-1， VIT-2， LLM （used in forwaed）

in gpu1： 
VIT-1， LLM  （used in forwaed）

while trainging，stuck at  ```self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)``` in deepspeed/runtime/zero/stage3.py or deepspeed/runtime/zero/stage1_2.py 

How to solve this problem

**Comment by jomayeri** [comment]
Is there a stack trace for this error (after a ctrl+c if it is stuck)?

**Comment by fuzuoyi** [comment]
after Ctrl+C （^C）

```
trainer before backward
trainer before backward
^CWARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3462429 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3462430 closing signal SIGINT

^CWARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3462429 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3462430 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 3462201 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fzy/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 730, in run
    self._shutdown(e.sigval)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 289, in _shutdown
    self._pcontext.close(death_sig)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 331, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 708, in _close
    handler.proc.wait(time_to_wait)
  File "/home/fzy/anaconda3/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fzy/anaconda3/lib/python3.11/subprocess.py", line 2040, in _wait
    time.sleep(delay)
  File "/home/fzy/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 3462201 got signal: 2
```

**Comment by jomayeri** [comment]
This looks to be getting stuck inside Pytorch. You might raise an issue with them to see if having different forwards on different GPUs will work.
