### ISSUE TITLE
Installation Error on Windows 11 through Command Prompt.

### ISSUE THREAD

**Issue by neonvarun** [microsoft/DeepSpeed#6702]
I am using Windows 11 no WSL, Installed Cuda , Pytorch, Visual Studio C++Build Tools, Windows SDK 10.0.26100.0 . 
I tired installing Deepspeed through Command Prompt but keep getting the same error again and again .
"unable to open aio.lib".
Some said the file is available in Windows Build tools SDK but it is not there.
I have intel i5 1155G7 CPU and Iris Graphics.

If anyone can help its Appreciated. 💯👍 
 
ERROR :
_______________________________________________________________________________________________________________________________________
C:\Users\varun>python --version
Python 3.11.0

C:\Users\varun>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:26:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0

C:\Users\varun>pip show torch
Name: torch
Version: 2.4.0+cpu
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Users\varun\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision

C:\Users\varun>pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.15.3.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      [2024-11-03 01:40:03,982] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-11-03 01:40:03,990] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      [2024-11-03 01:40:05,343] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-11-03 01:40:05,350] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\varun\AppData\Local\Temp\pip-install-xxdolnzk\deepspeed_a6d0b733a9314dacb34c7c24445e1f92\setup.py", line 209, in <module>
          result = subprocess.check_output(git_hash_cmd)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\varun\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 465, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\varun\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 546, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\varun\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\varun\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  Skip pre-compile of incompatible async_io; One can disable async_io with DS_BUILD_AIO=0
      Install Ops={'deepspeed_not_implemented': 1, 'async_io': False, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
_______________________________________________________________________________________________________________________________________

Thank You.

**Comment by loadams** [comment]
Hi @neonvarun - closing this issue for now.  Let us know if you are still hitting issues.

**Comment by neonvarun** [comment]
Thank you for your help its installed now 💯 .
