### ISSUE TITLE
No module named 'op_builder' when installing deepspeed

### ISSUE THREAD

**Issue by chrisirhc** [microsoft/DeepSpeed#6716]
Seeing the following when trying to install deepspeed==0.15.0 :
```
2024-11-05 12:26:26 SST	===== stderr start =====
2024-11-05 12:26:26 SST	  error: subprocess-exited-with-error
2024-11-05 12:26:26 SST
2024-11-05 12:26:26 SST	  × python setup.py egg_info did not run successfully.
2024-11-05 12:26:26 SST	  │ exit code: 1
2024-11-05 12:26:26 SST	  ╰─> [7 lines of output]
2024-11-05 12:26:26 SST	      Traceback (most recent call last):
2024-11-05 12:26:26 SST	        File "<string>", line 2, in <module>
2024-11-05 12:26:26 SST	        File "<pip-setuptools-caller>", line 34, in <module>
2024-11-05 12:26:26 SST	        File "/tmp/pip-wheel-qozevkut/deepspeed_bf661b1b88244946abdc9e360fe7e8c1/setup.py", line 39, in <module>
2024-11-05 12:26:26 SST	          from op_builder import get_default_compute_capabilities, OpBuilder
2024-11-05 12:26:26 SST	      ModuleNotFoundError: No module named 'op_builder'
2024-11-05 12:26:26 SST	      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
2024-11-05 12:26:26 SST	      [end of output]
2024-11-05 12:26:26 SST
2024-11-05 12:26:26 SST	  note: This error originates from a subprocess, and is likely not a problem with pip.
2024-11-05 12:26:26 SST	error: metadata-generation-failed
2024-11-05 12:26:26 SST
2024-11-05 12:26:26 SST	× Encountered error while generating package metadata.
2024-11-05 12:26:26 SST	╰─> See above for output.
```

This only occurred on python 3.11 version.

The installation is occurring via bazel, and I don't have a full reproduction steps as I'm only able to reproduce it on certain machines.
I suspect it's due to a combination of python/pip version.

So far, I think a workaround is to add the `--use-pep517` flag on the pip install command.

**Comment by loadams** [comment]
Interesting, on a node that repros the failure, could you share the output of `pip list` so we can see the versions of pip/torch/etc?

**Comment by chrisirhc** [comment]
I believe the versions are those listed in the following file, since it's using rules_python 0.34.0 : 
https://github.com/bazelbuild/rules_python/blob/0.34.0/python/private/pypi/deps.bzl

However, when I create a virtual environment using these versions and with Python 3.11.9, I'm unable to reproduce the issue.

**Comment by loadams** [comment]
@chrisirhc - I was only ever able to repro this with older pip versions, were you able to confirm if updating pip resolved the issue or some other bug in bazel was causing the issue?

**Comment by chrisirhc** [comment]
I wasn't able to reproduce it but I added the `--use-pep517` flag and that seems to resolve it generally.

If that flag itself is not supported then it must be an even older pip version.

Feel free to close. I opened this in case others might run into it but looks like it might just be me. 😅

**Comment by loadams** [comment]
No problem!  I think its good to have the issue to track and document it, and if anyone else hits it in the future hopefully they will find this and can comment here/see your solution.
