### ISSUE TITLE
CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by niebowen666** [microsoft/DeepSpeed#6723]
**Describe the bug**
when I run my code. I found the error:
```RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedEx(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)```

**ds_report output**
```
[2024-11-07 11:09:25,334] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-11-07 11:09:27.985422: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730948968.001130   14809 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730948968.005845   14809 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-07 11:09:28.021106: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
 [WARNING]  NVIDIA Inference is only supported on Ampere and newer architectures
 [WARNING]  FP Quantizer is using an untested triton version (3.1.0), only 2.3.(0, 1) and 3.0.0 are known to be compatible with these kernels
fp_quantizer ........... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
gds .................... [NO] ....... [OKAY]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
transformer_inference .. [NO] ....... [NO]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
inference_core_ops ..... [NO] ....... [NO]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
cutlass_ops ............ [NO] ....... [NO]
quantizer .............. [NO] ....... [OKAY]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
ragged_device_ops ...... [NO] ....... [NO]
 [WARNING]  NVIDIA Inference is only supported on Pascal and newer architectures
ragged_ops ............. [NO] ....... [NO]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/root/anaconda3/envs/deepspeed/lib/python3.9/site-packages/torch']
torch version .................... 2.5.0+cu121
deepspeed install path ........... ['/root/anaconda3/envs/deepspeed/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.15.3, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.4, cuda 12.4
shared memory (/dev/shm) size .... 125.75 GB
```

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU count and types: 1 GPU NVIDIA GeForce GTX TITAN X
 - Python version: 3.9.18

**my ds_config:**
```
ds_config = {
        "train_batch_size": args.batch_size,
        "optimizer": {
            "type": "Adam",
            "params": {
                "lr": 0.00006,
                "betas": [0.9, 0.95],
                "weight_decay": 0.01
            }
        },
        "bf16":{
            "enabled": True
        },
        "data_types":{
            "grad_accum_dtype": "bf16"
        },
        "zero_optimization": {
            "stage": 3,
            "offload_optimizer": {
                "device": "nvme",
                "nvme_path": "/mnt/nvme0n1",
                "pin_memory": False
            },

            "offload_param": {
                "device": "nvme",
                "nvme_path": "/mnt/nvme0n1",
                "buffer_count": 32,
                "buffer_size": 1e8,
                "max_in_cpu": 1e6,
                "pin_memory": False
            },
            "sub_group_size" : 0
        },
        "communication_data_type": "bf16"
    }
```
Thanks for your help!

**Comment by hwchen2017** [comment]
Bfloat16 is only supported on GPUs with compute capability 8.0 or newer.  The compute capability of TITAN X is 6.1, which doesn't support BF16 natively.

**Comment by niebowen666** [comment]
Thanks for your help！
I have changed my configuration from `bf16` to `fp16`.
But it return an error:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/nbw/code/llama3-DS/train.py", line 118, in <module>
[rank0]:     train(ModelArgs)
[rank0]:   File "/home/nbw/code/llama3-DS/train.py", line 87, in train
[rank0]:     model, _, _, _ = deepspeed.initialize(model=model,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 247, in __init__
[rank0]:     self._do_sanity_check()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1080, in _do_sanity_check
[rank0]:     raise ValueError("Type fp16 is not supported.")
[rank0]: ValueError: Type fp16 is not supported.
```
Is it because my GPU doesn't support FP16 either？

**Comment by niebowen666** [comment]
Besides, I have changed my ds_config to:
```
ds_config = {
        "train_batch_size": args.batch_size,
        "optimizer": {
            "type": "Adam",
            "params": {
                "lr": 0.00006,
                "betas": [0.9, 0.95],
                "weight_decay": 0.01
            }
        },
        "data_types":{
            "grad_accum_dtype": "fp32"
        },
        "zero_optimization": {
            "stage": 3,
            "offload_optimizer": {
                "device": "nvme",
                "nvme_path": "/mnt/nvme0n1",
                "pin_memory": True
            },

            "offload_param": {
                "device": "nvme",
                "nvme_path": "/mnt/nvme0n1",
                "buffer_count": 32,
                "buffer_size": 1e8,
                "max_in_cpu": 1e6,
                "pin_memory": True
            },
        },
        "communication_data_type": "fp32"
    }
```
and run my py file:
```
/mnt/nvme0n1/zero_stage_3/optimizer/rank0/0_74.tensor.swp: buffer nbytes != file bytes 231770112 != 231735296
python3: /usr/local/lib/python3.10/dist-packages/deepspeed/ops/csrc/aio/py_lib/deepspeed_py_io_handle.cpp:237: int deepspeed_io_handle_t::pread(const at::Tensor&, const char*, bool, bool): Assertion `buffer_bytes == num_file_bytes' failed.
```

**Comment by hwchen2017** [comment]
> [@hwchen2017](https://github.com/hwchen2017) Thanks for your help！ I have changed my configuration from `bf16` to `fp16`. But it return an error:
> 
> ```
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/nbw/code/llama3-DS/train.py", line 118, in <module>
> [rank0]:     train(ModelArgs)
> [rank0]:   File "/home/nbw/code/llama3-DS/train.py", line 87, in train
> [rank0]:     model, _, _, _ = deepspeed.initialize(model=model,
> [rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 193, in initialize
> [rank0]:     engine = DeepSpeedEngine(args=args,
> [rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 247, in __init__
> [rank0]:     self._do_sanity_check()
> [rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1080, in _do_sanity_check
> [rank0]:     raise ValueError("Type fp16 is not supported.")
> [rank0]: ValueError: Type fp16 is not supported.
> ```
> 
> Is it because my GPU doesn't support FP16 either？

FP16 is not fully supported on compute capability 6.x. See here: https://en.wikipedia.org/wiki/CUDA#Data_types

**Comment by hwchen2017** [comment]
> Besides, I have changed my ds_config to:
> 
> ```
> ds_config = {
>         "train_batch_size": args.batch_size,
>         "optimizer": {
>             "type": "Adam",
>             "params": {
>                 "lr": 0.00006,
>                 "betas": [0.9, 0.95],
>                 "weight_decay": 0.01
>             }
>         },
>         "data_types":{
>             "grad_accum_dtype": "fp32"
>         },
>         "zero_optimization": {
>             "stage": 3,
>             "offload_optimizer": {
>                 "device": "nvme",
>                 "nvme_path": "/mnt/nvme0n1",
>                 "pin_memory": True
>             },
> 
>             "offload_param": {
>                 "device": "nvme",
>                 "nvme_path": "/mnt/nvme0n1",
>                 "buffer_count": 32,
>                 "buffer_size": 1e8,
>                 "max_in_cpu": 1e6,
>                 "pin_memory": True
>             },
>         },
>         "communication_data_type": "fp32"
>     }
> ```
> 
> and run my py file:
> 
> ```
> /mnt/nvme0n1/zero_stage_3/optimizer/rank0/0_74.tensor.swp: buffer nbytes != file bytes 231770112 != 231735296
> python3: /usr/local/lib/python3.10/dist-packages/deepspeed/ops/csrc/aio/py_lib/deepspeed_py_io_handle.cpp:237: int deepspeed_io_handle_t::pread(const at::Tensor&, const char*, bool, bool): Assertion `buffer_bytes == num_file_bytes' failed.
> ```

FYI. @jomayeri
