### ISSUE TITLE
deepspeed installation problem

### ISSUE THREAD

**Issue by sagie-dekel** [microsoft/DeepSpeed#6817]
Hi,
During the installation, i get the following error:
```python
Collecting deepspeed
  Using cached deepspeed-0.16.0.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      [2024-12-04 11:05:58,747] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-04 11:05:58,767] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Warning: The cache directory for DeepSpeed Triton autotune, /home/sagie.dekel/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
      [2024-12-04 11:06:00,385] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-04 11:06:00,391] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/setup.py", line 40, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/op_builder/__init__.py", line 18, in <module>
          import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/deepspeed/__init__.py", line 25, in <module>
          from . import ops
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/deepspeed/ops/__init__.py", line 15, in <module>
          from ..git_version_info import compatible_ops as __compatible_ops__
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/deepspeed/git_version_info.py", line 29, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/op_builder/cpu/async_io.py", line 80, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-c2oi7t19/deepspeed_6339861123c84ed3856f1feb571e3473/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 759, in rmtree
          _rmtree_safe_fd(stack, onexc)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
          onexc(func, path, err)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 662, in _rmtree_safe_fd
          os.rmdir(name, dir_fd=dirfd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmp4yqce7ut'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

``` 

**My environment:**

- OS: Linux
Python: 3.12.7 (also tried to downgrade without success)
Transformers: 2.4.1
PyTorch: 4.46.1
CUDA (python -c 'import torch; print(torch.version.cuda)'): 11.8

**Packages Version:**
```python
# Name                    Version                   Build  Channel

_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.1.0           py312h06a4308_0
accelerate                1.0.0                    pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
blas                      1.0                         mkl
bottleneck                1.4.2           py312ha883a20_0
brotli-python             1.0.9           py312h6a678d5_8
bzip2                     1.0.8                h5eee18b_6
c-ares                    1.19.1               h5eee18b_0
ca-certificates           2024.11.26           h06a4308_0
certifi                   2024.8.30       py312h06a4308_0
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.4                 hbda6634_3
datasets                  3.0.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
expat                     2.6.3                h6a678d5_0
ez-setup                  0.9                      pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.16.1                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
grpcio                    1.62.2          py312h6a678d5_0
hjson                     3.1.0                    pypi_0    pypi
huggingface-hub           0.25.2                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306
jinja2                    3.1.4           py312h06a4308_1
jpeg                      9e                   h5eee18b_3
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.40                 h12ee557_0
lerc                      3.0                  h295c915_0
libabseil                 20240116.2      cxx17_h6a678d5_0
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.9.1.3              h99ab3db_1
libcurand                 10.3.5.147           h99ab3db_1
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libgrpc                   1.62.2               h2d74bed_0
libiconv                  1.16                 h5eee18b_3
libidn2                   2.3.4                h5eee18b_0
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0
libprotobuf               4.25.3               he621ea3_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h27cfd23_0
libuuid                   1.41.5               h5eee18b_0
libwebp-base              1.3.2                h5eee18b_1
llvm-openmp               14.0.6               h9e868ea_0
lz4-c                     1.9.4                h6a678d5_1
markdown                  3.4.1           py312h06a4308_0
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0           py312h5eee18b_1
mkl_fft                   1.3.11          py312h5eee18b_0
mkl_random                1.2.8           py312h526ad5a_0
mpmath                    1.3.0           py312h06a4308_0
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  3.3             py312h06a4308_0
ninja                     1.11.1.2                 pypi_0    pypi
numexpr                   2.10.1          py312h3c60e43_0
numpy                     1.26.4          py312hc5e2394_0
numpy-base                1.26.4          py312h0da6c21_0
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.5.2                he7f1fd0_0
openssl                   3.0.15               h5eee18b_0
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       24.3.1                   pypi_0    pypi
propcache                 0.2.0                    pypi_0    pypi
protobuf                  3.20.0                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pydantic                  2.10.1                   pypi_0    pypi
pydantic-core             2.27.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pysocks                   1.7.1           py312h06a4308_0
python                    3.12.7               h5148396_0
python-dateutil           2.9.0post0      py312h06a4308_2
python-tzdata             2023.3             pyhd3eb1b0_0
pytorch                   2.4.1           py3.12_cuda11.8_cudnn9.1.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1          py312h06a4308_0
pyyaml                    6.0.2           py312h5eee18b_0
rbo                       0.1.3                    pypi_0    pypi
re2                       2022.04.01           h295c915_0
readline                  8.2                  h5eee18b_0
regex                     2024.9.11                pypi_0    pypi
requests                  2.32.3          py312h06a4308_1
rich                      13.9.2                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
setuptools                69.5.0                   pypi_0    pypi
shtab                     1.7.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.45.3               h5eee18b_0
sympy                     1.13.3                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.17.0          py312h06a4308_0
tensorboard-data-server   0.7.0           py312h52d8a92_1
tk                        8.6.14               h39e8969_0
tokenizers                0.20.0                   pypi_0    pypi
torch                     2.4.1                    pypi_0    pypi
torchaudio                2.4.1               py312_cu118    pytorch
torchtriton               3.0.0                     py312    pytorch
torchvision               0.19.1              py312_cu118    pytorch
tqdm                      4.66.5          py312he106c6f_0
transformers              4.46.1                   pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
trl                       0.12.0                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0          py312h06a4308_0
tyro                      0.8.12                   pypi_0    pypi
tzdata                    2024b                h04d1e81_0
urllib3                   2.2.3           py312h06a4308_0
werkzeug                  3.0.6           py312h06a4308_0
wheel                     0.44.0          py312h06a4308_0
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1
yaml                      0.2.5                h7b6447c_0
yarl                      1.14.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
zstd                      1.5.6                hc292b87_0
```

Thanks for helping :)

**Comment by loadams** [comment]
Hi @sagie-dekel - I'll take a look, do you have a GPU on this system or is it just a CPU?  Since the first warnings show that DeepSpeed is unable to detect a GPU.

**Comment by sagie-dekel** [comment]
Hi @loadams, thanks for answering!

I don't have a GPU on my system. I use Portable Batch System to send jobs to a DGX system with GPU's (Nvidia A100).

**Comment by loadams** [comment]
@sagie-dekel - I see, thanks.  Could you try installing again (you should get the 0.16.1 version of DeepSpeed that was just released) and we can look at the logs there again?  

You can also specify the accelerator:

DS_ACCELERATOR=cuda pip install deepspeed (if you then want to build the ops for the platform you'll be running on).

**Comment by sagie-dekel** [comment]
Hi again @loadams,
I tried again with no change:

```python
Collecting deepspeed
  Downloading deepspeed-0.16.1.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      [2024-12-06 09:55:38,234] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-06 09:55:38,295] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Warning: The cache directory for DeepSpeed Triton autotune, /home/sagie.dekel/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
      [2024-12-06 09:55:42,579] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-06 09:55:42,585] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/setup.py", line 40, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/op_builder/__init__.py", line 18, in <module>
          import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/deepspeed/__init__.py", line 25, in <module>
          from . import ops
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/deepspeed/ops/__init__.py", line 15, in <module>
          from ..git_version_info import compatible_ops as __compatible_ops__
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/deepspeed/git_version_info.py", line 29, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/op_builder/cpu/async_io.py", line 80, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-2xlon9b6/deepspeed_8d50b259daab46e391dcffbc5fdafee4/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 759, in rmtree
          _rmtree_safe_fd(stack, onexc)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
          onexc(func, path, err)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 662, in _rmtree_safe_fd
          os.rmdir(name, dir_fd=dirfd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmp2elsisur'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

``` 

and with DS_ACCELERATOR=cuda:

```python
Collecting deepspeed
  Using cached deepspeed-0.16.1.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      [2024-12-06 09:56:17,550] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (override)
      Warning: The cache directory for DeepSpeed Triton autotune, /home/sagie.dekel/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
      [2024-12-06 09:56:19,279] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (override)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/setup.py", line 40, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/op_builder/__init__.py", line 18, in <module>
          import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/deepspeed/__init__.py", line 25, in <module>
          from . import ops
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/deepspeed/ops/__init__.py", line 15, in <module>
          from ..git_version_info import compatible_ops as __compatible_ops__
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/deepspeed/git_version_info.py", line 29, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/op_builder/async_io.py", line 99, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-29y3jxhv/deepspeed_a9a9f29f63ae4d6a9a827429683471e2/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 759, in rmtree
          _rmtree_safe_fd(stack, onexc)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
          onexc(func, path, err)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 662, in _rmtree_safe_fd
          os.rmdir(name, dir_fd=dirfd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmpkd0_j1zs'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by sagie-dekel** [comment]
Thanks @loadams - I got the same error trying to build from source for the latest DeepSpeed master branch.

I got similar error with ```DS_BUILD_OPS=0 pip install deepspeed``` , except additional warning at the end:

```python
Collecting deepspeed
  Using cached deepspeed-0.16.1.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      [2024-12-07 09:33:05,769] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-07 09:33:05,797] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Warning: The cache directory for DeepSpeed Triton autotune, /home/sagie.dekel/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
      [2024-12-07 09:33:08,303] [WARNING] [real_accelerator.py:174:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
      [2024-12-07 09:33:08,309] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cpu (auto detect)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-eg1gn0ie/deepspeed_b8611e10db8a4d33ac999cc1312d6908/setup.py", line 183, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-eg1gn0ie/deepspeed_b8611e10db8a4d33ac999cc1312d6908/op_builder/cpu/async_io.py", line 80, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-eg1gn0ie/deepspeed_b8611e10db8a4d33ac999cc1312d6908/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 759, in rmtree
          _rmtree_safe_fd(stack, onexc)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
          onexc(func, path, err)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/RLRF_env/lib/python3.12/shutil.py", line 662, in _rmtree_safe_fd
          os.rmdir(name, dir_fd=dirfd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmpjv_7ubse'
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

I created new python virtual environment with only  torch and transformers and got similar but different error (I also tried with DS_BUILD_OPS=0):
```python
Building wheels for collected packages: deepspeed
  Building wheel for deepspeed (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=0
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/setup.py", line 183, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/op_builder/cpu/async_io.py", line 80, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/my_env_name/lib/python3.11/shutil.py", line 763, in rmtree
          onerror(os.rmdir, path, sys.exc_info())
        File "/home/sagie.dekel/PROGS/anaconda3/envs/my_env_name/lib/python3.11/shutil.py", line 761, in rmtree
          os.rmdir(path, dir_fd=dir_fd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmpx3j8qp9g'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deepspeed
  Running setup.py clean for deepspeed
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=0
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/setup.py", line 183, in <module>
          op_compatible = builder.is_compatible()
                          ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/op_builder/cpu/async_io.py", line 80, in is_compatible
          aio_compatible = self.has_function('io_submit', ('aio', ))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/sagie.dekel/tmp/pip-install-sxhelc16/deepspeed_44d973d0b3ba406b9f0eee6cad7c7c79/op_builder/builder.py", line 388, in has_function
          shutil.rmtree(tempdir)
        File "/home/sagie.dekel/PROGS/anaconda3/envs/my_env_name/lib/python3.11/shutil.py", line 763, in rmtree
          onerror(os.rmdir, path, sys.exc_info())
        File "/home/sagie.dekel/PROGS/anaconda3/envs/my_env_name/lib/python3.11/shutil.py", line 761, in rmtree
          os.rmdir(path, dir_fd=dir_fd)
      OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmp3ojgoz1r'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for deepspeed
Failed to build deepspeed
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (deepspeed)

```

**Comment by loadams** [comment]
Hi @sagie-dekel - thanks for testing that.  The error still looks to be related to this:

```
OSError: [Errno 39] Directory not empty: '/home/sagie.dekel/tmp/tmpx3j8qp9g'
```

Do you have permissions to these directories?  Are you able to use python to try something like `os.mkdir(/home/sagie.dekel/tmp/test)`?

**Comment by sagie-dekel** [comment]
Hi again,
I solved it by creating a new environment with the exact packages mentioned in theDeepSpeed/environment.yml file (for others, notice the channels mentioned in the file if you are using it as well).

thanks for helping!
