### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1259010439** [microsoft/DeepSpeed#6827]
**Describe the bug**
The following error occurs when I execute DeepSpeed

Traceback (most recent call last):
  File "/root/miniconda3/envs/deepspeed/bin/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/root/miniconda3/envs/deepspeed/lib/python3.10/site-packages/deepspeed/__init__.py", line 10, in <module>
    import torch
  File "/root/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /root/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/lib/../../../../libcufft.so.10: cannot read file data

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by loadams** [comment]
Hi @1259010439 - this looks to be an error with your torch install:

```
ImportError: /root/miniconda3/envs/deepspeed/lib/python3.10/site-packages/torch/lib/../../../../libcufft.so.10: cannot read file data
```

Can you share the output of the following commands?

```
pip list
python -c "import torch; print('torch:', torch.__version__, torch)"
python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
```

**Comment by loadams** [comment]
Hi @1259010439 - let us know if you are still hitting this and we can investigate more.
