### ISSUE TITLE
averaged_gradients is None after a few hundred iterations

### ISSUE THREAD

**Issue by moyix** [microsoft/DeepSpeed#686]
Using the most recent DeepSpeed (34c83a5a64da67ff186eec4fdd7ab3c1badf0486) and training a 774M GPT2 with the Megatron-LM example, I hit the following error after a few hundred iterations:

```
[2021-01-22 19:14:45,882] [INFO] [logging.py:60:log_dist] [Rank 0] step=415, skipped=16, lr=[1.1969999999999999e-05, 1.1969999999999999e-05], mom=[(0.9, 0.999), (0.9, 0.999)]
[2021-01-22 19:14:45,882] [INFO] [timer.py:163:stop] 0/415, SamplesPerSec=50.36530602579739
Traceback (most recent call last):
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 713, in <module>
Traceback (most recent call last):
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 713, in <module>
    main()
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 686, in main
    main()
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 686, in main
    iteration, skipped = train(model, optimizer,
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 415, in train
    iteration, skipped = train(model, optimizer,
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 415, in train
    lm_loss, skipped_iter = train_step(train_data_iterator,
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 383, in train_step
    lm_loss, skipped_iter = train_step(train_data_iterator,
  File "/home/moyix/git/DeepSpeedExamples/Megatron-LM/pretrain_gpt2.py", line 383, in train_step
    model.step()
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/engine.py", line 1006, in step
    model.step()
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/engine.py", line 1006, in step
    self._take_model_step(lr_kwargs)
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/engine.py", line 961, in _take_model_step
    self._take_model_step(lr_kwargs)
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/engine.py", line 961, in _take_model_step
    self.optimizer.step()
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/zero/stage2.py", line 1383, in step
    self.optimizer.step()
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/zero/stage2.py", line 1383, in step
    self.get_grad_norm_direct(self.averaged_gradients[i],
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/zero/stage2.py", line 1246, in get_grad_norm_direct
    self.get_grad_norm_direct(self.averaged_gradients[i],
  File "/home/moyix/git/DeepSpeed/deepspeed/runtime/zero/stage2.py", line 1246, in get_grad_norm_direct
    for g, p in zip(gradients, params):
TypeError: 'NoneType' object is not iterable
    for g, p in zip(gradients, params):
TypeError: 'NoneType' object is not iterable
```

My config.json:

```
{
  "train_batch_size": 64,
  "gradient_accumulation_steps": 1,
  "steps_per_print": 1,
  "optimizer": {
    "type": "OneBitAdam",
    "params": {
      "lr": 0.001,
      "betas": [
        0.8,
        0.999
      ],
      "eps": 1e-8,
      "weight_decay": 3e-7,
      "freeze_step": 400,
      "cuda_aware": true
        }
  },
  "zero_optimization": {
    "stage": 2
  },
  "zero_allow_untested_optimizer": true,
  "gradient_clipping": 1.0,
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "activation_checkpointing": {
    "partition_activations": true,
    "contiguous_memory_optimization": false
  },
  "wall_clock_breakdown": false
}
```

I'm not sure what would cause them to be None at this stage, unfortunately. Any ideas?

**Comment by moyix** [comment]
Ah, I think I see – one-bit Adam has a bunch of other requirements that I didn't realize, like a CUDA-aware version of MPI. Sorry for the noise.
