### ISSUE TITLE
OnebitAdam got an unexpected keyword 'cuda-aware'

### ISSUE THREAD

**Issue by ShivanshuPurohit** [microsoft/DeepSpeed#690]
I am running a distributed language modeling script, and it gives the following error:
```
File "train.py", line 74, in <module>
    training_data=None)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/__init__.py", line 119, in initialize
    config_params=config_params)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 174, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 538, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 613, in _configure_basic_optimizer
    optimizer = OnebitAdam(model_parameters, self, **optimizer_parameters)
TypeError: __init__() got an unexpected keyword argument 'cuda-aware'
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    training_data=None)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/__init__.py", line 119, in initialize
    config_params=config_params)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 174, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 538, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 613, in _configure_basic_optimizer
    optimizer = OnebitAdam(model_parameters, self, **optimizer_parameters)
TypeError: __init__() got an unexpected keyword argument 'cuda-aware'
```
How do I approach this?

**Comment by conglongli** [comment]
Hi, thank you for your interests in 1-bit Adam. For your error, I think it's because that the actual config name is "cuda_aware", not "cuda-aware". And please make sure to set this config correctly depending on whether your network is InfiniBand or Ethernet. Please find more information in this tutorial: https://www.deepspeed.ai/tutorials/onebit-adam/

**Comment by conglongli** [comment]
Close this now since the issue seems got resolved, please feel free to reopen if needed.
