### ISSUE TITLE
    RuntimeError: Could not find llvm-config. Please install llvm-{8, 9, 10}-dev

### ISSUE THREAD

**Issue by rabeehk** [microsoft/DeepSpeed#731]
Hi
I am trying to install deepspeed, getting following error with python=3.7, pytroch 
pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
torchaudio                0.7.2                      py37    pytorch
torchvision               0.8.2                py37_cu102    pytorch

could you please have a look? thanks for your help

```
(updated) rkarimi@vgne039:/idiap/user/rkarimi/dev/test/transformers/examples/seq2seq$ pip install deepspeed 
Collecting deepspeed
  Using cached deepspeed-0.3.11-py3-none-any.whl
Requirement already satisfied: tqdm in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from deepspeed) (4.49.0)
Requirement already satisfied: numpy in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from deepspeed) (1.20.0)
Requirement already satisfied: torch>=1.2 in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from deepspeed) (1.7.1)
Requirement already satisfied: torchvision>=0.4.0 in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from deepspeed) (0.8.2)
Collecting tensorboardX==1.8
  Using cached tensorboardX-1.8-py2.py3-none-any.whl (216 kB)
Requirement already satisfied: six in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from tensorboardX==1.8->deepspeed) (1.15.0)
Requirement already satisfied: protobuf>=3.2.0 in /remote/idiap.svm/user.active/rkarimi/libs/anaconda3/envs/updated/lib/python3.7/site-packages (from tensorboardX==1.8->deepspeed) (3.14.0)
Collecting triton==0.2.3
  Using cached triton-0.2.3.tar.gz (943 kB)
    ERROR: Command errored out with exit status 1:
     command: /idiap/user/rkarimi/libs/anaconda3/envs/updated/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jj_2sq18/triton_de1e82220fc24007a8a638bfad744289/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jj_2sq18/triton_de1e82220fc24007a8a638bfad744289/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-are3rxak
         cwd: /tmp/pip-install-jj_2sq18/triton_de1e82220fc24007a8a638bfad744289/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jj_2sq18/triton_de1e82220fc24007a8a638bfad744289/setup.py", line 97, in <module>
        find_llvm()
      File "/tmp/pip-install-jj_2sq18/triton_de1e82220fc24007a8a638bfad744289/setup.py", line 28, in find_llvm
        raise RuntimeError('Could not find llvm-config. ' + instructions)
    RuntimeError: Could not find llvm-config. Please install llvm-{8, 9, 10}-dev
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by surak** [comment]
Do you have llvm installed?

**Comment by BurakAlpKuscu** [comment]
Hi sorry to bother but I have the same issue did ypu solved it anyhow?
