### ISSUE TITLE
Out of memory error with model parallelism

### ISSUE THREAD

**Issue by ShivanshuPurohit** [microsoft/DeepSpeed#769]
I am getting out of memory errors with even small layer models when I set `mp=2`, or anything >1.
My training script is [this](https://github.com/EleutherAI/gpt-neox/blob/main/examples/ds_pretrain_gpt2_XL_pipe_onebit.sh), and I am running on 2 nodes with 8x2080Ti each. I don't encounter the error when I disable model parallelism (`mp=1`).

The complete error is
```
10.140.219.185: 2021-02-19 05:53:13.321573: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
10.140.219.185: > initializing torch distributed ...
10.141.250.231: Traceback (most recent call last):
10.141.250.231:   File "pretrain_gpt2.py", line 183, in <module>
10.141.250.231:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/training.py", line 80, in pretrain
10.141.250.231:     initialize_megatron(extra_args_provider=extra_args_provider,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 77, in initialize_megatron
10.141.250.231:     finish_mpu_init()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 59, in finish_mpu_init
10.141.250.231:     _initialize_distributed()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 153, in _initialize_distributed
10.141.250.231:     torch.distributed.init_process_group(
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
10.141.250.231:     barrier()
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
10.141.250.231:     work = _default_pg.barrier()
10.141.250.231: RuntimeError: CUDA error: out of memory
10.141.250.231: Traceback (most recent call last):
10.141.250.231:   File "pretrain_gpt2.py", line 183, in <module>
10.141.250.231:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/training.py", line 80, in pretrain
10.141.250.231:     initialize_megatron(extra_args_provider=extra_args_provider,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 77, in initialize_megatron
10.141.250.231:     finish_mpu_init()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 59, in finish_mpu_init
10.141.250.231:     _initialize_distributed()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 153, in _initialize_distributed
10.141.250.231:     torch.distributed.init_process_group(
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
10.141.250.231:     barrier()
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
10.141.250.231:     work = _default_pg.barrier()
10.141.250.231: RuntimeError: CUDA error: out of memory
10.141.250.231: Traceback (most recent call last):
10.141.250.231:   File "pretrain_gpt2.py", line 183, in <module>
10.141.250.231:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/training.py", line 80, in pretrain
10.141.250.231:     initialize_megatron(extra_args_provider=extra_args_provider,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 77, in initialize_megatron
10.141.250.231:     finish_mpu_init()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 59, in finish_mpu_init
10.141.250.231:     _initialize_distributed()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 153, in _initialize_distributed
10.141.250.231:     torch.distributed.init_process_group(
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
10.141.250.231:     barrier()
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
10.141.250.231:     work = _default_pg.barrier()
10.141.250.231: RuntimeError: CUDA error: out of memory
10.141.250.231: Traceback (most recent call last):
10.141.250.231:   File "pretrain_gpt2.py", line 183, in <module>
10.141.250.231:     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/training.py", line 80, in pretrain
10.141.250.231:     initialize_megatron(extra_args_provider=extra_args_provider,
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 77, in initialize_megatron
10.141.250.231:     finish_mpu_init()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 59, in finish_mpu_init
10.141.250.231:     _initialize_distributed()
10.141.250.231:   File "/home/mchorse/gpt-neox/megatron/initialize.py", line 153, in _initialize_distributed
10.141.250.231:     torch.distributed.init_process_group(
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
10.141.250.231:     barrier()
10.141.250.231:   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
10.141.250.231:     work = _default_pg.barrier()
10.141.250.231: RuntimeError: CUDA error: out of memory
```

**Comment by jomayeri** [comment]
I don't observe deepspeed anywhere in the stack trace.
