### ISSUE TITLE
Broken pipe error when initialize model

### ISSUE THREAD

**Issue by yangxjzwd1** [microsoft/DeepSpeed#815]
**When  excuting "deepspeed.initialize(args, model=model)" , come into  RuntimeError:Broken pipe. I can't fix the issue by current infomation. could somebody help?  following is full Traceback:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "../../../espnet/asr/pytorch_backend/asr_deepspeed.py", line 671, in train
    model_engine, optimizer, _, _ = deepspeed.initialize(args, model=model)
  File "/home/xianjie.yang/.local/lib/python3.7/site-packages/deepspeed/__init__.py", line 119, in initialize
    config_params=config_params)
  File "/home/xianjie.yang/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 150, in __init__
    self._configure_distributed_model(model)
  File "/home/xianjie.yang/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 504, in _configure_distributed_model
    self._broadcast_model()
  File "/home/xianjie.yang/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 482, in _broadcast_model
    group=self.data_parallel_group)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 846, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: Broken pipe

**Comment by yangxjzwd1** [comment]
Sorry!  It turns out to be the Port conflict.
