### ISSUE TITLE
mpi_discovery fails on systems with hostname executable from GNU Inetutils

### ISSUE THREAD

**Issue by mrapplexz** [microsoft/DeepSpeed#826]
Hello! I'm trying to launch DeepSpeed on my local machine with Arch Linux and inetutils 1.9.4 installed, but getting the following error:
```
Traceback (most recent call last):
  File "/home/me/projectsds/ai/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/me/projectsds/ai/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 137, in __init__
    init_distributed(dist_backend=self.dist_backend)
  File "/home/me/projectsds/ai/venv/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 42, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "/home/me/projectsds/ai/venv/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 67, in mpi_discovery
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 64.
```
It happens because `hostname` executable from Inetutils doesn't support the `-I` flag.
https://www.gnu.org/software/inetutils/manual/html_node/hostname-invocation.html

**Comment by adithya-subramanian** [comment]
Hi,

I am also facing the same issue, any updates or workaround for this ? Thanks

**Comment by partha117** [comment]
Facing the same issue.

**Comment by aleb** [comment]
It would be nice to be able to specify the `MASTER_ADDR` environment variable to specify the master address. It's used in other places in DeepSpeed already.
