### ISSUE TITLE
None bug with deepspeed 

### ISSUE THREAD

**Issue by dorooddorood606** [microsoft/DeepSpeed#850]
Hi
I am running a code using deepspeed getting this error:
could you please help why this gets None? thanks 

  File "run_mlm.py", line 525, in <module>
    main()
  File "run_mlm.py", line 491, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/transformers/trainer.py", line 968, in train
    self.deepspeed.step()
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 959, in step
    self._take_model_step(lr_kwargs)
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 914, in _take_model_step
    self.optimizer.step()
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/deepspeed/runtime/zero/stage2.py", line 1425, in step
    self.optimizer.step()
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/torch/optim/adamw.py", line 121, in step
    group['eps'])
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/torch/optim/_functional.py", line 136, in adamw
    denom = (exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(eps)
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 2329531392 bytes. Error code 12 (Cannot allocate memory)
Exception ignored in: <function tqdm.__del__ at 0x7f9b52ef4440>
Traceback (most recent call last):
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/tqdm/std.py", line 1090, in __del__
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/tqdm/std.py", line 1280, in close
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/tqdm/std.py", line 574, in _decr_instances
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/threading.py", line 522, in set
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/threading.py", line 365, in notify_all
  File "/user/diba/libs/anaconda3/envs/transformer/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable

**Comment by RezaYazdaniAminabadi** [comment]
Hi @dorooddorood606 

I think the reason you see this error is that the CUDA memory was not sufficient to allocate some memory. However, as the log also shows, the exception for such error is ignored and the program continued running but with no tensor/variable allocated. Then, you are only trying to access a None object!

Reza

**Comment by stas00** [comment]
Looks like a bug in `tqdm.del` which didn't act on the exception.

@RezaYazdaniAminabadi, why do you suggest CUDA memory? It says `DefaultCPUAllocator`. And it tried to allocate 2.3GB.

**Comment by RezaYazdaniAminabadi** [comment]
Yes, you are right @stas00. I misread it!
Thanks for helping with this :)
