### ISSUE TITLE
RuntimeError: Fail to create cublas handle

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#853]
Trying master on another machine I get:
```
Traceback (most recent call last): 
 File "examples/seq2seq/run_seq2seq.py", line 650, in <module>
   main()
 File "examples/seq2seq/run_seq2seq.py", line 590, in main
   train_result = trainer.train(resume_from_checkpoint=checkpoint)
 File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 900, in train
   model, optimizer, lr_scheduler = init_deepspeed(self, num_training_steps=max_steps)
 File "/home/stas/hf/transformers-master/src/transformers/integrations.py", line 413, in init_deepspeed
Fail to create cublas handle.
   model, optimizer, _, lr_scheduler = deepspeed.initialize(
 File "/home/stas/hf/DeepSpeed/deepspeed/__init__.py", line 112, in initialize
   engine = DeepSpeedEngine(args=args,
 File "/home/stas/hf/DeepSpeed/deepspeed/runtime/engine.py", line 183, in __init__
Traceback (most recent call last):
   self._configure_optimizer(optimizer, model_parameters)
 File "/home/stas/hf/DeepSpeed/deepspeed/runtime/engine.py", line 592, in _configure_optimizer
 File "examples/seq2seq/run_seq2seq.py", line 650, in <module>
   basic_optimizer = self._configure_basic_optimizer(model_parameters)
 File "/home/stas/hf/DeepSpeed/deepspeed/runtime/engine.py", line 657, in _configure_basic_optimizer
   main()
 File "examples/seq2seq/run_seq2seq.py", line 590, in main
   train_result = trainer.train(resume_from_checkpoint=checkpoint)
 File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 900, in train
   optimizer = DeepSpeedCPUAdam(model_parameters,
 File "/home/stas/hf/DeepSpeed/deepspeed/ops/adam/cpu_adam.py", line 80, in __init__
   self.ds_opt_adam.create_adam(self.opt_id,
RuntimeError: Fail to create cublas handle.
```

this is with zero2 config and master:
```
{
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true,
        "cpu_offload": true
    },

    "zero_allow_untested_optimizer": true,

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 3e-5,
            "betas": [0.8, 0.999],
            "eps": 1e-8,
            "weight_decay": 3e-7
        }
    },

    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 3e-5,
            "warmup_num_steps": 500
        }
    },

    "steps_per_print": 2000,
    "wall_clock_breakdown": false
}

```

env
```
-------------------------------------------------- 
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
     runtime if needed. Op compatibility means that your system
     meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY] 
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY] 
fused_adam ............. [NO] ....... [OKAY] 
fused_lamb ............. [NO] ....... [OKAY] 
sparse_attn ............ [NO] ....... [OKAY] 
transformer ............ [NO] ....... [OKAY] 
stochastic_transformer . [NO] ....... [OKAY] 
utils .................. [NO] ....... [OKAY] 
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch']
torch version .................... 1.8.0
torch cuda version ............... 10.2
nvcc version ..................... 10.2
deepspeed install path ........... ['/home/stas/hf/DeepSpeed/deepspeed']
deepspeed info ................... 0.3.11+f888130, f888130, samyamr/inference-hook-fix
deepspeed wheel compiled w. ...... torch 1.8, cuda 10.2
```

(same with master, I was just testing this PR's branch - but same failure)

**Comment by stas00** [comment]
Must be some cuda-issue, since I reverted to 0.3.10 and now getting a variation of the same:
```
Traceback (most recent call last):
  File "examples/seq2seq/run_seq2seq.py", line 650, in <module>
    main()
  File "examples/seq2seq/run_seq2seq.py", line 590, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 1050, in train
    tr_loss += self.training_step(model, inputs)
  File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 1434, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/stas/hf/transformers-master/src/transformers/trainer.py", line 1466, in compute_loss
    outputs = model(**inputs)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 777, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/hf/transformers-master/src/transformers/models/t5/modeling_t5.py", line 1502, in forward
    encoder_outputs = self.encoder(
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/hf/transformers-master/src/transformers/models/t5/modeling_t5.py", line 951, in forward
    layer_outputs = layer_module(
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/hf/transformers-master/src/transformers/models/t5/modeling_t5.py", line 633, in forward
    self_attention_outputs = self.layer[0](
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/hf/transformers-master/src/transformers/models/t5/modeling_t5.py", line 540, in forward
    attention_output = self.SelfAttention(
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/hf/transformers-master/src/transformers/models/t5/modeling_t5.py", line 468, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

So the problem is most likely is with the setup. Going to experiment.

**Comment by stas00** [comment]
Nope, something is wrong with pytorch-1.8.0/cu102 - I downgraded to 1.7.1/cu102 and all works. Both 0.3.10 and master.
```
pip install torch=1.7.1 torchvision -f https://download.pytorch.org/whl/torch_stable.html
```
