### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by xzy256** [microsoft/DeepSpeed#887]
I run [pipeline_parallelism](https://github.com/microsoft/DeepSpeedExamples) example with 2 node(8 gpus per node) .
cmd:  `deepspeed --hostfile=hostfile  train.py -p 2 --steps=50  --deepspeed_config=ds_config.json`
When reach set steps，occur `ConnectionResetError: [Errno 104] Connection reset by peer` error. 
```
steps: 40 loss: 2.2691 iter time (s): 0.096 samples/sec: 665.274
[2021-03-24 03:10:07,750] [INFO] [logging.py:60:log_dist] [Rank 0] step=50, skipped=0, lr=[0.001], mom=[[0.9, 0.999]]
steps: 50 loss: 2.2092 iter time (s): 0.096 samples/sec: 669.031
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/pin_memory.py", line 21, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 284, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

```
env 
deepspeed image pulled from [docker hub](https://hub.docker.com/r/deepspeed/deepspeed) 
Distributor ID:	   Ubuntu 
Description:	   Ubuntu 18.04.3 LTS 
Release:	           18.04 
Codename:	   bionic 
NCCL_VERSION  2.4.8 
Python                3.6.9 
torch                  1.2.0 
torchvision         0.4.0

**Comment by xzy256** [comment]
It's my configuration fault.  Multi node's `ds_config.json`  is not same result in the error.
