### ISSUE TITLE
ZeRO 3: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by szhengac** [microsoft/DeepSpeed#907]
If I use the following snippet in BingBERT example with ZeRO 3, I received IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1) no matter if Transformer CUDA layer is enabled or not.

```
    with deepspeed.zero.Init(remote_device='cpu', pin_memory=True, enabled=True):
        model = BertMultiTask(args)
```

**Comment by tjruwase** [comment]
@szhengac, can you please share a stack trace?

**Comment by szhengac** [comment]
@tjruwase 

```
    model = BertMultiTask(args)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/turing/models.py", line 123, in __init__
    self.network = BertForPreTrainingPreLN(bert_config, args)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 1119, in __init__
    config, self.bert.embeddings.word_embeddings.weight)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 760, in __init__
    bert_model_embedding_weights)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 712, in __init__
    self.decoder = nn.Linear(bert_model_embedding_weights.size(1),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/deepspeed_train.py", line 597, in <module>
    main()
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/deepspeed_train.py", line 586, in main
    model, optimizer = prepare_model_optimizer(args)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/deepspeed_train.py", line 461, in prepare_model_optimizer
    model = BertMultiTask(args)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 208, in __exit__
    _disable_class(subclass)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 204, in _disable_class
    cls.__init__ = cls._old_init
AttributeError: type object 'LinearActivation' has no attribute '_old_init'
Traceback (most recent call last):
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/deepspeed_train.py", line 461, in prepare_model_optimizer
    model = BertMultiTask(args)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/turing/models.py", line 123, in __init__
    self.network = BertForPreTrainingPreLN(bert_config, args)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 1119, in __init__
    config, self.bert.embeddings.word_embeddings.weight)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 760, in __init__
    bert_model_embedding_weights)
  File "/usr/local/lib64/python3.7/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 164, in wrapper
    f(module, *args, **kwargs)
Killing subprocess 20444  File "/fsx/szhengac/DeepSpeedExamples/bing_bert/nvidia/modelingpreln.py", line 712, in __init__
```

**Comment by janEbert** [comment]
Hey, you need to make sure all necessary classes are imported before initializing `deepspeed.zero.Init`.

The context first registers its functionality on all subclasses of `torch.nn.Module`. When the context exits, it tries removing it for all subclasses and that's probably when the error happens.

These lines are the issue – the model is imported only after the context has been initialized. Adding these imports before entering the `deepspeed.zero.Init` context should solve your problem.
https://github.com/microsoft/DeepSpeedExamples/blob/127372571189ac905c8c92f4fe55a3d85c80324e/bing_bert/turing/models.py#L109-L113

**Comment by janEbert** [comment]
For future reference, the same can happen when a checkpoint is loaded during initialization. If only that checkpoint contains the class information but the necessary imports are missing before entering the context, that's another source for errors.

**Comment by szhengac** [comment]
I was using an older version where they are no these two lines
