### ISSUE TITLE
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

### ISSUE THREAD

**Issue by loretoparisi** [microsoft/DeepSpeed#943]
This code using `hugginface` + `torch` + `deepspeed` fails when running on `cpu`:

```python
import os
import librosa
import torch
from transformers import Wav2Vec2Tokenizer, Wav2Vec2ForCTC
import deepspeed

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-large-960h-lv60-self", 
    cache_dir=os.getenv("cache_dir", "../models"))
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-960h-lv60-self", 
    cache_dir=os.getenv("cache_dir", "../models"))

# DeepSpeed config
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '9994'
os.environ['RANK'] = "0"
os.environ['LOCAL_RANK'] = "0"
os.environ['WORLD_SIZE'] = "1"
config = {
    "train_batch_size": 8,
    "fp16": {
        "enabled": True,
        "min_loss_scale": 1,
        "opt_level": "O3"
    },
    "zero_optimization": {
        "stage": 2,
        "cpu_offload": True,
        "cpu_offload_params": True,
        "contiguous_gradients": True,
        "overlap_comm": True
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 0.001,
            "betas": [0.9, 0.999],
            "eps": 1e-6
        }
    }
}
model, optimizer, _, _ = deepspeed.initialize(config_params=config, model=model, model_parameters=model.parameters())

# choose tensor backend
BACKEND = "gpu" if torch.cuda.is_available() else "cpu"
# naive local audio dataset
audio_ds = [os.path.join(os.path.dirname(
    os.path.abspath(__file__)), 'data', 'sample.mp3'),
    os.path.join(os.path.dirname(
        os.path.abspath(__file__)), 'data', 'long_sample.mp3')]
for audio in audio_ds:
    y, _ = librosa.load(audio['data'], sr=16000, mono=True)
    input_values = tokenizer(y, return_tensors="pt", padding="longest").input_values
    decoded = tokenizer.batch_decode(torch.argmax(model(input_values.to(torch.float16).to(BACKEND)).logits, dim=-1))[0]
    print(decoded)
```

The error was

```
[2021-04-11 15:30:29,180] [INFO] [logging.py:60:log_dist] [Rank -1] DeepSpeed info: version=0.3.14, git-hash=unknown, git-branch=unknown
[2021-04-11 15:30:29,181] [INFO] [distributed.py:47:init_distributed] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "src/asr/deeps.py", line 50, in <module>
    model, optimizer, _, _ = deepspeed.initialize(config_params=config, model=model, model_parameters=model.parameters())
  File "/usr/local/lib/python3.7/site-packages/deepspeed/__init__.py", line 125, in initialize
    config_params=config_params)
  File "/usr/local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 144, in __init__
    init_distributed(dist_backend=self.dist_backend)
  File "/usr/local/lib/python3.7/site-packages/deepspeed/utils/distributed.py", line 51, in init_distributed
    init_method=init_method)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 510, in init_process_group
    timeout=timeout))
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 603, in _new_process_group_helper
    timeout)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
```

**Comment by tjruwase** [comment]
@loretoparisi, thanks for reporting this issue. Unfortunately, DeepSpeed is still not ready to run on CPUs alone. It seems you have workaround in your code base. Is it okay to close this issue here?

**Comment by loretoparisi** [comment]
@tjruwase thanks, so I cannot initialize DeepSpeed on cpu right now, and I have the check if gpu is avaiable and just skip it kie

```python
if torch.cuda.is_available():
    model, optimizer, _, _ = deepspeed.initialize(config_params=config, model=model, model_parameters=model.parameters())
```

[In the ZeRO-3 Offload](https://www.deepspeed.ai/news/2021/03/07/zero3-offload.html) there are references to CPU as well, so I assume it will be available at some point?

Thank you.

**Comment by tjruwase** [comment]
@elcolie, due to bandwidth reasons we still don't have full support for CPU only environments. But we have made Adam and Adagrad optimizers available for CPU. Which features are you most interested in on CPU?

**Comment by elcolie** [comment]
@tjruwase I don't know which features I need. Currently I just start looking at [gpt4all](https://github.com/nomic-ai/gpt4all). Thank you.
